const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {build}=require('esbuild'),{editor_plugins}=require('./editor_bundle.cjs');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_remote_picker_'));let win;const checks=[];app.disableHardwareAcceleration();app.setPath('userData',path.join(evidence,'profile'));
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1000,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 fs.writeFileSync(path.join(evidence,'index.html'),'<body></body>');await win.loadFile(path.join(evidence,'index.html'));const run=async s=>{try{return await win.webContents.executeJavaScript(s,true);}catch(error){console.error('Expression failed: '+s.slice(0,400));throw error;}},pause=()=>new Promise(r=>setTimeout(r,70)),wait=async s=>{for(let n=0;n<100;n++){if(await run(s))return;await pause();}throw Error('Timeout: '+s+' '+await run('JSON.stringify({body:document.body.innerText,errors,calls})'));};
 const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export * from "./src/remote_workspace_picker";export * from "./src/remote_workspace_files";export * from "./src/git_workspace_resources";export * from "./src/workspace_open_dialog";export {git_graph_panel} from "./src/git_graph_panel";export {GRAPH_SETTINGS_KEY} from "./src/git_graph_settings";',resolveDir:path.join(__dirname,'..')},loader:{'.css':'text'},bundle:true,format:'iife',globalName:'qa',write:false});await run(bundle.outputFiles[0].text+';void 0');
 await run(`window.errors=[];onunhandledrejection=e=>errors.push(String(e.reason));window.fs=require('fs');window.p=require('path');window.base=${JSON.stringify(evidence)};window.calls=[];window.delay_read=false;window.release_read=()=>{};
 window.provider=new qa.remote_file_provider({target:'alice@fixture',connected:()=>true,async request(op,args){calls.push([op,args.path]);if(op==='list'){if(delay_read)await new Promise(r=>release_read=r);const names=args.path==='/project'?[['sub',true],['file.md',false]]:args.path==='/project/sub'?[['deep',true],['目标.md',false]]:[];return{entries:names.map(([name,directory])=>({name,directory,link:false}))};}if(op==='filesystem')return{file:args.path.endsWith('.md'),directory:!args.path.endsWith('.md')};throw Error(op);}},fs,p,p.join(base,'cache','alice'),Buffer);window.release=qa.register_remote_files(provider);provider.root=provider.local_path('/project');qa.protect_remote_cache(p.join(base,'cache'),p);qa.select_remote_files(provider);
 window.result='pending';window.open=(dir=true,options={})=>{result='pending';qa.choose_remote_resource(dir,undefined,options).then(value=>result=value||'cancel');};window.btn=name=>[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent===name);window.row=name=>[...document.querySelectorAll('[role=option]')].find(b=>b.lastElementChild?.textContent===name);window.input=()=>document.querySelector('[aria-label="远程路径"]');open();void 0`);
 await wait('!!row("sub")');await run('window.background=document.createElement("button");document.body.append(background);background.focus();void 0');await pause();assert(await run('!!input()'),'background refresh focus cannot dismiss modal picker');await run('row("sub").click();void 0');assert.equal(await run('input().value'),'/project');assert.equal(await run('row("sub").getAttribute("aria-selected")'),'true');assert(await run('row("sub").classList.contains("selected")'));await run('btn("打开").click();void 0');await wait('result!=="pending"');assert.equal(await run('provider.remote_path(result)'),'/project/sub');checks.push('single click selects folder and confirm returns selected folder');
 await run('open();void 0');await wait('!!row("sub")');await run('row("sub").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}));void 0');await wait('input().value==="/project/sub"');await run('document.querySelector("nav button[title=\\"/project\\"]").click();void 0');await wait('input().value==="/project"');checks.push('double click enters folder and ancestor breadcrumb jumps directly');
 await run('document.querySelector(".workspace-dialog-close").click();open(false);void 0');await wait('!!row("file.md")');await run('input().value="sub/目标.md";input().dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));void 0');await wait('row("目标.md")?.getAttribute("aria-selected")==="true"');await run('btn("打开").click();void 0');await wait('result!=="pending"');assert.equal(await run('provider.remote_path(result)'),'/project/sub/目标.md');checks.push('relative typed file selects in parent and confirmation opens file');
 await run('open(true,{choose_local_folder:async()=>undefined});void 0');await wait('!!row("sub")');await run('btn("打开本地文件夹…").click();void 0');await pause();assert.equal(await run('result'),'pending');assert(await run('qa.active_remote_files()===provider'));await run('document.querySelector(".workspace-dialog-close").click();void 0');checks.push('cancel native local picker retains SSH dialog and workspace');
 await run('open(true,{choose_local_folder:async()=>p.join(base,"local")});void 0');await wait('!!row("sub")');await run('btn("打开本地文件夹…").click();void 0');await wait('result!=="pending"');assert.equal(await run('result'),path.join(evidence,'local'));assert(await run('qa.active_remote_files()===provider'));checks.push('local selection returns only a path; picker never mutates owner');
 await run('delay_read=true;open();void 0');await pause();await run('document.querySelector(".workspace-dialog-close").click();release_read();delay_read=false;void 0');await pause();assert.equal(await run('document.querySelectorAll("[role=dialog]").length'),0);checks.push('late read after close does not resurrect dialog');
 await run(`window.scope=qa.git_workspace_resources(p);window.fake={resources:scope,host:{path_api:p},disposed:false,repository_paths:qa.git_graph_panel.prototype.repository_paths};window.known=()=>qa.git_graph_panel.prototype.known_repos.call(fake);window.save=v=>qa.git_graph_panel.prototype.save_repos.call(fake,v);window.local=p.join(base,'local');window.foreign=p.join(base,'cache','bob','project');localStorage.setItem(qa.GRAPH_SETTINGS_KEY+'repositories',JSON.stringify([local,provider.root,foreign]));void 0`);
 assert.deepEqual(await run('known()'),[await run('provider.root')]);assert.equal(await run('scope.label(provider.root)'),'/project');assert(await run('(()=>{try{scope.assert(local);return false;}catch{return true;}})()'));await run('save([provider.root]);qa.select_remote_files(undefined);void 0');assert(await run('(()=>{try{scope.assert(provider.root);return false;}catch{return true;}})()'));await run('fake.resources=qa.git_workspace_resources(p);void 0');assert.deepEqual(await run('known()'),[path.join(evidence,'local')]);checks.push('mixed legacy history filters owner, hides orphan caches and rejects old scope');
 await run(`window.second=new qa.remote_file_provider({target:'bob@fixture',connected:()=>true,request:provider.connection.request},fs,p,p.join(base,'cache','bob'),Buffer);window.release_second=qa.register_remote_files(second);second.root=second.local_path('/project');qa.select_remote_files(second);fake.resources=qa.git_workspace_resources(p);save([second.root,provider.root,local]);void 0`);assert.deepEqual(await run('known()'),[await run('second.root')]);await run('qa.select_remote_files(provider);fake.resources=qa.git_workspace_resources(p);void 0');assert.deepEqual(await run('known()'),[await run('provider.root')]);await run('release_second();void 0');checks.push('two registered SSH accounts persist separate repository histories');
 await run(`(async()=>{qa.select_remote_files(provider);window.mounted=provider.root;window.closed_count=0;window.changed=0;window.native_reply={canceled:true};window.native_options;window.JSBridge={invoke:async(name,options)=>{if(name==='dialog.showOpenDialog'){native_options=options;return native_reply;}return true;}};window.File={setMountFolder:path=>mounted=path};fs.mkdirSync(local,{recursive:true});window.binding=qa.bind_workspace_open_dialog({context_root:()=>mounted,path_api:p,fs:qa.workspace_resource_fs(fs),prepare_workspace_switch:async()=>()=>closed_count++,core:{app:{commands:{run(){}}}}},()=>changed++,{ready:Promise.resolve(),suspend(){},resume:async()=>{}});window.switches=0;window.addEventListener('linux-note-workspace-context-changed',()=>switches++);await binding.open_local_folder();})()`);
 assert(await run('mounted===provider.root&&qa.active_remote_files()===provider&&switches===0&&!native_options.defaultPath'));await run('(async()=>{native_reply={filePaths:[local]};await binding.open_local_folder();})()');assert(await run('mounted===local&&!qa.active_remote_files()&&switches===1&&closed_count===1'));checks.push('native local cancel preserves owner; accepted folder commits single common lifecycle');
 for(const count of [20,100,1000]){assert(await run(`(()=>{for(let i=0;i<${count};i++){qa.select_remote_files(provider);const scope=qa.git_workspace_resources(p);if(!scope.accepts(provider.root)||scope.accepts(local))return false;qa.select_remote_files(undefined);if(scope.current())return false;}return true;})()`));checks.push(count+' owner transition rejects stale access');}
 await run('binding.dispose();release();void 0');assert.deepEqual(await run('errors'),[]);console.log(JSON.stringify({status:'PASS',checks,evidence,scope:'real Electron DOM and filesystem; SSH and native dialog ports controlled'}));win.destroy();app.quit();
}).catch(error=>{console.error(error);win?.destroy();app.exit(1);});
