const {app,BrowserWindow}=require('electron');
const {build}=require('esbuild');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_link_hover_'));
app.setPath('userData',path.join(root,'user_data'));app.disableHardwareAcceleration();
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
app.whenReady().then(async()=>{
  const win=new BrowserWindow({show:false,width:560,height:330,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false,offscreen:true}});
  const file=path.join(root,'host.html');
  fs.writeFileSync(file,'<!doctype html><meta charset="utf-8"><body><div id="write" contenteditable="true"><p>Draft preserved <span md-inline="link" class="md-link"><a id="local" href="hardware.md#接口" title="original title" aria-describedby="old-description"><strong>Hardware</strong></a></span></p><a id="external" href="https://example.invalid/?q=%3Cimg%3E">Remote</a><a id="cancel" href="missing.yml">Missing</a></div><section class="typ-markdown-preview"><a id="preview" href="../boards/board.yml">Board</a></section>');
  await win.loadFile(file);
  const bundle=await build({stdin:{contents:'export {bind_reading_link_hover} from "./src/reading_link_hover";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'hover_qa',write:false});
  const evaluate=source=>win.webContents.executeJavaScript(source);
  await evaluate(bundle.outputFiles[0].text);
  await evaluate(`window.reqnode=name=>require(name);window.File={bundle:{filePath:${JSON.stringify(path.join(root,'project-docs','chapter.md'))}}};window[Symbol.for('typora-code:workspace')]={app:{workspace:{eachLeaves:fn=>fn({state:{path:${JSON.stringify(path.join(root,'other','chapter.md'))}},view:{containerEl:document.querySelector('.typ-markdown-preview')}})}}};window.opens=0;document.addEventListener('click',event=>{opens++;event.preventDefault()});window.binding=hover_qa.bind_reading_link_hover();window.original_html=document.querySelector('#write').innerHTML;window.enter=id=>document.querySelector(id).dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));window.leave=id=>document.querySelector(id).dispatchEvent(new MouseEvent('mouseout',{bubbles:true,relatedTarget:document.body}));void 0`);
  await evaluate(`enter('#local strong')`);await delay(650);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden`),'does not show before the requested 1 second');
  await delay(450);
  assert.equal(await evaluate(`document.querySelector('.workspace-link-hover').textContent`),'hardware.md#接口\n'+path.join(root,'project-docs','hardware.md')+'#接口');
  assert.equal(await evaluate('opens'),0,'hover does not invoke navigation');
  await evaluate(`document.querySelector('#local').click()`);
  assert.equal(await evaluate('opens'),1,'existing click handler remains available');
  await evaluate(`leave('#local')`);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden&&document.querySelector('#write').innerHTML===original_html`),'leave restores native title and accessibility attributes without changing the draft');
  await evaluate(`enter('#cancel')`);await delay(350);await evaluate(`leave('#cancel')`);await delay(800);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden`),'leaving before the delay cancels stale results');
  await evaluate(`enter('#preview')`);await delay(1100);
  assert.equal(await evaluate(`document.querySelector('.workspace-link-hover').textContent`),'../boards/board.yml\n'+path.join(root,'boards','board.yml'));
  await evaluate(`document.dispatchEvent(new Event('scroll'))`);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden`),'scroll dismisses the tooltip');
  await evaluate(`enter('#external')`);await delay(1100);
  assert.equal(await evaluate(`document.querySelector('.workspace-link-hover').textContent`),'https://example.invalid/?q=%3Cimg%3E');
  assert(await evaluate(`!document.querySelector('.workspace-link-hover img')&&document.querySelector('.workspace-link-hover').getBoundingClientRect().right<=innerWidth`),'target is inert text contained in the viewport');
  await evaluate(`document.querySelector('#external').setAttribute('href','https://example.invalid/changed')`);await delay(20);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden`),'changing a link dismisses stale target information');
  await evaluate(`leave('#external');enter('#cancel');document.querySelector('#cancel').remove()`);await delay(1100);
  assert(await evaluate(`document.querySelector('.workspace-link-hover').hidden`),'removed document cannot leave a late tooltip');
  await evaluate(`enter('#local');binding.dispose()`);await delay(1100);
  assert(await evaluate(`!document.querySelector('.workspace-link-hover')&&document.querySelector('#local').title==='original title'&&!document.querySelector('#typora-code-link-hover')`),'dispose cancels pending work and restores host attributes');
  console.log('PASS '+root);win.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(root);app.exit(1)});
