// 默认范围、动态控件与独立覆写：真实鼠标/键盘输入，不复制生产CSS。
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const evidence=path.join(__dirname,'../../.cache/interaction_defaults_20260913');fs.mkdirSync(evidence,{recursive:true});
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'typora_hover_defaults_')));app.disableHardwareAcceleration();
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let win;const checks=[];
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:900,height:650,webPreferences:{contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,`<!doctype html><style>body{font:13px system-ui;margin:16px}button,[role=button],summary{box-sizing:border-box;border:1px solid #777;padding:4px;background:transparent;color:#222}#scope{display:flex;flex-wrap:wrap;gap:20px;width:650px}#circle{--workspace-interaction-radius:50%;border-radius:50%;width:40px;height:40px}#long{--workspace-interaction-radius:6px;border-radius:6px;width:230px;height:32px}#custom{--workspace-interaction-hover:rgb(10,70,110);--workspace-interaction-foreground:white}#none:hover,#none button:hover{background:rgb(230,180,40)}#outside{position:fixed;bottom:10px;right:10px}#nested{width:180px;--workspace-interaction-radius:12px}#custom{--workspace-interaction-radius:0}#dynamic{border-radius:0}#scope{--workspace-control-radius:4px}#nested button{margin-left:30px}</style><div id=scope><button id=circle>圆</button><button id=long>没有逐项登记的长矩形按钮</button><div id=custom role=button tabindex=0>模块覆写</div><button disabled id=disabled>禁用</button><div id=aria_disabled role=button aria-disabled=true tabindex=0>语义禁用</div><div id=none data-workspace-interaction=none><button>独立绘制</button></div><div class=monaco-editor><button id=editor>第三方编辑器</button></div><button id=nested>父按钮 <span role=button tabindex=0 id=child>内部操作</span></button><div id=write><button id=document>正文</button></div></div><button id=outside>范围外</button>`);await win.loadFile(html);win.webContents.debugger.attach();await win.webContents.debugger.sendCommand("Emulation.setFocusEmulationEnabled",{enabled:true});
 const ev=source=>win.webContents.executeJavaScript(source);
 const bundle=await require('esbuild').build({stdin:{contents:'export {acquire_workspace_interaction,workspace_interaction} from "./src/workspace_interaction";export {workspace_button} from "./src/workspace_widgets";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await ev(bundle.outputFiles[0].text);
 await ev('window.binding=qa.acquire_workspace_interaction(document.querySelector("#scope"));const b=qa.workspace_button("工厂默认",()=>{});b.id="factory";document.body.append(b);const fresh=document.createElement("button");fresh.id="dynamic";fresh.textContent="后加入的节点";document.querySelector("#scope").append(fresh);window.extra=qa.acquire_workspace_interaction();void 0');
 const move=async selector=>{const p=await ev(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`),z=win.webContents.getZoomFactor();win.webContents.sendInputEvent({type:'mouseMove',x:Math.round(p.x*z),y:Math.round(p.y*z)});await pause(90)};
 const style=selector=>ev(`(()=>{const n=document.querySelector(${JSON.stringify(selector)}),s=getComputedStyle(n),r=n.getBoundingClientRect();return {bg:s.backgroundColor,color:s.color,shape:[r.width,r.height,s.borderRadius,s.padding,s.display,s.position]}})()`);
 for(const theme of ['light','dark'])for(const zoom of [1,1.2,1.25]){
  win.webContents.setZoomFactor(zoom);await ev(`document.documentElement.dataset.workspaceFileIconTheme='${theme}'`);await pause(90);
  for(const [selector,radius] of [['#circle','50%'],['#long','6px'],['#dynamic','4px'],['#factory','4px'],['#custom','0px']]){
   await move('#outside');const before=await style(selector);assert.equal(before.shape[2],radius,selector+' shared default or explicit shape');await move(selector);const after=await style(selector);assert.notEqual(after.bg,before.bg,selector+' default hover');assert.deepEqual(after.shape,before.shape,'no size/shape changes');await move('#outside');assert.equal((await style(selector)).bg,before.bg);checks.push(theme+' '+zoom+' adaptive '+selector);
  }
  await move('#custom');assert.equal((await style('#custom')).bg,'rgb(10, 70, 110)');assert.equal((await style('#custom')).color,'rgb(255, 255, 255)');
  for(const selector of ['#disabled','#aria_disabled','#editor','#document']){await move('#outside');const before=await style(selector);await move(selector);assert.equal((await style(selector)).bg,before.bg,selector+' excluded');checks.push(theme+' '+zoom+' exclude '+selector)}
  await move('#none button');assert.equal((await style('#none button')).bg,'rgb(230, 180, 40)','none subtree owns its feedback');
  assert.equal((await style('#nested')).shape[2],'12px');assert.equal((await style('#child')).shape[2],'4px','parent override must not leak to child');
  await move('#child');assert.equal((await style('#nested')).bg,'rgba(0, 0, 0, 0)','only deepest control receives hover');assert.notEqual((await style('#child')).bg,'rgba(0, 0, 0, 0)');
 }
 win.webContents.setZoomFactor(1);
 await ev(`const primary=qa.workspace_button('主操作',()=>{});primary.id='primary';qa.workspace_interaction(primary,'primary');document.querySelector('#scope').append(primary);void 0`);
 for(const background of ['rgb(0, 120, 212)','rgb(17, 60, 100)']) {
  await ev(`document.documentElement.style.setProperty('--vscode-button-background','${background}');document.documentElement.style.setProperty('--vscode-button-hoverBackground','rgb(30, 90, 150)');document.documentElement.style.setProperty('--vscode-button-foreground','rgb(255, 255, 255)');`);
  await move('#outside');assert.equal((await style('#primary')).bg,background);
  await move('#primary');assert.equal((await style('#primary')).bg,'rgb(30, 90, 150)');assert.equal((await style('#primary')).color,'rgb(255, 255, 255)');
  await ev('document.querySelector("#primary").disabled=true');assert.equal((await style('#primary')).bg,background,'disabled primary does not use hover');
  await ev('document.querySelector("#primary").disabled=false');checks.push('primary theme, hover and disabled '+background);
 }
 await ev('document.querySelector("#primary").remove()');await move('#outside');win.webContents.focus();await ev('document.querySelector("#circle").focus()');win.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab'});await pause(80);
 assert(await ev('document.activeElement.id==="long"&&document.activeElement.matches(":focus-visible")&&getComputedStyle(document.activeElement).outlineStyle==="solid"'),'real keyboard focus uses shared outline '+JSON.stringify(await ev('({id:document.activeElement.id,visible:document.activeElement.matches(":focus-visible"),outline:getComputedStyle(document.activeElement).outlineStyle})')));checks.push('keyboard focus');
 await ev('binding.remove()');assert.equal((await style('#dynamic')).shape[2],'0px','scope disposal restores previous radius');await move('#outside');await move('#long');assert.equal((await style('#long')).bg,'rgba(0, 0, 0, 0)','removed scope restores unregistered descendants');
 await move('#factory');assert.notEqual((await style('#factory')).bg,'rgba(0, 0, 0, 0)','independent owner keeps common style');await ev('extra.remove()');assert(await ev('!document.getElementById("typora-code-style:workspace_interaction")'),'last owner removes fallback stylesheet');checks.push('independent ownership and disposal');
 fs.writeFileSync(path.join(evidence,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify({status:'PASS',count:checks.length,evidence}));win.destroy();app.exit(0);
}).catch(e=>{console.error(e.stack);if(win&&!win.isDestroyed())win.destroy();app.exit(1)});
