// 真实Chromium与生产CSS；仅使用独立设置存储和临时导出文件。
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'typora-color-settings-'));app.setPath('userData',path.join(base,'profile'));app.disableHardwareAcceleration();let win;
const checks=[],pause=ms=>new Promise(r=>setTimeout(r,ms)),ev=s=>win.webContents.executeJavaScript(s),check=async(s,label)=>{assert(await ev(s),label);checks.push(label);};
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1200,height:900,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false,offscreen:true}});
 for(const name of ['cpp_github-consolas.css','cpp_github-consolas_light.css','cpp_github-consolas_dark.css'])fs.copyFileSync(path.join(__dirname,'../..',name),path.join(base,name));
 const css=fs.readFileSync(path.join(__dirname,'../dist/workspace.css'),'utf8');
 fs.writeFileSync(path.join(base,'workspace.css'),css);
 fs.writeFileSync(path.join(base,'test.html'),`<link id=theme_css href=night.css><link id=typora-code-workspace-styles rel=stylesheet href=workspace.css><style>body{background:#191a1b;color:#bbb;--bg-color:#191a1b;--text-color:#bbb}#write{font:18px/1.6 Georgia;background:#222;color:#bbb}#write h1{font-size:32px}#write td{border:2px solid #888}#write a{color:#ccc}</style><body><div id=write><h1>标题</h1><p>正文 <a href=#target>链接</a></p><table><tr><td>表格</td></tr></table><pre><code class=hljs-string>字符串</code></pre></div><aside id=typora-sidebar></aside></body>`);
 await win.loadFile(path.join(base,'test.html'));
 const result=await require('esbuild').build({plugins:require('./editor_bundle.cjs').editor_plugins(),stdin:{contents:`export {bind_code_theme} from './src/reading_code_theme';export {highlight_preview_code} from './src/workspace_markdown_preview_render';export * from './src/workspace_color_settings';export * from './src/workspace_color_catalog';export {bind_workspace_settings_view} from './src/workspace_settings_view';export {bind_workspace_settings_sections} from './src/workspace_settings_sections';export {bind_workspace_colors} from './src/workspace_colors';export {markdown_theme_rules,observe_markdown_theme} from './src/workspace_markdown_theme';export {terminal_theme} from './src/terminal_theme';export {create_workspace_titlebar_definitions} from './src/workspace_titlebar_entries';`,resolveDir:path.join(__dirname,'..')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await ev(result.outputFiles[0].text);
 await ev(`window.values=new Map();window.commands=new Map();window.fail_save=false;window.reqnode=require;window.exports=[];window.cancel_export=false;window.JSBridge={async invoke(id,...args){if(id==='clipboard.write'){window.clipboard_value=JSON.parse(args[0]).text;return;}if(id==='dialog.showSaveDialog')return{canceled:cancel_export,filePath:${JSON.stringify(path.join(base,'colors.json'))}};throw Error('unsupported')}};window.core={app:{settings:{get:k=>values.get(k),set_and_save(k,v){if(fail_save)throw Error('磁盘失败');values.set(k,structuredClone(v));}},commands:{register(c){commands.set(c.id,c.callback);return()=>commands.delete(c.id)},run(id){commands.get(id)?.()}},workspace:{}}};window[Symbol.for('typora-code:workspace')]=core;window.binding=qa.bind_workspace_colors();window.sections=qa.bind_workspace_settings_sections({context_root:()=>''});window.view=qa.bind_workspace_settings_view(core);window.before=document.querySelector('#write').innerHTML;window.geometry=getComputedStyle(document.querySelector('#write h1')).fontSize;window.host=document.body.appendChild(document.createElement('div'));window.shadow=host.attachShadow({mode:'open'});window.refresh=()=>shadow.innerHTML='<style>'+qa.markdown_theme_rules()+'</style><div id=write>'+before+'</div>';window.unwatch=qa.observe_markdown_theme(refresh);refresh();window.input=(key,color)=>{const node=document.querySelector('[data-color-key="'+key+'"]');node.value=color;node.dispatchEvent(new Event('input',{bubbles:true}));};window.action=id=>document.querySelector('[data-color-action="'+id+'"]').click();window.color=(selector,root=document)=>getComputedStyle(root.querySelector(selector)).color;window.import_text=async text=>{const picker=document.querySelector('[data-color-import]');Object.defineProperty(picker,'files',{configurable:true,value:[{text:()=>Promise.resolve(text)}]});picker.dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,80));};commands.get('typora_code:custom_colors')();void 0`);await pause(500);
 await check(`document.querySelectorAll('.workspace-settings-modal').length===1&&document.querySelector('[data-color-key=markdown_link]')`,'主题命令直达唯一配色表');
 await check(`document.querySelector('[data-color-picker=markdown_link]').getBoundingClientRect().width===30`,'生产静态CSS下取色器宽度不被对话框覆盖');
 await check(`qa.WORKSPACE_COLOR_ROLES.length===new Set(qa.WORKSPACE_COLOR_ROLES.map(r=>r.key)).size&&qa.WORKSPACE_COLOR_ROLES.length>130`,'全部颜色目录无重复键');

 await check(`[...document.querySelectorAll('[data-color-key]')].filter(node=>!node.value).every(node=>['vscode_modern_activity_bar_item_active_foreground','vscode_list_focus_and_selection_outline'].includes(node.dataset.colorKey))`,'全部已定义角色显示实际色值，未定义角色不伪造灰色');
 await check(`document.querySelector('[data-color-key=markdown_link]').value.startsWith('#')`,'继承主题时显示可复制的实际色值');
 await ev(`document.querySelector('[data-color-copy=markdown_link]').click();void 0`);await pause(40);
 await check(`window.clipboard_value===document.querySelector('[data-color-key=markdown_link]').value`,'一键复制实际色值');
 await ev(`document.querySelector('[aria-label="新配色方案名称"]').value='柔和夜色';action('duplicate');void 0`);await pause(350);
 await check(`qa.read_color_config().profiles[0].name==='柔和夜色'`,'另存为独立命名方案');
 await check(`qa.parse_color_config(qa.serialize_color_config(qa.read_color_config())).profiles[0].name==='柔和夜色'`,'JSON保留命名方案身份');
 await ev(`window.applied_theme='';window.ClientCommand={setTheme(file){applied_theme=file;document.querySelector('#theme_css').href=file;}};action('activate');void 0`);await pause(180);
 await check(`applied_theme==='cpp_github-consolas_dark.css'&&qa.read_color_config().active.dark===qa.read_color_config().profiles[0].id`,'应用命名方案切换对应基础并保存活动身份');
 await check(`(async()=>{const entries=await qa.create_workspace_titlebar_definitions({core,context_root:()=>''},{ClientCommand,JSBridge:{invoke:async()=>({all:['cpp_github-consolas_dark.css'],current:'cpp_github-consolas_dark.css'})}},()=>{}).find(d=>d.label==='主题').entries();return entries.some(entry=>entry.label==='柔和夜色'&&entry.checked)&&!entries.find(entry=>entry.label==='CppGithubConsoles_Dark').checked;})()`,'主题菜单展示自定义方案且只有实际方案勾选');
 await ev(`qa.activate_color_profile('dark',()=>{});void 0`);await pause(20);
 await ev(`input('markdown_link','#456789');document.querySelector('[aria-label="对照配色方案"]').value='dark';document.querySelector('[aria-label="对照配色方案"]').dispatchEvent(new Event('change'));void 0`);await pause(350);
 await check(`qa.read_color_config().profiles[0].colors.markdown_link==='#456789'&&!qa.read_color_config().themes.dark.markdown_link`,'方案编辑不覆盖基础配置');
 await check(`document.querySelectorAll('.workspace-color-preview').length===2&&getComputedStyle(document.querySelectorAll('.workspace-color-preview')[1].parentElement).display!=='none'`,'双方案并排预览');
 await ev(`document.querySelector('.workspace-color-preview').contentDocument.querySelector('[data-color-target=markdown_link]').click();void 0`);
 await check(`document.querySelector('[data-color-row=markdown_link]').dataset.colorSelected==='true'`,'点击模板链接反向定位颜色行');
 await ev(`document.querySelector('[aria-label="新配色方案名称"]').value='柔和夜色';action('duplicate');void 0`);
 await check(`qa.read_color_config().profiles.length===1`,'重名另存拒绝且保留已有方案');
 await ev(`document.querySelector('.workspace-color-toolbar select').value='dark';document.querySelector('.workspace-color-toolbar select').dispatchEvent(new Event('change'));void 0`);await pause(350);
 await check(`color('#write a')==='rgb(92, 164, 223)'`,'保留用户试选默认链接色');
 await ev(`input('markdown_link','#789abc');input('ui_chrome','#182838');input('markdown_table_border','#abcdef');input('terminal_red','#aa1122');input('markdown_syntax_string','#228844');void 0`);await pause(100);
 await check(`color('#write a')==='rgb(120, 154, 188)'&&color('#write a',shadow)===color('#write a')`,'试色即时传播正文和Shadow');
 await check(`getComputedStyle(document.querySelector('#typora-sidebar')).backgroundColor==='rgb(24, 40, 56)'&&qa.terminal_theme().red==='#AA1122'`,'工作台和终端API跟随同一配置');
 await check(`getComputedStyle(document.querySelector('#write td')).borderTopColor==='rgb(171, 205, 239)'&&getComputedStyle(document.querySelector('#write td')).borderTopWidth==='2px'&&document.querySelector('[data-color-key=markdown_syntax_string]').readOnly`,'表格边线可调且宽度保持，代码语法归VS Code配置');
 await check(`values.get('workspace_colors').themes.dark.markdown_link==='#789ABC'&&document.querySelector('#write').innerHTML===before&&getComputedStyle(document.querySelector('#write h1')).fontSize===geometry`,'改动自动落盘且不改正文及排版');
 await ev(`const search=document.querySelector('.workspace-settings>input');search.value='markdown_link';search.dispatchEvent(new Event('input'));void 0`);
 await check(`document.querySelector('[data-color-key=markdown_link]').value==='#789ABC'&&qa.read_color_config().themes.dark.ui_chrome==='#182838'`,'搜索配色项保留已自动保存颜色');
 await ev(`input('markdown_link','red;display:none');void 0`);
 await check(`values.get('workspace_colors').themes.dark.markdown_link==='#789ABC'&&document.querySelector('[aria-invalid=true]')&&color('#write a')==='rgb(120, 154, 188)'`,'无效色值不能保存或注入CSS');
 await ev(`window.fail_save=true;input('markdown_link','#789abc80');void 0`);
 await check(`values.get('workspace_colors').themes.dark.markdown_link==='#789ABC'&&document.querySelector('.workspace-settings-status').textContent.includes('磁盘')`,'保存失败保留旧配置和可重试草稿');
 await ev(`window.fail_save=false;input('markdown_link','#789abc80');void 0`);
 await check(`values.get('workspace_colors').themes.dark.markdown_link==='#789ABC80'`,'透明度完整保存');
 await ev(`input('markdown_link','#123456');document.querySelector('.workspace-dialog-close').click();void 0`);await pause(80);
 await check(`qa.read_color_config().themes.dark.markdown_link==='#123456'&&!document.querySelector('.workspace-settings-modal')`,'关闭保留自动保存颜色');
 await ev(`commands.get('typora_code:custom_colors')();action('export');void 0`);await pause(120);
 assert(fs.existsSync(path.join(base,'colors.json')),'导出真实文件');checks.push('原生另存为端口返回路径后写入真实UTF8文件');
 const exported=fs.readFileSync(path.join(base,'colors.json'),'utf8');assert.equal(JSON.parse(exported).themes.dark.markdown_link,'#123456');
 await check(`qa.serialize_color_config(qa.parse_color_config(${JSON.stringify(exported)}))===${JSON.stringify(exported)}`,'JSON往返保持透明度及所有主题');
 await ev(`window.cancel_export=true;input('markdown_link','#111111');action('export');void 0`);await pause(60);assert.equal(fs.readFileSync(path.join(base,'colors.json'),'utf8'),exported);checks.push('取消导出不改文件');
 const imported=JSON.stringify({schema:1,themes:{light:{markdown_link:'#234'},dark:{markdown_link:'#678'}}});
 await ev(`import_text(${JSON.stringify(imported)})`);
 await check(`qa.read_color_config().themes.dark.markdown_link==='#667788'&&values.get('workspace_colors').themes.light.markdown_link==='#223344'`,'导入完整校验后自动保存两主题');
 for(const value of ['{',JSON.stringify({schema:2,themes:{light:{},dark:{}}}),JSON.stringify({schema:1,themes:{light:{},dark:{bogus:'#123'}}}),JSON.stringify({schema:1,themes:{light:{},dark:{markdown_link:'url(bad)'}}}),JSON.stringify({schema:1,themes:{light:[],dark:{}}})]){await ev(`import_text(${JSON.stringify(value)})`);await check(`qa.read_color_config().themes.dark.markdown_link==='#667788'`,'非法JSON原子拒绝 '+value);}
 await ev(`document.querySelector('.workspace-color-toolbar select').value='light';document.querySelector('.workspace-color-toolbar select').dispatchEvent(new Event('change'));document.querySelector('#theme_css').setAttribute('href','cpp_github-consolas.css');void 0`);await pause(80);
 await check(`color('#write a')==='rgb(34, 51, 68)'&&document.querySelector('[data-color-key=markdown_link]').value==='#223344'`,'明暗分别保存并按实际主题应用');
 await ev(`document.querySelector('#theme_css').setAttribute('href','github.css');void 0`);await pause(80);
 await check(`color('#write a')==='rgb(204, 204, 204)'&&!document.documentElement.hasAttribute('data-workspace-colors')`,'其他主题退出全部覆盖');
 await ev(`document.querySelector('#theme_css').setAttribute('href','night.css');void 0`);await pause(80);
 await check(`color('#write a')==='rgb(102, 119, 136)'`,'回到Night恢复其自定义');
 await ev(`document.querySelector('.workspace-color-toolbar select').value='dark';document.querySelector('.workspace-color-toolbar select').dispatchEvent(new Event('change'));input('markdown_link','#123');[...document.querySelectorAll('.workspace-settings-categories button')].find(b=>b.textContent==='编辑器').click();void 0`);await pause(80);
 await check(`qa.read_color_config().themes.dark.markdown_link==='#112233'`,'离开分类保留颜色');
 await ev(`commands.get('typora_code:custom_colors')();window.finish_import=undefined;const picker=document.querySelector('[data-color-import]');Object.defineProperty(picker,'files',{configurable:true,value:[{text:()=>new Promise(r=>finish_import=r)}]});picker.dispatchEvent(new Event('change'));document.querySelector('.workspace-dialog-close').click();finish_import(${JSON.stringify(imported.replace('#678','#abc'))});void 0`);await pause(80);
 await check(`qa.read_color_config().themes.dark.markdown_link==='#112233'`,'关闭后迟到导入不能覆盖配置');
 await ev(`commands.get('typora_code:custom_colors')();action('inherit');void 0`);await pause(80);
 await check(`color('#write a')==='rgb(92, 164, 223)'&&Object.keys(qa.read_color_config().themes.dark).length===0&&qa.read_color_config().themes.light.markdown_link==='#223344'`,'整主题恢复继承不改另一个主题');
 await ev(`(async()=>{window.release_code=await qa.bind_code_theme();window.code_sample=document.createElement('code');code_sample.className='language-c';code_sample.textContent='p = rcu_dereference(table[id]);';const code_host=document.body.appendChild(document.createElement('div'));window.code_shadow=code_host.attachShadow({mode:'open'});code_shadow.innerHTML='<style></style><div id=write></div>';const pre=document.createElement('pre');pre.append(code_sample);code_shadow.querySelector('#write').append(pre);await qa.highlight_preview_code(code_sample);code_shadow.querySelector('style').textContent=qa.markdown_theme_rules();})()`);
 await check(`getComputedStyle(code_sample.querySelector('span')).color==='rgb(204, 204, 204)'&&getComputedStyle([...code_sample.querySelectorAll('span')].find(span=>span.textContent==='rcu_dereference')).color==='rgb(220, 220, 170)'`,'C预览使用相同官方默认前景和函数色');
 await ev(`release_code();void 0`);
 const menu=await ev(`(async()=>{const defs=qa.create_workspace_titlebar_definitions({core,context_root:()=>''}, {JSBridge:{invoke:async()=>({all:['night.css'],current:'night.css'})}},()=>{});const entries=await defs.find(d=>d.label==='主题').entries();return entries.map(e=>e.label)})()`);
 assert(menu.includes('自定义颜色…'));checks.push('顶部主题菜单包含自定义颜色');
 await ev(`window.writes=0;window.observer=new MutationObserver(r=>writes+=r.length);observer.observe(document.getElementById('typora-code-custom-colors'),{childList:true});const config=qa.read_color_config();for(let i=0;i<1000;i++)qa.save_color_config(config);void 0`);await pause(100);
 await check('writes===0','1000次同值保存不重复写样式');
 for(let i=0;i<20;i++){await ev(`document.querySelector('#theme_css').setAttribute('href',${JSON.stringify(i%2?'night.css':'cpp_github-consolas.css')});void 0`);await pause(20);}
 await check(`document.querySelector('#write').innerHTML===before`,'20次切主题正文保持');
 win.setContentSize(700,650);win.webContents.setZoomFactor(1.25);await pause(100);
 await check(`document.querySelector('.workspace-color-toolbar').scrollWidth<=document.querySelector('.workspace-color-toolbar').clientWidth+1`,'窄窗口125%操作栏换行');
 await ev(`observer.disconnect();unwatch();view.dispose();sections.dispose();binding.dispose();void 0`);
 await check(`!document.getElementById('typora-code-custom-colors')&&!commands.has('typora_code:custom_colors')`,'销毁释放命令、主题样式');
 fs.writeFileSync(path.join(base,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify({status:'PASS',count:checks.length,evidence:base}));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);fs.writeFileSync(path.join(base,'checks.json'),JSON.stringify({status:'ERROR',error:String(error.stack),checks},null,2));win?.destroy();app.exit(1)});
