// 独立隐藏Electron + 真实工作台核心和Monaco；全部文件与历史位于临时目录。
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_explorer_history_')),folder=path.join(root,'repo'),first=path.join(folder,'one.c'),second=path.join(folder,'two.c');fs.mkdirSync(folder);fs.writeFileSync(first,'int original = 1;\n');fs.writeFileSync(second,'int second = 2;\n');
const git=(...args)=>execFileSync('git',args,{cwd:folder,encoding:'utf8',windowsHide:true});git('init','-q');git('add','.');git('-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','initial');
app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();let win;const checks=[];
app.whenReady().then(async()=>{
  win=new BrowserWindow({show:false,width:1180,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
  const page=path.join(root,'test.html');fs.writeFileSync(page,'<!doctype html><body><div id="typora-sidebar"><div id="sidebar-content"><div id="outline-content"></div><div id="file-library"></div><div id="file-library-search"><div><input id="file-library-search-input"></div></div><div id="file-library-search-result"></div></div></div><div id="typora-sidebar-resizer"></div><content><div id="write"></div></content><footer id="footer"><span id="footer-word-count"></span></footer>');await win.loadFile(page);
  win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
  const evaluate=source=>win.webContents.executeJavaScript(source),delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async source=>{for(let i=0;i<320;i++){if(await evaluate('(async()=>('+source+'))()'))return;await delay(25);}throw Error('Timeout: '+source);};
  const check=async(source,title)=>{if(!await evaluate('(async()=>('+source+'))()')){fs.writeFileSync(path.join(root,'failure.png'),(await win.webContents.capturePage()).toPNG());console.log('Visible menus:',await evaluate('JSON.stringify([...document.querySelectorAll("[role=menu]")].map(node=>({text:node.textContent,rect:node.getBoundingClientRect().toJSON()})))'));assert.fail(title);}checks.push(title);};
  const click=async(selector,button='left')=>{const point=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw Error('Missing '+${JSON.stringify(selector)});const r=node.getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()`);for(const type of ['mouseMove','mouseDown','mouseUp']){win.webContents.sendInputEvent({type,...point,button,clickCount:1});await delay(25);}};
  const key=async key_code=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key_code});win.webContents.sendInputEvent({type:'keyUp',keyCode:key_code});await delay(50);};
  await evaluate(`window.$=window.jQuery=require(${JSON.stringify(require.resolve('jquery'))});window.fixture_errors=[];window.addEventListener('error',e=>fixture_errors.push(String(e.error?.stack||e.error)));window.addEventListener('unhandledrejection',e=>fixture_errors.push(String(e.reason?.stack||e.reason)));window.reqnode=name=>require(name);window._options={userDataPath:${JSON.stringify(root)},mountFolder:${JSON.stringify(folder)},appLocale:'en',locale:'en'};
    window.fixture_object=()=>new Proxy(function(){},{get(target,key){if(key in target)return target[key];if(key==='then'||typeof key==='symbol')return undefined;return target[key]=fixture_object();}});
    window.editor=fixture_object();editor.writingArea=document.querySelector('#write');editor.library=fixture_object();editor.selection=fixture_object();editor.sourceView=fixture_object();editor.nodeMap={allNodes:{_set:[],first:()=>null}};editor.getMarkdown=()=>'';
    window.File=fixture_object();File.isNode=true;File.isMac=false;File.isWin=true;File.isReadonlyMode=false;File.isLocked=false;File.filePath='';File.bundle={filePath:''};File.option={};File.getMountFolder=()=>_options.mountFolder;File.setMountFolder=path=>_options.mountFolder=path;File.editor=editor;
    window.JSBridge=fixture_object();window.bridge=fixture_object();window.ClientCommand=fixture_object();window.CodeMirror=fixture_object();window.gettext=value=>value;void 0`);
  fs.mkdirSync(path.join(root,'typora_code','locales'),{recursive:true});for(const name of fs.readdirSync(path.join(__dirname,'../dist/locales')))fs.copyFileSync(path.join(__dirname,'../dist/locales',name),path.join(root,'typora_code','locales',name));
  await evaluate(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.js'),'utf8'));await evaluate('window.runtime=window[Symbol.for("typora-code:workspace")];runtime.ready');
  await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.css'),'utf8'));await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'));
  await win.webContents.insertCSS('html,body{width:100%;height:100%;margin:0;overflow:hidden;color:#24292f;background:#fff}.typ-ribbon,content{display:none!important}#typora-sidebar{display:block!important;position:fixed!important;left:0!important;top:0!important;width:340px!important;bottom:0!important;height:100%!important}#sidebar-content{position:absolute;inset:0}.typ-workspace-root{z-index:1!important;position:fixed!important;left:340px!important;right:0!important;top:0!important;bottom:0!important}.typ-workspace-split,.typ-workspace-tabs{min-width:0}.typ-workspace-tab-header{height:35px}.typ-tabs{display:flex}.typ-tab{height:35px;max-width:200px}footer{position:fixed;bottom:0}.typ-close:before{content:"×"}');
  const bundle=await require('esbuild').build({plugins:require('./editor_bundle.cjs').editor_plugins(),stdin:{contents:'export {bind_workspace_files} from "./src/workspace_files";export {bind_workspace_explorer} from "./src/workspace_explorer";export {bind_workspace_editor_actions} from "./src/workspace_editor_actions";export {bind_workspace_save_service} from "./src/workspace_save_service";export {bind_workspace_explorer_sections} from "./src/workspace_explorer_sections";export * from "./src/workspace_save_settings";export * from "./src/workspace_file_events";export {editor as monaco_editor,MarkerSeverity} from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.css':'text'},format:'iife',globalName:'history_qa'});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`window.notices=[];runtime.Notice=class{constructor(message){notices.push(message)}};window.ws=runtime.app.workspace;window.leaves=()=>{const result=[];ws.eachLeaves(leaf=>{result.push(leaf);});return result;};window.native_dirty=false;window.native_foreground=true;window.native_text="";window.native_failure=false;window.native_attempts=0;File.changeCounter={isDocumentEdited:()=>native_dirty};File.updateChangeCount=value=>{native_dirty=value;};File.isActiveWindow=()=>native_foreground;File.isFileLoading=()=>false;File.inSavingProcess=false;File._onFileSwitching=false;File._onInitParse=false;File.editor.sourceView.inSourceMode=false;File.saveUseNode=async function(save_as,silent){if(!this.isActiveWindow())return false;native_attempts++;if(native_failure)return false;require("fs").writeFileSync(this.bundle.filePath,native_text);native_dirty=false;JSBridge.invoke("app.sendEvent","didSave",{path:this.bundle.filePath});return true;};JSBridge.invoke=async()=>null;
    window.files=history_qa.bind_workspace_files(runtime);window.actions=history_qa.bind_workspace_editor_actions(files,{open(){throw Error('Unexpected window action')}});window.saves=history_qa.bind_workspace_save_service(files);window.explorer=history_qa.bind_workspace_explorer(runtime,{open_file:files.open_file,context_root:files.context_root,active_file:files.current_file,open_folder(){},copy:files.copy});window.original_root_menu=explorer.container.querySelector(".workspace-explorer-root-name").oncontextmenu;window.sections=history_qa.bind_workspace_explorer_sections(files,explorer,saves,actions.entries);explorer.show();window.first_path=${JSON.stringify(first)};window.second_path=${JSON.stringify(second)};void 0`);
  await evaluate('(async()=>{for(const leaf of leaves())await files.close_leaf(leaf);})()');await delay(60);
  await check('document.querySelectorAll(".workspace-explorer-open-row").length===0','empty layout contributes no fake New tab editor');
  await evaluate('(async()=>{window.empty_leaf=ws.activeLeaf;for(let i=0;i<100;i++)await files.close_leaf(empty_leaf);})()');
  await check('ws.activeLeaf===empty_leaf&&leaves().length===1','closing an empty group is idempotent instead of generating new placeholder identities');
  await check('document.querySelector(".workspace-explorer-opened-list").getBoundingClientRect().height===0','default empty Open Editors uses no reserved row');
  await evaluate('runtime.app.viewManager.registerView("fixture.blank",leaf=>new(class extends runtime.WorkspaceView{containerEl=document.createElement("section")})(leaf));window.blank=ws.createLeaf({type:"fixture.blank",state:{path:""}});ws.activeLeaf.parent.appendChild(blank);ws.activeLeaf=blank;void 0');await delay(60);
  await check('document.querySelectorAll(".workspace-explorer-open-row").length===1','a real untitled document with an empty path remains visible');
  await evaluate('native_dirty=true;void 0');
  await check('files.editor_state(blank).dirty','real untitled draft retains dirty protection');
  await evaluate('native_dirty=false;files.close_leaf(blank)');await delay(60);
  await evaluate('files.open_file(first_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.first=ws.activeLeaf;files.keep_open(first);void 0');
  await evaluate('files.open_file(second_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.second=ws.activeLeaf;void 0');
  await wait('[...document.querySelectorAll(".workspace-explorer-open-file")].some(button=>button.dataset.editorPath===first_path)&&[...document.querySelectorAll(".workspace-explorer-open-file")].some(button=>button.dataset.editorPath===second_path)');await check('document.querySelector(".workspace-explorer-opened")&&document.querySelector(".workspace-timeline")','Open Editors, Folders and Timeline bind to real leaves');
  // 模拟正文主题的等宽字体；工作台内容不能跟随正文配置。
  await evaluate("document.documentElement.style.setProperty('--monospace','Courier New');document.documentElement.style.setProperty('--font-family','Georgia');void 0");
  await check("['.workspace-explorer-toolbar strong','.workspace-explorer-name','.workspace-explorer-open-name'].every(selector=>getComputedStyle(document.querySelector(selector)).fontFamily.includes('Segoe'))",'Explorer title and file labels use UI typography independent of document theme');
  await check("getComputedStyle(document.querySelector('.workspace-explorer-name')).fontSize==='13px'&&getComputedStyle(document.querySelector('.workspace-explorer-name')).fontWeight==='400'",'file content has regular 13px body role');
  await evaluate(`window.header_geometry=()=>[...document.querySelectorAll('.workspace-explorer-opened>.workspace-explorer-section-heading,.workspace-explorer-root,.workspace-timeline>.workspace-explorer-section-heading')].map(heading=>{const title=heading.querySelector('.workspace-explorer-section-label,.workspace-explorer-root-name')||heading.querySelector('.workspace-explorer-section-title');const text=[...title.childNodes].find(node=>node.nodeType===Node.TEXT_NODE),range=document.createRange();range.selectNodeContents(text||title);const label=range.getBoundingClientRect(),icon=heading.querySelector('svg').getBoundingClientRect(),box=heading.getBoundingClientRect(),style=getComputedStyle(title);return{icon:icon.left,label:label.left,text_height:label.height,center:label.top+label.height/2-box.top,height:box.height,font:style.fontFamily,size:style.fontSize,weight:style.fontWeight};});void 0`);
  await check('(()=>{const rows=header_geometry();return rows.length===3&&rows.every(row=>row.height===28&&row.size==="12px"&&row.weight==="600"&&row.font.includes("Segoe")&&Math.abs(row.icon-rows[0].icon)<.1&&Math.abs(row.label-rows[0].label)<.1&&Math.abs(row.center-rows[0].center)<.1&&Math.abs(row.text_height-rows[0].text_height)<.1)})()','all three Explorer section arrows, actual text boxes and UI typography share one 28px header contract');
  await check('header_geometry().every(row=>Math.abs(row.icon-document.querySelector(".linux-note-workspace-explorer").getBoundingClientRect().left-4)<.1&&Math.abs(row.label-row.icon-20)<.1)','R061 Explorer section arrows start at 4px with a shared 16px icon and 4px text gap');
  for(const selector of ['.workspace-explorer-opened','.workspace-explorer-folders','.workspace-timeline']){
    const point=await evaluate(`(()=>{const node=document.querySelector('${selector} .workspace-section-title'),r=node.getBoundingClientRect();return{x:Math.round(r.left+25),y:Math.round(r.top+r.height/2)}})()`);
    win.webContents.sendInputEvent({type:'mouseMove',...point});await delay(40);
    await check(`(()=>{const node=document.querySelector('${selector} .workspace-section-header'),style=getComputedStyle(node),title=node.querySelector('.workspace-section-title');return style.marginLeft==='4px'&&style.marginRight==='4px'&&style.paddingLeft==='0px'&&style.backgroundColor!=='rgba(0, 0, 0, 0)'&&getComputedStyle(title).backgroundColor==='rgba(0, 0, 0, 0)';})()`,'R061 full header hover with transparent title and shared margins '+selector);
  }
  fs.writeFileSync(path.join(root,'header_geometry.json'),JSON.stringify({viewport:win.getContentSize(),scale:await evaluate('devicePixelRatio'),rows:await evaluate('header_geometry()')},null,2));
  const section_selectors=['.workspace-explorer-opened','.workspace-explorer-folders','.workspace-timeline'];
  // sendInputEvent 不从 keyDown 合成 char；原生 button 的 Enter/空格激活需要完整浏览器输入序列。
  const header_key=async key_code=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key_code});win.webContents.sendInputEvent({type:'char',keyCode:key_code==='Enter'?'\r':' '});win.webContents.sendInputEvent({type:'keyUp',keyCode:key_code});await delay(50);};
  for(const selector of section_selectors){
    await evaluate(`document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-title')}).focus();void 0`);
    if(await evaluate(`document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-title')}).getAttribute('aria-expanded')==='true'`))await header_key('Enter');
    await check(`document.querySelector(${JSON.stringify(selector)}).classList.contains('is-collapsed')&&getComputedStyle(document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-actions')})).display==='none'`,'keyboard collapse hides the '+selector+' actions without reserving space');
  }
  await check('(()=>{const rows=header_geometry();return rows.every(row=>row.height===28&&row.label===rows[0].label&&row.icon===rows[0].icon&&row.center===rows[0].center)})()','collapsed Explorer sections keep aligned arrows and actual text boxes');
  fs.writeFileSync(path.join(root,'headers_collapsed.png'),(await win.webContents.capturePage()).toPNG());
  for(const selector of section_selectors){
    await evaluate(`document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-title')}).focus();void 0`);await header_key('Space');
    await check(`document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-title')}).getAttribute('aria-expanded')==='true'&&getComputedStyle(document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-actions')})).display==='flex'`,'Space expands '+selector+' and reveals keyboard-accessible actions');
  }
  await evaluate('document.activeElement.blur();void 0');win.webContents.sendInputEvent({type:'mouseMove',x:1100,y:600});await delay(30);
  await check('[...document.querySelectorAll(".workspace-explorer-section-actions")].every(actions=>getComputedStyle(actions).display==="none")','expanded section actions disappear after pointer and keyboard focus leave the Explorer');
  await evaluate('window.normal_root_label=document.querySelector(".workspace-explorer-root-name").textContent;document.querySelector(".workspace-explorer-root-name").textContent="very_long_workspace_directory_name_中文名称_0123456789";document.querySelector("#typora-sidebar").style.setProperty("width","170px","important");void 0');
  for(const theme of ['light','dark']){
    await evaluate(`document.documentElement.dataset.workspaceFileIconTheme=${JSON.stringify(theme)};document.documentElement.style.setProperty('--text-color',${JSON.stringify(theme==='dark'?'#ededed':'#202020')});document.documentElement.style.setProperty('--side-bar-bg-color',${JSON.stringify(theme==='dark'?'#191a1b':'#fafafd')});void 0`);
    for(const selector of section_selectors){
      await evaluate(`document.querySelector(${JSON.stringify(selector+' .workspace-explorer-section-title')}).focus();void 0`);
      await check(`(()=>{const section=document.querySelector(${JSON.stringify(selector)}),header=section.querySelector('.workspace-explorer-section-heading'),title=header.querySelector('.workspace-explorer-section-title'),actions=header.querySelector('.workspace-explorer-section-actions'),a=actions.getBoundingClientRect(),t=title.getBoundingClientRect(),h=header.getBoundingClientRect();return getComputedStyle(actions).display==='flex'&&t.width>=20&&t.right<=a.left+.1&&a.right<=h.right&&h.height===28&&[...actions.querySelectorAll('button')].every(button=>{const r=button.getBoundingClientRect();return r.top>=h.top&&r.bottom<=h.bottom&&r.width===20&&r.height===20;})})()`,'170px '+theme+' '+selector+' keeps toggle and actions in one non-overlapping header row');
    }
    await check('getComputedStyle(document.querySelector(".workspace-explorer-root-name")).textOverflow==="ellipsis"&&document.querySelector(".workspace-explorer-root-name").scrollWidth>document.querySelector(".workspace-explorer-root-name").clientWidth','long root label truncates instead of shifting the common title inset in '+theme);
    await check('document.querySelector(".workspace-timeline .workspace-explorer-section-label").scrollWidth===document.querySelector(".workspace-timeline .workspace-explorer-section-label").clientWidth','narrow Timeline keeps its section title before truncating the secondary file name in '+theme);
    await check("[...document.querySelectorAll('.workspace-explorer-section-actions button')].filter(button=>button.getBoundingClientRect().width>0).every(button=>{const box=button.getBoundingClientRect(),icon=button.querySelector('svg').getBoundingClientRect();return icon.width===16&&icon.height===16&&Math.abs(icon.left+8-box.left-box.width/2)<.1&&Math.abs(icon.top+8-box.top-box.height/2)<.1;})",'secondary actions keep actual 16px glyphs centered inside their hit area in '+theme);
    fs.writeFileSync(path.join(root,'headers_narrow_'+theme+'.png'),(await win.webContents.capturePage()).toPNG());
  }
  await evaluate('document.querySelector(".workspace-explorer-root-name").textContent=normal_root_label;document.querySelector("#typora-sidebar").style.removeProperty("width");document.documentElement.dataset.workspaceFileIconTheme="light";document.documentElement.style.removeProperty("--text-color");document.documentElement.style.removeProperty("--side-bar-bg-color");void 0');
  await evaluate('document.querySelector(".workspace-explorer-root .workspace-explorer-section-title").focus();void 0');await key('Tab');
  await check('document.activeElement?.getAttribute("aria-label")==="新建文件"','expanded folder toolbar is reachable by Tab from its heading');
  await click('.workspace-timeline .workspace-explorer-section-title');
  await click('.workspace-explorer-open-file[data-editor-path$="one.c"]');await wait('ws.activeLeaf===first');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"afterDelay","files.autoSaveDelay":30,"workbench.localHistory.mergeWindow":0});first.view.editor.focused_editor().getModel().setValue("int autosaved = 3;\\n");void 0');
  await wait('!files.editor_state(first).dirty');assert.equal(fs.readFileSync(first,'utf8'),'int autosaved = 3;\n');await wait('(await saves.history.list(first_path)).length===1');checks.push('source edit automatically saves exact buffer and creates history');
  await evaluate('first.view.editor.focused_editor().getModel().setValue("int autosaved = 4;\\n");void 0');await wait('(await saves.history.list(first_path)).length===2');
  await click('.workspace-timeline .workspace-explorer-section-title');await wait('document.querySelectorAll(".workspace-timeline-entry[data-history-source=local]").length===2');await wait('document.querySelectorAll(".workspace-timeline-entry[data-history-source=git]").length===1');checks.push('Timeline combines saved history with actual Git file history');
  await check("(()=>{const entry=document.querySelector('.workspace-timeline-entry'),label=entry.querySelector('.workspace-timeline-label'),date=entry.querySelector('.workspace-timeline-date');return getComputedStyle(label).fontFamily.includes('Segoe')&&getComputedStyle(label).fontSize==='13px'&&getComputedStyle(label).fontWeight==='400'&&getComputedStyle(date).fontSize==='11px'&&getComputedStyle(date).fontFamily===getComputedStyle(label).fontFamily&&getComputedStyle(date).color!==getComputedStyle(label).color;})()",'Timeline content and secondary dates share UI typography with distinct metadata emphasis');
  const child_count=await evaluate('document.querySelectorAll(".workspace-timeline-entry").length');await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"off"});first.view.editor.focused_editor().getModel().setValue("int draft = 5;\\n");void 0');await delay(160);assert.equal(await evaluate('document.querySelectorAll(".workspace-timeline-entry").length'),child_count);assert.equal(fs.readFileSync(first,'utf8'),'int autosaved = 4;\n');
  await click('.workspace-timeline [aria-label="筛选时间线来源"]');await wait('!!document.querySelector("[role=menu]")');await evaluate('[...document.querySelectorAll("[role=menuitemcheckbox]")].find(node=>node.textContent.includes("Git 历史"))?.click();void 0');await key('Escape');
  await evaluate('runtime.app.commands.run("linux_note:local_history_restore");void 0');await wait('!!document.querySelector(".workspace-history-picker input")');
  await check('document.querySelector(".workspace-history-picker input").placeholder==="选择要查看本地历史的文件"','history recovery starts with file selector');await key('Enter');await wait('document.querySelector(".workspace-history-picker input")?.placeholder==="选择要打开的本地历史条目"');await key('Down');
  await check('document.querySelectorAll(".workspace-history-picker [role=option]")[1].getAttribute("aria-selected")==="true"','history keyboard navigation selects the older snapshot');await key('Enter');await wait('!!document.querySelector(".workspace-history-document [data-history-restore]")');
  await check('ws.activeLeaf.state.path.startsWith("typ://typora_code.local_history/")','second selector opens a real read-only diff document');
  await delay(100);await check('(()=>{const leaf=ws.activeLeaf.containerEl.getBoundingClientRect(),view=ws.activeLeaf.view.containerEl.getBoundingClientRect(),body=ws.activeLeaf.view.editor.body.getBoundingClientRect();return Math.abs(view.width-leaf.width)<2&&Math.abs(body.width-view.width)<2})()','history comparison fills its actual editor group instead of shrinking to a default Monaco width');
  await click('.workspace-history-document [data-history-restore]');await wait('!!document.querySelector("[role=dialog][aria-label=恢复文件内容]")');await check('document.querySelector("[aria-label=恢复文件内容]").textContent.includes("保存当前修改并恢复")','restore explains how unsaved edits are preserved');
  await evaluate('[...document.querySelectorAll("[aria-label=恢复文件内容] button")].find(node=>node.textContent==="保存当前修改并恢复").click();void 0');await wait('!document.querySelector("[aria-label=恢复文件内容]")');await wait('!files.editor_state(first).busy&&ws.activeLeaf===first');assert.equal(fs.readFileSync(first,'utf8'),'int autosaved = 3;\n');await check('(await Promise.all((await saves.history.list(first_path)).map(async entry=>new TextDecoder().decode(await saves.history.read(entry))))).includes("int draft = 5;\\n")','restore retains the exact unsaved draft in history before replacing disk contents');
  // 历史比较在异步保留恢复前版本期间关闭，迟到任务不得写回已经取消的目标。
  await evaluate('runtime.app.commands.run("linux_note:local_history_restore");void 0');await wait('document.querySelector(".workspace-history-picker input")?.placeholder==="选择要查看本地历史的文件"');await key('Enter');await wait('document.querySelector(".workspace-history-picker input")?.placeholder==="选择要打开的本地历史条目"');await key('Enter');await wait('ws.activeLeaf.state.path.startsWith("typ://typora_code.local_history/")');
  await evaluate('window.cancel_restore_leaf=ws.activeLeaf;cancel_restore_leaf.view.containerEl.dataset.historyFixture="cancel";window.restore_record=saves.history.record;window.restore_rename=require("fs").promises.rename;window.restore_writes=0;window.restore_blocked=false;saves.history.record=async(...args)=>{if(args[2]==="Before Restore"){restore_blocked=true;await new Promise(resolve=>window.release_restore=resolve);}return restore_record(...args)};require("fs").promises.rename=async(...args)=>{if(args[1]===first_path)restore_writes++;return restore_rename(...args)};void 0');
  const cancel_before=fs.readFileSync(first);
  await click('[data-history-fixture=cancel] [data-history-restore]');await evaluate('[...document.querySelectorAll("[aria-label=恢复文件内容] button")].find(node=>node.textContent==="恢复").click();void 0');await wait('restore_blocked');
  await evaluate('cancel_restore_leaf.parent.removeTab(cancel_restore_leaf.state.path);void 0');await delay(30);await evaluate('release_restore();void 0');await delay(160);
  assert.equal(await evaluate('restore_writes'),0,'closing the history comparison cancels a pending restore before disk replacement');assert.deepEqual(fs.readFileSync(first),cancel_before);await check('!document.querySelector("[aria-label=恢复文件内容]")','closing the history comparison also closes its owned restore confirmation');
  await evaluate('saves.history.record=restore_record;require("fs").promises.rename=restore_rename;void 0');await click('.workspace-explorer-open-file[data-editor-path$="one.c"]');
  await click('.workspace-explorer-toolbar [aria-label="资源管理器视图"]');await wait('!!document.querySelector(".git-graph-menu[role=menu]")');await check('document.querySelector(".git-graph-menu[role=menu]").textContent.includes("打开的编辑器")&&document.querySelector(".git-graph-menu[role=menu]").textContent.includes("时间线")','Explorer visibility menu contains the three view sections');await key('Escape');
  await evaluate('window.section_menu_count=0;window.section_menu_observer=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node instanceof HTMLElement&&node.classList.contains("git-graph-menu"))section_menu_count++;});section_menu_observer.observe(document.body,{childList:true});void 0');
  await click('.workspace-explorer-root-name','right');await wait('!!document.querySelector(".git-graph-menu[role=menu]")');await check('section_menu_count===1&&document.querySelector(".git-graph-menu").textContent.includes("打开的编辑器")','folder section title creates one visibility menu without first opening file operations');await key('Escape');await evaluate('section_menu_observer.disconnect();void 0');
  await evaluate('history_qa.set_workspace_save_settings({"explorer.openEditors.enabled":false,"timeline.enabled":false});void 0');await check('document.querySelector(".workspace-explorer-opened").hidden&&document.querySelector(".workspace-timeline").hidden','section visibility applies immediately');
  await evaluate('history_qa.set_workspace_save_settings({"explorer.openEditors.enabled":true,"timeline.enabled":true});void 0');
  await evaluate('document.documentElement.style.setProperty("--linux-note-shell-inactive-selection-background","#37373d");document.documentElement.style.setProperty("--linux-note-shell-inactive-selection-foreground","#cccccc");void 0');await check('getComputedStyle(document.querySelector(".workspace-explorer-open-row.is-active")).backgroundColor==="rgb(55, 55, 61)"','Open Editors selected state follows theme tokens');
  fs.writeFileSync(path.join(root,'explorer_history.png'),(await win.webContents.capturePage()).toPNG());
  await click('.workspace-explorer-root-name');await check('document.querySelector(".workspace-explorer-tree").hidden','Folders collapse independently');await evaluate('explorer.refresh();void 0');await delay(100);await check('!!document.querySelector(".workspace-explorer-folder-caret svg")','refresh preserves the folder section toggle');await click('.workspace-explorer-folder-caret');await check('!document.querySelector(".workspace-explorer-tree").hidden','folder caret expands the same tree');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"onFocusChange"});first.view.editor.focused_editor().getModel().setValue("int focus_saved = 6;\\n");void 0');await click('.workspace-explorer-open-file[data-editor-path$="two.c"]');await wait('!files.editor_state(first).dirty');assert.equal(fs.readFileSync(first,'utf8'),'int focus_saved = 6;\n');checks.push('changing active document triggers onFocusChange save');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"onWindowChange"});second.view.editor.focused_editor().getModel().setValue("int window_saved = 7;\\n");void 0');await click('.workspace-explorer-open-file[data-editor-path$="one.c"]');await delay(80);assert.equal(fs.readFileSync(second,'utf8'),'int second = 2;\n');await evaluate('window.dispatchEvent(new Event("blur"));void 0');await wait('!files.editor_state(second).dirty');assert.equal(fs.readFileSync(second,'utf8'),'int window_saved = 7;\n');checks.push('onWindowChange ignores tab switches and saves on window blur');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"afterDelay","files.autoSaveDelay":20,"files.autoSaveWhenNoErrors":true});history_qa.monaco_editor.setModelMarkers(second.view.editor.models[0],"fixture",[{severity:8,message:"fixture error",startLineNumber:1,startColumn:1,endLineNumber:1,endColumn:4}]);second.view.editor.models[0].setValue("int errors_block_save = 9;\\n");void 0');await delay(100);assert.equal(fs.readFileSync(second,'utf8'),'int window_saved = 7;\n');await check('files.has_editor_errors(second)&&files.editor_state(second).dirty','diagnostic errors prevent automatic save when configured');
  await evaluate('history_qa.monaco_editor.setModelMarkers(second.view.editor.models[0],"fixture",[]);second.view.editor.models[0].setValue("int errors_cleared = 10;\\n");void 0');await wait('!files.editor_state(second).dirty');assert.equal(fs.readFileSync(second,'utf8'),'int errors_cleared = 10;\n');checks.push('automatic saving resumes when the edited document has no errors');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"off"});second.view.editor.focused_editor().getModel().setValue("int keep_draft = 8;\\n");void 0');await delay(50);await click('.workspace-explorer-open-row.is-active','right');await wait('!!document.querySelector(".git-graph-menu [data-action=close_saved]")');await check('document.querySelector(".git-graph-menu button").dataset.action==="close"','single-editor file exposes the shared close commands');await click('.git-graph-menu [data-action=close_saved]');await wait('leaves().length===1&&leaves()[0]===second');await check('files.editor_state(second).dirty','Close Saved retains the unsaved editor');
  await click('.workspace-explorer-open-row>.git-icon-button');await wait('!!document.querySelector("[role=dialog]")');await key('Escape');await check('leaves().includes(second)&&files.editor_state(second).dirty','canceling close keeps the dirty document');
  const markdown=path.join(folder,'readme.md');fs.writeFileSync(markdown,'# Markdown\n');await evaluate(`files.open_file(${JSON.stringify(markdown)},{source:true})`);await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await delay(80);await click('.workspace-explorer-open-file[data-editor-path$="readme.md"]','right');await wait('!!document.querySelector(".git-graph-menu [data-action=reopen]")');await check('document.querySelector(".git-graph-menu button").dataset.action==="reopen"','Markdown context menu starts with shared Reopen With');await key('Escape');
  const native_path=path.join(folder,'native.md');fs.writeFileSync(native_path,'# Native baseline\n');await evaluate(`window.native_path=${JSON.stringify(native_path)};runtime.app.viewManager.registerView("fixture.native",leaf=>new(class extends runtime.WorkspaceView{containerEl=document.createElement("section");isEditor(){return true;}})(leaf));window.native_leaf=ws.createLeaf({type:"fixture.native",state:{path:native_path}});ws.activeLeaf.parent.appendChild(native_leaf);ws.activeLeaf=native_leaf;File.bundle={filePath:native_path};history_qa.set_workspace_save_settings({"files.autoSave":"afterDelay","files.autoSaveDelay":20});native_text="# Native automatically saved\\n";File.updateChangeCount(true);void 0`);await wait('!native_dirty');assert.equal(fs.readFileSync(native_path,'utf8'),'# Native automatically saved\n');await wait('(await saves.history.list(native_path)).length===1');checks.push('native dirty counter triggers silent save and successful didSave history');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"off"});native_text="# Native next\\n";File.updateChangeCount(true);if(File.option.enableAutoSave)File.saveUseNode(false,true);void 0');await delay(100);assert.equal(fs.readFileSync(native_path,'utf8'),'# Native automatically saved\n');checks.push('off mode prevents independent native auto-save while keeping the draft');
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"onWindowChange"});native_foreground=false;window.dispatchEvent(new Event("blur"));void 0');await wait('!native_dirty');assert.equal(fs.readFileSync(native_path,'utf8'),'# Native next\n');await check('File.isActiveWindow()===false','native window-blur save restores the actual foreground state');
  await evaluate('ws.activeLeaf=second.parent.toggleTab(second.state.path);history_qa.set_workspace_save_settings({"files.autoSave":"afterDelay"});native_text="# Native while source tab active\\n";File.updateChangeCount(true);void 0');await wait('!native_dirty');await check('ws.activeLeaf===second','saving the loaded native document does not switch active source tab');assert.equal(fs.readFileSync(native_path,'utf8'),'# Native while source tab active\n');await wait('(await saves.history.list(native_path)).length===3');
  const native_before=await evaluate('native_attempts');await evaluate('native_failure=true;native_text="# Native failed draft\\n";File.updateChangeCount(true);void 0');await wait('notices.some(message=>message.includes("自动保存未完成"))');await delay(180);await check('native_dirty&&!document.querySelector(".git-graph-dialog")','native save failure retains the draft without a save dialog');assert.equal(await evaluate('native_attempts'),native_before+1);assert.equal(await evaluate('(async()=> (await saves.history.list(native_path)).length)()'),3);
  // 落盘已完成而历史flush尚未返回时销毁，迟到成功不能重新打开文件或重载编辑器。
  await evaluate('history_qa.set_workspace_save_settings({"files.autoSave":"off"});runtime.app.commands.run("linux_note:local_history_restore");void 0');await wait('document.querySelector(".workspace-history-picker input")?.placeholder==="选择要查看本地历史的文件"');await win.webContents.insertText('one.c');await key('Enter');await wait('document.querySelector(".workspace-history-picker input")?.placeholder==="选择要打开的本地历史条目"');await key('Enter');await wait('ws.activeLeaf.state.path.startsWith("typ://typora_code.local_history/")');
  await evaluate('ws.activeLeaf.view.containerEl.dataset.historyFixture="dispose";window.original_flush=saves.history.flush;window.original_refresh=files.refresh_files;window.original_open=files.open_file;window.original_reload=files.reload_active;window.late_file_actions=[];window.restore_flush_blocked=false;saves.history.flush=async()=>{await original_flush();window.restore_flush_blocked=true;await new Promise(resolve=>window.release_restore_flush=resolve);};files.refresh_files=(...args)=>{late_file_actions.push("refresh");return original_refresh(...args)};files.open_file=(...args)=>{late_file_actions.push("open");return original_open(...args)};files.reload_active=(...args)=>{late_file_actions.push("reload");return original_reload(...args)};void 0');
  await click('[data-history-fixture=dispose] [data-history-restore]');await evaluate('[...document.querySelectorAll("[aria-label=恢复文件内容] button")].find(node=>node.textContent==="恢复").click();void 0');await wait('restore_flush_blocked');
  await evaluate('sections.dispose();saves.dispose();release_restore_flush();void 0');await delay(120);assert.deepEqual(await evaluate('late_file_actions'),[]);await check('!document.querySelector("[aria-label=恢复文件内容]")','disposing history during final flush leaves no late file open, reload or restore confirmation');
  await evaluate('saves.history.flush=original_flush;files.refresh_files=original_refresh;files.open_file=original_open;files.reload_active=original_reload;void 0');
  await check('fixture_errors.length===0','no uncaught errors');await evaluate('sections.dispose();saves.dispose();actions.dispose();explorer.dispose();void 0');await check('!document.querySelector(".workspace-explorer-opened,.workspace-timeline,.workspace-history-picker")','disposal removes views and pending pickers');await check('explorer.container.querySelector(".workspace-explorer-root-name").oncontextmenu===original_root_menu','disposing sections restores the original folder title context handler');await check('explorer.container.querySelector(".workspace-explorer-root-name").parentElement.className==="workspace-explorer-root"&&!explorer.container.querySelector(".workspace-explorer-section-title,.workspace-explorer-section-actions")','disposing sections restores the original root header DOM and removes only the shared section decorations');
  console.log(JSON.stringify({status:'PASS',checks,evidence:root},null,2));app.exit(0);
}).catch(error=>{console.error(error.stack||error);console.error('Evidence:',root);if(win)win.webContents.executeJavaScript('JSON.stringify({errors:window.fixture_errors,notices:window.notices,removals:window.removals,leaves:window.leaves?.().map(leaf=>({path:leaf.state.path,state:files.editor_state(leaf)})),opened:[...document.querySelectorAll(".workspace-explorer-open-file")].map(button=>({title:button.title,path:button.dataset.editorPath}))})').then(console.error).finally(()=>app.exit(1));else app.exit(1);});
