// 多远端、重命名与工作树全部使用隔离的本地 Git 仓库，不访问用户仓库或网络。
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import child_process from 'node:child_process';
import {build} from 'esbuild';
const compiled=await build({stdin:{contents:['git_scm_data','git_graph_actions','git_graph_repository','git_graph_settings','git_graph_runtime','workspace_open_dialog'].map(name=>`export * from './src/${name}.ts'`).join(';'),resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const api=await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'typora_scm_actions_')),checks=[];
const git=(root,args)=>child_process.execFileSync('git',['-c','core.hooksPath=.git/unused_hooks','-c','core.autocrlf=false',...args],{cwd:root,encoding:'utf8',windowsHide:true,stdio:['pipe','pipe','pipe']}).trim();
const create=name=>{const root=path.join(temp,name);fs.mkdirSync(root);git(root,['init','-b','main']);git(root,['config','user.name','SCM Test']);git(root,['config','user.email','scm@example.invalid']);git(root,['config','commit.gpgsign','false']);return root;};
const reader=api.create_git_runner({child_process,process}),writer=api.create_git_runner({child_process,process},{writable:true});
const state=root=>api.read_repository(reader.run,root,api.graph_defaults,100);
const plan=async(root,id,values={},target='')=>{const current=await state(root);return api.plan_git_action(reader.run,id,{root:current.root,hash:current.head,operation:'',target},values);};
const execute=async(root,id,values={},target='')=>api.execute_git_action(writer.run,await plan(root,id,values,target),()=>true);
try{
  const root=create('main repo');fs.writeFileSync(path.join(root,'first.md'),'base');git(root,['add','.']);git(root,['commit','-m','基础提交\n\n完整正文\n第二行']);const base=git(root,['rev-parse','HEAD']);
  const remote=path.join(temp,'remote.git'),second=path.join(temp,'second.git');git(temp,['clone','--bare',root,remote]);git(temp,['clone','--bare',root,second]);git(root,['remote','add','team/origin',remote]);git(root,['remote','add','backup',second]);git(root,['push','-u','team/origin','main:renamed']);git(root,['fetch','team/origin']);
  let current=await state(root);assert.equal(current.tracking.remote,'team/origin');assert.equal(current.tracking.remote_ref,'refs/heads/renamed');assert.equal(current.tracking.upstream_hash,base);
  fs.writeFileSync(path.join(root,'first.md'),'change');git(root,['commit','-am','更改']);current=await state(root);assert.equal(current.tracking.ahead,1);assert.equal(current.tracking.behind,0);checks.push('slash-containing remote and differently named upstream are read exactly');
  const push=await plan(root,'push',{remote:'team/origin',branch:'main',remote_branch:'renamed',upstream:false,force_lease:false});assert.equal(push.args.at(-1),'refs/heads/main:refs/heads/renamed');await api.execute_git_action(writer.run,push,()=>true);assert.equal(git(remote,['rev-parse','renamed']),current.head);checks.push('push updates only the configured remote branch');
  const fetch=await plan(root,'fetch',{remote:'',prune:false,prune_tags:false});assert.deepEqual(fetch.args,['fetch','--all']);await api.execute_git_action(writer.run,fetch,()=>true);assert(git(root,['show-ref','refs/remotes/backup/main']));checks.push('fetch all populates both local remotes');
  git(root,['branch','feature']);git(root,['checkout','feature']);git(root,['config','branch.feature.vscode-merge-base','team/origin/renamed']);current=await state(root);assert.equal(current.tracking.base,'refs/remotes/team/origin/renamed');assert.equal(current.tracking.base_hash,current.head);checks.push('explicit VS Code base resolves without guessed main names');
  git(root,['config','--unset','branch.feature.vscode-merge-base']);current=await state(root);assert.equal(current.tracking.base,'refs/remotes/team/origin/renamed');checks.push('base falls back through branch creation and checkout reflogs to the source upstream');
  git(root,['checkout','main']);const publisher=create('publisher');git(publisher,['remote','add','origin',remote]);git(publisher,['fetch','origin']);git(publisher,['checkout','-b','publish','origin/renamed']);fs.writeFileSync(path.join(publisher,'incoming.md'),'remote update');git(publisher,['add','.']);git(publisher,['commit','-m','远端新提交']);git(publisher,['push','origin','publish:renamed']);git(root,['fetch','team/origin']);const incoming=git(publisher,['rev-parse','HEAD']);
  git(root,['checkout','-b','unrelated',base]);fs.writeFileSync(path.join(root,'only-other.md'),'other branch');git(root,['add','.']);git(root,['commit','-m','其他分支']);const unrelated=git(root,['rev-parse','HEAD']);git(root,['checkout','main']);
  current=await api.read_repository(reader.run,root,{...api.graph_defaults,show_remotes:false},100,['AUTO']);assert.equal(current.tracking.behind,1);assert(current.commits.some(commit=>commit.hash===incoming));assert(!current.commits.some(commit=>commit.hash===unrelated));const head_only=await api.read_repository(reader.run,root,api.graph_defaults,100,['HEAD']);assert(!head_only.commits.some(commit=>commit.hash===incoming));checks.push('Auto includes incoming upstream commits while excluding unrelated branches, even when remote badges are hidden');
  const metadata_before=git(root,['config','--local','--list']);await state(root);assert.equal(git(root,['config','--local','--list']),metadata_before,'reading does not write Git config');
  git(root,['checkout','--detach',base]);assert.equal((await state(root)).tracking.upstream,'');git(root,['checkout','main']);const empty=create('empty');assert.equal((await state(empty)).head,'');checks.push('detached and unborn repositories have no invented upstream');
  const worktree=path.join(temp,'linked 中文');await execute(root,'worktree_add',{directory:worktree,branch:'linked'});assert.equal(git(worktree,['symbolic-ref','--short','HEAD']),'linked');assert(fs.existsSync(path.join(worktree,'first.md')));const trees=await api.read_worktrees(reader.run,root);assert.equal(trees.length,2);assert.equal(trees[0].main,true);assert.equal(trees[1].branch,'refs/heads/linked');checks.push('real linked worktree and branch are created');
  await assert.rejects(plan(root,'worktree_remove',{},root),/主工作树/);await assert.rejects(plan(worktree,'worktree_remove',{},worktree),/当前工作树/);
  fs.writeFileSync(path.join(worktree,'unsaved.md'),'keep');await assert.rejects(plan(root,'worktree_remove',{},worktree),/工作树包含/);fs.unlinkSync(path.join(worktree,'unsaved.md'));
  git(root,['worktree','lock',worktree]);await assert.rejects(plan(root,'worktree_remove',{},worktree),/已锁定/);git(root,['worktree','unlock',worktree]);
  const removal=await plan(root,'worktree_remove',{},worktree);fs.writeFileSync(path.join(worktree,'first.md'),'late write');await assert.rejects(api.execute_git_action(writer.run,removal,()=>true),/工作树包含/);assert(fs.existsSync(worktree));git(worktree,['restore','first.md']);checks.push('main/current/locked/dirty and edits after preview are protected');
  await execute(root,'worktree_remove',{},worktree);assert(!fs.existsSync(worktree));assert(git(root,['rev-parse','refs/heads/linked']));checks.push('clean worktree removal preserves its branch and commit');
  const detached=path.join(temp,'detached');await execute(root,'worktree_add',{directory:detached,branch:''});assert.equal((await api.read_worktrees(reader.run,root)).find(item=>item.path===detached.replace(/\\/g,'/')).branch,'');await execute(root,'worktree_remove',{},detached);
  assert.equal(api.commit_github_url('git@github.com:owner/repo.git',base),`https://github.com/owner/repo/commit/${base}`);assert.equal(api.commit_github_url('https://user:secret@github.com/owner/repo.git',base),`https://github.com/owner/repo/commit/${base}`);assert.equal(api.commit_github_url('https://example.org/repo',base),'');checks.push('GitHub link strips credentials and rejects unrelated hosts');
  assert.deepEqual(api.validate_history_shortcuts({refresh:'Mod+Shift+R',fetch:'F5'}),{refresh:'Mod+Shift+R',fetch:'F5'});for(const value of [{refresh:'r'},{refresh:'Mod+Mod+r'},{refresh:'Mod+r',fetch:'mod+R'},{unknown:'F1'}])assert.throws(()=>api.validate_history_shortcuts(value));checks.push('keybinding syntax and collisions are validated');
  const settings=api.validate_settings({history_toolbar_hidden:['fetch','pull'],history_shortcuts:{refresh:'F5'}});assert.equal(settings.history_toolbar_hidden.length,2);assert.throws(()=>api.validate_settings({history_toolbar_hidden:['more']}));checks.push('toolbar settings preserve recoverable actions and cannot hide More');
  const window_calls=[];
  globalThis.window={JSBridge:{invoke:async(...args)=>{window_calls.push(args);return {};}}};
  const picker=api.bind_workspace_open_dialog({fs,path_api:path,core:{app:{openFile(){throw new Error('must not route through editor');}}}},()=>{});
  await picker.open_folder_new_window(root);assert.deepEqual(window_calls,[['app.openFile',null,{mountFolder:path.normalize(root),anchor:'#'}]]);
  await assert.rejects(picker.open_folder_new_window('relative'),/路径无效/);await assert.rejects(picker.open_folder_new_window(path.join(root,'first.md')),/不是文件夹/);assert.equal(window_calls.length,1);
  picker.dispose();await picker.open_folder_new_window(root);assert.equal(window_calls.length,1);
  await assert.rejects(api.open_workspace_window(root,'https://example.invalid'),/文内片段/);delete globalThis.window.JSBridge;await assert.rejects(api.open_workspace_window(root),/新窗口入口/);delete globalThis.window;
  checks.push('new worktree window uses the native main-process bridge and validates paths, anchors and disposal');
  console.log(JSON.stringify({status:'PASS',checks,temp},null,2));
}finally{reader.cancel();writer.cancel();}
