// 独立 QuickPick 使用 Chromium 真实鼠标和键盘；范围确认只调用控制器刷新，不触碰 Git 仓库。
const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_scm_ref_picker_'));
app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();
let test_window,pointer_calls=0;const checks=[],metrics=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const verify=async(condition,label)=>{assert(await evaluate(condition),label);checks.push(label);};
const key=async(keyCode,modifiers=[])=>{test_window.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});test_window.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(50);};
const pointer=async(selector)=>{pointer_calls++;const point=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw new Error('Missing '+${JSON.stringify(selector)});node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect(),x=Math.round(r.x+r.width/2),y=Math.round(r.y+r.height/2);return{x,y,hit:node.contains(document.elementFromPoint(x,y))};})()`);assert(point.hit,selector+' must be hit-testable');for(const type of ['mouseMove','mouseDown','mouseUp']){test_window.webContents.sendInputEvent({type,x:point.x,y:point.y,button:'left',clickCount:1});await delay(15);}};
const ref=id=>'[data-git-ref="'+id+'"]';
const selected=()=>evaluate('[...document.querySelectorAll("[data-git-ref][aria-selected=true]")].map(row=>row.dataset.gitRef)');
const query=async(value)=>{await pointer('.git-scm-ref-filter');await key('A',['control']);await key('Backspace');if(value)test_window.webContents.insertText(value);await delay(50);};
const open=async(branches=[])=>{await evaluate(`picker.close(false);panel.root='C:/isolated';panel.runner={};panel.pending=false;panel.writing=false;panel.disposed=false;panel.state=state;panel.branches=${JSON.stringify(branches)};document.querySelector('#trigger').focus();picker.open();void 0`);await delay(60);};
const capture=async(name)=>fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:940,height:740,webPreferences:{contextIsolation:false,nodeIntegration:true,offscreen:true,backgroundThrottling:false}});
  const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;overflow:hidden;font:13px "Segoe UI",sans-serif}body{background:var(--bg-color,#fff);color:var(--text-color,#24292f)}#trigger{position:fixed;left:12px;bottom:30px}#outside{position:fixed;right:12px;bottom:30px}#write{position:fixed;top:500px}</style><button id="trigger">选择历史引用</button><button id="outside">正文之外的按钮</button><article id="write" contenteditable="true">正文不应被引用筛选修改。</article>');
  await test_window.loadFile(html);test_window.webContents.debugger.attach();await test_window.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
  const bundle=await build({stdin:{contents:'export {git_scm_ref_picker} from "./src/git_scm_ref_picker";',resolveDir:path.join(__dirname,'..')},bundle:true,format:'iife',globalName:'qa',loader:{'.css':'text'},write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`window._options={displayLang:'zh-CN'};window.refreshes=[];window.trusted_clicks=0;document.addEventListener('click',event=>{if(event.isTrusted)trusted_clicks++},true);window.state={root:'C:/isolated',refs:[{hash:'1'.repeat(40),name:'refs/heads/main'},{hash:'2'.repeat(40),name:'refs/heads/topic'},{hash:'3'.repeat(40),name:'refs/remotes/origin/main'},{hash:'4'.repeat(40),name:'refs/tags/release-1'},{hash:'5'.repeat(40),name:'refs/heads/a_very_long_branch_name_'+'readable_'.repeat(35)}]};window.panel={state,root:state.root,runner:{},branches:[],pending:false,writing:false,disposed:false,settings:{branch_globs:[{name:'Release family',glob:'refs/tags/release-*'}]},refresh:async()=>{refreshes.push([...panel.branches]);}};window.picker=new qa.git_scm_ref_picker(panel);void 0`);
  await open();await verify('document.activeElement.matches(".git-scm-ref-filter")','opening focuses the filter');assert.deepEqual(await selected(),['__all__']);checks.push('All is initially checked for the existing empty range');
  await verify(`document.querySelector('[data-git-ref="refs/heads/main"] .git-scm-ref-description').textContent==='1111111'&&document.querySelector('[data-git-ref="refs/remotes/origin/main"] .git-scm-ref-description').textContent.includes('3333333')&&document.querySelector('[data-git-ref="refs/tags/release-1"] .git-scm-ref-description').textContent.includes('4444444')`,'local remote and tag rows show the referenced seven-character commit IDs');await verify(`!!document.querySelector('[data-git-ref="refs/remotes/origin/main"] [data-git-icon=cloud]')`,'remote references use the official cloud icon');
  await pointer(ref('AUTO'));assert.deepEqual(await selected(),['AUTO']);await verify('refreshes.length===0','choosing Auto is a cancellable draft');await pointer(ref('refs/heads/topic'));await pointer(ref('refs/remotes/origin/main'));assert.deepEqual(await selected(),['refs/heads/topic','refs/remotes/origin/main']);checks.push('specific references support multiple selection and exclude special scopes');
  await query('release-1');assert.deepEqual(await evaluate('[...document.querySelectorAll("[data-git-ref]")].map(row=>row.dataset.gitRef)'),['refs/tags/release-1']);await pointer(ref('refs/tags/release-1'));await query('');assert.deepEqual(await selected(),['refs/heads/topic','refs/remotes/origin/main','refs/tags/release-1']);checks.push('filtering retains checked references outside the displayed search results');await verify('document.querySelector(".git-scm-ref-count").textContent.includes("3")','a visible badge beside the filter shows the complete selected count');await pointer('[data-git-ref-accept]');assert.deepEqual(await evaluate('refreshes'),[['refs/heads/topic','refs/remotes/origin/main','refs/tags/release-1']]);await verify('!document.querySelector(".git-scm-ref-picker")&&document.activeElement.id==="trigger"','Apply updates the range once, closes and restores source focus');
  await open(['refs/tags/release-1','refs/heads/topic']);const order=await evaluate('[...document.querySelectorAll("[data-git-ref]")].map(row=>row.dataset.gitRef)');assert.deepEqual(order.slice(0,4),['__all__','AUTO','refs/heads/topic','refs/tags/release-1']);await pointer(ref('refs/heads/topic'));assert.deepEqual(await evaluate('[...document.querySelectorAll("[data-git-ref]")].map(row=>row.dataset.gitRef)'),order);checks.push('initially selected references are promoted once without moving rows under the pointer');await key('Escape');await verify('refreshes.length===1&&document.activeElement.id==="trigger"','Escape cancels the draft and restores focus');
  await open();await pointer(ref('__all__'));await key('Enter');await verify('refreshes.length===1&&!document.querySelector(".git-scm-ref-picker")','accepting an empty selection behaves as cancellation');
  await open(['refs/heads/topic']);await pointer(ref('__all__'));await key('Enter');assert.deepEqual(await evaluate('refreshes.at(-1)'),[]);checks.push('All accepts the existing empty-array range encoding');
  await open();await pointer(ref('AUTO'));await key('Enter');assert.deepEqual(await evaluate('refreshes.at(-1)'),['AUTO']);checks.push('Auto accepts the existing AUTO encoding');
  await open();await pointer(ref('HEAD'));await pointer(ref('glob:refs/tags/release-*'));await key('Enter');assert.deepEqual(await evaluate('refreshes.at(-1)'),['HEAD','glob:refs/tags/release-*']);checks.push('HEAD and configured glob capabilities stay available without becoming checkout actions');
  await open();await query('main');await key('ArrowDown');await key('Tab');await key('Tab');await verify('document.activeElement.matches(".git-scm-ref-list")','Tab reaches the multiselect list');await key('Home');await key('Space');await key('End');await key('Space');await key('Enter');assert.deepEqual(await evaluate('refreshes.at(-1)'),['refs/heads/main','refs/remotes/origin/main']);checks.push('keyboard navigation and Space toggle references while Enter accepts');
  const expected=await evaluate('refreshes.length');await open();await query('no such reference exists');await verify('document.querySelectorAll("[data-git-ref]").length===0&&!!document.querySelector(".git-scm-ref-empty")','an unmatched filter displays an explicit empty state');await evaluate('document.querySelector(".git-scm-ref-filter").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",isComposing:true,bubbles:true}));void 0');await verify('!!document.querySelector(".git-scm-ref-picker")','IME composition Enter cannot submit the picker');await key('Escape');
  await open();await pointer(ref('AUTO'));await pointer('#outside');await verify('!document.querySelector(".git-scm-ref-picker")&&document.activeElement.id==="outside"','an outside pointer cancels without stealing its target focus');assert.equal(await evaluate('refreshes.length'),expected);
  for(const [name,change]of [['pending','panel.pending=true'],['writing','panel.writing=true'],['repository','panel.root="C:/other"'],['runner','panel.runner={}'],['state','panel.state={...state}'],['disposed','panel.disposed=true']]){
    await open();await evaluate(`window.stale=document.querySelector('[data-git-ref-accept]');${change};picker.update_state();void 0`);await verify('!document.querySelector(".git-scm-ref-picker")',name+' invalidation closes the outstanding draft');await evaluate('stale.click();void 0');assert.equal(await evaluate('refreshes.length'),expected,name+' stale confirm must not refresh');checks.push(name+' retained confirmation cannot apply to an obsolete controller');
  }
  for(const name of ['pending','writing','disposed']){await open();await evaluate(`picker.close();panel.${name}=true;picker.open();void 0`);await verify('!document.querySelector(".git-scm-ref-picker")',name+' controller cannot open a new picker');}
  await open();await evaluate('window.other_picker=new qa.git_scm_ref_picker(panel);other_picker.open();void 0');await verify('document.querySelectorAll(".git-scm-ref-picker").length===1','a second picker replaces the previous instance');await evaluate('other_picker.close();void 0');
  await evaluate('window.short_refs=state.refs;state.refs=[...short_refs,...Array.from({length:100},(_,index)=>({hash:String(index+10),name:"refs/heads/topic_"+String(index).padStart(3,"0")}))];void 0');await open();await key('Tab');await key('Tab');await key('End');await verify('(()=>{const list=document.querySelector(".git-scm-ref-list"),row=document.querySelector(".git-scm-ref-item.is-active"),box=row.getBoundingClientRect(),bounds=list.getBoundingClientRect();return list.scrollHeight>list.clientHeight&&bounds.height-parseFloat(getComputedStyle(list).paddingBottom)<=440&&box.top>=bounds.top&&box.bottom<=bounds.bottom+.5})()','long reference lists stay inside the 20-row height cap and keyboard navigation scrolls the active row into view');await key('Escape');await evaluate('state.refs=short_refs;void 0');
  for(const width of [320,600,940])for(const dark of [false,true]){
    test_window.setContentSize(width,620);await evaluate(`document.documentElement.style.cssText='--bg-color:${dark?'#202020':'#fff'};--side-bar-bg-color:${dark?'#202020':'#f8f8f8'};--text-color:${dark?'#eee':'#24292f'};--active-file-bg-color:${dark?'#37373d':'#e4e6f1'};--active-file-text-color:${dark?'#fff':'#222'};--item-hover-bg-color:${dark?'#333':'#eee'};'`);await open(['refs/heads/topic']);
    const layout=await evaluate(`(()=>{const root=document.querySelector('.git-scm-ref-picker'),box=root.getBoundingClientRect(),list=document.querySelector('.git-scm-ref-list'),rows=[...list.querySelectorAll('[data-git-ref]')],input=document.querySelector('.git-scm-ref-filter').getBoundingClientRect(),apply=document.querySelector('[data-git-ref-accept]').getBoundingClientRect();return {viewport:innerWidth,width:box.width,left:box.left,right:box.right,bottom:box.bottom,overflow:root.scrollWidth-root.clientWidth,header_gap:apply.left-input.right,count:(()=>{const r=document.querySelector('.git-scm-ref-count').getBoundingClientRect(),wrap=document.querySelector('.git-scm-ref-input').getBoundingClientRect();return {left:r.left,right:r.right,width:r.width,input_right:input.right,container_right:wrap.right}})(),rows:rows.map(node=>{const r=node.getBoundingClientRect();return {height:r.height,icon:[...node.querySelectorAll('svg')].map(icon=>icon.getBoundingClientRect().width),hit:node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}})}})()`);
    assert(Math.abs(layout.width-Math.min(600,layout.viewport-12))<.1,JSON.stringify(layout));assert(layout.left>=5&&layout.right<=layout.viewport-5&&layout.bottom<=620&&layout.overflow<=1,JSON.stringify(layout));assert(layout.header_gap>=5);assert(layout.count.width>0&&layout.count.left>=layout.count.input_right&&layout.count.right<=layout.count.container_right);for(const row of layout.rows){assert.equal(row.height,22);assert(row.hit);assert(row.icon.every(icon=>icon===14||icon===16));}metrics.push({width,dark,...layout});await capture('refs_'+width+'_'+(dark?'night':'light'));checks.push(width+'px '+(dark?'Night':'Light')+' picker keeps 22px rows, 600px cap, visible checkbox/icon targets and bounded long names');
  }
  await evaluate('picker.close();void 0');await verify('document.querySelector("#write").textContent==="正文不应被引用筛选修改。"','document content is untouched throughout selection');await verify('!document.querySelector("style[id*=git-scm-ref-picker]")','closing the last picker releases its isolated stylesheet');assert.equal(await evaluate('trusted_clicks'),pointer_calls);checks.push('all '+pointer_calls+' pointer actions are trusted Chromium mouse events');
  fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({status:'PASS',checks,metrics},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence},null,2));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(test_window&&!test_window.isDestroyed()){await capture('failure');test_window.destroy();}app.exit(1);});
