import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import child_process from 'node:child_process';
import { build } from 'esbuild';

const compiled = await build({ stdin: { contents: ['git_graph_repository', 'git_graph_actions', 'git_graph_settings', 'git_graph_runtime'].map(name => `export * from './src/${name}.ts';`).join('\n'), resolveDir: process.cwd() }, bundle: true, platform: 'node', format: 'esm', write: false });
const api = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_git_full_'));
const reader = api.create_git_runner({ child_process, process }); const writer = api.create_git_runner({ child_process, process }, { writable: true });
const checks = [];
const expect = (condition, message) => { assert(condition, message); checks.push(message); };
const git = (root, args) => child_process.execFileSync('git', ['-c', 'core.autocrlf=false', '-c', 'core.hooksPath=.git/unused_hooks', ...args], { cwd: root, encoding: 'utf8', windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const write = (root, file, value) => { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), value); };
const head = root => git(root, ['rev-parse', 'HEAD']);
const commit = (root, message) => { git(root, ['add', '--all']); git(root, ['commit', '-m', message]); return head(root); };
const create_repo = name => {
  const root = path.join(temp, name); fs.mkdirSync(root); git(root, ['init', '-b', 'main']);
  git(root, ['config', 'user.name', 'Graph Test']); git(root, ['config', 'user.email', 'graph@example.invalid']);
  git(root, ['config', 'core.autocrlf', 'false']);
  git(root, ['config', 'commit.gpgsign', 'false']); git(root, ['config', 'tag.gpgsign', 'false']); git(root, ['config', 'core.hooksPath', '.git/unused_hooks']);
  return root;
};
const defaults = id => Object.fromEntries(api.graph_actions.find(action => action.id === id).fields.map(field => [field.key, field.initial ?? (field.type === 'boolean' ? false : '')]));
const action = async (root, id, values = {}, target = '', hash = '', operation = '') => {
  const plan = await api.plan_git_action(reader.run, id, { root, target, hash, operation }, { ...defaults(id), ...values });
  await api.execute_git_action(writer.run, plan, () => true); return plan;
};
try {
  const root = create_repo('repo with spaces'); write(root, '中文 #%.md', 'one\n'); const first = commit(root, '开始 :tada:');
  await action(root, 'branch_create', { branch: 'feature', checkout: true }, '', first);
  write(root, 'feature.md', 'feature\n'); const feature = commit(root, '功能');
  await action(root, 'branch_checkout', {}, 'main'); write(root, 'main.md', 'main\n'); const main = commit(root, '主线');
  await action(root, 'merge', { mode: 'no-ff' }, '', feature); const merge = head(root);
  expect(git(root, ['show', '-s', '--format=%P', 'HEAD']).split(' ').length === 2, 'merge creates a real two-parent commit');
  await action(root, 'branch_create', { branch: 'temporary' }, '', first);
  await action(root, 'branch_rename', { branch: 'renamed' }, 'temporary');
  expect(git(root, ['rev-parse', 'renamed']) === first, 'create and rename branch preserve target');
  await action(root, 'branch_delete', {}, 'renamed');
  expect(!git(root, ['branch', '--list', 'renamed']), 'branch deletion removes selected ref');
  await action(root, 'tag_add', { tag: 'v1', message: '说明\n第二行' }, '', merge);
  expect(git(root, ['cat-file', '-t', 'v1']) === 'tag', 'annotated tag stores multiline message');
  const state = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  expect(state.commits.some(item => item.email === 'graph@example.invalid'), 'history reads author and committer metadata');
  const contained = await api.commit_containment(reader.run, state, first);
  expect(contained.includes('属于 HEAD') && contained.includes('refs/tags/v1'), 'containment reports HEAD and including refs');
  const branch_state = await api.read_repository(reader.run, root, api.graph_defaults, 200, ['refs/heads/feature']);
  expect(branch_state.commits.length === 2, 'single branch limits revision walk');
  const glob_state = await api.read_repository(reader.run, root, api.graph_defaults, 200, ['glob:heads/fea*']);
  expect(glob_state.commits.length === 2, 'custom branch glob limits revision walk');
  const files = await api.compare_files(reader.run, state, first, merge);
  expect(files.length === 2, 'arbitrary commit comparison returns both branch changes');
  git(root, ['mv', 'feature.md', 'renamed feature.md']); const rename = commit(root, 'rename');
  const renamed = await api.compare_files(reader.run, { ...state, head: rename }, merge, rename);
  expect(renamed[0].old_path === 'feature.md' && renamed[0].path === 'renamed feature.md', 'rename detection preserves both paths');
  write(root, '中文 #%.md', 'one\nworking\n'); write(root, 'new file.md', 'untracked\n');
  await action(root, 'stage', {}, '中文 #%.md');
  let dirty = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  expect(dirty.changes.some(file => file.index_status === 'M') && dirty.changes.some(file => file.status === '??'), 'index and untracked changes are distinct');
  expect((await api.compare_files(reader.run, dirty, rename, api.INDEX)).length === 1, 'staged comparison reads the index');
  await action(root, 'unstage', {}, '中文 #%.md');
  await action(root, 'stash_create', { untracked: true, message: 'draft' });
  dirty = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  assert.deepEqual({ stashes: dirty.stashes.length, changes: dirty.changes }, { stashes: 1, changes: [] }, JSON.stringify({ raw: git(root, ['stash', 'list', '--format=%H%x00%gd%x00%gs%x00%aI', '-z']), stashes: dirty.stashes, changes: dirty.changes }));
  expect(true, 'stash stores tracked and untracked edits');
  const stash = dirty.stashes[0]; await action(root, 'stash_apply', {}, stash.name, stash.hash);
  expect(fs.readFileSync(path.join(root, 'new file.md'), 'utf8') === 'untracked\n', 'stash apply restores untracked file');
  await action(root, 'reset', { mode: 'hard' }, '', rename); await action(root, 'clean', {}, '', rename);
  await action(root, 'stash_pop', {}, stash.name, stash.hash);
  expect(!git(root, ['stash', 'list']), 'stash pop removes only successfully applied stash');
  await action(root, 'stash_create', { untracked: true });
  let newest = (await api.read_repository(reader.run, root, api.graph_defaults, 200)).stashes[0];
  await action(root, 'stash_branch', { branch: 'from-stash' }, newest.name, newest.hash);
  expect(git(root, ['branch', '--show-current']) === 'from-stash', 'stash branch checks out a new branch');
  await action(root, 'stash_create', { untracked: true }); newest = (await api.read_repository(reader.run, root, api.graph_defaults, 200)).stashes[0];
  await action(root, 'stash_drop', {}, newest.name, newest.hash);
  expect(!git(root, ['stash', 'list']), 'stash drop removes selected stash');
  await action(root, 'branch_checkout', {}, 'main');
  const remote = path.join(temp, 'bare remote.git'); git(temp, ['init', '--bare', remote]);
  await action(root, 'remote_add', { remote: 'origin', url: remote });
  await action(root, 'push', { remote: 'origin', branch: 'main', upstream: true });
  expect(git(remote, ['rev-parse', 'refs/heads/main']) === rename, 'push writes a real local bare remote');
  await action(root, 'tag_push', { remote: 'origin' }, 'v1');
  expect(git(remote, ['rev-parse', 'refs/tags/v1^{}']) === merge, 'tag push sends annotated tag');
  await action(root, 'fetch', { remote: 'origin', prune: true });
  await action(root, 'remote_checkout', { branch: 'tracking' }, 'origin/main');
  expect(git(root, ['rev-parse', '--abbrev-ref', '@{upstream}']) === 'origin/main', 'remote checkout sets upstream');
  await action(root, 'branch_checkout', {}, 'main');
  await action(root, 'branch_fetch', { remote: 'origin', source: 'main', branch: 'fetched' });
  expect(git(root, ['rev-parse', 'fetched']) === rename, 'fetch maps remote ref to selected local branch');
  await action(root, 'pull', { remote: 'origin', branch: 'main', mode: 'ff-only' });
  await action(root, 'push', { remote: 'origin', branch: 'feature' });
  await action(root, 'remote_branch_delete', { remote: 'origin', branch: 'feature' });
  expect(!git(remote, ['for-each-ref', '--format=%(refname)', 'refs/heads/feature']), 'remote branch deletion targets server ref');
  await action(root, 'remote_edit', { remote: 'origin', url: remote, push_url: true });
  expect(git(root, ['remote', 'get-url', '--push', 'origin']) === remote, 'remote push URL editing');
  await action(root, 'remote_prune', { remote: 'origin' });
  await action(root, 'tag_delete', {}, 'v1'); await action(root, 'remote_remove', { remote: 'origin' });
  expect(!git(root, ['remote']), 'remote removal deletes configuration');
  const stale_plan = await api.plan_git_action(reader.run, 'branch_create', { root, hash: rename, target: '', operation: '' }, { branch: 'stale', checkout: false });
  git(root, ['branch', 'external', first]);
  await assert.rejects(api.execute_git_action(writer.run, stale_plan, () => true), /仓库已被其他程序改变/);
  const guarded_plan = await api.plan_git_action(reader.run, 'reset', { root, hash: first, target: '', operation: '' }, { mode: 'hard' });
  await assert.rejects(api.execute_git_action(writer.run, guarded_plan, () => false), /未保存修改/);
  expect(head(root) === rename, 'stale plan and dirty editor rejection cause no mutation');
  write(root, 'main.md', 'change one\n');
  const content_plan = await api.plan_git_action(reader.run, 'reset', { root, hash: rename, target: '', operation: '' }, { mode: 'hard' });
  write(root, 'main.md', 'change two\n');
  await assert.rejects(api.execute_git_action(writer.run, content_plan, () => true), /仓库已被其他程序改变/);
  expect(fs.readFileSync(path.join(root, 'main.md'), 'utf8') === 'change two\n', 'same-path edits invalidate an earlier destructive preview');
  const edit = create_repo('edit actions'); write(edit, 'one.md', 'one\n'); const base = commit(edit, 'base');
  write(edit, 'two.md', 'two\n'); const second = commit(edit, 'second'); write(edit, 'three.md', 'three\n'); const third = commit(edit, 'third');
  await action(edit, 'drop', {}, second, second);
  expect(!fs.existsSync(path.join(edit, 'two.md')) && fs.existsSync(path.join(edit, 'three.md')), 'drop removes selected commit and replays descendants');
  await action(edit, 'cherry_pick', {}, second, second);
  expect(fs.existsSync(path.join(edit, 'two.md')), 'cherry-pick applies commit');
  await action(edit, 'revert', {}, second, second);
  expect(!fs.existsSync(path.join(edit, 'two.md')), 'revert records inverse change');
  await action(edit, 'commit_checkout', {}, base, base);
  expect(!git(edit, ['branch', '--show-current']), 'commit checkout enters detached HEAD');
  await action(edit, 'branch_checkout', {}, 'main');
  await action(edit, 'branch_create', { branch: 'rebase-source', checkout: true }, '', base);
  write(edit, 'rebased.md', 'rebase\n'); commit(edit, 'rebase change');
  await action(edit, 'rebase', {}, '', third);
  expect(git(edit, ['show', '-s', '--format=%P', 'HEAD']) === third, 'rebase replays onto selected commit');
  write(edit, 'staged.md', 'stage\n'); await action(edit, 'stage', {}, 'staged.md'); await action(edit, 'commit', { message: '图内提交\n\n中文正文' });
  expect(git(edit, ['log', '-1', '--format=%B']).includes('中文正文'), 'commit action supports multiline messages');
  const interactive = create_repo('interactive'); write(interactive, 'base.md', 'base\n'); const interactive_base = commit(interactive, 'base');
  write(interactive, 'a.md', 'a\n'); const a = commit(interactive, 'a'); write(interactive, 'b.md', 'b\n'); const b = commit(interactive, 'b');
  write(interactive, 'c.md', 'c\n'); const c = commit(interactive, 'c');
  await action(interactive, 'rebase', { interactive: true, todo: `reword ${a} 新的标题 $()\npick ${b} b\nfixup ${c} c` }, '', interactive_base);
  expect(git(interactive, ['rev-list', '--count', 'HEAD']) === '3' && git(interactive, ['log', '--format=%s']).includes('新的标题 $()'), 'interactive rebase rewords literal text and fixes up commits');
  const unborn = create_repo('unborn'); write(unborn, 'new.md', 'new\n'); await action(unborn, 'stage', {}, 'new.md');
  const unborn_state = await api.read_repository(reader.run, unborn, api.graph_defaults, 200);
  expect((await api.compare_files(reader.run, unborn_state, api.EMPTY, api.WORKTREE))[0].path === 'new.md', 'unborn worktree comparison includes staged new file');
  await action(unborn, 'unstage', {}, 'new.md'); expect(git(unborn, ['ls-files']) === '' && fs.existsSync(path.join(unborn, 'new.md')), 'unstage before first commit preserves working file');
  const conflicts = create_repo('conflicts'); write(conflicts, 'same.md', 'base\n'); const common = commit(conflicts, 'base');
  git(conflicts, ['checkout', '-b', 'other']); write(conflicts, 'same.md', 'other\n'); const other = commit(conflicts, 'other');
  git(conflicts, ['checkout', 'main']); write(conflicts, 'same.md', 'main\n'); const before = commit(conflicts, 'main');
  await assert.rejects(action(conflicts, 'merge', { mode: 'normal' }, '', other));
  expect(fs.existsSync(path.join(conflicts, '.git/MERGE_HEAD')), 'conflicting merge retains recoverable Git operation');
  await action(conflicts, 'abort', {}, '', '', 'merge'); expect(head(conflicts) === before, 'abort restores pre-merge state');
  await assert.rejects(action(conflicts, 'merge', { mode: 'normal' }, '', other));
  write(conflicts, 'same.md', 'resolved\n'); git(conflicts, ['add', 'same.md']); await action(conflicts, 'continue', {}, '', '', 'merge');
  expect(!fs.existsSync(path.join(conflicts, '.git/MERGE_HEAD')), 'continue finishes resolved merge');
  await action(conflicts, 'reset', { mode: 'hard' }, '', before); await assert.rejects(action(conflicts, 'cherry_pick', {}, other, other));
  await action(conflicts, 'skip', {}, '', '', 'cherry-pick'); expect(head(conflicts) === before, 'skip abandons conflicted cherry-pick');
  expect(api.glob_matches('heads/feat*', 'heads/feature') && !api.glob_matches('heads/feat*', 'heads/main'), 'glob matcher');
  assert.throws(() => api.validate_settings({ initial_count: -1 })); assert.throws(() => api.validate_settings({ colors: ['not-a-color'] }));
  const storage = new Map(); const store = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
  api.save_reviews(store, [{ root, from: first, to: merge, reviewed: ['main.md'], updated_at: Date.now() }]);
  expect(api.load_reviews(store)[0].reviewed[0] === 'main.md' && api.load_reviews(store, Date.now() + 91 * 86400000).length === 0, 'review persistence and 90-day expiry');
  expect(api.pull_request_url('git@github.com:owner/repo.git', 'feature/a', 'main').includes('feature%2Fa'), 'GitHub PR URL encodes branches');
  expect(api.pull_request_url('https://gitlab.com/owner/repo.git', 'feature', 'main').includes('merge_requests/new'), 'GitLab PR form');
  expect(api.pull_request_url('https://bitbucket.org/owner/repo.git', 'feature', 'main').includes('pull-requests/new'), 'Bitbucket PR form');
  const signed = create_repo('signed'); const key = path.join(temp, 'signing_key');
  child_process.execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', key], { windowsHide: true, stdio: 'pipe' });
  const signers = path.join(temp, 'allowed_signers'); fs.writeFileSync(signers, 'graph@example.invalid ' + fs.readFileSync(key + '.pub', 'utf8'));
  git(signed, ['config', 'gpg.format', 'ssh']); git(signed, ['config', 'user.signingKey', key]); git(signed, ['config', 'gpg.ssh.allowedSignersFile', signers]);
  write(signed, 'signed.md', 'signed\n'); git(signed, ['add', 'signed.md']);
  const signed_plan = await api.plan_git_action(reader.run, 'commit', { root: signed, target: '', hash: '', operation: '', sign_commits: true }, { message: 'signed', amend: false });
  await api.execute_git_action(writer.run, signed_plan, () => true);
  expect(git(signed, ['show', '-s', '--format=%G?', 'HEAD']) === 'G', 'commit signing is verified with an isolated SSH key');
  const tag_plan = await api.plan_git_action(reader.run, 'tag_add', { root: signed, target: '', hash: head(signed), operation: '', sign_tags: true }, { tag: 'signed', message: 'signed tag', sign: false });
  await api.execute_git_action(writer.run, tag_plan, () => true); git(signed, ['verify-tag', 'signed']);
  expect(true, 'tag signature verifies with an isolated signing key');
  const archive = path.join(temp, 'version.zip'); await writer.run(signed, ['archive', '--format=zip', '--output=' + archive, 'HEAD']);
  expect(fs.readFileSync(archive).subarray(0, 2).toString() === 'PK', 'archive writes a ZIP file');
  console.log(JSON.stringify({ status: 'PASS', checks }, null, 2));
} finally {
  reader.cancel(); writer.cancel();
  assert(path.dirname(temp) === path.resolve(os.tmpdir()) && path.basename(temp).startsWith('typora_git_full_'));
  fs.rmSync(temp, { recursive: true, force: true });
}
