// 真实 Chromium 指针／键盘与隔离 Git 数据验证 R027，不操作用户窗口、远端或文件。
const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),child_process=require('node:child_process');
const {build}=require('esbuild'),{editor_plugins}=require('./editor_bundle.cjs');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'typora_scm_ui_')),root=path.join(temp,'repo'),other=path.join(temp,'other'),remote=path.join(temp,'remote.git');fs.mkdirSync(root);fs.mkdirSync(other);
const git=(cwd,args)=>child_process.execFileSync('git',['-c','core.hooksPath=.git/unused_hooks','-c','core.autocrlf=false',...args],{cwd,encoding:'utf8',windowsHide:true,stdio:['pipe','pipe','pipe']}).trim();
for(const dir of [root,other]){git(dir,['init','-b','main']);git(dir,['config','user.name','SCM QA']);git(dir,['config','user.email','scm@example.invalid']);git(dir,['config','commit.gpgsign','false']);fs.writeFileSync(path.join(dir,'before.md'),'# Original\n');git(dir,['add','.']);git(dir,['commit','-m','基础提交\n\n完整的第二段\n最后一行']);}
const base=git(root,['rev-parse','HEAD']);git(temp,['clone','--bare',root,remote]);git(root,['remote','add','origin',remote]);git(root,['push','-u','origin','main']);
git(root,['mv','before.md','renamed.md']);git(root,['commit','-m','重命名\n\n保留正文']);const head=git(root,['rev-parse','HEAD']);git(root,['branch','topic',base]);git(root,['tag','test-tag',base]);git(root,['config','branch.main.vscode-merge-base','origin/main']);
fs.writeFileSync(path.join(root,'renamed.md'),'# Edited\n');fs.writeFileSync(path.join(root,'new.md'),'# New\n');git(root,['add','new.md']);
app.setPath('userData',path.join(temp,'user_data'));app.disableHardwareAcceleration();let win;const checks=[];const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async source=>{try{return await win.webContents.executeJavaScript(source);}catch(error){console.error(source);throw error;}};
const wait=async source=>{for(let i=0;i<160;i++){if(await evaluate(source))return;await delay(50);}throw new Error('Timed out: '+source);};
const click=async(selector,mouse='left')=>{await delay(60);const p=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw new Error('Missing '+${JSON.stringify(selector)});node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x:Math.round(x),y:Math.round(y),hit:node.contains(document.elementFromPoint(x,y)),width:r.width,disabled:node.disabled};})()`);assert(p.hit&&p.width>0,JSON.stringify({selector,...p}));for(const type of ['mouseMove','mouseDown','mouseUp']){win.webContents.sendInputEvent({type,x:p.x,y:p.y,button:mouse,clickCount:1});await delay(20);}};
const key=async(keyCode,modifiers=[])=>{for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode,modifiers});await delay(80);};
const capture=async name=>fs.writeFileSync(path.join(temp,name+'.png'),(await win.webContents.capturePage()).toPNG());
app.whenReady().then(async()=>{
  win=new BrowserWindow({show:false,width:1050,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});win.webContents.on('console-message',(_e,_l,message)=>console.error(message));
  const html=path.join(temp,'test.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;overflow:hidden;font:13px system-ui}body{display:flex}#sidebar{width:380px;flex:none;height:100%}#editor{flex:1;min-width:0}button,input{font:inherit}</style><section id="sidebar" class="linux-note-git-source-control"></section><section id="editor"></section>');await win.loadFile(html);win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
  const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export {git_graph_panel} from "./src/git_graph_panel";export {create_graph_host} from "./src/git_graph_host";export {GRAPH_SETTINGS_KEY} from "./src/git_graph_settings";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{
    const css=document.createElement('style');css.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'))};document.head.append(css);
    window.reqnode=require;window._options={userDataPath:${JSON.stringify(temp)},displayLang:'zh-CN'};window.File={changeCounter:{isDocumentEdited:()=>false}};
    window.copied='';window.JSBridge={invoke:async(command,data)=>{if(command==='clipboard.write')copied=JSON.parse(data).text;}};
    const core={WorkspaceView:class{},app:{viewManager:{registerView(){}},commands:{run(...args){window.commands.push(args)},register(){}},workspace:{sidebar:{},on(){},ribbon:{addButton(){}},eachLeaves(){},activeLeaf:null}}};window.commands=[];
    window.host=qa.create_graph_host(core);window.opened=[];window.revisions=[];host.open_document=(...args)=>opened.push(args);host.open_revision_document=(...args)=>revisions.push(args);
    window.panel=new qa.git_graph_panel(host,${JSON.stringify(root)});document.querySelector('#sidebar').append(panel.workbench.sidebar);document.querySelector('#editor').append(panel.container);panel.save_repos([panel.root,${JSON.stringify(other)}]);void panel.refresh();
  })()`);await wait('!panel.pending&&panel.state?.commits.length===2');
  const revision_data=await evaluate('panel.state.tracking');assert.equal(revision_data.ahead,1);assert.equal(revision_data.behind,0);
  await click('.git-scm-view-menu');await click('[data-action=show_repositories]');await wait('document.querySelectorAll(".git-scm-repository-branch span").length===2');assert(await evaluate('[...document.querySelectorAll(".git-scm-repository-name")].some(node=>node.textContent==="repo")'));await capture('repositories_and_graph');
  await click('.git-scm-history-header','right');assert(await evaluate('!!document.querySelector("[data-action=hide_section]")&&!!document.querySelector("[data-action=show_repositories]")'));await key('Escape');
  const title_geometry=await evaluate(`(()=>{const title=document.querySelector('.git-scm-history-title'),toggle=title.parentElement,badge=toggle.querySelector('.git-scm-badge');return {ellipsis:getComputedStyle(title).textOverflow,text_nodes:[...toggle.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim()).length,badge_fits:badge.hidden||badge.getBoundingClientRect().right<=toggle.getBoundingClientRect().right+1};})()`);assert.equal(title_geometry.ellipsis,'ellipsis');assert.equal(title_geometry.text_nodes,0);assert(title_geometry.badge_fits);
  await click('[data-history-action=fetch]','right');await click('[data-action=hide_action]');assert(await evaluate('panel.settings.history_toolbar_hidden.includes("fetch")&&document.querySelector("[data-history-action=fetch]").hidden'));await click('.git-scm-history-more-menu');assert(await evaluate('!!document.querySelector("[data-action=fetch]")&&!!document.querySelector("[data-action=history_tree]")'));await capture('hidden_actions_overflow');await click('[data-action=fetch]');assert.equal(await evaluate('document.querySelector("[data-field=remote]").value'),'');await key('Escape');
  await click('.git-scm-history-more-menu','right');assert(await evaluate('document.querySelector("[data-action=hide_action]").disabled'));await click('[data-action=toggle_fetch]');assert(!await evaluate('document.querySelector("[data-history-action=fetch]").hidden'));checks.push('toolbar hides, restores and recovers Fetch All through More');
  await click('[data-history-action=refresh]','right');await click('[data-action=configure_keybinding]');await evaluate('document.querySelector("[data-history-keybinding=refresh]").value="Mod+Shift+R"');await click('.git-graph-dialog-footer button');assert.equal(await evaluate('panel.settings.history_shortcuts.refresh'),'Mod+Shift+R');
  await evaluate('window.refreshes=0;window.refresh_original=panel.refresh.bind(panel);panel.refresh=async(...args)=>{refreshes++;return refresh_original(...args)};panel.workbench.history.toggle.focus()');await key('R',['control','shift']);await wait('refreshes===1&&!panel.pending');await evaluate('panel.workbench.message.focus()');await key('R',['control','shift']);assert.equal(await evaluate('refreshes'),1);await evaluate('void (panel.refresh=refresh_original)');checks.push('configured keybinding executes same command only in SCM and leaves inputs alone');
  await click('[data-history-action=branches]');await evaluate('document.querySelector("input[type=search]").value="topic";document.querySelector("input[type=search]").dispatchEvent(new Event("input"))');assert.equal(await evaluate('[...document.querySelectorAll(".git-graph-filter:not([hidden])")].length'),1);await key('Escape');assert.equal(await evaluate('panel.branches.length'),0);
  await click('[data-history-action=branches]');await click('[data-scope=auto]');await wait('!panel.pending&&panel.branches[0]==="AUTO"');assert.equal(await evaluate('document.querySelector(".git-scm-history-scope").textContent'),'自动');await click('[data-history-action=branches]');await click('[data-scope=all]');await wait('!panel.pending&&panel.branches.length===0');await evaluate("panel.branches=['refs/heads/topic'];void panel.refresh()");await wait('!panel.pending&&!panel.state.commits.some(commit=>commit.hash===panel.state.head)');await click('[data-history-action=head]');await wait('!panel.pending&&panel.workbench.history.selected===panel.state.head');assert(await evaluate('panel.workbench.history.list.contains(document.activeElement)'));await click('[data-history-action=branches]');await click('[data-scope=all]');await wait('!panel.pending&&panel.branches.length===0');checks.push('reference search cancel and Auto/All selection preserve state, and Go to Current restores a filtered-out HEAD');
  for(const width of [180,240,380])for(const dark of [false,true]){await evaluate(`document.querySelector('#sidebar').style.width='${width}px';document.documentElement.style.setProperty('--bg-color','${dark?'#202020':'white'}');document.documentElement.style.color='${dark?'#eee':'#222'}';panel.workbench.history.toolbar.update()`);await delay(80);const metrics=await evaluate(`(()=>{const h=panel.workbench.history.header,m=panel.workbench.history.toolbar.more,r=m.getBoundingClientRect();return {overflow:h.scrollWidth-h.clientWidth,hit:m.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),visible:[...panel.workbench.history.toolbar.buttons].filter(([,node])=>!node.hidden).map(([id])=>id)};})()`);assert(metrics.overflow<=1,JSON.stringify(metrics));assert(metrics.hit);await click('.git-scm-history-more-menu');for(const id of ['branches','head','fetch','pull','push','refresh'])assert(metrics.visible.includes(id)||await evaluate(`!!document.querySelector('[data-action=${id}]')`));await key('Escape');await capture(`toolbar_${width}_${dark?'dark':'light'}`);}checks.push('narrow and wide toolbars keep every command reachable and the More target unobstructed');
  await evaluate("document.querySelector('#sidebar').style.width='380px';document.documentElement.style.setProperty('--bg-color','white');document.documentElement.style.color='#222';panel.workbench.history.toolbar.update()");
  await click(`[data-hash="${base}"]`,'right');for(const id of ['open_changes','open_github','checkout','commit_checkout','branch_create','delete_branch','tag_add','cherry_pick','compare_remote','compare_base','compare_with','copy_hash','copy_message'])assert(await evaluate(`!!document.querySelector('[data-action=${id}]')`),id);assert(await evaluate('document.querySelector("[data-action=open_github]").disabled'));await click('[data-action=copy_message]');await wait('copied.includes("最后一行")');const copied_message=await evaluate('copied');assert(copied_message.includes('完整的第二段'));checks.push('commit menu has real Git actions and copies the entire message');
  await click(`[data-hash="${head}"]`,'right');await click('[data-action=compare_remote]');await wait('opened.length===1');assert.equal(await evaluate('opened[0][0].left'),'# Original\n');assert.equal(await evaluate('opened[0][0].right'),'# Original\n');assert.equal(await evaluate('opened[0][2].key'),JSON.stringify([base,head,'renamed.md']));checks.push('compare with upstream uses immutable objects and rename-aware paths');
  await click('[data-file="renamed.md"]','right');assert(await evaluate('!document.querySelector("[data-action=open_head]").disabled'));await click('[data-action=open_head]');await wait('revisions.length===1');assert.equal(await evaluate('revisions[0][1]'),head);assert.equal(await evaluate('revisions[0][3]'),'# Original\n');await click('[data-file="new.md"]','right');assert(await evaluate('document.querySelector("[data-action=open_head]").disabled'));await key('Escape');
  await click('[data-file="renamed.md"]','right');await click('[data-action=reveal_explorer]');assert.equal(await evaluate('commands.at(-1)[0]'),'linux_note:reveal_in_explorer');checks.push('HEAD reads saved objects, new files disable HEAD and Explorer uses shared command');
  await click('.git-scm-operation-menu');await click('[data-action=worktrees]');await click('[data-action=worktree_manage]');await wait('document.querySelector(".git-scm-worktree-entry")');assert(await evaluate('[...document.querySelectorAll(".git-scm-worktree-entry button")].find(node=>node.textContent.includes("删除")).disabled'));await key('Escape');checks.push('repository Worktrees entry reads Git and protects the main worktree');
  await click('[data-history-action=fetch]');await click('[data-git-preview=fetch]');await wait('!document.querySelector("[data-git-execute=fetch]").disabled');await evaluate(`void panel.switch_repo(${JSON.stringify(other)})`);await wait(`!panel.pending&&panel.root===${JSON.stringify(other.replace(/\\/g,"/"))}`);await click('[data-git-execute=fetch]');await delay(100);assert(!await evaluate('panel.writing'));await key('Escape');checks.push('prepared action cannot execute after repository switch');
  const late_menu=await evaluate(`(()=>{window.stale=panel.workbench.file_entries({path:'before.md',status:'M'},'INDEX','WORKTREE',[],panel.root).find(entry=>entry.id==='open_head');return true})()`);assert(late_menu);await evaluate(`void panel.switch_repo(${JSON.stringify(root)})`);await wait(`!panel.pending&&panel.root===${JSON.stringify(root.replace(/\\/g,"/"))}`);await evaluate('stale.action()');assert.equal(await evaluate('revisions.length'),1);checks.push('stale file menu cannot open an object in the new repository');
  await evaluate('panel.dispose();host.dispose()');assert.equal(await evaluate('document.querySelectorAll(".git-scm-sidebar").length'),0);checks.push('SCM lifetime releases observers, listeners and rows');
  console.log(JSON.stringify({status:'PASS',checks,evidence:temp},null,2));win.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(temp);if(win&&!win.isDestroyed()){await capture('failure');win.destroy();}app.exit(1);});
