const {app,BrowserWindow}=require('electron');const {build}=require('esbuild');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_single_row_titlebar_'));app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();let win;
app.whenReady().then(async()=>{
 win=new BrowserWindow({width:1280,height:800,show:false,frame:false,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 await win.loadURL('data:text/html,'+encodeURIComponent(`<!doctype html><html><head><title>draft.md</title><style>body{margin:0;--typ-workspace-top:0px}.unibody-window{--typ-workspace-top:24px}#top-titlebar{height:24px;position:absolute;left:300px}#w-restore{display:none}#w-max-group{display:inline-block}#write{position:absolute;top:var(--typ-workspace-top);padding:30px}#w-full,#w-pin{display:none}</style></head><body class="typora-node unibody-window"><div id="top-titlebar"><button id="w-menu-btn">native root</button><span id="title-text">draft</span><div id="w-traffic-lights"><button class="toolbar-icon" id="w-min">min</button><span id="w-max-group"><button class="toolbar-icon" id="w-max">max</button><span id="w-full"></span><span id="w-pin"></span></span><button class="toolbar-icon" id="w-restore">restore</button><button class="toolbar-icon" id="w-close">close</button></div></div><div id="write" contenteditable="true">preserve my draft and selection</div></body></html>`));
 win.webContents.on('console-message',event=>{if(event.level==='error')console.error('renderer: '+event.message);});
 const run=async source=>{const result=await win.webContents.executeJavaScript(`(async()=>{try{return{ok:true,value:await (0,eval)(${JSON.stringify(source)})}}catch(error){return{ok:false,error:error.stack}}})()`);if(!result.ok)throw Error(result.error);return result.value;};const tick=()=>run('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
 await run(`const base=document.createElement('base');base.href='file:///E:/Typora/resources/window.html';document.head.prepend(base);void 0`);
 await win.webContents.insertCSS('img{box-sizing:border-box;border-left:2px solid transparent;border-right:4px solid transparent}img:not([height]){height:auto}');
 const core_path=path.join(__dirname,'../vendor/workspace_core');
 const bundle=await build({stdin:{contents:'export {install_workspace_titlebar} from "./src/workspace_titlebar";export {register_remote_workspace_context} from "./src/remote_workspace_context";export {create_workspace_titlebar_menu} from "./src/workspace_titlebar_menu";export {read_titlebar_settings} from "./src/workspace_titlebar_settings";export {Settings} from "./vendor/workspace_core/src/settings/settings";export {default as shared_menu_css} from "./src/git_graph.css";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},write:false,format:'iife',globalName:'qa',tsconfigRaw:{compilerOptions:{experimentalDecorators:true}},plugins:[...require("./editor_bundle.cjs").editor_plugins(),{name:'titlebar-settings-fixture',setup(ctx){
  ctx.onResolve({filter:/^src\/common\/service$/},()=>({path:'service',namespace:'fixture'}));ctx.onResolve({filter:/^src\/utils$/},()=>({path:'utils',namespace:'fixture'}));
  ctx.onResolve({filter:/.*/,namespace:'fixture'},args=>path.isAbsolute(args.path)?{path:args.path,namespace:'file'}:undefined);
  ctx.onLoad({filter:/.*/,namespace:'fixture'},({path:entry})=>({contents:entry==='service'?'export function useService(){throw Error("unexpected service lookup");}':`export {Store} from ${JSON.stringify(path.join(core_path,'src/utils/store.ts'))};export {debounced} from ${JSON.stringify(path.join(core_path,'src/utils/decorator/debounced.ts'))};`,loader:'js'}));
  ctx.onResolve({filter:/^src\//},args=>({path:path.join(core_path,args.path)+'.ts'}));
 }}]});await run(bundle.outputFiles[0].text);
 await run(`const style=document.createElement('style');style.textContent=qa.shared_menu_css;document.head.append(style);window.settings_path=${JSON.stringify(path.join(evidence,'settings.json'))};window.settings_writes=0;window.fail_settings=false;window.settings_config={configDir:${JSON.stringify(evidence)},readConfigJson:(_name,fallback)=>require('fs').existsSync(settings_path)?JSON.parse(require('fs').readFileSync(settings_path,'utf8')):fallback,writeConfigJson:(_name,value)=>{if(fail_settings)throw Error('fixture settings denied');require('fs').writeFileSync(settings_path,JSON.stringify(value),'utf8');settings_writes++;}};window.settings_store=new qa.Settings({filename:'settings',version:1},{debug(){}},settings_config);void 0`);
 await run(`window.calls=[];window.setting_calls=[];window.replies=[];window.errors=[];console.error=(...args)=>errors.push(String(args));window.File={isNode:true,isMac:false,option:{framelessWindow:false},bundle:{filePath:'C:/docs/draft.md'},editor:{stylize:{changeBlock:(...args)=>calls.push(['block',...args])}}};window.reqnode=name=>name==='process'?{platform:'win32'}:{ipcRenderer:{invoke:(...args)=>{setting_calls.push(args);return new Promise((resolve,reject)=>replies.push({resolve,reject}))}}};window.JSBridge={invoke:async()=>({files:[],folders:[]})};window.ClientCommand={newFile:()=>calls.push(['new'])};window.original_nodes=[...document.querySelector('#top-titlebar').childNodes];window.original_close=document.querySelector('#w-close');original_close.onclick=()=>calls.push(['close']);window.callbacks=[];window.files={context_root:()=> 'C:/docs',path_api:require('path').win32,source_editor_active:()=>false,can_save_active:()=>false,core:{app:{workspace:{activeLeaf:{state:{path:'C:/docs/draft.md'}},on:(name,callback)=>{callbacks.push(callback);return()=>callbacks.splice(callbacks.indexOf(callback),1)},sidebar:{toggle(){}}},commands:{run(){}}}}};window.binding=qa.install_workspace_titlebar(files,()=>calls.push(['search']));void 0`);
 assert.deepEqual(await run('setting_calls'),[['setting.put','framelessWindow',true]]);assert.equal(await run('document.querySelectorAll(".workspace-titlebar-center").length'),0);
 await run('replies[0].reject(Error("fixture"));void 0');await tick();assert.equal(await run('document.documentElement.dataset.linuxNoteTitlebar'),'setting-failed');
 await run('binding.dispose();window.binding=qa.install_workspace_titlebar(files,()=>{});void 0');assert.equal(await run('setting_calls.length'),2);
 await run('binding.dispose();document.documentElement.dataset.linuxNoteTitlebar="external";replies[1].resolve();File.option.framelessWindow=true;files.core.app.settings=settings_store;window.binding=qa.install_workspace_titlebar(files,()=>calls.push(["search"]));void 0');await tick();
 assert(await run('binding===qa.install_workspace_titlebar(files,()=>{})&&document.querySelector("#w-close")===original_close'));
 // Typora 原生切文档回调会直接查询并更新标题节点；隐藏后仍须连接，不能中断加载。
 await run(`document.querySelector('#title-text').classList.add('title-modified');document.querySelector('#title-text').textContent='target.md';document.querySelector('#title-text').classList.remove('title-modified');void 0`);
 assert(await run(`document.querySelector('#title-text').isConnected&&document.querySelector('#w-menu-btn').isConnected&&document.querySelector('#title-text').textContent==='target.md'&&document.querySelector('#title-text').getBoundingClientRect().height===0`));
 const geometry=await run(`(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};return{bar:rect('#top-titlebar'),logo:rect('.workspace-titlebar-logo'),search:rect('.workspace-titlebar-search'),controls:rect('#w-traffic-lights'),editor:rect('#write'),menus:[...document.querySelectorAll('.workspace-titlebar-menu>button')].filter(b=>!b.hidden).map(b=>b.textContent)}})()`);
 assert.equal(geometry.bar.height,35);assert.equal(geometry.editor.y,35);assert.deepEqual(geometry.menus,['文件','编辑','段落','格式','视图','主题','终端','']);assert.equal(geometry.search.height,22);assert.equal(geometry.controls.width,138);assert(geometry.search.x>300&&geometry.search.right<geometry.controls.x);
 assert.deepEqual(await run('[...document.querySelectorAll(".workspace-titlebar-menu>button")].slice(0,-1).map(b=>b.textContent)'),['文件','编辑','段落','格式','视图','主题','终端','帮助']);
 await run('document.querySelector(".workspace-titlebar-menu>button:last-child").click();void 0');await tick();assert(await run('document.querySelector(".workspace-titlebar-popup").textContent.includes("帮助")'),'overflow retains Help when the new terminal menu consumes its slot');await run('window.dispatchEvent(new Event("workspace-titlebar-dismiss"))');
 assert.equal(geometry.logo.width,24);assert.equal(geometry.logo.height,24);assert.equal(geometry.logo.y+12,17.5);
 await run(`document.querySelector('.workspace-titlebar-menu>button:nth-child(8)').click();void 0`);await tick();
 assert(await run(`[...document.querySelectorAll('.workspace-titlebar-popup button')].find(b=>b.textContent==='Typora Code GitHub 仓库').disabled`),'浏览器适配缺失时仓库入口禁用');
 await run(`window.dispatchEvent(new Event('workspace-titlebar-dismiss'));window.repository_urls=[];JSBridge.showInBrowser=url=>repository_urls.push(url);document.querySelector('.workspace-titlebar-menu>button:last-child').click();void 0`);await tick();
 await run(`[...document.querySelectorAll('.workspace-titlebar-popup button')].find(b=>b.textContent==='帮助').click();void 0`);await tick();
 assert(await run(`(()=>{const b=[...document.querySelectorAll('.workspace-titlebar-popup button')].find(b=>b.textContent==='Typora Code GitHub 仓库'),r=b.getBoundingClientRect();b.focus();return !b.disabled&&r.width>0&&r.right<=innerWidth&&r.left>=0})()`),'更多菜单内仓库入口完整可见');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return'});win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return'});await tick();
 assert.deepEqual(await run('repository_urls'),['https://github.com/FormingSystem/typora_code'],'键盘激活一次仅打开固定项目仓库');
 assert.equal(await run(`document.querySelectorAll('.workspace-titlebar-popup').length`),0,'打开浏览器后关闭菜单');
 await run(`files.context_root=()=> 'D:/alternate_workspace';window.dispatchEvent(new Event('linux-note-workspace-context-changed'));void 0`);
 assert.equal(await run('document.querySelector(".workspace-titlebar-search span").textContent'),'alternate_workspace','folder-only changes update the centered search label without a title or active editor change');
 await run(`window.release_remote=qa.register_remote_workspace_context(()=>({target:'alice@server.test',username:'alice',name:'开发虚拟机 / 日常账号',port:2222,remote_path:'/home/alice',state:'connected'}));window.dispatchEvent(new Event('typora-code-remote-state-changed'));`);
 assert.equal(await run('document.querySelector(".workspace-titlebar-search span").textContent'),'SSH: alice');
 assert((await run('document.querySelector(".workspace-titlebar-search").title')).includes('开发虚拟机 / 日常账号'));
 await run(`release_remote();window.dispatchEvent(new Event('linux-note-workspace-context-changed'));`);
 assert.equal(await run('document.querySelector(".workspace-titlebar-search span").textContent'),'alternate_workspace');
 await run(`files.context_root=()=> 'D:/';window.dispatchEvent(new Event('linux-note-workspace-context-changed'));void 0`);
 assert.equal(await run('document.querySelector(".workspace-titlebar-search span").textContent'),'D:/','drive root remains a visible search label when basename is empty');
 await run(`files.context_root=()=> 'D:/alternate_workspace';window.dispatchEvent(new Event('linux-note-workspace-context-changed'));void 0`);
 assert(await run(`(()=>{const logo=document.querySelector('.workspace-titlebar-logo'),style=getComputedStyle(logo);return logo.src.endsWith('/assets/icon/icon_32x32@2x.png')&&logo.getAttribute('width')==='24'&&logo.getAttribute('height')==='24'&&style.borderLeftWidth==='0px'&&style.borderRightWidth==='0px'&&logo.getBoundingClientRect().width+parseFloat(style.marginLeft)+parseFloat(style.marginRight)===32})()`),'same host Typora artwork is legible without widening its titlebar slot or inheriting document image borders');
 await run(`document.querySelector('.workspace-titlebar-search').click();window.dispatchEvent(new CustomEvent('linux-note-reading-history-state',{detail:{back:true,forward:false}}));window.travel=[];window.addEventListener('linux-note-reading-history-travel',event=>travel.push(event.detail.direction));document.querySelector('.workspace-titlebar-history').click();document.querySelectorAll('.workspace-titlebar-history')[1].click();void 0`);
 assert.deepEqual(await run('travel'),[-1]);assert.equal(await run('calls.at(-1)[0]'),'search');
 await run(`window.dispatchEvent(new CustomEvent('linux-note-reading-history-state',{detail:{back:true,forward:true}}));document.querySelectorAll('.workspace-titlebar-history')[1].click();void 0`);assert.deepEqual(await run('travel'),[-1,1]);

 // R029：搜索入口保留中性外观；用真实指针和键盘验证，不能只检查角色或CSS文本。
 win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
 const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 const move_pointer=async selector=>{const point=await run(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`),zoom=win.webContents.getZoomFactor();const position={x:Math.round(point.x*zoom),y:Math.round(point.y*zoom)};win.webContents.sendInputEvent({type:'mouseMove',...position});await pause(45);return position;};
 const appearance=selector=>run(`(()=>{const n=document.querySelector(${JSON.stringify(selector)}),s=getComputedStyle(n),r=n.getBoundingClientRect();return{background:s.backgroundColor,foreground:s.color,border:s.borderColor,radius:s.borderRadius,rect:[r.x,r.y,r.width,r.height]}})()`);
 const hover_evidence=[];
 for(const theme of ['light','dark'])for(const zoom of [1,1.25])for(const width of [1280,500]){
  win.setSize(width,800);win.webContents.setZoomFactor(zoom);await pause(100);await tick();
  await run(`document.documentElement.dataset.workspaceFileIconTheme=${JSON.stringify(theme)};document.body.style.setProperty('--text-color',${JSON.stringify(theme==='dark'?'#ccd6df':'#3f4652')});document.body.style.setProperty('--side-bar-bg-color',${JSON.stringify(theme==='dark'?'#191a1b':'#fafafd')});document.querySelector('#write').focus();void 0`);await pause(70);
  await move_pointer('#write');const before=await appearance('.workspace-titlebar-search'),navigation_before=await appearance('.workspace-titlebar-history'),calls_before=await run('calls.length');
  const position=await move_pointer('.workspace-titlebar-search');
  assert(await run(`document.querySelector('.workspace-titlebar-search').matches(':hover')&&document.activeElement===document.querySelector('#write')`),'hover reaches the search box without moving focus');
  assert.deepEqual(await appearance('.workspace-titlebar-search'),before,`neutral search hover ${theme}/${zoom}/${width}`);
  assert.equal(await run('calls.length'),calls_before,'hover must not activate search');
  assert(await run(`!document.querySelector('.workspace-titlebar-search').hasAttribute('aria-selected')&&!document.querySelector('.workspace-titlebar-search').hasAttribute('aria-pressed')&&document.querySelector('.workspace-titlebar-search').title==='搜索文件 (Ctrl+P)'`));
  for(const type of ['mouseDown','mouseUp'])win.webContents.sendInputEvent({type,button:'left',clickCount:1,...position});await pause(35);
  assert.equal(await run('calls.length'),calls_before+1,'one pointer click opens search once');assert.equal(await run('calls.at(-1)[0]'),'search');
  await move_pointer('.workspace-titlebar-history');assert.notEqual((await appearance('.workspace-titlebar-history')).background,navigation_before.background,'nearby navigation keeps normal hover feedback');assert.deepEqual(await appearance('.workspace-titlebar-search'),before,'leaving search restores its neutral appearance');
  hover_evidence.push({theme,zoom,width,...before});
 }
 win.setSize(1280,800);win.webContents.setZoomFactor(1);await run(`document.documentElement.dataset.workspaceFileIconTheme='light';document.body.style.removeProperty('--text-color');document.body.style.removeProperty('--side-bar-bg-color');void 0`);await pause(70);await move_pointer('#write');
 // 导航末项后按Tab进入搜索，检查焦点线及标准按钮键盘激活。
 await run(`document.querySelectorAll('.workspace-titlebar-history')[1].focus();void 0`);
 for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode:'Tab'});await pause(35);
 assert(await run(`document.activeElement===document.querySelector('.workspace-titlebar-search')&&document.activeElement.matches(':focus-visible')&&getComputedStyle(document.activeElement).outlineWidth==='1px'`),'keyboard search focus stays visible');
 for(const key_code of ['Return','Space']){const before=await run('calls.length');win.webContents.sendInputEvent({type:'keyDown',keyCode:key_code});win.webContents.sendInputEvent({type:'char',keyCode:key_code==='Return'?'\r':' '});win.webContents.sendInputEvent({type:'keyUp',keyCode:key_code});await pause(35);assert.equal(await run('calls.length'),before+1,key_code+' opens search once');assert.equal(await run('calls.at(-1)[0]'),'search');}
 fs.writeFileSync(path.join(evidence,'search_hover.json'),JSON.stringify(hover_evidence,null,2));

 // H001.1：真实右键进入显示配置，复用生产设置持久化与公共菜单。
 const context_selector='.workspace-titlebar-context';
 const right_click=async(selector)=>{const position=await move_pointer(selector);for(const type of ['mouseDown','mouseUp'])win.webContents.sendInputEvent({type,button:'right',clickCount:1,...position});await pause(50);assert(await run(`!!document.querySelector('${context_selector}')`),'right click opens titlebar configuration');};
 const choose=async key=>{await run(`document.querySelector('${context_selector} [data-action="${key}"]').click();void 0`);await tick();};
 const escape=async()=>{for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode:'Escape'});await pause(30);};
 const visible=selector=>run(`document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect().width>0`);
 await run(`window.native_context_calls=0;document.querySelector('#top-titlebar').addEventListener('contextmenu',()=>native_context_calls++);document.querySelector('#write').focus();getSelection().selectAllChildren(document.querySelector('#write'));void 0`);
 await right_click('.workspace-titlebar-menu>button');
 assert.deepEqual(await run(`Array.from(document.querySelectorAll('${context_selector} button')).map(b=>[b.textContent,b.getAttribute('role'),b.getAttribute('aria-checked')])`),[['菜单栏','menuitemcheckbox','true'],['命令中心','menuitemcheckbox','true'],['导航控件','menuitemcheckbox','true']]);
 assert.equal(await run('native_context_calls'),0,'host root menu cannot receive the intercepted contextmenu');
 await escape();assert(await run(`!document.querySelector('${context_selector}')&&document.activeElement===document.querySelector('#write')&&getSelection().toString()==='preserve my draft and selection'`),'Escape restores editor focus and selection');
 await right_click('.workspace-titlebar-menu>button');const writes_before=await run('settings_writes');await choose('navigation_controls');
 assert.equal(await run('settings_writes'),writes_before+1,'one click persists exactly once');assert(!await visible('.workspace-titlebar-history'));assert(await visible('.workspace-titlebar-search'));
 await right_click('.workspace-titlebar-search');await choose('command_center');assert(!await visible('.workspace-titlebar-search'));assert(await visible('.workspace-titlebar-window-title'));
 assert.equal(await run(`document.querySelector('.workspace-titlebar-window-title').textContent`),'draft.md');
 await right_click('.workspace-titlebar-window-title');assert.equal(await run(`document.querySelectorAll('${context_selector} button').length`),2,'navigation option follows command center enablement');await choose('command_center');assert(!await visible('.workspace-titlebar-history'),'navigation preference survives command center toggling');
 await right_click('.workspace-titlebar-search');await choose('navigation_controls');assert(await visible('.workspace-titlebar-history'));
 await right_click('.workspace-titlebar-menu>button');await choose('menu_bar');assert.equal(await run(`Array.from(document.querySelectorAll('.workspace-titlebar-menu>button')).filter(b=>!b.hidden).length`),1,'compact menu removes category slots');
 await run(`document.querySelector('.workspace-titlebar-menu>button:last-child').click();void 0`);await tick();assert(await run(`document.querySelector('.workspace-titlebar-popup').textContent.includes('文件')&&document.querySelector('.workspace-titlebar-popup').textContent.includes('帮助')`));
 await right_click('.workspace-titlebar-search');assert(!await run(`!!document.querySelector('.workspace-titlebar-popup')`),'right click replaces a main dropdown');await choose('menu_bar');
 await right_click('.workspace-titlebar-menu>button');await run(`fail_settings=true;void 0`);const persisted_before=fs.readFileSync(path.join(evidence,'settings.json'),'utf8');await choose('command_center');
 assert(await visible('.workspace-titlebar-search'));assert.equal(fs.readFileSync(path.join(evidence,'settings.json'),'utf8'),persisted_before,'failed save retains persistent values');assert(await run(`document.querySelector('[role="dialog"]').textContent.includes('fixture settings denied')`));await escape();await run('fail_settings=false;void 0');
 await run(`settings_store.set_and_save('unrelated',{keep:42});settings_store.set_and_save('titlebar',{menu_bar:'invalid',command_center:null,navigation_controls:3,keep:'retained'});void 0`);await tick();
 assert.deepEqual(await run('qa.read_titlebar_settings(settings_store)'),{menu_bar:true,command_center:true,navigation_controls:true});
 await right_click('.workspace-titlebar-menu>button');await choose('menu_bar');assert.equal(JSON.parse(fs.readFileSync(path.join(evidence,'settings.json'),'utf8')).settings.titlebar.keep,'retained');
 await run(`binding.dispose();settings_store=new qa.Settings({filename:'settings',version:1},{debug(){}},settings_config);files.core.app.settings=settings_store;binding=qa.install_workspace_titlebar(files,()=>calls.push(['search']));void 0`);await tick();
 assert.equal(await run(`Array.from(document.querySelectorAll('.workspace-titlebar-menu>button')).filter(b=>!b.hidden).length`),1,'fresh settings instance restores persisted compact mode');assert.deepEqual(await run(`settings_store.get('unrelated')`),{keep:42});
 await run(`document.querySelector('.workspace-titlebar-menu>button:last-child').focus();void 0`);for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode:'F10',modifiers:['shift']});await pause(35);assert(await run(`!!document.querySelector('${context_selector}')`));await choose('menu_bar');
 await run(`window.outside_field=document.createElement('input');outside_field.id='outside-field';outside_field.style.cssText='position:fixed;left:400px;bottom:40px;width:100px;height:24px';document.body.append(outside_field);void 0`);
 await right_click('.workspace-titlebar-menu>button');const outside=await move_pointer('#outside-field');for(const type of ['mouseDown','mouseUp'])win.webContents.sendInputEvent({type,button:'left',clickCount:1,...outside});await pause(30);assert(await run(`!document.querySelector('${context_selector}')&&document.activeElement===outside_field`),'outside click closes without stealing the clicked input focus');await run('outside_field.remove();void 0');
 const context_evidence=[];
 for(const theme of ['light','dark'])for(const zoom of [1,1.25]){
  win.setSize(500,650);win.webContents.setZoomFactor(zoom);await run(`document.documentElement.dataset.workspaceFileIconTheme=${JSON.stringify(theme)};document.body.style.setProperty('--text-color',${JSON.stringify(theme==='dark'?'#ededed':'#202020')});document.body.style.setProperty('--bg-color',${JSON.stringify(theme==='dark'?'#191a1b':'#fafafd')});void 0`);await pause(50);await right_click('.workspace-titlebar-menu>button:last-child');
  const measured=await run(`(()=>{const m=document.querySelector('${context_selector}'),r=m.getBoundingClientRect(),b=m.querySelector('button'),s=getComputedStyle(m);return{left:r.left,right:r.right,bottom:r.bottom,width:innerWidth,height:innerHeight,row:b.getBoundingClientRect().height,foreground:s.color,background:s.backgroundColor}})()`);
  assert(measured.left>=0&&measured.right<=measured.width&&measured.bottom<=measured.height);assert.equal(measured.row,24);assert.equal(measured.foreground,theme==='dark'?'rgb(237, 237, 237)':'rgb(32, 32, 32)');assert.equal(measured.background,theme==='dark'?'rgb(25, 26, 27)':'rgb(250, 250, 253)');context_evidence.push({theme,zoom,...measured});
  fs.writeFileSync(path.join(evidence,`context_${theme}_${zoom}.png`),(await win.webContents.capturePage()).toPNG());await escape();
 }
 fs.writeFileSync(path.join(evidence,'titlebar_context.json'),JSON.stringify(context_evidence,null,2));
 win.setSize(1280,800);win.webContents.setZoomFactor(1);await run(`document.documentElement.dataset.workspaceFileIconTheme='light';document.body.style.removeProperty('--text-color');document.body.style.removeProperty('--bg-color');void 0`);await pause(70);await move_pointer('#write');

 // 真实命令定义直接打开自己的条目，不先弹完整根菜单。
 await run(`window.editor=document.querySelector('#write');editor.focus();window.range=document.createRange();range.setStart(editor.firstChild,9);range.setEnd(editor.firstChild,17);getSelection().removeAllRanges();getSelection().addRange(range);document.querySelectorAll('.workspace-titlebar-menu>button')[2].click();void 0`);await tick();
 assert(await run(`document.querySelector('.workspace-titlebar-popup').textContent.includes('一级标题')&&!document.querySelector('.workspace-titlebar-popup').textContent.includes('新建窗口')`));
 await run(`window.stale_item=document.querySelector('.workspace-titlebar-entry:not(:disabled)');for(const type of ['keydown','keyup'])editor.dispatchEvent(new KeyboardEvent(type,{key:'Escape',bubbles:true,cancelable:true}));window.before_stale=calls.length;stale_item.click();void 0`);assert(await run('calls.length===before_stale&&!document.querySelector(".workspace-titlebar-popup")'));
 await run(`document.querySelectorAll('.workspace-titlebar-menu>button')[2].click();void 0`);await tick();
 await run(`document.querySelector('.workspace-titlebar-entry:not(:disabled)').click();void 0`);assert.deepEqual(await run('calls.at(-1)'),['block','header1']);assert.equal(await run('getSelection().toString()'),'my draft');assert(await run('document.activeElement===editor'));
 // 用真实菜单组件跑超长/嵌套/迟到结果和窄窗，而非仅检查CSS文本。
 await run(`window.owned_menu=document.querySelector('.workspace-titlebar-menu');owned_menu.style.display='none';window.long_defs=Array.from({length:7},(_,index)=>({label:['文件','编辑','段落','格式','视图','主题','帮助'][index],mnemonic:String(index),entries:async()=>Array.from({length:65},(_,n)=>({label:'item '+index+' '+n,action:()=>calls.push(['item',index,n]),children:n===3?[{label:'nested',action:()=>calls.push(['nested'])}]:undefined}))}));window.menu=qa.create_workspace_titlebar_menu(document.querySelector('#top-titlebar'),long_defs);document.querySelector('.workspace-titlebar-left').append(menu.element);menu.refresh();menu.element.children[2].click();void 0`);await tick();
 assert(await run(`(()=>{const p=document.querySelector('.workspace-titlebar-popup'),r=p.getBoundingClientRect();return r.top>=35&&r.bottom<=innerHeight-34&&p.scrollHeight>p.clientHeight&&p.clientHeight<innerHeight})()`));
 await run(`document.querySelector('.workspace-titlebar-popup').dispatchEvent(new WheelEvent('wheel',{deltaX:160,shiftKey:true,bubbles:true,cancelable:true}));void 0`);assert(await run('document.querySelector(".workspace-titlebar-popup").scrollTop>100'));
 await run(`document.querySelector('.workspace-titlebar-popup').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true,cancelable:true}));void 0`);assert.equal(await run('document.activeElement.textContent'),'item 2 64');
 await run(`document.querySelector('.workspace-titlebar-popup').dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true,cancelable:true}));document.querySelectorAll('.workspace-titlebar-popup>.workspace-titlebar-entry')[3].click();void 0`);assert.equal(await run('document.querySelectorAll(".workspace-titlebar-popup").length'),2);
 assert(await run('[...document.querySelectorAll(".workspace-titlebar-popup")].every(p=>{const r=p.getBoundingClientRect();return r.top>=35&&r.left>=0&&r.right<=innerWidth})'));
 await run(`document.querySelector('.workspace-titlebar-popup').dispatchEvent(new WheelEvent('wheel',{deltaY:20,bubbles:true,cancelable:true}));void 0`);assert.equal(await run('document.querySelectorAll(".workspace-titlebar-popup").length'),1);
 await run(`long_defs[0].entries=()=>new Promise(resolve=>window.late=resolve);menu.element.children[0].click();menu.element.children[1].click();late([{label:'stale menu'}]);void 0`);await tick();assert(!await run('document.querySelector(".workspace-titlebar-popup").textContent.includes("stale")'));
 await win.setSize(500,650);await tick();assert(await run(`(()=>{const search=document.querySelector('.workspace-titlebar-search').getBoundingClientRect(),controls=document.querySelector('#w-traffic-lights').getBoundingClientRect();return search.width>=24&&search.left>=0&&search.right<=controls.left&&controls.right<=innerWidth&&menu.element.lastChild.hidden===false})()`));
 for(const zoom of [1,1.25])for(const width of [500,1280])for(const dark of [false,true]){
  win.setSize(width,800);win.webContents.setZoomFactor(zoom);await pause(100);await tick();
  await run(`document.body.style.setProperty('--bg-color','${dark?'#191a1b':'#fff'}');document.body.style.setProperty('--text-color','${dark?'#ddd':'#24292f'}');long_defs[0].entries=async()=>[{label:'普通命令',shortcut:'Ctrl+Z'},{label:'不可用',disabled:true},{label:'未选',checked:false},{label:'已选',checked:true},{label:'子菜单',children:[{label:'子项'}]}];menu.close();menu.element.children[0].click();void 0`);await tick();
  const slot_metrics=await run(`(()=>{const rows=[...document.querySelectorAll('.workspace-titlebar-popup>.workspace-titlebar-entry')];return rows.map(row=>({text:row.textContent,role:row.getAttribute('role'),checked:row.getAttribute('aria-checked'),slot:!!row.querySelector('.workspace-titlebar-check'),glyph:!!row.querySelector('[data-git-icon=check]'),inset:row.querySelector('.workspace-titlebar-label').getBoundingClientRect().left-row.getBoundingClientRect().left}));})()`);
  assert(slot_metrics.length===5&&slot_metrics.every((row,i)=>row.slot===(i===2||i===3)&&Math.abs(row.inset-26)<1&&row.role===((i===2||i===3)?'menuitemcheckbox':'menuitem'))&&slot_metrics[2].checked==='false'&&slot_metrics[3].glyph,'R065.2 titlebar '+[zoom,width,dark]+JSON.stringify(slot_metrics));
  await run(`document.querySelectorAll('.workspace-titlebar-entry')[4].click();void 0`);await tick();
  assert(await run(`!document.querySelectorAll('.workspace-titlebar-popup')[1].querySelector('.workspace-titlebar-check')`),'nested plain item has no gutter');
  if(zoom===1&&width===1280&&!dark)fs.writeFileSync(path.join(evidence,'menu_slots.png'),await win.webContents.capturePage().then(image=>image.toPNG()));
 }
 win.webContents.setZoomFactor(1);
 await run(`menu.dispose();owned_menu.style.display='';void 0`);await win.setSize(1280,800);await tick();
 assert.equal(await run('[...owned_menu.children].filter(button=>!button.hidden).map(button=>button.textContent).join(",")'),'文件,编辑,段落,格式,视图,主题,终端,');
 await run(`window.input=document.createElement('input');input.value='abcdef';document.body.append(input);input.focus();input.setSelectionRange(2,4);owned_menu.children[2].click();void 0`);await tick();
 await run(`for(const type of ['keydown','keyup'])window.dispatchEvent(new KeyboardEvent(type,{key:'Escape',bubbles:true,cancelable:true}));void 0`);assert(await run('!document.querySelector(".workspace-titlebar-popup")&&document.activeElement===input&&input.selectionStart===2&&input.selectionEnd===4'));
 await run('input.remove();editor.focus();void 0');
 await run(`document.querySelector('#w-close').click();void 0`);assert.equal(await run('calls.at(-1)[0]'),'close');
 fs.writeFileSync(path.join(evidence,'titlebar.png'),(await win.webContents.capturePage()).toPNG());
 await right_click('.workspace-titlebar-menu>button');await run(`window.stale_context_action=document.querySelector('.workspace-titlebar-context [data-action="menu_bar"]');void 0`);const writes_before_dispose=await run('settings_writes');
 await run(`binding.dispose();binding.dispose();stale_context_action.click();void 0`);assert(await run('original_nodes.every((node,i)=>document.querySelector("#top-titlebar").childNodes[i]===node)&&document.querySelector("#w-close")===original_close&&callbacks.length===0&&!document.querySelector(".workspace-titlebar-popup")&&!document.querySelector(".workspace-titlebar-context")&&document.documentElement.dataset.linuxNoteTitlebar==="external"'));
 assert.equal(await run('settings_writes'),writes_before_dispose,'disposed menu actions cannot change settings');assert.equal(await run(`settings_store._listeners.titlebar.length`),0,'titlebar removes its settings subscription');
 const native_before_dispose=await run('native_context_calls');await run(`document.querySelector('#title-text').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}));void 0`);assert.equal(await run('native_context_calls'),native_before_dispose+1,'disposal releases right-click interception');
 assert.equal(await run('editor.textContent'),'preserve my draft and selection');
 fs.writeFileSync(path.join(evidence,'geometry.json'),JSON.stringify(geometry,null,2));console.log('PASS single row titlebar: 8 search hover cases; native right-click interception; 3 persisted visibility toggles and dependency restoration; failed saves; fresh settings reload; 4 context menu theme/zoom cases; keyboard, Escape and outside focus; direct menus; selection; Shift-wheel; nested bounds; stale results; compact overflow; original controls and disposal. '+evidence);win.destroy();app.exit(0);
}).catch(error=>{console.error(error);win?.destroy();app.exit(1)});
