const {app,BrowserWindow}=require('electron');
const {build}=require('esbuild'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_appearance_')),checks=[];
app.setPath('userData',path.join(root,'profile'));app.disableHardwareAcceleration();app.on('window-all-closed',()=>{});
let win;const pause=ms=>new Promise(r=>setTimeout(r,ms)),read=s=>win.webContents.executeJavaScript(s);
const check=async(s,label)=>{assert(await read(s),label);checks.push(label);};
app.whenReady().then(async()=>{
 const html=path.join(root,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>body{margin:0}.typ-workspace-root{position:absolute;top:35px;left:200px;right:0;bottom:24px}footer{position:absolute;bottom:0;height:24px}#write{font-size:18px}[hidden]{display:none!important}</style><section class="typ-workspace-root"><article id="write">Unchanged document</article></section><footer class="ty-footer"></footer>');
 const bundle=await build({stdin:{contents:'export * from "./src/workspace_content_zoom";export * from "./src/reading_font_zoom";export * from "./src/terminal_panel";export * from "./src/terminal_layout";',resolveDir:path.join(__dirname,'..')},bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text'}});
 const open=async()=>{win=new BrowserWindow({show:false,width:1000,height:750,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});await win.loadFile(html);await read(bundle.outputFiles[0].text);await read(`window.frame=require('electron').webFrame;window.binding=qa.bind_content_zoom({reqnode:require,ClientCommand:{setZoomLevel:v=>frame.setZoomLevel(v),resetZoom:()=>frame.setZoomLevel(0)}});window.panel=qa.create_terminal_panel(()=>{});window.layout=qa.create_terminal_layout(panel.body,panel.tabs,()=>{});window.font=qa.bind_reading_font_zoom(document.querySelector('.typ-workspace-root'),document.querySelector('#write'));window.done=()=>{font.dispose();binding.dispose();layout.dispose();panel.dispose();};void 0`);await pause(70);};
 await open();await check('qa.content_font_size(18)===18&&qa.content_font_size(14,"terminal")===14&&!panel.visible','first launch uses defaults');
 await read('qa.change_content_font("editor",3);qa.change_content_font("terminal",5);frame.setZoomLevel(-1);binding.sync();panel.show();panel.container.querySelector("[role=separator]").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowUp"}));panel.maximize();localStorage.setItem("unrelated","preserved");void 0');await pause(80);
 const saved=await read('({editor:qa.content_font_size(18)*frame.getZoomFactor(),terminal:qa.content_font_size(14,"terminal")*frame.getZoomFactor(),factor:frame.getZoomFactor(),raw:localStorage.getItem("typora-code:content-zoom:v1")})');
 await read('done()');await check('localStorage.getItem("typora-code:terminal-panel-visible")==="true"','disposal preserves visible state');win.destroy();
 for(let i=0;i<20;i++){await open();await check(`Math.abs(qa.content_font_size(18)*frame.getZoomFactor()-${saved.editor})<.001&&Math.abs(qa.content_font_size(14,"terminal")*frame.getZoomFactor()-${saved.terminal})<.001&&Math.abs(frame.getZoomFactor()-${saved.factor})<.001`,'new renderer restores fonts and zoom without cumulative compensation '+i);await read('done()');win.destroy();}
 await open();await check('panel.maximized&&Number(localStorage.getItem("linux-note-terminal-panel-height"))===.45','panel maximization and normal height survive restart');
 await read('qa.reset_content_appearance();panel.reset();layout.reset();void 0');await check('frame.getZoomFactor()===1&&qa.content_font_size(18)===18&&qa.content_font_size(14,"terminal")===14&&!panel.visible&&!panel.maximized&&localStorage.getItem("unrelated")==="preserved"&&document.querySelector("#write").textContent==="Unchanged document"','reset restores appearance while retaining content and unrelated state');
 await read('done()');win.destroy();await open();await check('frame.getZoomFactor()===1&&qa.content_font_size(18)===18&&!panel.maximized&&localStorage.getItem("typora-code:terminal-panel-visible")==="false"','reset persists across renderer restart');
 await read('done();localStorage.setItem("typora-code:content-zoom:v1",JSON.stringify({schema:1,editor:"bad",terminal:9999,startup_factor:0,window_factor:-1}))');win.destroy();await open();await check('qa.content_font_size(18)===18&&qa.content_font_size(14,"terminal")===14','invalid stored values fall back to defaults');await read('done()');
 console.log(JSON.stringify({status:'PASS',checks,evidence:root}));fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);win?.destroy();app.exit(1)});
