// 真实Monaco/TextMate/clangd组合；不以协议替身替代最终绘制。
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_code_analysis_')),checks=[],samples=[];let win;
app.setPath('userData',path.join(root,'profile'));app.disableHardwareAcceleration();
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const ev=source=>win.webContents.executeJavaScript(source);
const wait=async expression=>{for(let i=0;i<250;i++){if(await ev(expression))return;await delay(50);}throw Error('Timeout: '+expression+' '+await ev('JSON.stringify(window.state||window.errors)'));};
const code=['// 中文 😀','#define VALUE 7','typedef unsigned int port_t;','struct device { int state; };','int real(int arg) { return arg + VALUE; }',''].join('\n');
fs.writeFileSync(path.join(root,'source.c'),code);
app.whenReady().then(async()=>{
 const bundle=await require('esbuild').build({plugins:require('./editor_bundle.cjs').editor_plugins(),stdin:{contents:`export {git_diff_editor} from './src/git_diff_editor';export * from './src/monaco_code_theme';export * from './src/reading_code_theme';export * from './src/source_semantic_tokens';export * from './src/workspace_document_symbols';export * from './src/language_service_settings';export * from './src/source_navigation';export * as monaco from 'monaco-editor/editor/editor.api';`,resolveDir:base},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});
 fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><style>:root{--workspace-code-theme:dark_2026}body{margin:0;background:#121314;color:#bbbebf}.git-monaco-body{height:330px}.git-graph-document{width:900px}</style><body>');
 win=new BrowserWindow({show:false,width:1100,height:850,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});win.webContents.on('console-message',details=>console.log(details.message));await win.loadFile(path.join(root,'index.html'));
 await ev(`window.reqnode=name=>require(name);window.errors=[];addEventListener('error',e=>errors.push(String(e.error)));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));window.data={};window[Symbol.for('typora-code:workspace')]={app:{settings:{get:key=>data[key],set_and_save:(key,value)=>{data[key]=value}}}};void 0`);
 await ev(bundle.outputFiles[0].text);
 await ev(`window.source=new qa.git_diff_editor({title:'source.c',file:${JSON.stringify(path.join(root,'source.c'))},left:${JSON.stringify(code)}});document.body.append(source.container);window.preview=new qa.git_diff_editor({title:'preview.c',file:'preview.c',left:${JSON.stringify(code)}});document.body.append(preview.container);source.focused_editor().updateOptions({readOnly:false});window.model=source.models[0];window.selection={startLineNumber:5,startColumn:5,endLineNumber:5,endColumn:9};source.focused_editor().setSelection(selection);void 0`);
 await ev('qa.initialize_monaco_code_theme()');await delay(150);
 const themes=require('../vendor/vscode_themes/resolved.json');
 for(const mode of ['dark_2026','light_2026','dark','light']){
  await ev(`document.documentElement.style.setProperty('--workspace-code-theme',${JSON.stringify(mode)});document.documentElement.dataset.workspaceColors=${JSON.stringify(mode.startsWith('dark')?'dark':'light')};document.body.style.background=${JSON.stringify(themes[mode].colors['editor.background'])};qa.sync_monaco_code_theme();void 0`);await delay(180);
  const values=await ev(`(()=>{model.tokenization.forceTokenization(model.getLineCount());const line=model.tokenization.getLineTokens(5);return {background:getComputedStyle(source.container.querySelector('.monaco-editor-background')).backgroundColor,preview:getComputedStyle(preview.container.querySelector('.monaco-editor-background')).backgroundColor,font:source.focused_editor().getOption(qa.monaco.editor.EditorOption.fontInfo).fontFamily,selection:source.focused_editor().getSelection(),tokens:Array.from({length:line.getCount()},(_,i)=>({text:line.getLineContent().slice(line.getStartOffset(i),line.getEndOffset(i)),fg:line.getForeground(i)}))}})()`);
  const hex=themes[mode].colors['editor.background'],rgb='rgb('+[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)).join(', ')+')';assert.equal(values.background,rgb);assert.equal(values.preview,rgb);assert.equal(values.selection.startColumn,5);assert(new Set(values.tokens.map(t=>t.fg)).size>=3,'real TextMate categories');samples.push({mode,...values});
 }
 // 查找/替换文本框的真实剪贴板、撤销及菜单边界。
 const old_clipboard=require('electron').clipboard.readText();
 const key=async(name,modifiers=['control'])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:name,modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode:name,modifiers});await delay(70);};
 try{
  await ev(`source.focused_editor().getAction('editor.action.startFindReplaceAction').run();void 0`);await delay(120);
  for(const part of ['find-part','replace-part']){
   await ev(`window.input=source.container.querySelector('.${part} textarea');input.focus();input.select();document.execCommand('insertText',false,'selected input');input.select();void 0`);
   await key('c');assert.equal(require('electron').clipboard.readText(),'selected input');
   require('electron').clipboard.writeText('paste target');await key('v');assert.equal(await ev('input.value'),'paste target');assert.equal(await ev('model.getValue()'),code);
   await key('z');assert.equal(await ev('input.value'),'selected input');await key('y');assert.equal(await ev('input.value'),'paste target');
   await ev(`input.select();input.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:150,clientY:90}));void 0`);
   assert.deepEqual(await ev(`[...document.querySelectorAll('.workspace-text-input-menu [data-action]')].map(e=>e.dataset.action)`),['input_undo','input_redo','input_cut','input_copy','input_paste','input_selectAll']);
   await ev(`document.querySelector('[data-action="input_cut"]').click();void 0`);assert.equal(await ev('input.value'),'');assert.equal(await ev('model.getValue()'),code);
  }
  checks.push('Find and Replace Chromium Ctrl C/V/Z/Y plus input-only menu cut preserve source model');
  for(const mode of ['light','dark','light_2026','dark_2026']){
   await ev(`document.documentElement.style.setProperty('--workspace-code-theme','${mode}');document.body.style.background='${themes[mode].colors['editor.background']}';document.documentElement.dataset.workspaceColors='${mode.startsWith('dark')?'dark':'light'}';qa.sync_monaco_code_theme();for(const node of source.container.querySelectorAll('.find-part .monaco-custom-toggle'))if(!node.classList.contains('checked'))node.click();void 0`);await delay(100);
   const actual=await ev(`(()=>{const widget=source.container.querySelector('.find-widget'),toggle=widget.querySelector('.codicon-regex');return {widget:getComputedStyle(widget).backgroundColor,active:getComputedStyle(toggle).backgroundColor,foreground:getComputedStyle(toggle).color,disabled:getComputedStyle(widget.querySelector('.codicon-preserve-case')).opacity}})()`);
   const css_color=async value=>ev(`(()=>{const e=document.createElement('i');e.style.color='${value}';document.body.append(e);const value=getComputedStyle(e).color;e.remove();return value;})()`);
   assert.equal(actual.widget,await css_color(themes[mode].colors['editorWidget.background']));assert.equal(actual.active,await css_color(themes[mode].colors['inputOption.activeBackground']));samples.push({find_mode:mode,...actual});
   const hover_point=await ev(`(()=>{const node=source.container.querySelector('.find-part .codicon-regex');node.click();const r=node.getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)};})()`);
   win.webContents.sendInputEvent({type:'mouseMove',...hover_point});await delay(60);
   const hover=await ev(`(()=>{const node=source.container.querySelector('.find-part .codicon-regex'),probe=document.createElement('i');probe.style.backgroundColor='var(--vscode-inputOption-hoverBackground)';node.append(probe);const expected=getComputedStyle(probe).backgroundColor;probe.remove();return {hovered:node.matches(':hover'),actual:getComputedStyle(node).backgroundColor,expected};})()`);assert(hover.hovered);assert.equal(hover.actual,hover.expected);samples.push({hover_mode:mode,...hover});
  }
  checks.push('Find option selected and real mouse hover backgrounds plus widget surface follow four official palettes');
  await ev(`source.focused_editor().getContribution('editor.contrib.findController').closeFindWidget();preview.context_menu(new MouseEvent('contextmenu',{clientX:150,clientY:90}));void 0`);
  assert.equal(await ev(`document.querySelector('[data-action="cut"]').disabled&&document.querySelector('[data-action="paste"]').disabled`),true);
  await key('Escape',[]);await ev(`source.context_menu(new MouseEvent('contextmenu',{clientX:150,clientY:90}));void 0`);assert.equal(await ev(`document.querySelector('[data-action="paste"]').disabled`),false);await key('Escape',[]);
  checks.push('readonly preview disables source cut/paste; writable source enables them');
  await ev(`source.focused_editor().setSelection(selection);source.context_menu(new MouseEvent('contextmenu',{clientX:150,clientY:90}));document.querySelector('[data-action="copy"]').click();void 0`);await delay(80);assert.equal(require('electron').clipboard.readText(),'real');
  await ev(`source.context_menu(new MouseEvent('contextmenu',{clientX:150,clientY:90}));document.querySelector('[data-action="cut"]').click();void 0`);await wait(`!model.getValue().includes('int real(')`);
  await key('z');assert.equal(await ev('model.getValue()'),code);
  require('electron').clipboard.writeText('renamed');await ev(`source.focused_editor().setSelection(selection);source.context_menu(new MouseEvent('contextmenu',{clientX:150,clientY:90}));document.querySelector('[data-action="paste"]').click();void 0`);await wait(`model.getValue().includes('int renamed(')`);await key('z');assert.equal(await ev('model.getValue()'),code);checks.push('source context copy cut paste execute Monaco commands and retain undo');
  await ev(`window.diff=new qa.git_diff_editor({title:'diff.c',file:'diff.c',left:'int old_value;',right:'int new_value;'});document.body.append(diff.container);void 0`);
  for(const target of ['preview.focused_editor()','diff.editor.getModifiedEditor()']){
   await ev(`window.input_editor=${target};input_editor.focus();input_editor.getAction('actions.find').run();void 0`);await delay(80);
   await ev(`window.input=input_editor.getDomNode().querySelector('.find-part textarea');input.focus();input.select();document.execCommand('insertText',false,'view query');input.select();void 0`);
   assert.equal(await ev('document.activeElement===input'),true,target+' input focus '+await ev('document.activeElement.outerHTML'));
   await key('c');assert.equal(require('electron').clipboard.readText(),'view query');require('electron').clipboard.writeText('changed query');await key('v');assert.equal(await ev('input.value'),'changed query');
   await ev(`input.select();input.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:150,clientY:90}));void 0`);
   assert.equal(await ev(`!!document.querySelector('.workspace-text-input-menu')&&!document.querySelector('[data-action="input_paste"]').disabled`),true);
   await key('Escape',[]);await ev(`input_editor.getContribution('editor.contrib.findController').closeFindWidget();void 0`);
  }
  assert.equal(await ev('preview.models[0].getValue()'),code);assert.deepEqual(await ev('diff.models.map(model=>model.getValue())'),['int old_value;','int new_value;']);
  await ev('diff.dispose();void 0');checks.push('readonly preview and shared diff Find allow input clipboard while both source models stay unchanged');
 }finally{require('electron').clipboard.writeText(old_clipboard);}
 const language_samples={rust:'pub fn twice(value: i32) -> i32 { value * 2 } // comment',python:'def greet(value):\n    return "Hello" + str(value) # comment',java:'public class Sample { int twice(int value) { return value * 2; } } // comment',shell:'greet() { echo "hello $1"; } # comment',powershell:'function Get-Greeting { param([string]$Name) "Hello $Name" } # comment',csharp:'public class Sample { int Twice(int value) { return value * 2; } } // comment'};
 for(const [language,text] of Object.entries(language_samples)){
  const colors=await ev(`(async()=>{await qa.monaco.languages.getLanguages().find(item=>item.id===${JSON.stringify(language)})?.loader?.();const sample=qa.monaco.editor.createModel(${JSON.stringify(text)},${JSON.stringify(language)});await new Promise(resolve=>setTimeout(resolve,100));sample.tokenization.forceTokenization(sample.getLineCount());const colors=new Set();for(let line=1;line<=sample.getLineCount();line++){const tokens=sample.tokenization.getLineTokens(line);for(let i=0;i<tokens.getCount();i++)colors.add(tokens.getForeground(i));}sample.dispose();return [...colors];})()`);assert(colors.length>=3,language+'基础语法分类');samples.push({language,lexical_colors:colors});
 }
 checks.push('Python Java Bash PowerShell C# Rust actual Monaco lexical tokenization');
 checks.push('four official palettes rendered in source and preview; C TextMate tokens, selection and font retained');
 await ev(`document.documentElement.style.setProperty('--workspace-code-theme','dark_2026');qa.sync_monaco_code_theme();window.binding=qa.subscribe_document_symbols(model,${JSON.stringify(path.join(root,'source.c'))},${JSON.stringify(root)},value=>window.state=value);void 0`);
 await wait('state&&!state.loading&&qa.source_semantics(model)?.data.length>0');await delay(700);
 const semantic=await ev(`(()=>{const value=qa.source_semantics(model),encoded=qa.convert_semantic_tokens(value),line=model.tokenization.getLineTokens(5);return {provider:state.provider,types:value.token_types,count:encoded.length/5,line:Array.from({length:line.getCount()},(_,i)=>({text:line.getLineContent().slice(line.getStartOffset(i),line.getEndOffset(i)),fg:line.getForeground(i)})),complete:model.tokenization.hasCompleteSemanticTokens()}})()`);
 assert.equal(semantic.provider,'clangd');assert(semantic.types.includes('parameter'));assert(semantic.count>5);assert(semantic.complete,'Monaco consumes semantic tokens');samples.push({semantic});checks.push('real clangd semantic legend and ranges consumed by Monaco');
 await ev(`source.focused_editor().executeEdits('test',[{range:{startLineNumber:6,startColumn:1,endLineNumber:6,endColumn:1},text:'int unsaved_only;\\n'}]);void 0`);await wait('state.symbols.some(s=>s.name==="unsaved_only")&&!state.loading');assert.equal(fs.readFileSync(path.join(root,'source.c'),'utf8'),code);checks.push('unsaved text reanalysis preserves disk');
 await ev(`model.setValue('#define ENABLE 0\\n#if ENABLE\\nint inactive(void) { return 1; }\\n#if 1\\nint nested;\\n#endif\\n#else\\nint active;\\n#endif\\n');void 0`);
 await wait(`model.getAllDecorations().some(d=>d.options.inlineClassName==='source-inactive-region')&&!state.loading`);
 const inactive=await ev(`model.getAllDecorations().filter(d=>d.options.inlineClassName==='source-inactive-region').map(d=>d.range)`);assert(inactive.some(r=>r.startLineNumber<=3&&r.endLineNumber>=5));assert(!inactive.some(r=>r.startLineNumber<=8&&r.endLineNumber>=8));samples.push({inactive});
 for(const mode of ['dark_2026','light_2026']){await ev(`document.documentElement.style.setProperty('--workspace-code-theme','${mode}');qa.sync_monaco_code_theme();source.focused_editor().revealLine(3);void 0`);await wait(`!!source.container.querySelector('.source-inactive-region')`);assert.equal(await ev(`getComputedStyle(source.container.querySelector('.source-inactive-region')).opacity`),'0.55');}
 await ev(`model.setValue(model.getValue().replace('ENABLE 0','ENABLE 1'));void 0`);assert.equal(await ev(`model.getAllDecorations().filter(d=>d.options.inlineClassName==='source-inactive-region').length`),0);
 await wait(`model.getAllDecorations().some(d=>d.options.inlineClassName==='source-inactive-region'&&d.range.startLineNumber===8)&&!state.loading`);
 await ev(`model.setValue('int active_only;');void 0`);await wait('!state.loading');assert.equal(await ev(`model.getAllDecorations().filter(d=>d.options.inlineClassName==='source-inactive-region').length`),0);
 checks.push('real clangd conditional macro nested else ranges; opacity in light/dark; edit clears stale ranges and active-only clears decorations');
 await ev(`window.nav_targets=[];window.nav_notices=[];window.nav=qa.bind_source_navigation(source.focused_editor(),{valid:()=>true,query:(kind,position,signal)=>binding.navigate(kind,position,signal),open:async target=>{nav_targets.push(target)},notice:message=>nav_notices.push(message)});model.setValue('int destination(int value) { return value; }\\nint call(void) { return destination(7); }\\n');source.focused_editor().setPosition({lineNumber:2,column:26});void 0`);
 await ev(`source.focused_editor().getDomNode().dispatchEvent(new KeyboardEvent('keydown',{key:'F12',bubbles:true,cancelable:true}));void 0`);await wait('nav_targets.length===1');assert.equal(await ev('nav_targets[0].range.start.line'),0);checks.push('F12 through actual source navigation binding and shared LSP');
 const point=await ev(`(()=>{const editor=source.focused_editor(),p=editor.getScrolledVisiblePosition({lineNumber:2,column:26}),r=editor.getDomNode().getBoundingClientRect();return {x:Math.round(r.left+p.left+2),y:Math.round(r.top+p.top+p.height/2)}})()`);
 win.webContents.sendInputEvent({type:'mouseDown',...point,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseUp',...point,button:'left',clickCount:1});await delay(100);assert.equal(await ev('nav_targets.length'),1,'plain click is not navigation');
 win.webContents.sendInputEvent({type:'mouseDown',...point,button:'left',clickCount:1,modifiers:['control']});win.webContents.sendInputEvent({type:'mouseUp',...point,button:'left',clickCount:1,modifiers:['control']});await wait('nav_targets.length===2');checks.push('Chromium Ctrl+left click navigates; plain left click preserves editing');
 await ev(`window.selection_searches=0;window.addEventListener('linux-note-search-selection',()=>selection_searches++);source.focused_editor().setSelection({startLineNumber:2,startColumn:26,endLineNumber:2,endColumn:36});void 0`);
 win.webContents.sendInputEvent({type:'mouseDown',...point,button:'left',clickCount:1,modifiers:['control']});win.webContents.sendInputEvent({type:'mouseUp',...point,button:'left',clickCount:1,modifiers:['control']});await wait('nav_targets.length===3');assert.equal(await ev('selection_searches'),0);checks.push('selected source Ctrl+click belongs to navigation, not selection search');
 await ev(`model.setValue('int broken(void) { return missing_symbol; }');void 0`);await wait('state.diagnostics?.some(d=>d.message.includes("missing_symbol"))&&state.diagnostics_version===model.getVersionId()');checks.push('late real clangd diagnostics match current unsaved model version');
 await ev(`nav.dispose();void 0`);
 await ev(`window.pending_navigation=[];window.controlled_targets=[];window.controlled_nav=qa.bind_source_navigation(source.focused_editor(),{valid:()=>true,query:()=>new Promise(resolve=>pending_navigation.push(resolve)),open:async target=>controlled_targets.push(target),notice:()=>{}});window.result_target={file_path:${JSON.stringify(path.join(root,'source.c'))},range:{start:{line:0,character:4},end:{line:0,character:10}}};void 0`);
 for(let index=0;index<20;index++)await ev(`(async()=>{const task=controlled_nav.run('definition');model.setValue(model.getValue()+' ');pending_navigation.shift()([result_target]);await task;})()`);
 assert.equal(await ev('controlled_targets.length'),0);checks.push('20 delayed navigation results after edits do not open files');
 await ev(`window.choice_task=controlled_nav.run('definition');pending_navigation.shift()([result_target,{...result_target,range:{start:{line:1,character:0},end:{line:1,character:2}}}]);void 0`);
 await wait('!!document.querySelector(".workspace-history-picker")');
 await ev(`controlled_nav.dispose();void 0`);await wait('!document.querySelector(".workspace-history-picker")');assert.equal(await ev('controlled_targets.length'),0);checks.push('multiple destinations use shared picker; disposal cancels without opening');
 await ev(`qa.save_language_service_profiles(${JSON.stringify(root)},'user',{c:{provider:'disabled'}});void 0`);await wait('state.provider==="disabled"&&!state.loading');assert(await ev('!qa.source_semantics(model)'));checks.push('settings change cancels analysis and clears obsolete semantic colors');
 await ev('binding.dispose();source.dispose();preview.dispose();void 0');assert.equal(await ev('qa.monaco.editor.getModels().length'),0);assert.deepEqual(await ev('errors'),[]);checks.push('model disposal and no unhandled errors');
 fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks,samples},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence:root}));win.destroy();app.exit(0);
}).catch(error=>{fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'FAIL',checks,samples,error:String(error.stack)},null,2));console.error(error);win?.destroy();app.exit(1);});
