// 按已核对的 Typora 原生节点及委托事件验证移动，测试不修改安装目录。
const {app, BrowserWindow}=require('electron');
const assert=require('node:assert/strict'), fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_workspace_footer_'));
app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();
let test_window;const checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const check=(condition,label)=>{assert(condition,label);checks.push(label)};
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:900,height:600,webPreferences:{contextIsolation:false,offscreen:true,backgroundThrottling:false}});
  const html=path.join(evidence,'test.html');
  fs.writeFileSync(html,`<!doctype html><meta charset="utf-8"><style>
  *{box-sizing:border-box}html,body{margin:0;height:100%;font:13px system-ui;--bg-color:#fff;--text-color:#333}body{background:#fff;color:#333}#typora-sidebar{position:absolute;width:260px;left:40px;top:0;bottom:0;background:#eee}#sidebar-content{position:absolute;top:0;bottom:30px;width:100%;background:#f7f7f7}main{position:absolute;left:300px;right:0;top:0;bottom:30px}footer.ty-footer{position:fixed;left:300px;right:0;bottom:0;height:30px;display:none;border-top:1px solid #ddd}.show-footer footer.ty-footer{display:block;contain:style}.footer-item{line-height:28px}.footer-item-left{float:left}.footer-item-right{float:right}.linux-note-git-status{float:left;display:inline-flex;gap:2px;max-width:65%;overflow:hidden;white-space:nowrap}.sidebar-footer{position:absolute;left:0;bottom:0;width:100%;height:30px;border-top:1px solid #ddd;display:none;opacity:0;background:inherit}.active-tab-files.use-file-tree-style .sidebar-footer{display:flex;opacity:1}.sidebar-footer-item{display:inline-block;line-height:28px;font-size:12px;cursor:default;padding:0 4px}.use-file-tree-style .sidebar-footer-item{opacity:0}.sidebar-footer-main-item{flex:1;display:inline-block;overflow:hidden;background:inherit}.sidebar-footer-main-item-label{flex:1;text-align:center;text-overflow:ellipsis;overflow-x:hidden}.sidebar-footer-main-item .footer-btn{display:inline-block}#sidebar-menu-btn>.sidebar-footer-item{display:flex;white-space:nowrap;overflow-x:hidden}#sidebar-files-menu{display:none;position:absolute;bottom:2px;top:auto;left:4px;right:4px;margin:0;padding:6px;border:1px solid #999;box-shadow:0 5px 10px #0003;background:inherit;list-style:none}.show-sidebar-footer-context #sidebar-files-menu{display:block}#sidebar-files-menu li{white-space:nowrap;overflow-x:hidden}.active-tab-files #unpin-outline-btn{display:none}.active-tab-outline .file-action-item{display:none!important}.active-tab-outline .sidebar-footer{display:none!important}.switch-file-list-btn-to-list,.switch-file-list-btn-to-tree{display:none}.use-file-tree-style .switch-file-list-btn-to-list,.use-file-list-style .switch-file-list-btn-to-tree{display:inline}.pin-outline{--sidebar-width:260px}
  </style><body class="show-footer pin-outline"><aside id="typora-sidebar" class="active-tab-files use-file-tree-style"><div id="sidebar-content">侧栏下方预览</div><div class="sidebar-footer" id="ty-sidebar-footer"><div style="display:flex"><div class="sidebar-footer-item file-action-item" id="sidebar-new-file-btn" ty-hint="新建文件">+</div><div class="sidebar-footer-item outline-action-item" id="unpin-outline-btn" ty-hint="取消固定大纲">↗</div><div class="sidebar-footer-main-item" id="sidebar-menu-btn"><span class="sidebar-footer-item"><span class="sidebar-footer-main-item-label" id="sidebar-footer-main-item-label">非常长的仓库文件夹名称</span><span class="footer-btn">⋮</span></span><ul id="sidebar-files-menu" tabindex="-1"><li id="open-folder-from-sidebar-menu">打开文件夹…</li><li id="refresh-from-sidebar-menu">刷新</li></ul></div><div class="sidebar-footer-item file-action-item" id="switch-file-list-btn" ty-hint="切换文件列表/树"><span class="switch-file-list-btn-to-list">☷</span><span class="switch-file-list-btn-to-tree">⊞</span></div></div></div></aside><main>原生正文</main><footer class="ty-footer" aria-hidden="true"><div class="footer-item footer-item-left linux-note-git-status">master　↓ 0 ↑ 0　提交图</div><div class="footer-item footer-item-left" id="toggle-sourceview-btn">&lt;/&gt;</div><div class="footer-item footer-item-right" id="footer-word-count">114 词</div></footer></body>`);
  await test_window.loadFile(html);
  await evaluate(`window.old_actions=document.querySelector('#ty-sidebar-footer');window.old_menu=document.querySelector('#sidebar-files-menu');window.counts={new_file:0,list:0,unpin:0,open:0};old_actions.addEventListener('click',event=>{if(event.target.closest('#sidebar-new-file-btn'))counts.new_file++;if(event.target.closest('#switch-file-list-btn')){counts.list++;const sidebar=document.querySelector('#typora-sidebar'),tree=sidebar.classList.contains('use-file-tree-style');sidebar.classList.toggle('use-file-tree-style',!tree);sidebar.classList.toggle('use-file-list-style',tree);}});old_actions.addEventListener('mousedown',event=>{if(event.target.closest('#sidebar-menu-btn>.sidebar-footer-item')){old_actions.classList.toggle('show-sidebar-footer-context');old_menu.focus();}});old_menu.addEventListener('mousedown',event=>{if(event.target.closest('#open-folder-from-sidebar-menu'))counts.open++;});document.addEventListener('click',event=>{if(event.target.closest('#unpin-outline-btn'))counts.unpin++;});`);
  const bundle=await build({stdin:{contents:'export {install_workspace_footer} from "./src/workspace_footer";',resolveDir:path.join(__dirname,'..')},bundle:true,format:'iife',globalName:'footer_qa',loader:{'.css':'text'},write:false});
  await evaluate(bundle.outputFiles[0].text);await evaluate('window.binding=footer_qa.install_workspace_footer();void 0');
  check(await evaluate('old_actions.parentNode===document.querySelector("footer.ty-footer")&&old_menu===document.querySelector("#sidebar-files-menu")'), 'moves original container and dropdown without cloning event targets');
  check(await evaluate('getComputedStyle(document.querySelector("#sidebar-content")).bottom==="0px"'), 'sidebar preview receives the old footer height');
  check(await evaluate('footer_qa.install_workspace_footer()===binding&&document.querySelectorAll("[data-workspace-footer-style]").length===1'), 'repeated initialization does not duplicate controls or styles');
  const action_width_before=await evaluate('old_actions.getBoundingClientRect().width');
  await evaluate('document.querySelector("#sidebar-new-file-btn").click();document.querySelector("#switch-file-list-btn").click();document.querySelector("#sidebar-menu-btn>.sidebar-footer-item").dispatchEvent(new MouseEvent("mousedown",{bubbles:true}));document.querySelector("#open-folder-from-sidebar-menu").dispatchEvent(new MouseEvent("mousedown",{bubbles:true}));');
  await delay(30);
  check(await evaluate('counts.new_file===1&&counts.list===1&&counts.open===1&&document.activeElement===old_menu'), 'native delegated file, layout and menu handlers survive the move');
  const metrics=await evaluate('(()=>{const rect=node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};return{actions:rect(old_actions),row:rect(old_actions.firstElementChild),menu_button:rect(document.querySelector("#sidebar-menu-btn")),label:rect(document.querySelector("#sidebar-footer-main-item-label")),toggle:rect(document.querySelector("#switch-file-list-btn")),menu:rect(old_menu),sidebar:rect(document.querySelector("#typora-sidebar")),git:rect(document.querySelector(".linux-note-git-status")),words:rect(document.querySelector("#footer-word-count"))}})()');
  check(metrics.actions.x>=metrics.sidebar.right&&metrics.actions.right<=metrics.words.x+1&&metrics.actions.x>=metrics.git.right,'file controls align on central right without overlapping Git or word count');
  check(Math.abs(action_width_before-metrics.actions.width)<=1&&Math.abs(metrics.actions.width-66)<=1&&Math.abs(metrics.row.width-metrics.actions.width)<=1,'list/tree switching keeps the native action group at its three-control content width');
  check(Math.abs(metrics.menu_button.width-22)<=1&&Math.abs(metrics.toggle.width-22)<=1&&metrics.label.width<=1,'the folder label remains in the original DOM without stretching the menu trigger');
  check(metrics.menu.bottom<=metrics.actions.y&&metrics.menu.x>=0&&metrics.menu.right<=900,'dropdown opens above moved controls within the window');
  await evaluate('old_actions.classList.remove("show-sidebar-footer-context");document.querySelector("#typora-sidebar").className="active-tab-outline use-file-list-style"');await delay(40);
  check(await evaluate('getComputedStyle(old_actions).display!=="none"&&getComputedStyle(document.querySelector("#unpin-outline-btn")).display!=="none"&&getComputedStyle(document.querySelector("#sidebar-new-file-btn")).display==="none"'), 'outline controls stay in central footer while native contextual visibility is preserved');
  await evaluate('document.querySelector("#unpin-outline-btn").click();document.querySelector("#typora-sidebar").className="active-tab-files use-file-list-style"');await delay(40);
  check(await evaluate('counts.unpin===1&&getComputedStyle(document.querySelector(".switch-file-list-btn-to-tree")).display!=="none"'), 'document delegated outline action and native list/tree glyph state remain functional');
  await evaluate('document.querySelector("#typora-sidebar").style.display="none"');
  check(await evaluate('getComputedStyle(old_actions).display!=="none"'),'hiding sidebar does not hide the relocated native controls');
  await evaluate('document.querySelector("footer.ty-footer").style.left="680px"');
  check(await evaluate('(()=>{const r=old_actions.getBoundingClientRect(),g=document.querySelector(".linux-note-git-status").getBoundingClientRect(),w=document.querySelector("#footer-word-count").getBoundingClientRect();return r.left>=g.right&&r.right<=w.left+1&&w.right<=innerWidth})()'),'controls and Git shrink without overlapping in a 220px editor');
  fs.writeFileSync(path.join(evidence,'footer.png'),(await test_window.webContents.capturePage()).toPNG());
  await evaluate('binding.dispose();binding.dispose();document.querySelector("#typora-sidebar").style.display=""');
  check(await evaluate('old_actions.parentNode.id==="typora-sidebar"&&!document.querySelector("[data-workspace-footer-style]")&&document.querySelector("footer.ty-footer").getAttribute("aria-hidden")==="true"'),'dispose restores original placement, accessibility and styles');
  console.log(JSON.stringify({status:'PASS',checks,metrics,evidence}));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(test_window&&!test_window.isDestroyed()){fs.writeFileSync(path.join(evidence,'failure.png'),(await test_window.webContents.capturePage()).toPNG());test_window.destroy();}app.exit(1)});
