import assert from 'node:assert/strict';
import path from 'node:path';
import {build} from 'esbuild';
const compiled=await build({entryPoints:['src/terminal_settings.ts'],bundle:true,platform:'node',format:'esm',write:false});
const api=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
let saved=JSON.stringify({profile:'cmd',font_size:18,scrollback:2000,location:'down'}),writes=0;
const process_api={platform:'win32',env:{SystemRoot:'C:\\Windows',ComSpec:'cmd.exe',PATH:'original',NODE_OPTIONS:'inherited'}};
const store=api.create_terminal_settings({getItem:()=>saved,setItem:(_,text)=>{saved=text;writes++;}},process_api,path.win32);
assert.equal(store.get().font_size,18);assert.equal(store.get().location,'panel');assert.equal(writes,0);
const old=saved;assert.throws(()=>store.update({...store.get(),font_size:NaN}));assert.equal(saved,old);
assert.throws(()=>store.update({...store.get(),env:{BAD:14}}));assert.throws(()=>store.update({...store.get(),profile:'unknown'}));
let updates=0;store.subscribe(()=>updates++);
const profile={id:'project',title:'Project',executable:'${env:SystemRoot}/shell.exe',args:['--flag','a b','$(literal)'],env:{path:'${workspaceFolder}/bin',REMOVE:null},cwd:'build',color:'#112233'};
store.update({...store.get(),profiles:[profile],profile:'project',env:{REMOVE:'yes',MODE:'test'}});
assert.equal(updates,1);const launch=api.resolve_terminal_launch(store.get(),store.profiles().find(item=>item.id==='project'),'D:\\repo',process_api,path.win32);
assert.deepEqual(launch.args,['--flag','a b','$(literal)']);assert.equal(launch.cwd,'D:\\repo\\build');assert.equal(launch.env.path,'D:\\repo/bin');assert.equal(launch.env.PATH,undefined);assert.equal(launch.env.REMOVE,undefined);assert.equal(launch.env.NODE_OPTIONS,undefined);assert.equal(launch.env.MODE,'test');
assert.equal(api.resolve_terminal_launch(store.get(),profile,'D:\\chosen',process_api,path.win32,true).cwd,'D:\\chosen');
const isolated=store.get();isolated.font_size=99;assert.equal(store.get().font_size,18);
assert.throws(()=>store.update({...store.get(),profiles:[profile,profile]}));store.dispose();
console.log(JSON.stringify({status:'PASS',checks:['valid stored fields retained','invalid update atomic','default profile must exist','custom profile arguments remain separate','relative cwd and variable expansion','case-insensitive Windows env replacement and null removal','explicit selected directory wins','configuration snapshots isolated']}));
