// 平台适配器以可控快照验证生命周期；这里不触碰用户系统剪贴板。
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const built=await build({entryPoints:[fileURLToPath(new URL('../src/workspace_file_clipboard.ts',import.meta.url))],bundle:true,format:'esm',write:false});
const {create_workspace_file_clipboard:create}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
let snapshot={paths:[],version:'0',move_requested:false},serial=0,disposed=false,read_gate,validate_gate,transfer_gate,failure=false;
const transfers=[],adapter={read:async()=>{const value=structuredClone(snapshot);if(read_gate)await read_gate;return value},write:async paths=>(snapshot={paths,version:String(++serial),move_requested:false}),clear:async version=>{if(snapshot.version!==version)return false;snapshot={paths:[],version:String(++serial),move_requested:false};return true;},dispose:()=>{disposed=true}},actions={validate:async()=>{if(validate_gate)await validate_gate;},transfer:async(...args)=>{transfers.push(args);if(transfer_gate)await transfer_gate;if(failure)throw Error('conflict');return ['/target/copied'];}};
const service=create(adapter,actions);let notifications=0;const unsubscribe=service.subscribe(()=>notifications++);
await service.copy('/root',['/root/a','/root/a'],false);assert.deepEqual(snapshot.paths,['/root/a']);await service.paste('/root','/target');assert.deepEqual(transfers.at(-1).slice(3),[false,true]);assert.equal(snapshot.paths.length,1);
await service.copy('/root',['/root/a'],true);assert(service.is_cut('/root/a'));await service.paste('/root','/target');assert.deepEqual(transfers.at(-1).slice(3),[true,false]);assert.deepEqual(snapshot.paths,[]);assert(!service.is_cut('/root/a'));
await service.copy('/root',['/root/a'],true);snapshot={paths:['/outside/b'],version:'external',move_requested:true};await service.refresh();assert(!service.is_cut('/root/a'));assert.match((await service.paste('/root','/target')).message,/源文件保留/);assert.deepEqual(transfers.at(-1).slice(3),[false,true]);
await service.copy('/root',['/root/a'],true);await service.paste('/other','/other/target');assert.deepEqual(transfers.at(-1).slice(3),[false,true]);assert.equal(snapshot.paths.length,1);
failure=true;await assert.rejects(service.paste('/root','/target'),/conflict/);assert(service.is_cut('/root/a'));failure=false;
let release;read_gate=new Promise(resolve=>release=resolve);let valid=true;const count=transfers.length,pending=service.paste('/root','/target',()=>valid);assert(service.is_busy());await assert.rejects(service.paste('/root','/target'),/正在处理/);valid=false;release();await assert.rejects(pending,/目标已改变/);assert.equal(transfers.length,count);read_gate=undefined;
validate_gate=new Promise(resolve=>release=resolve);valid=true;const before=structuredClone(snapshot),copying=service.copy('/root',['/root/b'],true,()=>valid);valid=false;release();await assert.rejects(copying,/上下文已改变/);assert.deepEqual(snapshot,before);validate_gate=undefined;
transfer_gate=new Promise(resolve=>release=resolve);const moving=service.paste('/root','/target');await new Promise(resolve=>setTimeout(resolve,0));snapshot={paths:['/outside/new'],version:'newer',move_requested:false};release();await moving;assert.equal(snapshot.version,'newer','successful old cut cannot clear a newer copy');transfer_gate=undefined;
await service.copy('/root',['/root/a'],true);let finish_refresh;read_gate=new Promise(resolve=>finish_refresh=resolve);const refreshing=service.refresh();await service.copy('/root',['/root/b'],true);finish_refresh();await refreshing;read_gate=undefined;assert(service.is_cut('/root/b'),'older focus refresh cannot invalidate newer cut intent');
// 旧读取的失败与成功一样只能处理自身快照，不能把后来建立的剪切降级为复制。
await service.copy('/root',['/root/a'],true);let reject_refresh;read_gate=new Promise((_resolve,reject)=>reject_refresh=reject);const failed_refresh=service.refresh();
await service.copy('/root',['/root/b'],true);const notify_after_new_cut=notifications;reject_refresh(Error('old clipboard read failed'));await failed_refresh;read_gate=undefined;
assert(service.is_cut('/root/b'),'older failed focus refresh cannot invalidate newer cut intent');assert.equal(notifications,notify_after_new_cut,'stale failure must not publish a change to the newer cut');
await service.paste('/root','/target');assert.deepEqual(transfers.at(-1).slice(1),[['/root/b'],'/target',true,false],'new cut still routes through the protected move after an older read fails');
// 当前剪切自身的读取失败仍应清除标记，不能把异常全部吞掉而保留失效状态。
await service.copy('/root',['/root/a'],true);read_gate=new Promise((_resolve,reject)=>reject_refresh=reject);const current_failed_refresh=service.refresh();reject_refresh(Error('current clipboard read failed'));await current_failed_refresh;read_gate=undefined;assert(!service.is_cut('/root/a'),'current failed focus refresh invalidates its own cut intent');
snapshot={paths:[],version:'empty',move_requested:false};await assert.rejects(service.paste('/root','/target'),/没有文件/);
snapshot={paths:['bad\0path'],version:'bad',move_requested:false};await assert.rejects(service.paste('/root','/target'),/不合法/);
await service.copy('/root',Array.from({length:1025},(_,i)=>'/root/'+i),false);assert.equal(snapshot.paths.length,1025);assert.equal(snapshot.paths.at(-1),'/root/1024');
snapshot={paths:['/root/a'],version:'ok',move_requested:false};read_gate=new Promise(resolve=>release=resolve);const ending=service.paste('/root','/target');unsubscribe();const notify_before=notifications;service.dispose();release();await assert.rejects(ending,/目标已改变/);assert(disposed);assert.equal(notifications,notify_before);await assert.rejects(service.copy('/root',['/root/a'],false),/已关闭/);
console.log(JSON.stringify({status:'PASS',checks:['deduplicated system copy','version-bound local cut','external copy and external cut preserve source','cross-root cut becomes copy','conflict retains cut','asynchronous context and busy guards','copy cancellation before write','newer clipboard survives old move cleanup','late focus refresh retains newer cut intent','late failed focus refresh preserves newer cut and its protected move','current failed focus refresh invalidates its own cut intent','empty and malformed payload bounds','dispose cancels pending paste and listeners']}));
