import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {build} from 'esbuild';
const compiled=await build({stdin:{contents:'export * from "./src/workspace_local_history";export * from "./src/workspace_history_restore";export * from "./src/workspace_text_document";export * from "./src/workspace_file_events";',resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const api=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_local_history_')),directory=path.join(root,'history'),file=path.join(root,'test.md');
let options={enabled:true,max_entries:50,merge_window:10,exclude:{},workspace_root:root};
const modules={fs,path_api:path,crypto},history=api.create_local_history_store(modules,directory,()=>options),bytes=text=>Buffer.from(text),checks=[];
const first=await history.record(file,bytes('one'));assert(first);assert.deepEqual(Buffer.from(await history.read(first)),bytes('one'));
const duplicate=await history.record(file,bytes('one'));assert.equal(duplicate.id,first.id);
const merged=await history.record(file,bytes('two'));assert.equal((await history.list(file)).length,1);assert.notEqual(merged.id,first.id);await assert.rejects(history.read(first),/删除|合并/u);
options.merge_window=0;await history.record(file,bytes('three'));assert.equal((await history.list(file)).length,2);
const reopened=api.create_local_history_store(modules,directory,()=>options);assert.equal((await reopened.resources())[0].file_path,file);assert.equal((await reopened.list(file)).length,2);checks.push('persistent resources, exact bytes, deduplication and merge policy');
const clock=Date.now,same_tick=path.join(root,'same_tick.md');let tick_entries;
try{Date.now=()=>1000;await history.record(same_tick,bytes('first'));await history.record(same_tick,bytes('second'));tick_entries=await history.list(same_tick);}finally{Date.now=clock;}
assert.deepEqual(Buffer.from(await history.read(tick_entries[0])),bytes('second'));assert(tick_entries[0].timestamp>tick_entries[1].timestamp);checks.push('same-millisecond saves retain chronological order');
options.max_entries=2;await history.record(file,bytes('four'));assert.equal((await history.list(file)).length,2);
assert(await history.record(path.join(root,'big'),Buffer.alloc(257*1024,65)));assert.equal(await history.record(path.join(root,'binary'),Buffer.from([1,0,2,0,5])),undefined);
const large_entry=await history.record(path.join(root,'large.md'),Buffer.alloc(17*1024*1024,65));assert(large_entry);assert.equal((await history.read(large_entry)).length,17*1024*1024);
options.exclude={'**/*.secret':true};assert.equal(await history.record(path.join(root,'a.secret'),bytes('secret')),undefined);
for(const [glob,name,expected] of [['**/*.md','a.md',true],['**/*.md','a/b.md',true],['*.md','a/b.md',false],['folder/{a,b}.txt','folder/b.txt',true],['a[!b]?.txt','acd.txt',true]])assert.equal(api.history_glob_matches(glob,name),expected);
options.enabled=false;assert.equal(await history.record(file,bytes('off')),undefined);options.enabled=true;options.exclude={};options.max_entries=50;checks.push('retention preferences and exclusions remain; content size does not block snapshots');
const unicode=path.join(root,'中文.md');const utf16=Buffer.concat([Buffer.from([255,254]),Buffer.from('中文\r\n','utf16le')]);const unicode_entry=await history.record(unicode,utf16);assert(unicode_entry);assert.deepEqual(Buffer.from(await history.read(unicode_entry)),utf16);
const saved=[];const unsubscribe=api.observe_workspace_file_saved(event=>{saved.push(event);void history.record(event.file_path,event.bytes,event.source);});
fs.writeFileSync(file,'baseline\r\n');const document=api.create_text_document({fs,path_api:path},file);await document.load();await document.save('saved\n');await history.flush();assert.equal(saved.length,1);assert.deepEqual(Buffer.from(saved[0].bytes),fs.readFileSync(file));
fs.writeFileSync(file,'external');await assert.rejects(document.save('conflicting'),/变化|修改|changed/u);assert.equal(saved.length,1);unsubscribe();checks.push('actual successful save events preserve encoding; conflict emits no history');
const old=await history.record(file,bytes('restore this'), 'File Saved',true);fs.writeFileSync(file,'current');
await api.restore_history_entry(modules,history,old,history.hash(bytes('current')),()=>true);assert.equal(fs.readFileSync(file,'utf8'),'restore this');assert((await history.list(file)).some(entry=>entry.source==='Before Restore'));
fs.writeFileSync(file,'changed again');await assert.rejects(api.restore_history_entry(modules,history,old,history.hash(bytes('current')),()=>true),/变化/u);assert.equal(fs.readFileSync(file,'utf8'),'changed again');
await assert.rejects(api.restore_history_entry(modules,history,old,history.hash(bytes('changed again')),()=>false),/变化|取消/u);
fs.chmodSync(file,0o444);await assert.rejects(api.restore_history_entry(modules,history,old,history.hash(bytes('changed again')),()=>true),/只读/u);fs.chmodSync(file,0o644);
fs.unlinkSync(file);await api.restore_history_entry(modules,history,old,undefined,()=>true);assert.equal(fs.readFileSync(file,'utf8'),'restore this');
fs.unlinkSync(file);const racing={...modules,fs:{promises:{...fs.promises,link:async(from,to)=>{fs.writeFileSync(to,'racing writer');return fs.promises.link(from,to);}}}};
await assert.rejects(api.restore_history_entry(racing,history,old,undefined,()=>true),{code:'EEXIST'});assert.equal(fs.readFileSync(file,'utf8'),'racing writer');
assert(!fs.readdirSync(root).some(name=>name.startsWith('.typora-history-')));checks.push('restore retains preimage, recovers deleted file, rejects external changes, read-only and racing recreation');
const renamed=path.join(root,'renamed.md');await history.move(file,renamed);assert.equal((await history.list(file)).length,0);assert((await history.list(renamed)).length>0);assert.equal(Buffer.from(await history.read({...old,file_path:renamed})).toString(),'restore this');
const folder=path.join(root,'folder'),nested=path.join(folder,'nested.md');await history.record(nested,bytes('nested'));await history.move(folder,path.join(root,'moved'),true);assert.equal((await history.list(path.join(root,'moved','nested.md'))).length,1);checks.push('file and directory rename carry saved history');
const concurrent=path.join(root,'concurrent.md');await Promise.all([history.record(concurrent,bytes('window one')),reopened.record(concurrent,bytes('window two'))]);assert.equal((await history.list(concurrent)).length,2);
const corrupt=(await history.list(concurrent))[0];const bucket=path.join(directory,history.hash(path.sep==='\\'?path.resolve(concurrent).toLowerCase():path.resolve(concurrent)));fs.writeFileSync(path.join(bucket,corrupt.id+'.data'),'tampered');await assert.rejects(history.read(corrupt),/校验/u);checks.push('independent window entries and corruption detection');
console.log(JSON.stringify({status:'PASS',checks,evidence:root},null,2));
