// R053：真实Chromium指针打开生产浮层；正文主题污染、Markdown安全与几何均检查实际DOM。
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const evidence=path.resolve(__dirname,'../../.cache/commit_hover_ui_'+Date.now());fs.mkdirSync(evidence,{recursive:true});
app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();
let win;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),samples=[];
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1200,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 win.webContents.on('console-message',event=>{if(event.level==='error')console.error(event.message)});
 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>body{font:13px "Segoe UI";margin:0}#list{position:absolute;top:240px;left:0;width:260px;height:60px}button{width:100%;height:30px}p,li{font:40px serif;margin:90px;color:red}ul{padding-left:90px}strong{font-size:40px}</style><div id="list"><button class="git-scm-history-commit" data-hash="'+ 'a'.repeat(40)+'">修复目录恢复<span class="git-scm-history-ref"><span class="git-scm-history-ref-name">main</span></span></button></div>');await win.loadFile(html);
 const ev=async code=>{try{return await win.webContents.executeJavaScript(code)}catch(error){console.error('Renderer stage: '+code.slice(0,100));throw error}};
 const bundle=await require('esbuild').build({stdin:{contents:'export {bind_git_commit_hover} from "./src/git_commit_hover";export {create_workspace_hover_markdown} from "./src/workspace_hover_markdown";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await ev(bundle.outputFiles[0].text);
 await ev(`(()=>{const style=document.createElement('style');style.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'))};document.head.append(style)})()`);
 const source='fix(workspace): 恢复上次文件\n\n- **目录隔离**与 `main`\n- 第二项\n  - 子项\n\n[文档](https://example.com/doc) [危险](javascript:alert(1))\n\n<img src="https://example.com/tracker" onerror="alert(1)">\n\n![远端图](https://example.com/image.png)';
 await ev(`window.source=${JSON.stringify(source)};window.requests=[];window.copies=[];window.links=[];window.failure=false;window.late=false;window.release=null;window.panel={root:'fixture',state:{root:'fixture',head:'${'a'.repeat(40)}',commits:[{hash:'${'a'.repeat(40)}',parents:[],subject:'摘要',author:'作者',date:'2026-09-19'}]},emoji:s=>s,date:c=>c.date,report:e=>{window.problem=String(e)},host:{copy:s=>copies.push(s),open_url:s=>links.push(s)},runner:{run:async(r,args)=>{requests.push(args);if(failure)throw Error('read failed');if(late&&!args.includes('--numstat'))await new Promise(r=>release=r);return args.includes('--numstat')?'91\t11\tfile.md\0':source}}};window.binding=qa.bind_git_commit_hover(document.querySelector('#list'),panel);void 0`);
 const move=async(on=true)=>{const zoom=win.webContents.getZoomFactor();win.webContents.sendInputEvent({type:'mouseMove',x:Math.round((on?100:inner_safe())*zoom),y:Math.round((on?252:80)*zoom)});await pause(on?600:300);};
 const inner_safe=()=>20;
 for(const theme of ['light','dark'])for(const zoom of [1,1.25])for(const width of [1200,600]){
  await move(false);win.setSize(width,800);win.webContents.setZoomFactor(zoom);await ev(`document.documentElement.dataset.workspaceFileIconTheme='${theme}';document.body.style.background='${theme==='dark'?'#202122':'white'}'`);await pause(200);console.log('geometry '+theme+' '+zoom+' '+width);await move();
  const result=await ev(`(()=>{const tip=document.querySelector('.git-commit-hover'),host=tip.querySelector('.git-commit-hover-message>div'),root=host.shadowRoot,ul=root.querySelector('ul'),p=root.querySelector('p'),r=tip.getBoundingClientRect();return {font:getComputedStyle(host).fontSize,line:getComputedStyle(host).lineHeight,padding:getComputedStyle(ul).paddingLeft,list:root.querySelectorAll('li').length,paragraphMargin:getComputedStyle(p).marginBottom,unsafe:!!root.querySelector('img,script,[onerror],a[href^="javascript:"]'),raw:root.textContent.includes('<img'),strong:getComputedStyle(root.querySelector('strong')).fontSize,pre:getComputedStyle(host).whiteSpace,overflow:tip.scrollWidth-tip.clientWidth,bounds:r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,borders:[...tip.querySelectorAll('.git-commit-hover-stats,.git-commit-hover-refs,.git-commit-hover-copy')].map(n=>getComputedStyle(n).borderTopWidth),size:r.toJSON()}})()`);
  assert.equal(result.font,'12px');assert.equal(result.line,'19px');assert.equal(result.strong,'12px');assert.equal(result.padding,'20px');assert.equal(result.list,3);assert.equal(result.paragraphMargin,'4px');assert(!result.unsafe&&result.raw&&result.bounds);assert.equal(result.pre,'normal');assert(result.overflow<=1);assert(result.borders.every(n=>parseFloat(n)>0&&parseFloat(n)<=1));
  samples.push({theme,zoom,width,...result});fs.writeFileSync(path.join(evidence,theme+'_'+zoom+'_'+width+'.png'),(await win.webContents.capturePage()).toPNG());
 }
 await ev(`document.querySelector('.git-commit-hover-message>div').shadowRoot.querySelector('a').click();document.querySelector('.git-commit-hover-copy').click();void 0`);await pause(40);assert.deepEqual(await ev('links'),['https://example.com/doc']);assert.deepEqual(await ev('copies'),['a'.repeat(40)]);
 await ev(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));void 0`);assert.equal(await ev(`!!document.querySelector('.git-commit-hover')`),false);
 // 不为压力测试触发1000次Git进程；以实际1000条正文测DOM布局，生命周期独立重复20次。
 for(const count of [20,100,1000]){
  await move(false);await ev(`binding.dispose();source='压力提交\\n\\n'+Array.from({length:${count}},(_,i)=>'- 项目 '+i).join('\\n');binding=qa.bind_git_commit_hover(document.querySelector('#list'),panel);void 0`);const start=Date.now();await move();
  assert.equal(await ev(`document.querySelector('.git-commit-hover-message>div').shadowRoot.querySelectorAll('li').length`),count);assert(await ev(`(()=>{const tip=document.querySelector('.git-commit-hover');return tip.clientHeight<innerHeight&&tip.scrollHeight>=tip.clientHeight})()`));samples.push({stress_items:count,elapsed_ms:Date.now()-start});
 }
 await move(false);await ev(`binding.dispose();failure=true;binding=qa.bind_git_commit_hover(document.querySelector('#list'),panel);void 0`);await move();assert(await ev(`!!document.querySelector('.git-commit-hover-message>div').shadowRoot.textContent.includes('摘要')`));
 await move(false);await ev(`binding.dispose();failure=false;late=true;binding=qa.bind_git_commit_hover(document.querySelector('#list'),panel);void 0`);await move();await ev(`panel.root='new-root';binding.hide();release();void 0`);await pause(80);assert.equal(await ev(`!!document.querySelector('.git-commit-hover')`),false);
 for(let i=0;i<20;i++)await ev(`binding.dispose();binding=qa.bind_git_commit_hover(document.querySelector('#list'),panel);binding.dispose();void 0`);
 assert.equal(await ev(`document.querySelectorAll('.workspace-hover-surface,.workspace-hover-pointer').length`),0);assert.equal(await ev(`document.querySelector('.git-scm-history-commit').hasAttribute('aria-describedby')`),false);
 fs.writeFileSync(path.join(evidence,'checks.json'),JSON.stringify({status:'PASS',samples,checks:['Markdown语义与主题隔离','固定上游12/19/20/4几何','8组明暗缩放宽窄','HTTP链接及复制','Esc取消','读取失败摘要保留','切库迟到拒绝','20次销毁清理','20/100/1000条列表压力']},null,2));console.log('PASS commit hover Markdown: '+evidence);win.destroy();app.quit();
}).catch(error=>{console.error(error.stack);if(win&&!win.isDestroyed())win.destroy();app.exit(1)});
