// 隐藏 Electron 使用 Chromium 指针和键盘；不启动或修改用户 Typora。
const {app,BrowserWindow}=require("electron");
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {build}=require("esbuild");const {editor_plugins}=require("./editor_bundle.cjs");
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),"typora_media_viewer_"));app.setPath("userData",path.join(fixture,"profile"));app.disableHardwareAcceleration();
let win;const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async code=>{try{return await win.webContents.executeJavaScript(code)}catch(error){throw new Error(code,{cause:error})}};
const checks=[];async function check(code,label){assert(await evaluate(`Boolean(${code})`),label);checks.push(label);}
async function click(selector){const point=await evaluate(`(()=>{const b=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.round(b.left+b.width/2),y:Math.round(b.top+b.height/2)}})()`);for(const type of ["mouseMove","mouseDown","mouseUp"]){win.webContents.sendInputEvent({type,...point,button:"left",clickCount:1});await delay(25);}await delay(60);}
async function double_click(selector){const point=await evaluate(`(()=>{const b=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.round(b.left+b.width/2),y:Math.round(b.top+b.height/2)}})()`);for(const count of [1,2])for(const type of ['mouseDown','mouseUp']){win.webContents.sendInputEvent({type,...point,button:'left',clickCount:count});await delay(25)}await delay(120);}
async function key(keyCode,modifiers=[]){win.webContents.sendInputEvent({type:"keyDown",keyCode,modifiers});win.webContents.sendInputEvent({type:"keyUp",keyCode,modifiers});await delay(45);}
async function until(code){for(let i=0;i<100;i++){if(await evaluate(code))return;await delay(30);}throw Error("timeout: "+code);}
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1000,height:760,webPreferences:{offscreen:true,contextIsolation:false,backgroundThrottling:false}});
 const html=path.join(fixture,"test.html");fs.writeFileSync(html,`<!doctype html><meta charset="utf-8"><style>html,body{margin:0;background:#fff;color:#24292f}content{display:block;position:absolute;inset:40px 40px 70px;overflow:auto}#write{padding:20px;line-height:1.6}#write img{max-width:100%;height:auto}footer{position:fixed;height:30px;bottom:0}body.dark{background:#171717;color:#ddd;--text-color:#ddd;--bg-color:#171717}</style><input id="focus" value="draft unchanged"><content><article id="write" contenteditable="true"><p id="text">Selection stays here</p><p><a href="#target"><img id="large" alt="中文大图"></a></p><p id="multiple"><img id="small" alt="小图"><img id="other" alt="另一个图"></p><div style="height:1400px">Below</div></article></content><footer class="ty-footer">Footer</footer><div id="shadow-host"></div>`,"utf8");
 await win.loadFile(html);
 const bundled=await build({plugins:editor_plugins(),stdin:{contents:'export {bind_reading_images} from "./src/reading_image_viewer";export {open_reading_media,close_reading_media} from "./src/reading_media_viewer";export {install_workspace_shortcuts} from "./src/workspace_shortcuts";',resolveDir:path.join(__dirname,"..")},bundle:true,write:false,format:"iife",globalName:"qa",loader:{".css":"text"}});await evaluate(bundled.outputFiles[0].text);
 await evaluate(`window.svg_url=(w,h)=>'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'"><rect width="100%" height="100%" fill="#ace"/><text x="10" y="40" fill="#123">Image detail '+w+' x '+h+'</text></svg>');large.src=svg_url(12000,8000);small.src=svg_url(96,64);other.src=svg_url(160,80);window.binding=qa.bind_reading_images(document.body,'content > #write img');window.links=0;document.querySelector('a').onclick=e=>{links++;e.preventDefault()};document.querySelector('#focus').focus();window.selection=document.createRange();selection.selectNodeContents(document.querySelector('#text'));getSelection().removeAllRanges();getSelection().addRange(selection);window.before_html=document.querySelector('#write').innerHTML;window.selected_text=getSelection().toString();window.window_zoom=0;window.shortcuts=qa.install_workspace_shortcuts({commands:{run(){window_zoom++}},workspace:{}},{ClientCommand:{zoomIn(){},zoomOut(){},resetZoom(){}}});void 0;`);
 await until(`document.querySelectorAll('.reading-image-open:not([hidden])').length>=1`);
 await evaluate(`window.image_clicks=0;large.addEventListener('click',()=>image_clicks++);document.querySelector('a').onclick=e=>e.preventDefault();void 0;`);
 await click('#large');await check(`!document.querySelector('.reading-media-viewer')&&image_clicks===1`,"Single image click stays with native selection");
 const image_point=await evaluate(`(()=>{const b=large.getBoundingClientRect();return{x:Math.round(b.left+b.width/2),y:Math.round(b.top+b.height/2)}})()`);
 for(const count of [1,2])for(const type of ['mouseDown','mouseUp']){win.webContents.sendInputEvent({type,...image_point,button:'left',clickCount:count});await delay(25)}await delay(100);
 await check(`document.querySelectorAll('.reading-media-viewer').length===1&&document.querySelector('.reading-media-content img').naturalWidth===12000`,"Double image click opens one viewer");await key('Escape');
 await evaluate(`document.querySelector('#focus').focus();getSelection().removeAllRanges();getSelection().addRange(selection)`);
 await check(`document.querySelectorAll('#write button').length===0&&document.querySelectorAll('.reading-image-open').length===3`,"Buttons outside original content; one per image");
 await click('.reading-image-open');await until(`!!document.querySelector('.reading-media-viewer')`);
 await check(`document.querySelector('.reading-media-content img').naturalWidth===12000&&parseFloat(document.querySelector('output').value)<20`,"First click opens huge image completely below 20 percent");
 await check(`document.querySelector('#write').innerHTML===before_html&&getSelection().toString()===selected_text&&links===0`,"Opening preserves original DOM, selection and linked-image navigation");
 await click('[data-action="reset"]');await check(`document.querySelector('output').value==='100%'`,"100 percent returns natural size");
 await click('[data-action="zoom-in"]');await check(`document.querySelector('output').value==='125%'`,"Zoom button uses existing 1.25 step");
 await key('-', ['control']);await check(`document.querySelector('output').value==='100%'&&window_zoom===0`,"Keyboard zoom stays local");
 const point=await evaluate(`(()=>{const b=document.querySelector('.reading-media-canvas').getBoundingClientRect();return{x:Math.round(b.left+b.width/2),y:Math.round(b.top+b.height/2)}})()`);
 for(const event of [{type:'mouseDown',...point},{type:'mouseMove',x:point.x+75,y:point.y+40},{type:'mouseUp',x:point.x+75,y:point.y+40}]){win.webContents.sendInputEvent({...event,button:'left',clickCount:1});await delay(40);}
 await check(`document.querySelector('.reading-media-viewer').style.getPropertyValue('--reading-media-pan-x')==='75px'`,"Pointer drag pans image");
 win.webContents.sendInputEvent({type:'mouseWheel',...point,deltaY:50,modifiers:['control'],canScroll:true});await delay(80);
 await check(`parseFloat(document.querySelector('output').value)>100&&window_zoom===0`,"Ctrl wheel zoom does not change window scale");
 await click('[data-action="fit"]');await check(`document.querySelector('.reading-media-viewer').style.getPropertyValue('--reading-media-pan-x')==='0px'`,"Fit resets panning");
 await evaluate(`document.querySelector('[data-action="close"]').focus()`);await key('Tab');await check(`document.activeElement.dataset.action==='zoom-out'`,"Tab stays within viewer");
 await key('Escape');await check(`!document.querySelector('.reading-media-viewer')&&document.activeElement.classList.contains('reading-image-open')&&document.querySelector('#write').innerHTML===before_html`,"Escape closes and restores entry focus without editing");
 await evaluate(`document.querySelector('content').scrollTop=900`);await delay(100);
 await check(`document.querySelector('.reading-image-open').hidden`,"Scrolled-out image has no floating button over another panel");
 await evaluate(`document.querySelector('content').scrollTop=0;document.body.classList.add('dark')`);await delay(150);await click('.reading-image-open');await until(`document.querySelector('.reading-media-viewer')?.dataset.theme==='dark'`);
 const evidence=path.resolve(__dirname,'../../.cache/reading_media_viewer_ui');fs.mkdirSync(evidence,{recursive:true});await click('[data-action="fit"]');fs.writeFileSync(path.join(evidence,'image_dark.png'),(await win.webContents.capturePage()).toPNG());
 win.setSize(440,540);await delay(150);
 await check(`(()=>{const c=document.querySelector('.reading-media-canvas').getBoundingClientRect();return [...document.querySelectorAll('.reading-media-header button')].every(n=>{const b=n.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth&&b.bottom<=c.top})})()`,"Narrow toolbar wraps without covering canvas or controls");
 fs.writeFileSync(path.join(evidence,'image_narrow.png'),(await win.webContents.capturePage()).toPNG());
 await key('Escape');win.setSize(1000,760);await evaluate(`document.body.classList.remove('dark');large.src=svg_url(700,300)`);await delay(120);await click('.reading-image-open');await check(`document.querySelector('.reading-media-content img').naturalWidth===700`,"Reloaded image uses latest resource");
 await evaluate(`large.src=svg_url(800,320)`);await delay(150);await check(`!document.querySelector('.reading-media-viewer')`,"Resource replacement closes old viewer");
 await evaluate(`large.src='file:///missing-image-for-viewer-test.png'`);await delay(150);await check(`document.querySelector('.reading-image-open').hidden`,"Broken image does not offer an invalid action");
 await evaluate(`large.remove();document.querySelector('#multiple').scrollIntoView({block:'center'})`);await delay(120);await check(`document.querySelectorAll('.reading-image-open').length===2`,"Removed images release their controls");
 await click('.reading-image-open');await check(`document.querySelector('output').value==='100%'`,"Small image starts at natural size");
 await evaluate(`document.querySelector('.reading-media-content img').src='file:///missing-viewer-image.png'`);await delay(120);await check(`document.querySelector('.reading-media-error')&&document.querySelector('[data-action="fit"]').disabled&&!document.querySelector('[data-action="close"]').disabled`,"Viewer load failure remains closeable");await key('Escape');
 await evaluate(`small.style.width='16px'`);await delay(120);await double_click('#small');await check(`document.querySelector('.reading-media-content img')?.naturalWidth===96&&document.querySelector('.reading-image-open').hidden`,"Tiny image double click works without an oversized inline button");await key('Escape');
 await evaluate(`binding.dispose();binding.dispose();window.shadow=document.querySelector('#shadow-host').attachShadow({mode:'open'});shadow.innerHTML='<article style="position:fixed;left:50px;top:70px;width:400px;height:250px;overflow:auto"><img alt="历史图像"></article>';window.article=shadow.querySelector('article');article.querySelector('img').src=svg_url(500,300);window.history_binding=qa.bind_reading_images(article);void 0;`);await delay(150);await click('.reading-image-open');await check(`document.querySelector('.reading-media-content img').naturalWidth===500`,"Historical Shadow DOM images use same viewer");
 await evaluate(`history_binding.dispose()`);await check(`!document.querySelector('.reading-media-viewer')&&!document.querySelector('.reading-image-actions')`,"Reader disposal removes open viewer and entry layer");
 await evaluate(`window.diagram=document.createElementNS('http://www.w3.org/2000/svg','svg');diagram.setAttribute('width','400');diagram.setAttribute('height','200');diagram.innerHTML='<rect width="400" height="200" fill="#acf"/>';qa.open_reading_media({content:diagram,width:400,height:200,label:'Mermaid 图表全屏查看'});void 0;`);await delay(80);await check(`document.querySelector('output').value==='100%'&&document.querySelector('.reading-media-content svg')`,"Mermaid retains SVG content and original initial scale");await click('[data-action="fit-width"]');await key('Escape');
 await evaluate(`window.binding2=qa.bind_reading_images(document.body,'content > #write img');void 0;`);await delay(120);await check(`document.querySelectorAll('.reading-image-actions').length===1&&document.querySelectorAll('.reading-image-open').length===2`,"Rebinding does not leave duplicate buttons");await evaluate(`binding2.dispose();shortcuts.dispose()`);
 console.log(JSON.stringify({status:'PASS',checks:checks.length,details:checks,evidence},null,2));
}).catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{win?.destroy();app.exit(process.exitCode||0)});
