// 真实 Electron 运行常驻工作台入口与全部编排模块；宿主核心仅提供可核查的注册表和原生文件容器。
const { app, BrowserWindow } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { build } = require('esbuild');
const { editor_plugins } = require('./editor_bundle.cjs');
const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_workspace_switch_'));
const repository=path.join(evidence,'repository');fs.mkdirSync(repository);
const source_path = path.join(repository, 'source.ts');fs.writeFileSync(source_path, 'const original = 1;\n');
const git=(...args)=>require('node:child_process').execFileSync('git',args,{cwd:repository,windowsHide:true,stdio:'pipe'});fs.writeFileSync(path.join(repository,'second.ts'),'const second = 2;\n');git('init','-b','main');git('add','source.ts','second.ts');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture');
app.setPath('userData', path.join(evidence, 'profile'));app.disableHardwareAcceleration();
let test_window;const checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async source=>{try{return await test_window.webContents.executeJavaScript(source)}catch(error){console.error("Failed renderer expression: "+source.slice(0,600));throw error}};
const capture=async name=>{await delay(100);fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());};
const wait=async source=>{for(let i=0;i<200;i++){if(await evaluate(source))return;await delay(30);}throw new Error('Timeout: '+source+'; '+await evaluate('JSON.stringify({errors:fixture_errors,state:document.documentElement.dataset.linuxNoteTyporaEnhancements})'));};
app.whenReady().then(async()=>{
 await (await import("./build_source_symbol_assets.mjs")).build_source_symbol_assets(path.join(evidence,"typora_code"));
 for(const directory of ['plugins','update'])fs.cpSync(path.join(__dirname,'../dist/assets',directory),path.join(evidence,'typora_code/assets',directory),{recursive:true});
 require("electron").ipcMain.handle("setting.put",(_event,key,value)=>{assert.equal(key,"framelessWindow");assert.equal(value,true);return true;});
 const {build_workspace_styles,static_workspace_css_plugin}=await import(require('node:url').pathToFileURL(path.join(__dirname,'build_workspace_styles.mjs')).href);await build_workspace_styles({outdir:evidence});
 test_window=new BrowserWindow({show:false,width:1100,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 const html=path.join(evidence,'fixture.html');fs.copyFileSync(path.join(__dirname,'../fixtures/workspace_host.html'),html);
 await test_window.loadFile(html);
 await evaluate(`window.fixture_root=${JSON.stringify(repository)};window.fixture_source=${JSON.stringify(source_path)};`);
 await evaluate(fs.readFileSync(path.join(__dirname,'../fixtures/workspace_host.js'),'utf8'));await evaluate(`window._options.userDataPath=${JSON.stringify(evidence)};void 0`);await evaluate('window.original_outline=document.querySelector("#outline-content");window.original_outline_parent=original_outline.parentNode');
 await evaluate('fixture_settings.set_and_save=fixture_settings.set;fixture_core.app.vault={on:fixture_core.app.workspace.on};File.editor.library.onRootChanged=function(root){if(window.fixture_root_refresh_error)throw Error("fixture native refresh failure");if(root)File.setMountFolder(root);};void 0');
 const baseline_plugins=process.env.TYPORA_WORKSPACE_SWITCH_BASELINE?[{name:'baseline-source',setup(builder){builder.onLoad({filter:/[\\/]src[\\/].*\.ts$/},args=>{const relative=path.relative(path.join(__dirname,'../..'),args.path).split(path.sep).join('/');try{return {contents:require('node:child_process').execFileSync('git',['show',process.env.TYPORA_WORKSPACE_SWITCH_BASELINE+':'+relative],{cwd:path.join(__dirname,'../..'),encoding:'utf8',stdio:['ignore','pipe','pipe']}),loader:'ts'};}catch{return undefined;}});}}]:[];
 const bundle=await build({preserveSymlinks:true,stdin:{contents:'export {start_typora_code,shutdown_typora_code} from "./src/workspace_startup";export {get_workspace_files} from "./src/workspace_files";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},plugins:[...baseline_plugins,static_workspace_css_plugin(),...editor_plugins()],bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text','.svg':'text','.png':'dataurl','.wasm':'binary'},define:{'process.env.NODE_ENV':'"production"'}});
 await evaluate(bundle.outputFiles[0].text);
 await evaluate('fixture_core.app.settings=fixture_settings;document.body.append(fixture_root_element);void 0');
 await evaluate('qa.start_typora_code()');await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"');
 // 空组补齐已核对的核心契约；仅夹具缺少自动空叶子，不代替被测切换服务。
 await evaluate(`fixture_factories.set('core.empty',leaf=>new fixture_core.WorkspaceView(leaf));window.switch_group=fixture_native_leaf.parent;window.remove_original=switch_group.removeTab;switch_group.removeTab=function(...args){const value=remove_original.apply(this,args);if(!fixture_leaves.length){const leaf=fixture_core.app.workspace.createLeaf({type:'core.empty',state:{path:'typ://core.empty/switch'}});this.appendChild(leaf);}return value;};window.notices=[];fixture_core.Notice=class{constructor(value){notices.push(value)}};void 0`);
 const second=path.join(evidence,'second');fs.mkdirSync(second);fs.writeFileSync(path.join(second,'target.ts'),'const target = 2;\n');
 const run_second=(...args)=>require('node:child_process').execFileSync('git',args,{cwd:second,windowsHide:true,stdio:'pipe'});
 run_second('init','-b','target-branch');run_second('add','.');run_second('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture');
 const plain=path.join(evidence,'plain');fs.mkdirSync(plain);fs.writeFileSync(path.join(plain,'plain.txt'),'plain\n');
 await evaluate(`window.second_root=${JSON.stringify(second)};window.plain_root=${JSON.stringify(plain)};window.run_folder=path=>fixture_commands.get('linux_note:open_folder_path').callback(path);void 0`);
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');await wait('document.querySelectorAll(".workspace-explorer-row").length>=2');
 await evaluate('qa.get_workspace_files().open_file(fixture_source)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('fixture_commands.get("linux_note:timeline").callback();document.querySelector(".workspace-timeline button[title=固定当前文件]")?.click();void 0');
 assert(await evaluate('document.querySelector(".workspace-timeline button[title=固定当前文件]").getAttribute("aria-pressed")==="true"'));
 await evaluate('fixture_commands.get("linux_note:search").callback();const query=document.querySelector(".workspace-search-query-box textarea");query.value="original";query.dispatchEvent(new Event("input",{bubbles:true}));void 0');await wait('document.querySelectorAll(".workspace-search-match").length>0');
 await evaluate('fixture_commands.get("linux_note:source_control").callback();void 0');await wait('document.querySelector(".git-status-branch")?.textContent.includes("main")');
 await evaluate('run_folder(second_root)');await wait('File.getMountFolder()===second_root');
 assert(await evaluate('!fixture_leaves.some(leaf=>leaf.state.path.includes("source.ts"))'),'old editor must be removed');
 await wait('document.querySelector(".git-status-branch")?.textContent.includes("target-branch")');
 assert(!await evaluate('document.querySelector(".linux-note-git-source-control")?.textContent.includes("source.ts")'));
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');await wait('Boolean(document.querySelector(\'.workspace-explorer-row[data-path$="target.ts"]\'))');
 assert(!await evaluate('document.querySelector(\'.workspace-explorer-row[data-path$="source.ts"]\')'));
 assert(await evaluate('!document.querySelector(".workspace-timeline-target")?.textContent'));
 await evaluate('fixture_commands.get("linux_note:search").callback();void 0');await delay(350);assert.equal(await evaluate('document.querySelectorAll(".workspace-search-match").length'),0);
 checks.push('workspace switch clears prior search matches and the pinned timeline target');
 checks.push('A→B closes old editors and refreshes Explorer, SCM and status branch to B');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(second_root,"target.ts"))');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('window.dirty_leaf=fixture_core.app.workspace.activeLeaf;dirty_leaf.view.editor.models[0].setValue("const target = 3;\\n");window.cancel_switch=run_folder(fixture_root);void 0');
 await wait('Boolean(document.querySelector("[data-workspace-switch]"))');
 assert(await evaluate('File.getMountFolder()===second_root&&fixture_leaves.includes(dirty_leaf)'));
 await evaluate('document.querySelector("[data-workspace-switch]").querySelector(".git-graph-dialog-footer").lastElementChild.click();void 0');await evaluate('cancel_switch');
 assert(await evaluate('File.getMountFolder()===second_root&&dirty_leaf.view.dirty()&&fixture_leaves.includes(dirty_leaf)'));
 assert.equal(fs.readFileSync(path.join(second,'target.ts'),'utf8'),'const target = 2;\n');
 await evaluate('window.real_save=dirty_leaf.view.text_document.save;dirty_leaf.view.text_document.save=async()=>{throw Error("fixture save failure")};window.failed_switch=run_folder(fixture_root);void 0');
 await wait('Boolean(document.querySelector("[data-workspace-switch]"))');
 await evaluate('[...document.querySelector("[data-workspace-switch]").querySelectorAll("button")].find(button=>button.textContent==="全部保存并切换").click();void 0');
 await wait('document.querySelector("[data-workspace-switch]")?.textContent.includes("保存未完成")');
 assert(await evaluate('File.getMountFolder()===second_root&&fixture_leaves.includes(dirty_leaf)&&dirty_leaf.view.dirty()'));
 await evaluate('document.querySelector("[data-workspace-switch] .git-graph-dialog-footer").lastElementChild.click();dirty_leaf.view.text_document.save=real_save;void 0');await evaluate('failed_switch');
 checks.push('save failure leaves root, dirty text and editor intact with a retry message');
 await evaluate('window.saved_switch=run_folder(fixture_root);void 0');await wait('Boolean(document.querySelector("[data-workspace-switch]"))');
 await evaluate('[...document.querySelector("[data-workspace-switch]").querySelectorAll("button")].find(button=>button.textContent==="全部保存并切换").click();void 0');await evaluate('saved_switch');
 await wait('File.getMountFolder()===fixture_root');assert.equal(fs.readFileSync(path.join(second,'target.ts'),'utf8'),'const target = 3;\n');
 checks.push('dirty source cancellation preserves root, editor and disk; save-and-switch writes only its original file');
 await evaluate('qa.get_workspace_files().open_file(fixture_source)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('window.same_leaf=fixture_core.app.workspace.activeLeaf;run_folder(fixture_root)');assert(await evaluate('fixture_leaves.includes(same_leaf)'));
 await evaluate('run_folder(require("path").join(fixture_root,"missing"))');assert(await evaluate('File.getMountFolder()===fixture_root&&fixture_leaves.includes(same_leaf)'));
 checks.push('same root refresh retains editors; invalid directory does not close or switch');
 await evaluate('File.editor.library.onRootChanged(second_root)');await wait('File.getMountFolder()===second_root');assert(!await evaluate('fixture_leaves.includes(same_leaf)'));
 await evaluate('run_folder(plain_root)');await wait('File.getMountFolder()===plain_root');await wait('document.querySelector(".linux-note-git-status")?.dataset.repository==="none"');
 await evaluate('window.fixture_root_refresh_error=true;run_folder(second_root)');await wait('File.getMountFolder()===second_root');await wait('document.querySelector(".git-status-branch")?.textContent.includes("target-branch")');
 assert(await evaluate('notices.some(value=>value.includes("fixture native refresh failure"))'));await evaluate('window.fixture_root_refresh_error=false;void 0');
 checks.push('native cache failure reports an error but all domain state follows the committed new root');
 await evaluate('fixture_commands.get("linux_note:close_folder").callback()');await wait('File.getMountFolder()===""');
 assert(!await evaluate('fixture_leaves.some(leaf=>!leaf.state.path.startsWith("typ://core.empty"))'));
 checks.push('native recent-root route shares switch; non-Git and close-folder do not expose prior branch or editor');
 await evaluate('run_folder(fixture_root)');
 await evaluate('fixture_commands.get("linux_note:git_graph").callback();void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.panel)');
 await wait('!fixture_core.app.workspace.activeLeaf.view.panel.pending');
 await evaluate('window.busy_panel=fixture_core.app.workspace.activeLeaf.view.panel;busy_panel.writing=true;void 0');await evaluate('run_folder(second_root)');
 assert(await evaluate('File.getMountFolder()===fixture_root&&!busy_panel.disposed&&notices.some(value=>value.includes("Git写操作"))'));
 await evaluate('busy_panel.writing=false;run_folder(second_root)');
 checks.push('in-flight Git write veto preserves the old workspace and controller');
 await evaluate('fixture_commands.get("linux_note:terminal").callback();void 0');await wait('Boolean(document.querySelector(".linux-note-terminal[data-session]"))');
 await evaluate('window.terminal_switch=run_folder(fixture_root);void 0');await wait('Boolean(document.querySelector("[data-workspace-switch]"))');
 assert(await evaluate('document.querySelector("[data-workspace-switch]").textContent.includes("终端")&&File.getMountFolder()===second_root'));
 await evaluate('[...document.querySelector("[data-workspace-switch]").querySelectorAll("button")].find(button=>button.textContent==="切换工作区").click();void 0');await evaluate('terminal_switch');
 await wait('!document.querySelector(".linux-note-terminal[data-session]")');
 checks.push('terminal sessions are disclosed before switch and removed only after acceptance');
 await evaluate('run_folder(fixture_root)');await wait('document.querySelector(".git-status-branch")?.textContent.includes("main")');await delay(250);
 // R040.2：原生配置开启后，各根会话独立恢复，保留顺序和活动项。
 await evaluate('File.option.restoreWhenLaunch=2;run_folder(second_root)');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(second_root,"target.ts"))');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('run_folder(fixture_root)');
 await evaluate('qa.get_workspace_files().open_file(fixture_source)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(fixture_root,"second.ts"))');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('qa.get_workspace_files().open_file(fixture_source)');
 await evaluate('run_folder(second_root)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 assert(await evaluate('qa.get_workspace_files().editor_state(fixture_core.app.workspace.activeLeaf).file_path.endsWith("target.ts")'));
 await evaluate('run_folder(fixture_root)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 assert(await evaluate('qa.get_workspace_files().editor_state(fixture_core.app.workspace.activeLeaf).file_path===fixture_source'));
 assert(await evaluate('fixture_leaves.filter(leaf=>qa.get_workspace_files().editor_state(leaf).kind==="source").map(leaf=>require("path").basename(qa.get_workspace_files().editor_state(leaf).file_path)).join(",")==="source.ts,second.ts"'));
 checks.push('per-root saved order and active file restore after A→B→A with native restoreWhenLaunch=2');
 await evaluate('run_folder(second_root)');fs.unlinkSync(path.join(repository,'second.ts'));
 await evaluate('run_folder(fixture_root)');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 assert(await evaluate('notices.some(value=>value.includes("second.ts"))'));
 assert(await evaluate('qa.get_workspace_files().editor_state(fixture_core.app.workspace.activeLeaf).file_path===fixture_source'));
 checks.push('missing file reports a partial restore and retains the available active file');
 await evaluate('run_folder(plain_root)');await evaluate('qa.get_workspace_files().open_file(require("path").join(plain_root,"plain.txt"))');await wait('Boolean(fixture_core.app.workspace.activeLeaf?.view.editor?.models?.[0])');
 await evaluate('qa.get_workspace_files().close_leaf(fixture_core.app.workspace.activeLeaf)');
 await evaluate('run_folder(second_root)');await evaluate('run_folder(plain_root)');
 assert(await evaluate('fixture_leaves.every(leaf=>qa.get_workspace_files().editor_state(leaf).kind==="other")'));
 checks.push('closing the last file persists an empty session, with no fallback to global recent files');
 await evaluate('File.option.restoreWhenLaunch=1;run_folder(fixture_root)');
 assert(await evaluate('fixture_leaves.every(leaf=>qa.get_workspace_files().editor_state(leaf).kind==="other")'));
 checks.push('folder-only native preference disables file restoration');
 await wait('document.querySelector(".git-status-branch")?.textContent.includes("main")');await delay(350);
 const before_listeners=await evaluate('fixture_listener_snapshot()');fs.writeFileSync(path.join(evidence,'listeners_before.json'),JSON.stringify(before_listeners,null,2));
 for(let i=0;i<20;i++){await evaluate(i%2?'run_folder(fixture_root)':'run_folder(second_root)');await delay(20);}
 await wait('document.querySelector(".git-status-branch")?.textContent.includes("main")');await delay(250);const after_listeners=await evaluate('fixture_listener_snapshot()');fs.writeFileSync(path.join(evidence,'listeners_after.json'),JSON.stringify(after_listeners,null,2));console.log('Evidence: '+evidence);const identities=items=>items.map(item=>[item.target,item.type,item.callback,item.stack.split("\n")[2]].join("|")).sort();assert.deepEqual(identities(after_listeners),identities(before_listeners),'workspace switches must preserve the settled global listener owners');
 assert(await evaluate('fixture_leaves.every(leaf=>leaf.state.path.startsWith("typ://core.empty"))'));
 checks.push('20 complete workspace transitions leave no old tabs or additional global listeners');
 assert.deepEqual(await evaluate('fixture_errors'),[]);
 fs.writeFileSync(path.join(evidence,'checks.json'),JSON.stringify({status:'PASS',requirement:'R040.1',checks},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence}));
 test_window.destroy();app.quit();
}).catch(error=>{console.error(error);fs.writeFileSync(path.join(evidence,'failure.txt'),String(error.stack));test_window?.destroy();app.exit(1);});
