const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {build}=require('esbuild');
app.disableHardwareAcceleration();
let test_window;
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_pr_ui_'));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
app.whenReady().then(async()=>{
  const bundle=await build({stdin:{contents:'export * from "./src/git_graph_pull_request_dialog";export * from "./src/git_graph_settings";export * from "./src/git_graph_tab_icon";import css from "./src/git_graph.css";const style=document.createElement("style");style.textContent=css;document.head.append(style);',resolveDir:path.resolve(__dirname,'..')},bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text'}});
  const file=path.join(root,'test.html');fs.writeFileSync(file,'<!doctype html><meta charset="utf-8"><body></body>','utf8');
  test_window=new BrowserWindow({show:false,width:1000,height:760,webPreferences:{offscreen:true,backgroundThrottling:false}});await test_window.loadFile(file);await evaluate(bundle.outputFiles[0].text);
  await evaluate(`window.opened=[];window.saved=[];window.panel={settings:structuredClone(qa.graph_defaults),state:{remotes:[{name:'origin',fetch:'git@github.com:fork/code.git'},{name:'upstream',fetch:'https://github.com/owner/code.git'}]},host:{open_url:async url=>{opened.push(url)}},persist_settings(){saved.push(structuredClone(this.settings));}};qa.show_pull_request_dialog(panel,'feature/a&b');void 0`);
  assert.equal(await evaluate('document.querySelector("[aria-label=源远端]").value'),'origin');
  assert.equal(await evaluate('document.querySelector("[aria-label=目标远端]").value'),'upstream');
  const click_text=label=>evaluate(`(()=>{const item=[...document.querySelectorAll('.git-graph-dialog-footer button')].find(node=>node.textContent===${JSON.stringify(label)});if(!item)throw new Error('missing button');item.click();})()`);
  await click_text('下一步');assert.equal(await evaluate('document.querySelector("[aria-label=源仓库所有者]").value'),'fork');assert.equal(await evaluate('document.querySelector("[aria-label=目标仓库所有者]").value'),'owner');
  await click_text('保存配置');await click_text('打开表单');
  assert.equal(new URL((await evaluate('opened'))[0]).pathname,'/owner/code/compare/main...fork:feature%2Fa%26b');
  assert.equal(await evaluate('saved.length'),1);await click_text('关闭');
  await evaluate('qa.show_pull_request_dialog(panel,"topic");void 0');assert.equal(await evaluate('document.querySelectorAll(".git-pr-field").length'),2,'saved integration bypasses configuration steps');await click_text('关闭');
  await evaluate(`panel.settings.pr_providers=[{name:'Internal Review',template_url:'$1/new?owner=$2&source=$4&target=$8&project=$7'}];qa.show_pull_request_dialog(panel,'中文/topic',true);void 0`);
  await evaluate('document.querySelector("[aria-label=服务提供方]").value="Internal Review";document.querySelector("[aria-label=目标远端]").value="";void 0');await click_text('下一步');
  await evaluate('document.querySelector("[aria-label=服务根地址]").value="https://review.example";document.querySelector("[aria-label=目标仓库所有者]").value="team";document.querySelector("[aria-label=目标仓库名称]").value="project";void 0');await click_text('保存配置');await click_text('打开表单');
  const custom=new URL((await evaluate('opened')).at(-1));assert.equal(custom.hostname,'review.example');assert.equal(custom.searchParams.get('source'),'中文/topic');assert.equal(await evaluate('panel.settings.pr_config.destination_remote'),'');
  await evaluate('document.body.append(qa.git_graph_tab_icon("colour"),qa.git_graph_tab_icon("grey"));void 0');
  assert.equal(await evaluate('new Set([...document.querySelector("[data-graph-tab-theme=colour]").querySelectorAll("circle")].map(node=>node.getAttribute("fill"))).size'),2);
  assert.equal(await evaluate('[...document.querySelector("[data-graph-tab-theme=grey]").querySelectorAll("circle")].every(node=>node.getAttribute("fill")==="currentColor")'),true);
  fs.writeFileSync(path.join(root,'pull_request_configuration.png'),(await test_window.webContents.capturePage()).toPNG());
  console.log(JSON.stringify({status:'PASS',checks:['origin/upstream inferred for fork integration','two configuration steps persist and reopen directly','custom named providers and non-remote destination','branch URL characters remain one value','colour and grey tab icons'],evidence:root}));test_window.destroy();app.exit(0);
}).catch(error=>{console.error(error);test_window?.destroy();app.exit(1);});
