const {app,BrowserWindow}=require('electron');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_pointer_drag_'));app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1100,height:780,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true}});win.webContents.on('console-message',(_e,_l,m)=>console.log(m));const html=path.join(root,'host.html');fs.writeFileSync(html,'<!doctype html><body><div id="typora-sidebar"><div id="sidebar-content"><div id="outline-content"></div><div id="file-library"></div><div id="file-library-search"><div><input id="file-library-search-input"></div></div><div id="file-library-search-result"></div></div></div><div id="typora-sidebar-resizer"></div><content><div id="write"></div></content><footer id="footer"><span id="footer-word-count"></span></footer>','utf8');await win.loadFile(html);
await win.webContents.executeJavaScript(`window.$=window.jQuery=require(${JSON.stringify(require.resolve('jquery'))});window.fixture_errors=[];window.addEventListener('error',e=>(fixture_errors.push(String(e.error?.stack||e.error)),console.log(e.error?.stack)));window.addEventListener('unhandledrejection',e=>fixture_errors.push(String(e.reason)));window.reqnode=name=>require(name);window._options={userDataPath:${JSON.stringify(root)},mountFolder:${JSON.stringify(path.join(root,'one'))},appLocale:'en',locale:'en'};window.fixture_noop=()=>{};window.fixture_object=()=>new Proxy(function(){},{get(target,key){if(key in target)return target[key];if(key==='then'||typeof key==='symbol')return undefined;return target[key]=fixture_object();}});window.editor=fixture_object();editor.writingArea=document.querySelector('#write');editor.library=fixture_object();editor.selection=fixture_object();editor.sourceView=fixture_object();editor.nodeMap={allNodes:{_set:[],first:()=>null}};editor.getMarkdown=()=>'';window.File=fixture_object();File.isNode=true;File.isMac=false;File.isWin=true;File.filePath='';File.bundle={filePath:''};File.option={};File.getMountFolder=()=>_options.mountFolder;File.setMountFolder=path=>_options.mountFolder=path;File.editor=editor;window.JSBridge=fixture_object();window.bridge=fixture_object();window.ClientCommand=fixture_object();window.CodeMirror=fixture_object();window.gettext=value=>value;void 0`);
// Only host APIs are substituted; runtime production bundle and settings/fs implementation are real.
fs.mkdirSync(path.join(root,'typora_code','locales'),{recursive:true});for(const name of fs.readdirSync(path.join(__dirname,'../dist/locales')))fs.copyFileSync(path.join(__dirname,'../dist/locales',name),path.join(root,'typora_code','locales',name));
await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.js'),'utf8'));
await win.webContents.executeJavaScript(`window.runtime=window[Symbol.for('typora-code:workspace')];runtime.ready.then(()=>'ready').catch(error=>{console.log(fixture_errors.join('\\n'));throw error})`);

const evaluate=source=>win.webContents.executeJavaScript(source);const pause=()=>new Promise(resolve=>setTimeout(resolve,80));const checks=[];
const check=async(source,label)=>{if(!await evaluate(source)){console.error(await evaluate('JSON.stringify({active:runtime.app.workspace.activeLeaf?.state, clicks:window.clicks, order:window.group?.children.map(n=>n.state?.path), errors:fixture_errors, events:window.pointer_events})'));throw new Error(label);}checks.push(label)};
await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.css'),'utf8'));
await win.webContents.insertCSS('html,body{margin:0;width:100%;height:100%;font-size:16px}body{overflow:hidden}#typora-sidebar-resizer,.typ-ribbon{display:none!important}#typora-sidebar{position:fixed;left:0;top:40px;width:48px;bottom:0;z-index:200000;background:#eee;overflow:hidden}content{display:none!important}.fixture-tabs-host{position:fixed!important;inset:40px 60px 80px!important;width:auto!important;height:auto!important;margin:0!important;display:flex!important;z-index:100000!important;background:white}.fixture-tabs-host>.typ-workspace-tabs{flex:1;min-width:0;max-width:100%}');
// 只替代未调用的默认 service 参数；模型、标签增删及视图生命周期使用真实 core runtime。
const bundle=await require('esbuild').build({stdin:{contents:'export {draggableTabs} from "./vendor/workspace_core/src/ui/layout/tabs/draggable";export {draggable} from "./vendor/workspace_core/src/ui/components/draggable";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.scss':'empty'},format:'iife',globalName:'drag_qa',plugins:[{name:'explicit-runtime',setup(build){build.onResolve({filter:/^src\/common\/service$/},()=>({path:'service',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export function useService(){throw new Error("Explicit actual workspace required");}',loader:'ts'}));}}]});await evaluate(bundle.outputFiles[0].text);
await win.webContents.insertCSS('.typ-workspace-tabs{width:50%!important;min-width:0!important}.typ-workspace-tab-header{height:35px;flex:none;overflow-x:auto!important;overflow-y:hidden}.typ-tabs{width:max-content;display:flex}.typ-tab{height:35px!important;min-width:115px!important;max-width:115px!important;font:13px system-ui!important;box-sizing:border-box}.typ-workspace-tab-content{background:#fafafa;min-height:100px}.fixture-tabs-host{z-index:100000!important}.typ-close{margin-left:auto}');
await evaluate(`window.group=runtime.app.workspace.activeLeaf.parent;window.root_el=runtime.app.workspace.rootSplit.containerEl;root_el.classList.add('fixture-tabs-host');runtime.app.viewManager.registerView('fixture.drag',leaf=>new class extends runtime.WorkspaceView{constructor(leaf){super(leaf);this.containerEl=document.createElement('div');this.draft='UNSAVED '+leaf.state.path;}onOpen(){}}(leaf));window.add_file=(target,name)=>{const leaf=runtime.app.workspace.createLeaf({type:'fixture.drag',state:{path:name}});target.appendChild(leaf);return leaf;};window.first=add_file(group,'one.md');window.second=add_file(group,'two.c');window.third=add_file(group,'three.md');group.removeTab('');window.other=new group.constructor();runtime.app.workspace.rootSplit.appendChild(other);window.other_leaf=add_file(other,'other.md');runtime.app.workspace.activeLeaf=third;window.drag_binding=drag_qa.draggableTabs(runtime.app.workspace.rootSplit,runtime.app.workspace);window.detached=[];document.addEventListener('typora-code:tab-detach',e=>{e.preventDefault();detached.push(e.detail)});window.clicks=0;window.native_drags=0;window.pointer_events=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>pointer_events.push([type,e.target.outerHTML.slice(0,300),e.clientX,e.clientY,e.defaultPrevented]),true);root_el.addEventListener('click',()=>clicks++);document.addEventListener('dragstart',()=>native_drags++);window.order=target=>target.children.map(leaf=>leaf.state.path);window.clean=()=>!document.querySelector('[data-workspace-drag-preview]')&&!document.querySelector('[data-workspace-drag-source]')&&![...document.querySelectorAll('[data-workspace-drop-marker]')].some(node=>getComputedStyle(node).display!=='none')&&!root_el.querySelector('.mod-drag-over');void 0`);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const point=source=>evaluate(`(()=>{const node=${source},box=node.getBoundingClientRect();return{x:Math.round(box.left+(node.matches(".typ-tab")?20:box.width/2)),y:Math.round(box.top+box.height/2)}})()`);
const tab=(group,name)=>`${group}.tabHeader.getTabById(${JSON.stringify(name)})`;
const input=async(type,p,extra={})=>{win.webContents.sendInputEvent({type,...p,button:'left',clickCount:1,...extra});await delay(35)};
const down=p=>input('mouseDown',p),move=p=>input('mouseMove',p,{modifiers:['leftButtonDown']}),up=p=>input('mouseUp',p);
const drag=async(from,to)=>{await down(from);await move(to);await up(to);await delay(50)};
const key=async key=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key});win.webContents.sendInputEvent({type:'keyUp',keyCode:key});await delay(40)};
const before=await evaluate('clicks'),one=await point(tab('group','one.md'));
await down(one);await move({x:one.x+3,y:one.y+2});await check('clean()','sub-threshold movement leaves the UI and order untouched');await up({x:one.x+3,y:one.y+2});await check(`runtime.app.workspace.activeLeaf===first&&clicks===${before+1}`,'left click below threshold still activates the original tab');
const three=await point(tab('group','three.md')),end={x:three.x+50,y:three.y};await down(one);await move(end);
await check('order(group).join() === "one.md,two.c,three.md"&&first.view.draft==="UNSAVED one.md"','holding the drag does not change document ownership, draft, or tab order');
await check(`(()=>{const p=document.querySelector('[data-workspace-drag-preview]'),s=document.querySelector('[data-workspace-drag-source]'),b=p?.getBoundingClientRect();return p?.textContent.includes('one')&&p.getAttribute('aria-hidden')==='true'&&!p.hasAttribute('data-id')&&!p.querySelector('[data-id]')&&Math.abs(b.left+20-${end.x})<2&&s===group.tabHeader.getTabById('one.md')&&getComputedStyle(s).opacity==='0.45'&&!!document.querySelector('[data-workspace-drop-marker]')})()`,'actual tab preview follows the held pointer and exposes a separate insertion line');
fs.writeFileSync(path.join(root,'held_tab.png'),(await win.webContents.capturePage()).toPNG());await up(end);
await check('order(group).join()==="two.c,three.md,one.md"&&[...group.tabHeader.container.children].map(n=>n.dataset.id).join()==="two.c,three.md,one.md"&&group.tabContentEl.children[2]===first.containerEl&&first.parent===group&&clean()','release reorders the real model, header, and leaf nodes together');
await check(`clicks===${before+1}&&native_drags===0`,'drag completion suppresses the click and never starts a second HTML drag');
// Duplicate file paths in different groups must not make the global first matching leaf move.
await evaluate(`window.duplicate=add_file(other,'two.c');runtime.app.workspace.activeLeaf=third;void 0`);await pause();
const second_start=await point(tab('group','two.c')),duplicate_target=await point(tab('other','two.c'));
await drag(second_start,duplicate_target);await check('second.parent===group&&duplicate.parent===other&&detached.length===0&&clean()','dropping on a group with the same path preserves both exact leaves and does not detach');
const target=await point(tab('other','other.md'));await drag(await point(tab('group','one.md')),{x:target.x-15,y:target.y});
await check('first.parent===other&&other.children[0]===first&&second.parent===group&&runtime.app.workspace.activeLeaf===first&&first.view.draft==="UNSAVED one.md"&&clean()','cross-group drop moves the original leaf and draft to the exact insertion point');
// Cancellation must remain safe even if Esc precedes release by more than the old 400 ms workaround.
const cancel_start=await point(tab('group','three.md')),cancel_target=await point(tab('group','two.c'));const clicks_before_cancel=await evaluate('clicks');
await down(cancel_start);await move({x:cancel_target.x-15,y:cancel_target.y});await key('Escape');await delay(550);await up({x:cancel_target.x-15,y:cancel_target.y});
await check(`order(group).join()==="two.c,three.md"&&clicks===${clicks_before_cancel}&&clean()&&detached.length===0`,'Esc cancels feedback and a later mouse release cannot activate or move anything');
await down(await point(tab('group','three.md')));await move({x:20,y:400});await evaluate('window.dispatchEvent(new Event("blur"));void 0');await up({x:20,y:400});await check('third.parent===group&&detached.length===0&&clean()','window blur cancels the drag without creating a new window');
await down(await point(tab('group','three.md')));await move({x:20,y:400});await up({x:20,y:400});await check('third.parent===group&&detached.length===0&&clean()','an activity or sidebar surface is never treated as a new-window drop');
const blank=await evaluate('({x:Math.round(innerWidth/2),y:innerHeight-20})');await down(await point(tab('group','three.md')));await move(blank);
await check('document.querySelector("[data-workspace-drag-preview]")?.dataset.workspaceDropEffect==="detach"&&document.querySelector("[data-workspace-drag-preview]").textContent.includes("移到新窗口")','leaving the editor group by 30px shows explicit new-window feedback');await up(blank);
await check('detached.length===1&&detached[0].leaf===third&&detached[0].source_group===group&&Number.isFinite(detached[0].screen_x)&&third.parent===group&&third.view.draft==="UNSAVED three.md"&&clean()','detach emits the exact leaf and screen point while retaining the original document pending host ACK');
// Typora's rendered content is outside the workspace group's DOM; its physical group remains a legal drop target.
await evaluate(`window.body_leaf=add_file(group,'body.md');runtime.app.workspace.activeLeaf=body_leaf;void 0`);await pause();
const body_box=await evaluate('(()=>{const r=other.tabContentEl.getBoundingClientRect();return{left:r.left,top:r.top,width:r.width,height:r.height}})()');
const native_content_css=await win.webContents.insertCSS(`content{display:block!important;position:fixed!important;left:${body_box.left}px!important;top:${body_box.top}px!important;width:${body_box.width}px!important;height:${body_box.height}px!important;z-index:200000!important;background:white}`);
const body_target={x:Math.round(body_box.left+body_box.width/2),y:Math.round(body_box.top+body_box.height/2)};
await down(await point(tab('group','body.md')));await move(body_target);
await check('document.elementFromPoint('+body_target.x+','+body_target.y+').closest("content")&&document.querySelector("[data-workspace-drop-marker]").getBoundingClientRect().height>100','rendered Markdown content outside the group DOM receives visible group-area drop feedback');await up(body_target);
await check('body_leaf.parent===other&&other.children.at(-1)===body_leaf&&detached.length===1&&clean()','native Markdown content resolves by its real group bounds and keeps the same leaf');await win.webContents.removeInsertedCSS(native_content_css);

// Continuous overflow movement reaches tabs beyond the current viewport while held.
await evaluate(`for(let i=0;i<15;i++)add_file(group,'overflow_'+i+'.md');group.tabHeader.containerEl.scrollLeft=0;void 0`);await pause();
const overflow_start=await point(tab('group','two.c')),edge=await evaluate('(()=>{const r=group.tabHeader.containerEl.getBoundingClientRect();return{x:Math.round(r.right-5),y:Math.round(r.top+15)}})()');
await down(overflow_start);await move(edge);await delay(260);await check('group.tabHeader.containerEl.scrollLeft>0','holding near the header edge scrolls overflowing tabs without a wheel');await key('Escape');await up(edge);
// A removed source cancels immediately, without waiting for another pointer event.
await evaluate('group.tabHeader.containerEl.scrollLeft=0;void 0');await down(await point(tab('group','two.c')));await move({x:overflow_start.x+15,y:overflow_start.y+8});await evaluate('window.removed_tab=group.tabHeader.getTabById("two.c");removed_tab.remove();void 0');await pause();await check('clean()&&detached.length===1','removing a dragged source cleans capture and all feedback promptly');await up(edge);await evaluate('group.tabHeader.container.prepend(removed_tab);void 0');
// Actual pointer cancellation and generic object sort use the same cancellation semantics.
await evaluate('group.tabHeader.containerEl.scrollLeft=0;window.last_pointer=0;document.addEventListener("pointerdown",e=>last_pointer=e.pointerId,{capture:true});void 0');await down(await point(tab('group','two.c')));await move({x:overflow_start.x+15,y:overflow_start.y+8});await evaluate('document.dispatchEvent(new PointerEvent("pointercancel",{pointerId:last_pointer,bubbles:true}));void 0');await up(edge);await check('clean()&&second.parent===group&&detached.length===1','pointercancel cannot reorder, detach, or leak a ghost');
await evaluate(`window.generic=document.createElement('div');generic.style.cssText='position:fixed;left:0;top:0;z-index:300000;display:flex';generic.innerHTML='<div draggable="true" style="width:50px;height:30px">A</div><div draggable="true" style="width:50px;height:30px">B</div>';document.body.append(generic);window.generic_changes=0;window.generic_binding=drag_qa.draggable(generic,'x',()=>generic_changes++);void 0`);
await drag({x:25,y:15},{x:95,y:15});await check('generic.textContent==="BA"&&generic_changes===1&&clean()','the core generic tool sorter also uses held-pointer preview and release-only commit');
await evaluate('generic_binding();generic.remove();drag_binding();void 0');await check('clean()','disposal cancels the shared session and removes feedback');assert.deepEqual(await evaluate('fixture_errors'),[]);
fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence:root}));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(root);app.exit(1)});
