const {app,BrowserWindow}=require('electron');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_core_smoke_'));app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true}});win.webContents.on('console-message',(_e,_l,m)=>console.log(m));const html=path.join(root,'host.html');fs.writeFileSync(html,'<!doctype html><body><div id="typora-sidebar"><div id="sidebar-content"><div id="outline-content"></div><div id="file-library"></div><div id="file-library-search"><div><input id="file-library-search-input"></div></div><div id="file-library-search-result"></div></div></div><div id="typora-sidebar-resizer"></div><content><div id="write"></div></content><footer id="footer"><span id="footer-word-count"></span></footer>','utf8');await win.loadFile(html);
await win.webContents.executeJavaScript(`window.$=window.jQuery=require(${JSON.stringify(require.resolve('jquery'))});window.fixture_errors=[];window.addEventListener('error',e=>(fixture_errors.push(String(e.error?.stack||e.error)),console.log(e.error?.stack)));window.addEventListener('unhandledrejection',e=>fixture_errors.push(String(e.reason)));window.reqnode=name=>require(name);window._options={userDataPath:${JSON.stringify(root)},mountFolder:${JSON.stringify(path.join(root,'one'))},appLocale:'en',locale:'en'};window.fixture_noop=()=>{};window.fixture_object=()=>new Proxy(function(){},{get(target,key){if(key in target)return target[key];if(key==='then'||typeof key==='symbol')return undefined;return target[key]=fixture_object();}});window.editor=fixture_object();editor.writingArea=document.querySelector('#write');editor.library=fixture_object();editor.selection=fixture_object();editor.sourceView=fixture_object();editor.nodeMap={allNodes:{_set:[]}};editor.getMarkdown=()=>'';window.File=fixture_object();File.isNode=true;File.isMac=false;File.isWin=true;File.filePath='';File.bundle={filePath:''};File.option={};File.getMountFolder=()=>_options.mountFolder;File.setMountFolder=path=>_options.mountFolder=path;File.editor=editor;window.JSBridge=fixture_object();window.bridge=fixture_object();window.ClientCommand=fixture_object();window.CodeMirror=fixture_object();window.gettext=value=>value;void 0`);
// Only host APIs are substituted; runtime production bundle and settings/fs implementation are real.
fs.mkdirSync(path.join(root,'typora_code','locales'),{recursive:true});for(const name of fs.readdirSync(path.join(__dirname,'../dist/locales')))fs.copyFileSync(path.join(__dirname,'../dist/locales',name),path.join(root,'typora_code','locales',name));
await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.js'),'utf8'));
await win.webContents.executeJavaScript(`window.runtime=window[Symbol.for('typora-code:workspace')];runtime.ready.then(()=>'ready').catch(error=>{console.log(fixture_errors.join('\\n'));throw error})`);
// 真实核心创建/移除占位叶子；仅加载文件适配层 CSS，不重建标签实现。
await win.webContents.executeJavaScript(`const style=document.createElement('style');style.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/workspace_files.css'),'utf8'))};document.head.append(style);window.empty_group=runtime.app.workspace.activeLeaf.parent;window.empty_canvas=runtime.app.workspace.activeLeaf.containerEl;void 0`);
assert(await win.webContents.executeJavaScript(`empty_group.activeLeaf.state.path===''&&getComputedStyle(empty_group.tabHeader.getTabById('')).display!=='none'`));
await win.webContents.executeJavaScript(`empty_group.removeTab('');window.empty_canvas=empty_group.activeLeaf.containerEl;void 0`);
assert(await win.webContents.executeJavaScript(`empty_group.activeLeaf.state.path.startsWith('typ://core.empty/')&&getComputedStyle(empty_group.tabHeader.containerEl).display==='none'&&empty_canvas.isConnected`));
await win.webContents.executeJavaScript(`window.test_leaf=runtime.app.workspace.createLeaf({type:'core.markdown',state:{path:'fixture.md'}});empty_group.appendChild(test_leaf);runtime.app.workspace.activeLeaf=test_leaf;void 0`);
assert(await win.webContents.executeJavaScript(`empty_group.children.length===1&&empty_group.children[0]===test_leaf&&getComputedStyle(empty_group.tabHeader.containerEl).display!=='none'&&!empty_canvas.isConnected`));
await win.webContents.executeJavaScript(`empty_group.removeTab('fixture.md');void 0`);
assert(await win.webContents.executeJavaScript(`empty_group.containerEl.isConnected&&empty_group.children.length===1&&empty_group.activeLeaf.state.path.startsWith('typ://core.empty/')&&getComputedStyle(empty_group.tabHeader.containerEl).display==='none'`));
await win.webContents.executeJavaScript(`window.untitled_leaf=runtime.app.workspace.createLeaf({type:'core.markdown',state:{path:''}});empty_group.appendChild(untitled_leaf);runtime.app.workspace.activeLeaf=untitled_leaf;window.fixture_draft='unsaved draft';editor.getMarkdown=()=>fixture_draft;void 0`);
assert(await win.webContents.executeJavaScript(`getComputedStyle(empty_group.tabHeader.getTabById('')).display!=='none'&&getComputedStyle(empty_group.tabHeader.containerEl).display!=='none'&&editor.getMarkdown()==='unsaved draft'`));
await win.webContents.executeJavaScript(`window.split_group=new empty_group.constructor();runtime.app.workspace.rootSplit.appendChild(split_group);split_group.appendChild(runtime.app.workspace.createLeaf({type:'core.empty',state:{path:'typ://core.empty/test/New tab'}}));void 0`);
assert(await win.webContents.executeJavaScript(`getComputedStyle(split_group.tabHeader.containerEl).display==='none'&&getComputedStyle(empty_group.tabHeader.containerEl).display!=='none'&&editor.getMarkdown()==='unsaved draft'&&empty_group.children[0]===untitled_leaf`));
await win.webContents.executeJavaScript(`runtime.app.workspace.rootSplit.removeChild(split_group);void 0`);
assert(await win.webContents.executeJavaScript(`runtime.app.workspace.rootSplit.containerEl.isConnected`));await win.webContents.executeJavaScript(`window.first_app=runtime.app;window.first_workspace=runtime.app.workspace;window.first_root=first_workspace.rootSplit.containerEl;File.setMountFolder(${JSON.stringify(path.join(root,'two'))});runtime.app.settings.set('useAutoSwap',false);void 0`);await new Promise(r=>setTimeout(r,1200));assert(await win.webContents.executeJavaScript(`runtime.app===first_app&&runtime.app.workspace===first_workspace&&first_root.isConnected&&!runtime.app.plugins&&!runtime.app.internalPlugins&&!document.querySelector('[data-id="core.settings"]')`));assert.deepEqual(await win.webContents.executeJavaScript('fixture_errors'),[]);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'typora_code/settings/workspace.json'),'utf8')).settings.useAutoSwap,false);assert(!fs.existsSync(path.join(root,'one/.typora'))&&!fs.existsSync(path.join(root,'two/.typora')));await win.webContents.executeJavaScript('window.extra_loads=0;runtime.app.on(\'load\',()=>extra_loads++);runtime.app.start();runtime.app.start();void 0');assert.equal(await win.webContents.executeJavaScript('extra_loads'),0);console.log('PASS '+root);win.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(root);app.exit(1)});
