import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import child_process from 'node:child_process';
import { build } from 'esbuild';

const compiled = await build({ stdin: { contents: ['git_graph_repository', 'git_graph_actions', 'git_graph_settings', 'git_graph_runtime', 'git_ignore'].map(name => `export * from './src/${name}.ts';`).join('\n'), resolveDir: process.cwd() }, bundle: true, platform: 'node', format: 'esm', write: false });
const api = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_git_full_'));
const reader = api.create_git_runner({ child_process, process }); const writer = api.create_git_runner({ child_process, process }, { writable: true });
const checks = [];
const expect = (condition, message) => { assert(condition, message); checks.push(message); };
const git = (root, args) => child_process.execFileSync('git', ['-c', 'core.autocrlf=false', '-c', 'core.hooksPath=.git/unused_hooks', ...args], { cwd: root, encoding: 'utf8', windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const write = (root, file, value) => { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), value); };
const head = root => git(root, ['rev-parse', 'HEAD']);
const commit = (root, message) => { git(root, ['add', '--all']); git(root, ['commit', '-m', message]); return head(root); };
const create_repo = name => {
  const root = path.join(temp, name); fs.mkdirSync(root); git(root, ['init', '-b', 'main']);
  git(root, ['config', 'user.name', 'Graph Test']); git(root, ['config', 'user.email', 'graph@example.invalid']);
  git(root, ['config', 'core.autocrlf', 'false']);
  git(root, ['config', 'commit.gpgsign', 'false']); git(root, ['config', 'tag.gpgsign', 'false']); git(root, ['config', 'core.hooksPath', '.git/unused_hooks']);
  return root;
};
const defaults = id => Object.fromEntries(api.graph_actions.find(action => action.id === id).fields.map(field => [field.key, field.initial ?? (field.type === 'boolean' ? false : '')]));
const action = async (root, id, values = {}, target = '', hash = '', operation = '') => {
  const plan = await api.plan_git_action(reader.run, id, { root, target, hash, operation }, { ...defaults(id), ...values });
  await api.execute_git_action(writer.run, plan, () => true); return plan;
};
try {
  const root = create_repo('repo with spaces'); write(root, '中文 #%.md', 'one\n'); const first = commit(root, '开始 :tada:');
  await action(root, 'branch_create', { branch: 'feature', checkout: true }, '', first);
  write(root, 'feature.md', 'feature\n'); const feature = commit(root, '功能');
  await action(root, 'branch_checkout', {}, 'main'); write(root, 'main.md', 'main\n'); const main = commit(root, '主线');
  await action(root, 'merge', { mode: 'no-ff' }, '', feature); const merge = head(root);
  expect(git(root, ['show', '-s', '--format=%P', 'HEAD']).split(' ').length === 2, 'merge creates a real two-parent commit');
  await action(root, 'branch_create', { branch: 'temporary' }, '', first);
  await action(root, 'branch_rename', { branch: 'renamed' }, 'temporary');
  expect(git(root, ['rev-parse', 'renamed']) === first, 'create and rename branch preserve target');
  await action(root, 'branch_delete', {}, 'renamed');
  expect(!git(root, ['branch', '--list', 'renamed']), 'branch deletion removes selected ref');
  await action(root, 'tag_add', { tag: 'v1', message: '说明\n第二行' }, '', merge);
  expect(git(root, ['cat-file', '-t', 'v1']) === 'tag', 'annotated tag stores multiline message');
  const state = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  expect(state.commits.some(item => item.email === 'graph@example.invalid'), 'history reads author and committer metadata');
  const root_hover = await api.read_commit_hover_detail(reader.run, state, state.commits.find(item => item.hash === first));
  assert.deepEqual(root_hover, {message:'开始 :tada:',files:1,insertions:1,deletions:0});
  const merge_hover = await api.read_commit_hover_detail(reader.run, state, state.commits.find(item => item.hash === merge));
  expect(merge_hover.files===1&&merge_hover.insertions===1&&merge_hover.deletions===0,'commit hover compares merge against its first parent');
  const hover_root=create_repo('hover stats');write(hover_root,'old name.md','one\ntwo\n');write(hover_root,'binary.dat',Buffer.from([0,1,2]));commit(hover_root,'含二进制的首笔');
  git(hover_root,['mv','old name.md','new name.md']);write(hover_root,'binary.dat',Buffer.from([0,3,4]));write(hover_root,'added.md','added\n');const hover_hash=commit(hover_root,'完整提交信息\n\n保留 <img> 和换行');
  const hover_state=await api.read_repository(reader.run,hover_root,api.graph_defaults,20);
  const hover_detail=await api.read_commit_hover_detail(reader.run,hover_state,hover_state.commits.find(item=>item.hash===hover_hash));
  assert.deepEqual(hover_detail,{message:'完整提交信息\n\n保留 <img> 和换行',files:3,insertions:1,deletions:0});
  await assert.rejects(api.read_commit_hover_detail(reader.run,hover_state,{hash:'--bad',parents:[]}),/./u);
  expect(!git(hover_root,['status','--porcelain'])&&head(hover_root)===hover_hash,'commit hover preserves repository and handles root, rename, binary and full message safely');
  const contained = await api.commit_containment(reader.run, state, first);
  expect(contained.includes('属于 HEAD') && contained.includes('refs/tags/v1'), 'containment reports HEAD and including refs');
  const branch_state = await api.read_repository(reader.run, root, api.graph_defaults, 200, ['refs/heads/feature']);
  expect(branch_state.commits.length === 2, 'single branch limits revision walk');
  const glob_state = await api.read_repository(reader.run, root, api.graph_defaults, 200, ['glob:heads/fea*']);
  expect(glob_state.commits.length === 2, 'custom branch glob limits revision walk');
  const files = await api.compare_files(reader.run, state, first, merge);
  expect(files.length === 2, 'arbitrary commit comparison returns both branch changes');
  git(root, ['mv', 'feature.md', 'renamed feature.md']); const rename = commit(root, 'rename');
  const renamed = await api.compare_files(reader.run, { ...state, head: rename }, merge, rename);
  expect(renamed[0].old_path === 'feature.md' && renamed[0].path === 'renamed feature.md', 'rename detection preserves both paths');
  write(root, '中文 #%.md', 'one\nworking\n'); write(root, 'new file.md', 'untracked\n');
  await action(root, 'stage', {}, '中文 #%.md');
  let dirty = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  expect(dirty.changes.some(file => file.index_status === 'M') && dirty.changes.some(file => file.status === '??'), 'index and untracked changes are distinct');
  expect((await api.compare_files(reader.run, dirty, rename, api.INDEX)).length === 1, 'staged comparison reads the index');
  await action(root, 'unstage', {}, '中文 #%.md');
  await action(root, 'stash_create', { untracked: true, message: 'draft' });
  dirty = await api.read_repository(reader.run, root, api.graph_defaults, 200);
  assert.deepEqual({ stashes: dirty.stashes.length, changes: dirty.changes }, { stashes: 1, changes: [] }, JSON.stringify({ raw: git(root, ['stash', 'list', '--format=%H%x00%gd%x00%gs%x00%aI', '-z']), stashes: dirty.stashes, changes: dirty.changes }));
  expect(true, 'stash stores tracked and untracked edits');
  const stash = dirty.stashes[0]; await action(root, 'stash_apply', {}, stash.name, stash.hash);
  expect(fs.readFileSync(path.join(root, 'new file.md'), 'utf8') === 'untracked\n', 'stash apply restores untracked file');
  await action(root, 'reset', { mode: 'hard' }, '', rename); await action(root, 'clean', {}, '', rename);
  await action(root, 'stash_pop', {}, stash.name, stash.hash);
  expect(!git(root, ['stash', 'list']), 'stash pop removes only successfully applied stash');
  await action(root, 'stash_create', { untracked: true });
  let newest = (await api.read_repository(reader.run, root, api.graph_defaults, 200)).stashes[0];
  await action(root, 'stash_branch', { branch: 'from-stash' }, newest.name, newest.hash);
  expect(git(root, ['branch', '--show-current']) === 'from-stash', 'stash branch checks out a new branch');
  await action(root, 'stash_create', { untracked: true }); newest = (await api.read_repository(reader.run, root, api.graph_defaults, 200)).stashes[0];
  await action(root, 'stash_drop', {}, newest.name, newest.hash);
  expect(!git(root, ['stash', 'list']), 'stash drop removes selected stash');
  await action(root, 'branch_checkout', {}, 'main');
  const remote = path.join(temp, 'bare remote.git'); git(temp, ['init', '--bare', remote]);
  await action(root, 'remote_add', { remote: 'origin', url: remote });
  await action(root, 'push', { remote: 'origin', branch: 'main', upstream: true });
  expect(git(remote, ['rev-parse', 'refs/heads/main']) === rename, 'push writes a real local bare remote');
  await action(root, 'tag_push', { remote: 'origin' }, 'v1');
  expect(git(remote, ['rev-parse', 'refs/tags/v1^{}']) === merge, 'tag push sends annotated tag');
  await action(root, 'fetch', { remote: 'origin', prune: true });
  await action(root, 'remote_checkout', { branch: 'tracking' }, 'origin/main');
  expect(git(root, ['rev-parse', '--abbrev-ref', '@{upstream}']) === 'origin/main', 'remote checkout sets upstream');
  await action(root, 'branch_checkout', {}, 'main');
  await action(root, 'branch_fetch', { remote: 'origin', source: 'main', branch: 'fetched' });
  expect(git(root, ['rev-parse', 'fetched']) === rename, 'fetch maps remote ref to selected local branch');
  await action(root, 'pull', { remote: 'origin', branch: 'main', mode: 'ff-only' });
  await action(root, 'push', { remote: 'origin', branch: 'feature' });
  await action(root, 'remote_branch_delete', { remote: 'origin', branch: 'feature' });
  expect(!git(remote, ['for-each-ref', '--format=%(refname)', 'refs/heads/feature']), 'remote branch deletion targets server ref');
  await action(root, 'remote_edit', { remote: 'origin', url: remote, push_url: true });
  expect(git(root, ['remote', 'get-url', '--push', 'origin']) === remote, 'remote push URL editing');
  await action(root, 'remote_prune', { remote: 'origin' });
  await action(root, 'tag_delete', {}, 'v1'); await action(root, 'remote_remove', { remote: 'origin' });
  expect(!git(root, ['remote']), 'remote removal deletes configuration');
  const stale_plan = await api.plan_git_action(reader.run, 'branch_create', { root, hash: rename, target: '', operation: '' }, { branch: 'stale', checkout: false });
  git(root, ['branch', 'external', first]);
  await assert.rejects(api.execute_git_action(writer.run, stale_plan, () => true), /仓库已被其他程序改变/);
  const guarded_plan = await api.plan_git_action(reader.run, 'reset', { root, hash: first, target: '', operation: '' }, { mode: 'hard' });
  await assert.rejects(api.execute_git_action(writer.run, guarded_plan, () => false), /未保存修改/);
  expect(head(root) === rename, 'stale plan and dirty editor rejection cause no mutation');
  write(root, 'main.md', 'change one\n');
  const content_plan = await api.plan_git_action(reader.run, 'reset', { root, hash: rename, target: '', operation: '' }, { mode: 'hard' });
  write(root, 'main.md', 'change two\n');
  await assert.rejects(api.execute_git_action(writer.run, content_plan, () => true), /仓库已被其他程序改变/);
  expect(fs.readFileSync(path.join(root, 'main.md'), 'utf8') === 'change two\n', 'same-path edits invalidate an earlier destructive preview');
  const edit = create_repo('edit actions'); write(edit, 'one.md', 'one\n'); const base = commit(edit, 'base');
  write(edit, 'two.md', 'two\n'); const second = commit(edit, 'second'); write(edit, 'three.md', 'three\n'); const third = commit(edit, 'third');
  await action(edit, 'drop', {}, second, second);
  expect(!fs.existsSync(path.join(edit, 'two.md')) && fs.existsSync(path.join(edit, 'three.md')), 'drop removes selected commit and replays descendants');
  await action(edit, 'cherry_pick', {}, second, second);
  expect(fs.existsSync(path.join(edit, 'two.md')), 'cherry-pick applies commit');
  await action(edit, 'revert', {}, second, second);
  expect(!fs.existsSync(path.join(edit, 'two.md')), 'revert records inverse change');
  await action(edit, 'commit_checkout', {}, base, base);
  expect(!git(edit, ['branch', '--show-current']), 'commit checkout enters detached HEAD');
  await action(edit, 'branch_checkout', {}, 'main');
  await action(edit, 'branch_create', { branch: 'rebase-source', checkout: true }, '', base);
  write(edit, 'rebased.md', 'rebase\n'); commit(edit, 'rebase change');
  await action(edit, 'rebase', {}, '', third);
  expect(git(edit, ['show', '-s', '--format=%P', 'HEAD']) === third, 'rebase replays onto selected commit');
  write(edit, 'staged.md', 'stage\n'); await action(edit, 'stage', {}, 'staged.md'); await action(edit, 'commit', { message: '图内提交\n\n中文正文' });
  expect(git(edit, ['log', '-1', '--format=%B']).includes('中文正文'), 'commit action supports multiline messages');
  const interactive = create_repo('interactive'); write(interactive, 'base.md', 'base\n'); const interactive_base = commit(interactive, 'base');
  write(interactive, 'a.md', 'a\n'); const a = commit(interactive, 'a'); write(interactive, 'b.md', 'b\n'); const b = commit(interactive, 'b');
  write(interactive, 'c.md', 'c\n'); const c = commit(interactive, 'c');
  await action(interactive, 'rebase', { interactive: true, todo: `reword ${a} 新的标题 $()\npick ${b} b\nfixup ${c} c` }, '', interactive_base);
  expect(git(interactive, ['rev-list', '--count', 'HEAD']) === '3' && git(interactive, ['log', '--format=%s']).includes('新的标题 $()'), 'interactive rebase rewords literal text and fixes up commits');
  const unborn = create_repo('unborn'); write(unborn, 'new.md', 'new\n'); await action(unborn, 'stage', {}, 'new.md');
  const unborn_state = await api.read_repository(reader.run, unborn, api.graph_defaults, 200);
  expect((await api.compare_files(reader.run, unborn_state, api.EMPTY, api.WORKTREE))[0].path === 'new.md', 'unborn worktree comparison includes staged new file');
  await action(unborn, 'unstage', {}, 'new.md'); expect(git(unborn, ['ls-files']) === '' && fs.existsSync(path.join(unborn, 'new.md')), 'unstage before first commit preserves working file');
  const conflicts = create_repo('conflicts'); write(conflicts, 'same.md', 'base\n'); const common = commit(conflicts, 'base');
  git(conflicts, ['checkout', '-b', 'other']); write(conflicts, 'same.md', 'other\n'); const other = commit(conflicts, 'other');
  git(conflicts, ['checkout', 'main']); write(conflicts, 'same.md', 'main\n'); const before = commit(conflicts, 'main');
  await assert.rejects(action(conflicts, 'merge', { mode: 'normal' }, '', other));
  expect(fs.existsSync(path.join(conflicts, '.git/MERGE_HEAD')), 'conflicting merge retains recoverable Git operation');
  await action(conflicts, 'abort', {}, '', '', 'merge'); expect(head(conflicts) === before, 'abort restores pre-merge state');
  await assert.rejects(action(conflicts, 'merge', { mode: 'normal' }, '', other));
  write(conflicts, 'same.md', 'resolved\n'); git(conflicts, ['add', 'same.md']); await action(conflicts, 'continue', {}, '', '', 'merge');
  expect(!fs.existsSync(path.join(conflicts, '.git/MERGE_HEAD')), 'continue finishes resolved merge');
  await action(conflicts, 'reset', { mode: 'hard' }, '', before); await assert.rejects(action(conflicts, 'cherry_pick', {}, other, other));
  await action(conflicts, 'skip', {}, '', '', 'cherry-pick'); expect(head(conflicts) === before, 'skip abandons conflicted cherry-pick');
  expect(api.glob_matches('heads/feat*', 'heads/feature') && !api.glob_matches('heads/feat*', 'heads/main'), 'glob matcher');
  assert.throws(() => api.validate_settings({ initial_count: -1 })); assert.throws(() => api.validate_settings({ colors: ['not-a-color'] }));
  const storage = new Map(); const store = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
  api.save_reviews(store, [{ root, from: first, to: merge, reviewed: ['main.md'], updated_at: Date.now() }]);
  expect(api.load_reviews(store)[0].reviewed[0] === 'main.md' && api.load_reviews(store, Date.now() + 91 * 86400000).length === 0, 'review persistence and 90-day expiry');
  expect(api.pull_request_url('git@github.com:owner/repo.git', 'feature/a', 'main').includes('feature%2Fa'), 'GitHub PR URL encodes branches');
  expect(api.pull_request_url('https://gitlab.com/owner/repo.git', 'feature', 'main').includes('merge_requests/new'), 'GitLab PR form');
  expect(api.pull_request_url('https://bitbucket.org/owner/repo.git', 'feature', 'main').includes('pull-requests/new'), 'Bitbucket PR form');
  const signed = create_repo('signed'); const key = path.join(temp, 'signing_key');
  child_process.execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', key], { windowsHide: true, stdio: 'pipe' });
  const signers = path.join(temp, 'allowed_signers'); fs.writeFileSync(signers, 'graph@example.invalid ' + fs.readFileSync(key + '.pub', 'utf8'));
  git(signed, ['config', 'gpg.format', 'ssh']); git(signed, ['config', 'user.signingKey', key]); git(signed, ['config', 'gpg.ssh.allowedSignersFile', signers]);
  write(signed, 'signed.md', 'signed\n'); git(signed, ['add', 'signed.md']);
  const signed_plan = await api.plan_git_action(reader.run, 'commit', { root: signed, target: '', hash: '', operation: '', sign_commits: true }, { message: 'signed', amend: false });
  await api.execute_git_action(writer.run, signed_plan, () => true);
  expect(git(signed, ['show', '-s', '--format=%G?', 'HEAD']) === 'G', 'commit signing is verified with an isolated SSH key');
  const tag_plan = await api.plan_git_action(reader.run, 'tag_add', { root: signed, target: '', hash: head(signed), operation: '', sign_tags: true }, { ...defaults('tag_add'), tag: 'signed', message: 'signed tag', sign: false });
  await api.execute_git_action(writer.run, tag_plan, () => true); git(signed, ['verify-tag', 'signed']);
  expect(true, 'tag signature verifies with an isolated signing key');
  const archive = path.join(temp, 'version.zip'); await writer.run(signed, ['archive', '--format=zip', '--output=' + archive, 'HEAD']);
  expect(fs.readFileSync(archive).subarray(0, 2).toString() === 'PK', 'archive writes a ZIP file');
  const scm = create_repo('source control'); const old_path = '旧名 [1] #%.c'; const new_path = '新名 [1] #%.c';
  write(scm, old_path, 'int value = 1;\n'); const scm_first = commit(scm, '初始文件');
  git(scm, ['mv', '--', old_path, new_path]); commit(scm, '重命名'); write(scm, new_path, 'int value = 2;\n'); commit(scm, '修改内容');
  const timeline = await api.read_file_history(reader.run, scm, new_path);
  expect(timeline.length === 3 && timeline[0].file.path === new_path && timeline[1].file.old_path === old_path && timeline[2].file.path === old_path && timeline[2].commit.hash === scm_first, 'file timeline follows rename and retains historical paths');
  write(scm, new_path, 'int value = 3;\n'); await action(scm, 'stage', {}, new_path); write(scm, new_path, 'int value = 4;\n');
  await action(scm, 'discard_file', {}, new_path);
  expect(fs.readFileSync(path.join(scm,new_path),'utf8') === 'int value = 3;\n', 'discard restores index version and preserves staged content');
  await action(scm, 'unstage_all'); expect(!git(scm,['diff','--cached','--name-only']), 'unstage all keeps working files');
  write(scm,'new [2].md','untracked'); write(scm,'new 2.md','neighbor');
  await action(scm,'delete_untracked',{},'new [2].md');
  expect(!fs.existsSync(path.join(scm,'new [2].md')) && fs.existsSync(path.join(scm,'new 2.md')), 'discard untracked file treats brackets literally and leaves neighboring file');
  await action(scm,'stage_all'); expect(git(scm,['diff','--cached','--name-only']).includes('new 2.md'),'stage all includes untracked file');
  await action(scm,'unstage_all'); git(scm,['restore','--worktree','--',new_path]);
  git(scm,['mv','--',new_path,'moved.c']);
  const batch = await api.plan_git_action(reader.run,'unstage',{root:scm,target:'moved.c',hash:head(scm),operation:'',paths:['moved.c',new_path]},{});
  await api.execute_git_action(writer.run,batch,()=>true);
  expect(!git(scm,['diff','--cached','--name-only']) && fs.existsSync(path.join(scm,'moved.c')), 'unstaging rename removes both index paths without moving working file');
  const clone_path = path.join(temp,'克隆仓库'); await action(scm,'clone',{url:scm,directory:clone_path});
  expect(head(clone_path) === head(scm),'clone creates selected destination with committed history');
  const ignored_root = create_repo('precise ignores'); const modules = {fs, path_api: path};
  const append_ignore = file => api.append_git_ignore(modules, reader.run, ignored_root, file);
  const ignore_file = path.join(ignored_root, '.gitignore'); const original_ignore = Buffer.from('\ufeff# existing rules\r\nkeep-original'); fs.writeFileSync(ignore_file, original_ignore);
  const special = '目录 [1]/#秘密 ! 文件[2].md'; write(ignored_root, special, 'secret'); write(ignored_root, '目录 [1]/#秘密 ! 文件2.md', 'neighbor'); write(ignored_root, 'other/' + special, 'another directory');
  const ignored_result = await append_ignore(special); const ignore_bytes = fs.readFileSync(ignore_file);
  expect(ignore_bytes.subarray(0, original_ignore.length).equals(original_ignore) && ignore_bytes.subarray(original_ignore.length).toString() === '\r\n' + ignored_result.rule + '\r\n', 'ignore append preserves original BOM, bytes and CRLF without a final newline');
  expect(await reader.run(ignored_root, ['check-ignore', '--', special]) === special + '\n', 'root ignore rule matches the exact special filename');
  await assert.rejects(reader.run(ignored_root, ['check-ignore', '--', '目录 [1]/#秘密 ! 文件2.md']), error => error.code === 1);
  await assert.rejects(reader.run(ignored_root, ['check-ignore', '--', 'other/' + special]), error => error.code === 1);
  expect(true, 'ignore rule escapes brackets and anchors the complete path at repository root');
  expect(!(await append_ignore(special)).changed && fs.readFileSync(ignore_file).equals(ignore_bytes), 'repeating an effective exact ignore rule leaves existing bytes unchanged');
  write(ignored_root, 'tracked.md', 'tracked'); await action(ignored_root, 'stage', {}, 'tracked.md');
  await assert.rejects(append_ignore('tracked.md'), /已经加入 Git 跟踪/);
  expect((await reader.run(ignored_root, ['ls-files', '-z', '--', 'tracked.md'])) === 'tracked.md\0' && fs.readFileSync(ignore_file).equals(ignore_bytes), 'ignore rejects tracked files without removing index entries or editing rules');
  for (const invalid of ['../outside.md', '/absolute.md', 'bad\nname.md', '.git/config']) await assert.rejects(append_ignore(invalid), /精确忽略规则/);
  expect(true, 'ignore rejects traversal, metadata paths and line-breaking filenames');
  const patterns = ['literal*.md', 'question?.md', '#start!.md', 'bracket[ab].md', 'trailing ', ...(process.platform === 'win32' ? [] : ['back\\slash.md'])];
  fs.writeFileSync(ignore_file, patterns.map(api.exact_ignore_rule).join('\n') + '\n');
  for (const name of patterns) {
    await reader.run(ignored_root, ['check-ignore', '--no-index', '--quiet', '--', name]);
    await assert.rejects(reader.run(ignored_root, ['check-ignore', '--no-index', '--quiet', '--', 'nested/' + name]), error => error.code === 1);
  }
  for (const name of ['literalXYZ.md', 'questionA.md', 'bracketa.md', 'trailing']) await assert.rejects(reader.run(ignored_root, ['check-ignore', '--no-index', '--quiet', '--', name]), error => error.code === 1);
  expect(api.exact_ignore_rule('back\\slash.md') === '/back\\\\slash.md', 'Git validates wildcard, leading marker and trailing-space escaping; literal backslashes are escaped for POSIX filenames');
  fs.writeFileSync(ignore_file, Buffer.from([0xff, 0xfe, 0x61, 0])); write(ignored_root, 'untouched.md', 'untouched');
  await assert.rejects(append_ignore('untouched.md'), /UTF-8/);
  expect(fs.readFileSync(ignore_file).equals(Buffer.from([0xff, 0xfe, 0x61, 0])), 'non-UTF8 ignore content is rejected without alteration');
  fs.unlinkSync(ignore_file); const outside = path.join(temp, 'outside-ignore'); fs.writeFileSync(outside, 'outside\n'); fs.linkSync(outside, ignore_file);
  await assert.rejects(append_ignore('untouched.md'), /无链接的普通文件/);
  expect(fs.readFileSync(outside, 'utf8') === 'outside\n', 'hard-linked ignore file is rejected without writing its other name');
  fs.unlinkSync(ignore_file); const linked_directory = path.join(temp, 'linked-ignore-directory'); fs.mkdirSync(linked_directory); fs.symlinkSync(linked_directory, ignore_file, process.platform === 'win32' ? 'junction' : 'dir');
  await assert.rejects(append_ignore('untouched.md'), /无链接的普通文件/);
  expect(fs.readdirSync(linked_directory).length === 0, 'symbolic-link or junction ignore path is rejected');
  fs.unlinkSync(ignore_file); const new_ignore = await append_ignore('untouched.md');
  expect(new_ignore.changed && fs.readFileSync(ignore_file, 'utf8') === '/untouched.md\n' && !(await reader.run(ignored_root, ['ls-files', '-z', '--', '.gitignore'])), 'missing root ignore is created without staging the rule file');
  // 使用真实仓库验证上游选项对应的磁盘结果及复合操作边界。
  const parity = create_repo('upstream parity'); write(parity, 'base.md', 'base'); const parity_base = commit(parity, 'base');
  const parity_remote = path.join(temp, 'parity_remote.git'); git(temp, ['init', '--bare', parity_remote]); git(parity, ['remote', 'add', 'origin', parity_remote]);
  await action(parity, 'tag_add', {tag: 'annotated-default', push: true, remote: 'origin'}, '', parity_base);
  expect(git(parity, ['cat-file', '-t', 'annotated-default']) === 'tag' && git(parity_remote, ['rev-parse', 'refs/tags/annotated-default^{}']) === parity_base, 'default annotated tag and optional push execute both visible steps');
  await action(parity, 'tag_add', {tag: 'light', tag_type: 'lightweight'}, '', parity_base);
  expect(git(parity, ['cat-file', '-t', 'light']) === 'commit', 'explicit lightweight tag points directly at commit');
  const spaced_plan = await api.plan_git_action(reader.run, 'branch_create', {root: parity, target:'',hash:parity_base,operation:'',reference_space:'-'}, {branch:'feature space',checkout:false});
  await api.execute_git_action(writer.run, spaced_plan, () => true); expect(git(parity,['rev-parse','feature-space']) === parity_base,'reference space substitution is validated and creates the substituted ref');
  git(parity,['checkout','-b','squash-source']); write(parity,'squashed.md','squashed'); commit(parity,'source subject'); git(parity,['checkout','main']);
  const squash_plan = await action(parity,'merge',{mode:'squash',squash_message:'default'},'squash-source',git(parity,['rev-parse','squash-source']));
  expect(squash_plan.preview.includes('commit') && git(parity,['show','HEAD:squashed.md']) === 'squashed' && git(parity,['show','-s','--format=%P','HEAD']) === parity_base,'squash plan previews and creates a single-parent commit');
  expect(!git(parity,['diff','--cached','--name-only']),'automatic squash commit clears only successfully committed index');
  git(parity,['checkout','squash-source']); write(parity,'later.md','later'); commit(parity,'later source'); git(parity,['checkout','main']); const before_deferred = head(parity);
  await action(parity,'merge',{mode:'squash',no_commit:true},'squash-source',git(parity,['rev-parse','squash-source']));
  expect(head(parity) === before_deferred && git(parity,['diff','--cached','--name-only']).includes('later.md'),'no-commit squash retains staged changes without creating a commit');
  const squash_git = create_repo('squash git message'); write(squash_git,'base.md','base'); const squash_base = commit(squash_git,'base');
  git(squash_git,['checkout','-b','source']); write(squash_git,'change.md','new'); const squash_source = commit(squash_git,'keep source subject'); git(squash_git,['checkout','main']);
  await action(squash_git,'merge',{mode:'squash',squash_message:'git'},'source',squash_source);
  expect(git(squash_git,['show','-s','--format=%B','HEAD']).includes('keep source subject'),'Git SQUASH_MSG retains source commit message');
  const no_change_head = head(squash_git); await action(squash_git,'merge',{mode:'squash'},'HEAD',no_change_head);
  expect(head(squash_git) === no_change_head,'squash without staged differences skips a redundant empty commit');
  await assert.rejects(action(squash_git,'tag_add',{tag:'local-after-push-failure',push:true,remote:'missing'},'',squash_base),/第一步已完成/);
  expect(git(squash_git,['rev-parse','local-after-push-failure^{}']) === squash_base,'failed optional push reports the preserved local tag instead of claiming atomic rollback');
  // 在真实squash与后续commit之间注入宿主草稿、外部暂存和读取失败。
  for (const scenario of ['draft', 'index', 'check-error']) {
    const guarded = create_repo('squash guard '+scenario); write(guarded,'base.md','base'); const guarded_head=commit(guarded,'base');
    git(guarded,['checkout','-b','source']);write(guarded,'source.md','source');const source_head=commit(guarded,'source');git(guarded,['checkout','main']);
    const guarded_plan=await api.plan_git_action(reader.run,'merge',{root:guarded,target:'source',hash:source_head},{...defaults('merge'),mode:'squash',squash_message:'default'});
    let first_done=false, index_reads=0, commit_attempted=false;
    const guarded_run=async(root,args,...rest)=>{
      if(args[0]==='commit')commit_attempted=true;
      if(first_done&&scenario==='check-error'&&args[0]==='diff'&&args.includes('--cached'))throw new Error('injected post-squash check failure');
      const result=await writer.run(root,args,...rest);
      if(args[0]==='merge')first_done=true;
      if(first_done&&scenario==='index'&&args[0]==='ls-files'&&args.includes('--stage')&&++index_reads===1){write(root,'external.md','external staged');git(root,['add','--','external.md']);}
      return result;
    };
    await assert.rejects(api.execute_git_action(guarded_run,guarded_plan,()=>scenario!=='draft'||!first_done),/第一步已完成/u);
    expect(first_done&&!commit_attempted&&head(guarded)===guarded_head&&git(guarded,['diff','--cached','--name-only']).includes('source.md'),'post-squash '+scenario+' refuses followup and retains completed index changes with partial-success error');
    if(scenario==='index')expect(git(guarded,['show',':external.md'])==='external staged','concurrent external index content is preserved rather than committed or rolled back');
  }
  console.log(JSON.stringify({ status: 'PASS', checks }, null, 2));
} finally {
  reader.cancel(); writer.cancel();
  assert(path.dirname(temp) === path.resolve(os.tmpdir()) && path.basename(temp).startsWith('typora_git_full_'));
  fs.rmSync(temp, { recursive: true, force: true });
}
