// 真实 Chromium 指针／键盘与隔离 Git 数据验证 R027，不操作用户窗口、远端或文件。
const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),child_process=require('node:child_process');
const {build}=require('esbuild'),{editor_plugins}=require('./editor_bundle.cjs');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'typora_scm_ui_')),root=path.join(temp,'repo'),other=path.join(temp,'other'),remote=path.join(temp,'remote.git');fs.mkdirSync(root);fs.mkdirSync(other);
const git=(cwd,args)=>child_process.execFileSync('git',['-c','core.hooksPath=.git/unused_hooks','-c','core.autocrlf=false',...args],{cwd,encoding:'utf8',windowsHide:true,stdio:['pipe','pipe','pipe']}).trim();
for(const dir of [root,other]){git(dir,['init','-b','main']);git(dir,['config','user.name','SCM QA']);git(dir,['config','user.email','scm@example.invalid']);git(dir,['config','commit.gpgsign','false']);fs.writeFileSync(path.join(dir,'before.md'),'# Original\n');git(dir,['add','.']);git(dir,['commit','-m','基础提交\n\n完整的第二段\n最后一行']);}
const base=git(root,['rev-parse','HEAD']);git(temp,['clone','--bare',root,remote]);git(root,['remote','add','origin',remote]);git(root,['push','-u','origin','main']);
git(root,['mv','before.md','renamed.md']);git(root,['commit','-m','重命名\n\n保留正文']);const head=git(root,['rev-parse','HEAD']);git(root,['branch','topic',base]);git(root,['tag','test-tag',base]);git(root,['config','branch.main.vscode-merge-base','origin/main']);
fs.writeFileSync(path.join(root,'renamed.md'),'# Edited\n');fs.writeFileSync(path.join(root,'new.md'),'# New\n');git(root,['add','new.md']);
app.setPath('userData',path.join(temp,'user_data'));app.disableHardwareAcceleration();let win;const checks=[];const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async source=>{try{return await win.webContents.executeJavaScript(source);}catch(error){console.error(source);throw error;}};
const wait=async source=>{for(let i=0;i<160;i++){if(await evaluate(source))return;await delay(50);}throw new Error('Timed out: '+source);};
const click=async(selector,mouse='left')=>{await delay(60);const p=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw new Error('Missing '+${JSON.stringify(selector)});node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x:Math.round(x),y:Math.round(y),hit:node.contains(document.elementFromPoint(x,y)),width:r.width,disabled:node.disabled};})()`);assert(p.hit&&p.width>0,JSON.stringify({selector,...p}));for(const type of ['mouseMove','mouseDown','mouseUp']){win.webContents.sendInputEvent({type,x:p.x,y:p.y,button:mouse,clickCount:1});await delay(20);}};
const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});if(keyCode==='Enter')win.webContents.sendInputEvent({type:'char',keyCode:'\r',modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(80);};
const capture=async name=>fs.writeFileSync(path.join(temp,name+'.png'),(await win.webContents.capturePage()).toPNG());
app.whenReady().then(async()=>{
  win=new BrowserWindow({show:false,width:1050,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});win.webContents.on('console-message',(_e,_l,message)=>console.error(message));
  const html=path.join(temp,'test.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;overflow:hidden;font:13px system-ui}body{display:flex}#sidebar{width:380px;flex:none;height:100%}#editor{flex:1;min-width:0}button,input{font:inherit}</style><section id="sidebar" class="linux-note-git-source-control"></section><section id="editor"></section>');await win.loadFile(html);win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
  const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export {git_graph_panel} from "./src/git_graph_panel";export {create_graph_host} from "./src/git_graph_host";export {GRAPH_SETTINGS_KEY} from "./src/git_graph_settings";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{
    const css=document.createElement('style');css.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'))};document.head.append(css);
    window.reqnode=require;window._options={userDataPath:${JSON.stringify(temp)},displayLang:'zh-CN'};window.File={changeCounter:{isDocumentEdited:()=>false}};
    window.copied='';window.JSBridge={invoke:async(command,data)=>{if(command==='clipboard.write')copied=JSON.parse(data).text;}};
    const core={WorkspaceView:class{},app:{viewManager:{registerView(){}},commands:{run(...args){window.commands.push(args)},register(){}},workspace:{sidebar:{},on(){},ribbon:{addButton(){}},eachLeaves(){},activeLeaf:null}}};window.commands=[];
    window.host=qa.create_graph_host(core);window.opened=[];window.revisions=[];host.open_document=(...args)=>opened.push(args);host.open_revision_document=(...args)=>revisions.push(args);
    window.panel=new qa.git_graph_panel(host,${JSON.stringify(root)});document.querySelector('#sidebar').append(panel.workbench.sidebar);document.querySelector('#editor').append(panel.container);panel.save_repos([panel.root,${JSON.stringify(other)}]);void panel.refresh();
  })()`);await wait('!panel.pending&&panel.state?.commits.length===2');
  const revision_data=await evaluate('panel.state.tracking');assert.equal(revision_data.ahead,1);assert.equal(revision_data.behind,0);
  await click('.git-scm-view-menu');await click('[data-action=show_repositories]');await wait('document.querySelectorAll(".git-scm-repository-branch span").length===2');assert(await evaluate('[...document.querySelectorAll(".git-scm-repository-name")].some(node=>node.textContent==="repo")'));await capture('repositories_and_graph');
  await click('.git-scm-history-header','right');assert(await evaluate('!!document.querySelector("[data-action=hide_section]")&&!!document.querySelector("[data-action=show_repositories]")'));await key('Escape');
  const title_geometry=await evaluate(`(()=>{const title=document.querySelector('.git-scm-history-title'),toggle=title.parentElement,badge=toggle.querySelector('.git-scm-badge');return {ellipsis:getComputedStyle(title).textOverflow,text_nodes:[...toggle.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim()).length,badge_fits:badge.hidden||badge.getBoundingClientRect().right<=toggle.getBoundingClientRect().right+1};})()`);assert.equal(title_geometry.ellipsis,'ellipsis');assert.equal(title_geometry.text_nodes,0);assert(title_geometry.badge_fits);
  await click('[data-history-action=fetch]','right');await click('[data-action=hide_action]');assert(await evaluate('panel.settings.history_toolbar_hidden.includes("fetch")&&document.querySelector("[data-history-action=fetch]").hidden'));await click('.git-scm-history-more-menu');assert(await evaluate('!!document.querySelector("[data-action=fetch]")&&!!document.querySelector("[data-action=history_tree]")'));await capture('hidden_actions_overflow');await click('[data-action=fetch]');await wait('!panel.writing&&!panel.pending');assert.equal(await evaluate('document.querySelectorAll(".git-graph-dialog-shade,[data-field=remote]").length'),0);
  await click('.git-scm-history-more-menu','right');assert(await evaluate('document.querySelector("[data-action=hide_action]").disabled'));await click('[data-action=toggle_fetch]');assert(!await evaluate('document.querySelector("[data-history-action=fetch]").hidden'));checks.push('toolbar hides, restores and recovers Fetch All through More');
  await click('[data-history-action=refresh]','right');await click('[data-action=configure_keybinding]');await evaluate('document.querySelector("[data-history-keybinding=refresh]").value="Mod+Shift+R"');await click('.git-graph-dialog-footer button');assert.equal(await evaluate('panel.settings.history_shortcuts.refresh'),'Mod+Shift+R');
  await evaluate('window.refreshes=0;window.refresh_original=panel.refresh.bind(panel);panel.refresh=async(...args)=>{refreshes++;return refresh_original(...args)};panel.workbench.history.toggle.focus()');await key('R',['control','shift']);await wait('refreshes===1&&!panel.pending');await evaluate('panel.workbench.message.focus()');await key('R',['control','shift']);assert.equal(await evaluate('refreshes'),1);await evaluate('void (panel.refresh=refresh_original)');checks.push('configured keybinding executes same command only in SCM and leaves inputs alone');
  await click('[data-history-action=branches]');await evaluate('document.querySelector(".git-scm-ref-filter").value="topic";document.querySelector(".git-scm-ref-filter").dispatchEvent(new Event("input"))');assert.equal(await evaluate('[...document.querySelectorAll("[data-git-ref]")].length'),1);await key('Escape');assert.equal(await evaluate('panel.branches.length'),0);
  await click('[data-history-action=branches]');await click('[data-git-ref=AUTO]');await click('[data-git-ref-accept]');await wait('!panel.pending&&panel.branches[0]==="AUTO"');assert.equal(await evaluate('document.querySelector(".git-scm-history-scope").textContent'),'自动');await click('[data-history-action=branches]');await click('[data-git-ref=__all__]');await click('[data-git-ref-accept]');await wait('!panel.pending&&panel.branches.length===0');await evaluate("panel.branches=['refs/heads/topic'];void panel.refresh()");await wait('!panel.pending&&!panel.state.commits.some(commit=>commit.hash===panel.state.head)');await click('[data-history-action=head]');await wait('!panel.pending&&panel.workbench.history.selected===panel.state.head');assert(await evaluate('panel.workbench.history.list.contains(document.activeElement)'));await click('[data-history-action=branches]');await click('[data-git-ref=__all__]');await click('[data-git-ref-accept]');await wait('!panel.pending&&panel.branches.length===0');checks.push('reference search cancel and Auto/All selection preserve state, and Go to Current restores a filtered-out HEAD');
  for(const width of [180,240,380])for(const dark of [false,true]){await evaluate(`document.querySelector('#sidebar').style.width='${width}px';document.documentElement.style.setProperty('--bg-color','${dark?'#202020':'white'}');document.documentElement.style.color='${dark?'#eee':'#222'}';panel.workbench.history.toolbar.update()`);await delay(80);const metrics=await evaluate(`(()=>{const h=panel.workbench.history.header,m=panel.workbench.history.toolbar.more,r=m.getBoundingClientRect();return {overflow:h.scrollWidth-h.clientWidth,hit:m.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),visible:[...panel.workbench.history.toolbar.buttons].filter(([,node])=>!node.hidden).map(([id])=>id)};})()`);assert(metrics.overflow<=1,JSON.stringify(metrics));assert(metrics.hit);await click('.git-scm-history-more-menu');for(const id of ['branches','head','fetch','pull','push','refresh'])assert(metrics.visible.includes(id)||await evaluate(`!!document.querySelector('[data-action=${id}]')`));await key('Escape');await capture(`toolbar_${width}_${dark?'dark':'light'}`);}checks.push('narrow and wide toolbars keep every command reachable and the More target unobstructed');
  await evaluate("document.querySelector('#sidebar').style.width='380px';document.documentElement.style.setProperty('--bg-color','white');document.documentElement.style.color='#222';panel.workbench.history.toolbar.update()");
  await click(`[data-hash="${base}"]`,'right');for(const id of ['open_changes','open_github','checkout','commit_checkout','branch_create','delete_branch','tag_add','cherry_pick','compare_remote','compare_base','compare_with','copy_hash','copy_message'])assert(await evaluate(`!!document.querySelector('[data-action=${id}]')`),id);assert(await evaluate('document.querySelector("[data-action=open_github]").disabled'));await click('[data-action=copy_message]');await wait('copied.includes("最后一行")');const copied_message=await evaluate('copied');assert(copied_message.includes('完整的第二段'));checks.push('commit menu has real Git actions and copies the entire message');
  await click(`[data-hash="${head}"]`,'right');await click('[data-action=compare_remote]');await wait('opened.length===1');assert.equal(await evaluate('opened[0][0].left'),'# Original\n');assert.equal(await evaluate('opened[0][0].right'),'# Original\n');assert.equal(await evaluate('opened[0][2].key'),JSON.stringify([base,head,'renamed.md']));checks.push('compare with upstream uses immutable objects and rename-aware paths');
  await click('[data-file="renamed.md"]','right');assert(await evaluate('!document.querySelector("[data-action=open_head]").disabled'));await click('[data-action=open_head]');await wait('revisions.length===1');assert.equal(await evaluate('revisions[0][1]'),head);assert.equal(await evaluate('revisions[0][3]'),'# Original\n');await click('[data-file="new.md"]','right');assert(await evaluate('document.querySelector("[data-action=open_head]").disabled'));await key('Escape');
  await click('[data-file="renamed.md"]','right');await click('[data-action=reveal_explorer]');assert.equal(await evaluate('commands.at(-1)[0]'),'linux_note:reveal_in_explorer');checks.push('HEAD reads saved objects, new files disable HEAD and Explorer uses shared command');
  await click('.git-scm-operation-menu');await click('[data-action=worktrees]');await click('[data-action=worktree_manage]');await wait('document.querySelector(".git-scm-worktree-entry")');assert(await evaluate('[...document.querySelectorAll(".git-scm-worktree-entry button")].find(node=>node.textContent.includes("删除")).disabled'));await key('Escape');checks.push('repository Worktrees entry reads Git and protects the main worktree');
  await evaluate('window.stale_fetch=panel.workbench.history.toolbar.entry("fetch");void 0');await click('[data-history-action=fetch]');await wait('!panel.writing&&!panel.pending');assert.equal(await evaluate('document.querySelectorAll(".git-graph-dialog-shade,[data-git-preview=fetch]").length'),0);await evaluate(`void panel.switch_repo(${JSON.stringify(other)})`);await wait(`!panel.pending&&panel.root===${JSON.stringify(other.replace(/\\/g,"/"))}`);await evaluate('stale_fetch.action()');await delay(100);assert(!await evaluate('panel.writing'));assert(await evaluate('document.querySelector("[data-history-action=fetch]").disabled'));checks.push('Fetch immediately completes and a retained toolbar command cannot execute after repository switch');
  const late_menu=await evaluate(`(()=>{window.stale=panel.workbench.file_entries({path:'before.md',status:'M'},'INDEX','WORKTREE',[],panel.root).find(entry=>entry.id==='open_head');return true})()`);assert(late_menu);await evaluate(`void panel.switch_repo(${JSON.stringify(root)})`);await wait(`!panel.pending&&panel.root===${JSON.stringify(root.replace(/\\/g,"/"))}`);await evaluate('stale.action()');assert.equal(await evaluate('revisions.length'),1);checks.push('stale file menu cannot open an object in the new repository');
  // 标题操作复用生产事务；所有读写均限制在本脚本创建的临时仓库。
  const title_selector=id=>`[data-scm-title-action=${id}]`;
  const title_buttons=await evaluate(`(()=>{const heading=document.querySelector('summary.git-scm-input-heading'),actions=heading.querySelector('.git-scm-input-actions');return {branch:!!heading.querySelector('.git-scm-branch'),order:actions&&[...actions.querySelectorAll('button')].map(node=>node.dataset.scmTitleAction||'more'),accessible:actions&&[...actions.querySelectorAll('button')].every(node=>node.tabIndex>=0&&(node.getAttribute('aria-label')||node.title))};})()`);
  assert.equal(title_buttons.branch,false,'Changes heading no longer contains the old branch control');
  assert.deepEqual(title_buttons.order,['commit','refresh','graph','more']);assert(title_buttons.accessible);
  const starting_status=git(root,['status','--porcelain=v1']),starting_index=git(root,['write-tree']);
  await evaluate(`(()=>{
    window.title_calls={refresh:[],graph:[],quick:[],writer:[]};window.title_refresh_original=panel.refresh.bind(panel);window.title_quick_original=panel.quick_action.bind(panel);
    window.title_runner=panel.runner;window.title_run_original=panel.runner.run;window.title_writer=panel.writer;window.title_write_original=panel.writer.run;
    panel.refresh=(...args)=>{title_calls.refresh.push(args);return title_refresh_original(...args)};
    panel.quick_action=(...args)=>{title_calls.quick.push(args);return title_quick_original(...args)};
    host.show_history=root=>title_calls.graph.push(root);
    panel.runner.run=async(...args)=>{if(window.title_hold_read){window.title_hold_read=false;window.title_read_pending=true;await new Promise(resolve=>window.title_release_read=resolve);window.title_read_pending=false;}return title_run_original(...args)};
    panel.writer.run=async(...args)=>{title_calls.writer.push(args);if(args[1][0]==='commit'){window.title_write_pending=true;await new Promise(resolve=>window.title_release_write=resolve);window.title_write_pending=false;}return title_write_original(...args)};
  })()`);
  const assert_title_disabled=async expected=>{
    const actual=await evaluate(`Object.fromEntries([...document.querySelectorAll('[data-scm-title-action],.git-scm-commit')].map(node=>[node.dataset.scmTitleAction||'main',node.disabled]))`);
    assert.deepEqual(actual,expected);
  };
  const ready_buttons={commit:false,refresh:false,graph:false,main:false},busy_buttons={commit:true,refresh:true,graph:true,main:true};
  await assert_title_disabled(ready_buttons);
  await click(title_selector('commit'));assert(await evaluate('document.activeElement===panel.workbench.message&&panel.workbench.input_section.open'));
  await click('.git-scm-commit');assert(await evaluate('document.activeElement===panel.workbench.message'));
  assert.equal(await evaluate('title_calls.quick.length'),0);assert.equal(await evaluate('title_calls.writer.length'),0);assert.equal(git(root,['rev-parse','HEAD']),head);
  checks.push('title and main commit reject empty messages, focus the input and never start a Git transaction');

  await click('.git-scm-message');await key('A',['control']);await key('Backspace');
  const title_message='SCM title action QA';for(const character of title_message)win.webContents.sendInputEvent({type:'char',keyCode:character});
  await wait(`panel.workbench.message.value===${JSON.stringify(title_message)}`);
  assert.equal(await evaluate('localStorage.getItem(panel.workbench.storage_key("message"))'),title_message);
  await click('.git-scm-commit-options');await click('[data-action=commit_options]');assert(!await evaluate('document.querySelector("[data-git-preview=commit]")'));
  assert(await evaluate('document.querySelector("[data-field=message]").value.includes("SCM title action QA")'));await key('Escape');
  assert.equal(git(root,['rev-parse','HEAD']),head);assert.equal(git(root,['status','--porcelain=v1']),starting_status);assert.equal(git(root,['write-tree']),starting_index);assert.equal(await evaluate('title_calls.writer.length'),0);
  checks.push('commit options need one submission and cancelling leaves HEAD, index and working files unchanged');

  await click('summary.git-scm-input-heading');assert.equal(await evaluate('panel.workbench.input_section.open'),false);
  await click(title_selector('commit'));await wait('panel.writing&&window.title_write_pending');await assert_title_disabled(busy_buttons);assert.equal(await evaluate('panel.workbench.input_section.open'),false,'a populated title commit leaves the Changes section collapsed');
  await click('summary.git-scm-input-heading');assert(await evaluate('panel.workbench.input_section.open'));
  const writing_calls=await evaluate('JSON.stringify(title_calls)');
  for(const id of ['commit','refresh','graph'])await click(title_selector(id));await click('.git-scm-commit');
  await click('.git-scm-message');await key('Enter',['control']);assert.equal(await evaluate('JSON.stringify(title_calls)'),writing_calls,'busy pointer and keyboard activation cannot start another transaction');
  await evaluate('title_release_write()');await wait('!panel.writing&&!panel.pending&&panel.state.commits.length===3');await assert_title_disabled(ready_buttons);
  const title_head=git(root,['rev-parse','HEAD']);assert.notEqual(title_head,head);assert.equal(git(root,['rev-parse','HEAD^']),head);assert.equal(git(root,['rev-list','--count','HEAD']), '3');assert.equal(git(root,['show','-s','--format=%B','HEAD']),title_message);
  assert.deepEqual(await evaluate('title_calls.quick.map(args=>args[0])'),['commit']);assert.equal(await evaluate('title_calls.writer.filter(args=>args[1][0]==="commit").length'),1);
  assert.equal(await evaluate('panel.workbench.message.value'),'');assert.equal(await evaluate('localStorage.getItem(panel.workbench.storage_key("message"))'),null);
  assert.equal(fs.readFileSync(path.join(root,'renamed.md'),'utf8'),'# Edited\n');assert.equal(fs.readFileSync(path.join(root,'new.md'),'utf8'),'# New\n');assert.equal(git(root,['diff','--cached','--name-only']),'');
  checks.push('title commit runs exactly one existing Git transaction in the temporary repository, clears the saved message and preserves working text');

  const refresh_before=await evaluate('title_calls.refresh.length');await evaluate('window.title_hold_read=true');await click(title_selector('refresh'));await wait('panel.pending&&window.title_read_pending');await assert_title_disabled(busy_buttons);
  const pending_calls=await evaluate('JSON.stringify(title_calls)');for(const id of ['commit','refresh','graph'])await click(title_selector(id));await click('.git-scm-commit');assert.equal(await evaluate('JSON.stringify(title_calls)'),pending_calls);
  await evaluate('title_release_read()');await wait('!panel.pending&&panel.container.dataset.state==="ready"');await assert_title_disabled(ready_buttons);
  assert.equal(await evaluate('title_calls.refresh.length'),refresh_before+1);assert.deepEqual(await evaluate('title_calls.refresh.at(-1)'),[false]);assert.equal(git(root,['rev-parse','HEAD']),title_head);
  await click(title_selector('graph'));assert.deepEqual(await evaluate('title_calls.graph'),[root.replace(/\\/g,'/')]);assert(await evaluate('panel.workbench.input_section.open'));
  checks.push('title refresh performs one real read without resetting history, blocks duplicate actions while pending and Graph receives the active root');

  // 同一仍有效仓库的读取错误必须禁用写入，但保留刷新恢复入口。
  await evaluate('panel.runner.run=async()=>{throw new Error("SCM title controlled read failure")};void panel.refresh(false)');await wait('!panel.pending&&panel.container.dataset.state==="error"');
  await assert_title_disabled({commit:true,refresh:false,graph:true,main:true});await evaluate('void (panel.runner.run=title_run_original)');await click(title_selector('refresh'));await wait('!panel.pending&&panel.container.dataset.state==="ready"');await assert_title_disabled(ready_buttons);
  await evaluate('window.title_saved_state=panel.state;window.title_saved_root=panel.root;panel.state=undefined;panel.update_scm_actions()');await assert_title_disabled({commit:true,refresh:false,graph:true,main:true});
  await evaluate(`panel.state=title_saved_state;panel.root=${JSON.stringify(other.replace(/\\/g,'/'))};panel.update_scm_actions()`);await assert_title_disabled({commit:true,refresh:false,graph:true,main:true});
  await evaluate('panel.root="";panel.update_scm_actions()');await assert_title_disabled(busy_buttons);
  await evaluate('panel.state=title_saved_state;panel.root=title_saved_root;panel.update_scm_actions()');await assert_title_disabled(ready_buttons);
  checks.push('read errors and invalid state disable both commit entries and Graph; an idle root keeps Refresh available for recovery, while no root disables it');

  // 原生 summary 的点击与键盘折叠不得由内部标题动作触发。
  await click('summary.git-scm-input-heading');assert.equal(await evaluate('panel.workbench.input_section.open'),false);
  await click(title_selector('refresh'));await wait('!panel.pending');assert.equal(await evaluate('panel.workbench.input_section.open'),false);
  await click(title_selector('graph'));assert.equal(await evaluate('panel.workbench.input_section.open'),false);
  await click('.git-scm-operation-menu');assert(await evaluate('!!document.querySelector("[data-action=worktrees]")'));assert.equal(await evaluate('panel.workbench.input_section.open'),false);await key('Escape');
  const empty_collapsed_calls=await evaluate('title_calls.quick.length');await click(title_selector('commit'));assert(await evaluate('panel.workbench.input_section.open&&!panel.workbench.changes_body.inert&&document.activeElement===panel.workbench.message'),'an empty collapsed commit reveals and focuses its editable message');assert.equal(await evaluate('title_calls.quick.length'),empty_collapsed_calls);assert.equal(git(root,['rev-parse','HEAD']),title_head);
  await click('summary.git-scm-input-heading');assert.equal(await evaluate('panel.workbench.input_section.open'),false);
  await evaluate('document.querySelector(".git-scm-input-heading").focus()');await key('Tab');assert.equal(await evaluate('document.activeElement.dataset.scmTitleAction'),'commit');assert(await evaluate('document.activeElement.matches(":focus-visible")'));await key('Enter');assert(await evaluate('panel.workbench.input_section.open&&!panel.workbench.changes_body.inert&&document.activeElement===panel.workbench.message'),'keyboard commit also reveals an empty collapsed input');assert.equal(await evaluate('title_calls.quick.length'),empty_collapsed_calls);
  await evaluate('document.querySelector(".git-scm-input-heading").focus()');await key('Tab');await key('Tab');assert.equal(await evaluate('document.activeElement.dataset.scmTitleAction'),'refresh');const keyboard_refresh=await evaluate('title_calls.refresh.length');await key('Enter');await wait('!panel.pending');assert.equal(await evaluate('title_calls.refresh.length'),keyboard_refresh+1);
  await evaluate('document.querySelector(".git-scm-input-heading").focus()');for(let i=0;i<3;i++)await key('Tab');assert.equal(await evaluate('document.activeElement.dataset.scmTitleAction'),'graph');const keyboard_graph=await evaluate('title_calls.graph.length');await key('Enter');assert.equal(await evaluate('title_calls.graph.length'),keyboard_graph+1);
  await key('Tab');assert(await evaluate('document.activeElement.matches(".git-scm-operation-menu")'));await key('Enter');assert(await evaluate('!!document.querySelector("[data-action=worktrees]")&&panel.workbench.input_section.open'));await key('Escape');
  checks.push('refresh, Graph, More and populated commits preserve collapse; empty commits reveal the input; all actions follow native Tab/Enter order with a visible focus ring');

  const title_layouts=[];
  for(const width of [180,240,380])for(const dark of [false,true]){
    await evaluate(`document.querySelector('#sidebar').style.width='${width}px';document.body.style.backgroundColor='${dark?'#202020':'#fff'}';document.documentElement.style.setProperty('--bg-color','${dark?'#202020':'#fff'}');document.documentElement.style.setProperty('--text-color','${dark?'#eee':'#222'}');document.documentElement.style.color='${dark?'#eee':'#222'}';panel.workbench.history.toolbar.update()`);await delay(100);
    win.webContents.sendInputEvent({type:'mouseMove',x:1000,y:700});await delay(100);
    const layout=await evaluate(`(()=>{const heading=document.querySelector('.git-scm-input-heading'),rect=heading.getBoundingClientRect(),label=heading.querySelector('.git-scm-input-title'),label_rect=label?.getBoundingClientRect(),nodes=[...heading.querySelectorAll('.git-scm-input-actions button')];const canvas=document.createElement('canvas');canvas.width=canvas.height=1;const context=canvas.getContext('2d',{willReadFrequently:true}),luminance=rgb=>rgb.slice(0,3).map(value=>value/255).map(value=>value<=.04045?value/12.92:((value+.055)/1.055)**2.4).reduce((sum,value,index)=>sum+value*[.2126,.7152,.0722][index],0);const icon_contrast=node=>{context.fillStyle='#fff';context.fillRect(0,0,1,1);const chain=[];for(let parent=node;parent;parent=parent.parentElement)chain.unshift(parent);for(const parent of chain){context.fillStyle=getComputedStyle(parent).backgroundColor;context.fillRect(0,0,1,1)}const background=luminance([...context.getImageData(0,0,1,1).data]);context.fillStyle=getComputedStyle(node.querySelector('svg')).color;context.fillRect(0,0,1,1);const foreground=luminance([...context.getImageData(0,0,1,1).data]);return (Math.max(background,foreground)+.05)/(Math.min(background,foreground)+.05)};return {overflow:heading.scrollWidth-heading.clientWidth,left:rect.left,right:rect.right,label_right:label_rect?.right||rect.left,buttons:nodes.map(node=>{const r=node.getBoundingClientRect(),svg=node.querySelector('svg').getBoundingClientRect();return {id:node.dataset.scmTitleAction||'more',left:r.left,right:r.right,width:r.width,height:r.height,svg_width:svg.width,svg_height:svg.height,color:getComputedStyle(node).color,contrast:icon_contrast(node),hit:node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}})};})()`);
    assert(layout.overflow<=1,JSON.stringify({width,dark,...layout}));assert(layout.label_right<=layout.buttons[0].left+1,JSON.stringify(layout));
    for(const [index,button]of layout.buttons.entries()){assert(Math.abs(button.width-22)<.1&&Math.abs(button.height-22)<.1,JSON.stringify(button));assert(Math.abs(button.svg_width-16)<.1&&Math.abs(button.svg_height-16)<.1,JSON.stringify(button));assert(button.hit,JSON.stringify(button));assert(button.contrast>=3,JSON.stringify(button));assert(button.left>=layout.left&&button.right<=layout.right+1,JSON.stringify(layout));if(index)assert(layout.buttons[index-1].right<=button.left+.1,JSON.stringify(layout));}
    title_layouts.push({width,dark,...layout});await capture(`changes_title_${width}_${dark?'dark':'light'}`);
  }
  fs.writeFileSync(path.join(temp,'changes_title_layouts.json'),JSON.stringify(title_layouts,null,2));checks.push('180/240/380 pixel light and dark headings retain four unobstructed 22px targets with 16px SVGs and no label overlap and readable icon contrast');
  await evaluate('window.title_disposed_buttons=[...document.querySelectorAll("[data-scm-title-action],.git-scm-commit")];window.title_dispose_calls=JSON.stringify(title_calls);panel.dispose();host.dispose()');
  assert.equal(await evaluate('document.querySelectorAll(".git-scm-sidebar").length'),0);assert(await evaluate('title_disposed_buttons.every(node=>node.disabled)'),'disposed title and main buttons remain disabled even when retained by a caller');await evaluate('for(const node of title_disposed_buttons){node.click();node.onclick?.(new MouseEvent("click",{cancelable:true}))}');assert.equal(await evaluate('JSON.stringify(title_calls)'),await evaluate('title_dispose_calls'));assert.equal(git(root,['rev-parse','HEAD']),title_head);
  checks.push('SCM lifetime releases observers, listeners and rows and disables retained title and main commit controls');
  console.log(JSON.stringify({status:'PASS',checks,evidence:temp},null,2));win.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(temp);if(win&&!win.isDestroyed()){await capture('failure');win.destroy();}app.exit(1);});
