// 使用生产弹窗与真实 Chromium 点击；隐藏窗口不产生操作系统焦点事件，focusin及宿主鼠标兼容路径以显式事件验证。
const {app,BrowserWindow}=require('electron'),{build}=require('esbuild');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_dismissal_'));app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();
let win;const checks=[],delay=ms=>new Promise(r=>setTimeout(r,ms)),run=code=>win.webContents.executeJavaScript(code);
const check=async(code,label)=>{const ok=await run(`Boolean(${code})`);checks.push({label,ok});};
const mouse=async(selector)=>{const p=await run(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()`);for(const type of ['mouseMove','mouseDown','mouseUp'])win.webContents.sendInputEvent({type,...p,button:'left',clickCount:1});await delay(70);};
const escape=async()=>{for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode:'Escape'});await delay(50);};
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1000,height:760,webPreferences:{offscreen:true,contextIsolation:false,nodeIntegration:true,backgroundThrottling:false}});
 const html=path.join(evidence,'test.html');fs.writeFileSync(html,'<!doctype html><style>#origin{position:absolute;left:20px;top:520px}#outside{position:absolute;left:300px;top:520px}#blank{position:absolute;left:20px;top:580px;width:200px;height:70px}.git-graph-dialog-shade{position:fixed;inset:0;z-index:10}.git-graph-dialog{position:absolute;left:200px;top:100px;width:300px;padding:20px;background:#eee}.git-graph-menu{z-index:20}</style><input id="origin" value="abcdef"><input id="outside" value="destination"><div id="blank"></div><div id="shadow"></div>');await win.loadFile(html);win.webContents.focus();
 const bundle=await build({stdin:{contents:'export {workspace_dialog,workspace_menu,dispose_workspace_widgets} from "./src/workspace_widgets";export {create_workspace_quick_open} from "./src/workspace_quick_open";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await run(bundle.outputFiles[0].text);
 await run(`window.origin_input=document.querySelector('#origin');window.outside=document.querySelector('#outside');window.opened_files=[];window.picker=qa.create_workspace_quick_open({context_root:()=>'',path_api:require('path'),open_file:async p=>opened_files.push(p),fs:require('fs')});window.open_picker=()=>{origin_input.focus();origin_input.setSelectionRange(2,4);picker.open();picker.input.dispatchEvent(new FocusEvent('focusin',{bubbles:true,composed:true}))};window.open_dialog=()=>{window.dialog=qa.workspace_dialog('Options');dialog.content.innerHTML='<input id="dialog-input"><div id="panel-blank" style="height:40px"></div>';};void 0`);
 await run('open_picker();void 0');await mouse('#outside');await check(`picker.root.hidden&&document.activeElement===outside`,'Outside pointer dismisses file picker and focuses destination on first click');
 await run(`open_picker();for(const type of ['mousedown','mouseup'])outside.dispatchEvent(new MouseEvent(type,{bubbles:true,cancelable:true}));void 0`);await check(`picker.root.hidden`,'Host mousedown-only path dismisses file picker');await run('picker.close();void 0');
 await run(`open_picker();outside.focus();outside.dispatchEvent(new FocusEvent('focusin',{bubbles:true,composed:true}));void 0`);await delay(25);await check(`picker.root.hidden&&document.activeElement===outside`,'Host focusin event outside dismisses file picker without restoring original selection');await run('picker.close();void 0');
 await run('origin_input.focus();open_dialog();void 0');await delay(30);await mouse('#blank');await check(`!document.querySelector('.git-graph-dialog-shade')`,'Dialog backdrop is cancel, never confirmation');await run('dialog.close();void 0');
 await run('open_picker();void 0');await mouse('.workspace-quick-open-input-row');await check(`!picker.root.hidden`,'Clicking picker input stays open');await run(`picker.root.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));void 0`);await check(`!picker.root.hidden`,'Blank padding inside picker is inside its boundary');await escape();await check(`picker.root.hidden&&document.activeElement===origin_input&&origin_input.selectionStart===2&&origin_input.selectionEnd===4`,'Escape restores the original input and selection');
 await run('open_dialog();void 0');await delay(30);await mouse('#panel-blank');await check(`!!document.querySelector('.git-graph-dialog-shade')`,'Blank area inside dialog remains interactive');await run(`window.menu_close=qa.workspace_menu(new MouseEvent('contextmenu',{clientX:650,clientY:60}),[{title:'Child',action(){},children:[{title:'Leaf',action(){}}]}]);void 0`);await mouse('#dialog-input');await check(`!document.querySelector('.git-graph-menu')&&!!document.querySelector('.git-graph-dialog-shade')&&document.activeElement.id==='dialog-input'`,'One physical gesture closes menu only and enters underlying dialog');await escape();
 await run('open_dialog();void 0');await delay(30);await run(`window.child=qa.workspace_dialog('Child');child.content.innerHTML='<input id="child-input">';void 0`);await delay(30);await mouse('#blank');await check(`document.querySelectorAll('.git-graph-dialog-shade').length===1`,'Pointer, mouse compatibility and focus events do not cascade through nested dialogs');await escape();
 await run(`window.shadow=document.querySelector('#shadow').attachShadow({mode:'open'});shadow.innerHTML='<input>';open_picker();shadow.querySelector('input').focus();shadow.querySelector('input').dispatchEvent(new FocusEvent('focusin',{bubbles:true,composed:true}));void 0`);await delay(30);await check(`picker.root.hidden&&shadow.activeElement===shadow.querySelector('input')`,'Host focusin event into external Shadow DOM cancels without stealing it');
 await run(`open_dialog();dialog.content.append(document.querySelector('#shadow'));shadow.querySelector('input').focus();void 0`);await delay(30);await check(`!!document.querySelector('.git-graph-dialog-shade')`,'Shadow DOM input inside dialog does not dismiss');await run(`window.dispatchEvent(new Event('blur'));void 0`);await check(`!!document.querySelector('.git-graph-dialog-shade')`,'System color picker window blur does not cancel a settings dialog');await escape();
 await run(`open_picker();window.dispatchEvent(new Event('blur'));void 0`);await check(`picker.root.hidden`,'File quick input cancels on window blur');
 await run(`origin_input.focus();window.menu_close=qa.workspace_menu(new MouseEvent('contextmenu',{clientX:650,clientY:60}),[{title:'Child',action(){},children:[{title:'Leaf',action(){}}]}]);void 0`);for(const type of ['keyDown','keyUp'])win.webContents.sendInputEvent({type,keyCode:'Right'});await delay(35);await check(`document.querySelectorAll('.git-graph-menu').length===2`,'Focusing child menu is within the menu family');await escape();await check(`document.querySelectorAll('.git-graph-menu').length===1`,'Escape first returns from child to parent');await mouse('#outside');await check(`!document.querySelector('.git-graph-menu')&&document.activeElement===outside`,'Outside click closes all menus in the same family');
 await run(`picker.dispose();window.resolve_scan=undefined;window.picker=qa.create_workspace_quick_open({context_root:()=>'/work',path_api:require('path'),open_file:async p=>opened_files.push(p),fs:{promises:{readdir:()=>new Promise(r=>resolve_scan=r)}}});picker.open();void 0`);await mouse('#outside');await run(`resolve_scan([{name:'late.md',isFile:()=>true,isDirectory:()=>false}]);void 0`);await delay(100);await check(`picker.root.hidden&&!picker.root.querySelector('.workspace-quick-open-result')&&!opened_files.length`,'Late directory results cannot reopen a cancelled search or open a file');
 await run(`picker.dispose();qa.dispose_workspace_widgets();window.leaked=0;window.addEventListener('keyup',e=>{if(e.key==='Escape')leaked++});void 0`);await escape();await check(`leaked===1`,'Disposed layers leave ordinary Escape with the application');
 fs.writeFileSync(path.join(evidence,'checks.json'),JSON.stringify(checks,null,2));console.log(JSON.stringify({checks,evidence}));assert(checks.every(x=>x.ok),checks.filter(x=>!x.ok).map(x=>x.label).join('\n'));win.destroy();app.exit(0);
}).catch(e=>{console.error(e);console.error(evidence);win?.destroy();app.exit(1)});
