const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{build}=require('esbuild');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'typora_community_ui_'));app.setPath('userData',path.join(base,'profile'));app.disableHardwareAcceleration();let win;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),checks=[];
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:920,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 win.webContents.on('console-message',event=>console.log('renderer:',event.message));
 await win.loadURL('data:text/html,<html><head></head><body><div id="typora-sidebar"><div id="sidebar-content" style="height:calc(100vh - 40px);width:260px"></div></div><button id="outside">outside</button></body></html>');
 const ev=async s=>{try{return await win.webContents.executeJavaScript(s)}catch(error){console.error('Renderer expression:',s);throw error}},check=async(label,s)=>{assert(await ev(s),label);checks.push(label);};
 const bundle=await build({entryPoints:[path.join(__dirname,'../src/community_plugins.ts')],bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await ev(bundle.outputFiles[0].text);
 await ev(`
 const css=document.createElement('style');css.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../dist/workspace.css'),'utf8'))};document.head.append(css);
 window._options={userDataPath:${JSON.stringify(base)},appVersion:'1.14.10'};window.records=[{id:'example.plugin',name:'示例插件',description:'完整描述',version:'1.0.0',repo:'example/plugin',enabled:false,running:false}];window.listeners=new Set();window.calls=[];window.disposed_count=0;
 window.fake={list:()=>records,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},start:async()=>{},dispose:async()=>{disposed_count++},catalog:async()=>[{id:'example.remote',name:'远程插件',description:'目录描述',repo:'example/remote'}],latest:async()=>({version:'1.0.0'}),set_enabled:async(id,value)=>{calls.push([id,value]);Object.assign(records.find(r=>r.id===id),{enabled:value,running:value});listeners.forEach(fn=>fn())},install_online:async(info)=>{records.push({...info,version:'1.0.0',enabled:false});listeners.forEach(fn=>fn())},uninstall:async(id)=>{records=records.filter(r=>r.id!==id);listeners.forEach(fn=>fn())}};
 window.reqnode=name=>name.endsWith('community_plugin_service.cjs')?{create_community_service:()=>fake,compare_version:()=>0}:name.endsWith('workspace_update_service.cjs')?{}:require(name);
 window.sidebar={activePanel:null,panel:null,addPanel(panel){this.panel=panel;return()=>{panel.containerEl.remove();panel.onhide();this.panel=null}},show(){this.activePanel=this.panel;document.querySelector('#sidebar-content').append(this.panel.containerEl);this.panel.onshow()},hide(){this.panel.containerEl.remove();this.panel.onhide()},switch(){this.show()}};
 window.commands={};window[Symbol.for('typora-code:workspace')]={SidebarPanel:class{addRibbonButton(button){this.ribbonButton=button}},app:{workspace:{sidebar},commands:{register(command){commands[command.id]=command.callback;return()=>delete commands[command.id]}}},Notice:class{}};
 const saved_require=reqnode;window.reqnode=name=>name.endsWith('community_plugin_service.cjs')?{create_community_service(){throw Error('配置目录不可写')}}:saved_require(name);
 window.preflight_failure=false;try{qa.bind_community_plugins()}catch{preflight_failure=true;}window.reqnode=saved_require;void 0;
 `);
 await check('服务初始化失败不留下ABI、命令或样式','preflight_failure&&!window[Symbol.for("typora-plugin-core@v2")]&&!Object.keys(commands).length&&!document.getElementById("typora-code-style:community_plugins")');
 await ev(`window.binding=qa.bind_community_plugins();commands['typora_code:community_plugins']();void 0;
 `);await pause(100);
 await check('社区配置同引用对象触发保存且默认对象跨实例独立',`(()=>{class Base{setDefault(value){this.data=value}get(key){return this.data[key]}set(key,value){if(this.get(key)!==value){this.data[key]=value;this.changes=(this.changes||0)+1}}}const Settings=qa.community_settings_class(Base),a=new Settings(),b=new Settings(),defaults={nested:{value:1}};a.setDefault(defaults);b.setDefault(defaults);const changed=a.get('nested');changed.value=2;a.set('nested',changed);return a.changes===1&&b.get('nested').value===1&&defaults.nested.value===1;})()`);
 const click=async text=>{await ev(`[...document.querySelectorAll('.workspace-community-manager button')].find(n=>n.textContent===${JSON.stringify(text)}).click();void 0`);await pause(40);};
 await ev(`const host_style=document.createElement('style');host_style.textContent='header {position:absolute;top:0} input {display:block}';document.head.append(host_style);void 0`);
 await check('宿主header/input规则不覆盖标题或显示隐藏ZIP控件',`getComputedStyle(document.querySelector('input[type=file]')).display==='none'&&document.querySelector('.workspace-community-title').getBoundingClientRect().bottom<=document.querySelector('.workspace-community-manager').getBoundingClientRect().top`);
 await check('管理页显示信任边界与已安装插件',`document.querySelector('.workspace-community-manager').textContent.includes('进程权限')&&document.querySelectorAll('.workspace-community-row').length===1`);
 await click('信任并启用');await check('启用只调用服务一次并显示最新状态','calls.length===1&&records[0].enabled&&document.querySelector(".workspace-community-row").textContent.includes("已启用")');
 await click('停用');await check('停用更新状态','calls.length===2&&!records[0].enabled');
 await ev(`const input=document.querySelector('input[type=search]');input.value='不存在';input.dispatchEvent(new Event('input'));void 0`);await check('搜索过滤当前插件','!document.querySelector(".workspace-community-row")');
 await ev(`document.querySelector('input[type=search]').value='';document.querySelector('input[type=search]').dispatchEvent(new Event('input'));void 0`);
 await click('社区插件市场');await click('安装');await check('安装直接转到已安装且明确下一步',`document.querySelector('.workspace-community-message').textContent.includes('默认停用')&&document.querySelector('.workspace-community-toolbar button[aria-pressed=true]').textContent==='已安装'`);await click('已安装');await check('在线安装完成保持停用','records.length===2&&!records[1].enabled');
 await ev(`window.saved_catalog=fake.catalog;fake.catalog=async()=>{throw Error('网络失败验收')};void 0`);await click('社区插件市场');await click('刷新目录');await check('网络错误可见且恢复控件','document.querySelector(".workspace-community-message").textContent.includes("网络失败验收")&&![...document.querySelectorAll(".workspace-community-toolbar button")].some(n=>n.disabled)');
 for(const theme of ['light','dark']){await ev(`document.documentElement.dataset.workspaceFileIconTheme='${theme}';void 0`);win.webContents.setZoomFactor(1.25);await pause(40);await check(theme+'缩放时管理窗口仍在视口内',`(()=>{const r=document.querySelector('.workspace-community-sidebar').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1})()`);}
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(60);await check('Escape不销毁常驻扩展面板','!!document.querySelector(".workspace-community-manager")&&listeners.size===1');
 await click('已安装');
 await ev(`window.saved_manager=document.querySelector('.workspace-community-manager');window.saved_search=saved_manager.querySelector('input[type=search]');saved_search.value='示例';saved_search.dispatchEvent(new Event('input'));for(let i=0;i<20;i++){sidebar.hide();commands['typora_code:community_plugins']();}void 0`);
 await check('20次侧栏显隐保留筛选与单个订阅','saved_manager===document.querySelector(".workspace-community-manager")&&saved_search.value==="示例"&&listeners.size===1');
 await ev(`window.tab_counts={load:0,show:0,hide:0,unload:0};window.setting_tab={name:'示例配置',containerEl:document.createElement('div'),load(){tab_counts.load++},show(){tab_counts.show++;this.containerEl.innerHTML='<input aria-label="示例值" value="保留">'},hide(){tab_counts.hide++},unload(){tab_counts.unload++}};window.unregister_tab=window[Symbol.for('typora-code:workspace')].app.community_plugins.register_setting_tab('example.plugin',setting_tab);commands['typora_code:community_plugin_settings']();void 0`);
 await check('设置选择页显示真实已注册插件','document.querySelector(".workspace-community-setting-list").textContent.includes("示例插件")');
 await ev(`document.querySelector('.workspace-community-setting-list button').click();void 0`);await pause(20);
 await check('设置入口打开同一SettingTab','document.querySelector(".workspace-community-settings input").value==="保留"&&tab_counts.show===1');
 await click('设置');await check('重复设置入口不搬移节点或创建第二弹窗','document.querySelectorAll(".workspace-community-settings").length===1&&tab_counts.show===1');
 await ev(`unregister_tab();unregister_tab();void 0`);await check('停用注销关闭配置且卸载仅一次','!document.querySelector(".workspace-community-settings")&&tab_counts.unload===1');
 await ev(`commands['typora_code:community_plugin_settings']();void 0`);await check('无可配置插件时说明状态','document.querySelector(".workspace-community-setting-list").textContent.includes("尚未启用" )');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(60);
 await check('真实Escape只关闭插件设置并保留侧栏','!document.querySelector(".workspace-community-settings")&&!!document.querySelector(".workspace-community-manager")');
 await ev(`commands['typora_code:community_plugins']();window.finish_catalog=undefined;fake.catalog=()=>new Promise(resolve=>finish_catalog=resolve);void 0`);await click('社区插件市场');await click('刷新目录');await check('异步期间防重复动作','[...document.querySelectorAll(".workspace-community-toolbar button")].every(n=>n.disabled)');
 await ev(`binding.dispose();finish_catalog([]);void 0`);await pause(60);await check('销毁后迟到结果不重开窗口且ABI清理','!document.querySelector(".workspace-community-manager")&&disposed_count===1&&!window[Symbol.for("typora-plugin-core@v2")]&&Object.keys(commands).length===0&&listeners.size===0');
 await ev(`records=[];fake.catalog=async()=>[{id:'example.catalog',name:'真实目录端口',description:'选择安装',author:'作者检索词',repo:'example/catalog',platforms:['win32']},{id:'example.mac',name:'另一系统',description:'不可装',repo:'example/mac',platforms:['darwin']}];window.second=qa.bind_community_plugins();commands['typora_code:community_plugins']();void 0`);await pause(60);
 await check('空安装首次自动加载社区市场而非空白已安装',`document.querySelector('.workspace-community-toolbar button[aria-pressed=true]').textContent==='社区插件市场'&&document.querySelectorAll('.workspace-community-row').length===2`);
 await check('不支持当前系统的包禁用安装并说明原因',`[...document.querySelectorAll('.workspace-community-row')].find(n=>n.textContent.includes('另一系统')).querySelector('button').disabled`);
 await ev(`document.querySelector('input[type=search]').value='作者检索词';document.querySelector('input[type=search]').dispatchEvent(new Event('input'));void 0`);
 await check('作者筛选及真实仓库说明可见',`document.querySelectorAll('.workspace-community-row').length===1&&document.querySelector('.workspace-community-source').href==='https://github.com/example/catalog'`);
 await ev(`commands['typora_code:community_plugin_settings']();[...document.querySelectorAll('.workspace-community-settings button')].find(n=>n.textContent==='浏览社区插件市场').click();void 0`);
 await check('空设置可以直接返回社区市场选择插件',`!document.querySelector('.workspace-community-settings')&&document.querySelectorAll('.workspace-community-row').length===2`);
 await ev(`second.dispose();void 0`);
 console.log(JSON.stringify({status:'PASS',checks,evidence:base,scope:'真实Chromium窗口/键盘、共享对话框与服务端口替身'}));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);win?.destroy();app.exit(1)});
