// 真实Monaco/TextMate/clangd组合；不以协议替身替代最终绘制。
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_code_analysis_')),checks=[],samples=[];let win;
app.setPath('userData',path.join(root,'profile'));app.disableHardwareAcceleration();
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const ev=source=>win.webContents.executeJavaScript(source);
const wait=async expression=>{for(let i=0;i<250;i++){if(await ev(expression))return;await delay(50);}throw Error('Timeout: '+expression+' '+await ev('JSON.stringify(window.state||window.errors)'));};
const code=['// 中文 😀','#define VALUE 7','typedef unsigned int port_t;','struct device { int state; };','int real(int arg) { return arg + VALUE; }',''].join('\n');
fs.writeFileSync(path.join(root,'source.c'),code);
app.whenReady().then(async()=>{
 const bundle=await require('esbuild').build({plugins:require('./editor_bundle.cjs').editor_plugins(),stdin:{contents:`export {git_diff_editor} from './src/git_diff_editor';export * from './src/monaco_code_theme';export * from './src/reading_code_theme';export * from './src/source_semantic_tokens';export * from './src/workspace_document_symbols';export * from './src/language_service_settings';export * as monaco from 'monaco-editor/editor/editor.api';`,resolveDir:base},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});
 fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><style>:root{--workspace-code-theme:dark_2026}body{margin:0;background:#121314;color:#bbbebf}.git-monaco-body{height:330px}.git-graph-document{width:900px}</style><body>');
 win=new BrowserWindow({show:false,width:1100,height:850,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});win.webContents.on('console-message',details=>console.log(details.message));await win.loadFile(path.join(root,'index.html'));
 await ev(`window.reqnode=name=>require(name);window.errors=[];addEventListener('error',e=>errors.push(String(e.error)));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));window.data={};window[Symbol.for('typora-code:workspace')]={app:{settings:{get:key=>data[key],set_and_save:(key,value)=>{data[key]=value}}}};void 0`);
 await ev(bundle.outputFiles[0].text);
 await ev(`window.source=new qa.git_diff_editor({title:'source.c',file:${JSON.stringify(path.join(root,'source.c'))},left:${JSON.stringify(code)}});document.body.append(source.container);window.preview=new qa.git_diff_editor({title:'preview.c',file:'preview.c',left:${JSON.stringify(code)}});document.body.append(preview.container);source.focused_editor().updateOptions({readOnly:false});window.model=source.models[0];window.selection={startLineNumber:5,startColumn:5,endLineNumber:5,endColumn:9};source.focused_editor().setSelection(selection);void 0`);
 await ev('qa.initialize_monaco_code_theme()');await delay(150);
 const themes=require('../vendor/vscode_themes/resolved.json');
 for(const mode of ['dark_2026','light_2026','dark','light']){
  await ev(`document.documentElement.style.setProperty('--workspace-code-theme',${JSON.stringify(mode)});document.documentElement.dataset.workspaceColors=${JSON.stringify(mode.startsWith('dark')?'dark':'light')};document.body.style.background=${JSON.stringify(themes[mode].colors['editor.background'])};qa.sync_monaco_code_theme();void 0`);await delay(180);
  const values=await ev(`(()=>{model.tokenization.forceTokenization(model.getLineCount());const line=model.tokenization.getLineTokens(5);return {background:getComputedStyle(source.container.querySelector('.monaco-editor-background')).backgroundColor,preview:getComputedStyle(preview.container.querySelector('.monaco-editor-background')).backgroundColor,font:source.focused_editor().getOption(qa.monaco.editor.EditorOption.fontInfo).fontFamily,selection:source.focused_editor().getSelection(),tokens:Array.from({length:line.getCount()},(_,i)=>({text:line.getLineContent().slice(line.getStartOffset(i),line.getEndOffset(i)),fg:line.getForeground(i)}))}})()`);
  const hex=themes[mode].colors['editor.background'],rgb='rgb('+[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)).join(', ')+')';assert.equal(values.background,rgb);assert.equal(values.preview,rgb);assert.equal(values.selection.startColumn,5);assert(new Set(values.tokens.map(t=>t.fg)).size>=3,'real TextMate categories');samples.push({mode,...values});
 }
 const language_samples={rust:'pub fn twice(value: i32) -> i32 { value * 2 } // comment',python:'def greet(value):\n    return "Hello" + str(value) # comment',java:'public class Sample { int twice(int value) { return value * 2; } } // comment',shell:'greet() { echo "hello $1"; } # comment',powershell:'function Get-Greeting { param([string]$Name) "Hello $Name" } # comment',csharp:'public class Sample { int Twice(int value) { return value * 2; } } // comment'};
 for(const [language,text] of Object.entries(language_samples)){
  const colors=await ev(`(async()=>{await qa.monaco.languages.getLanguages().find(item=>item.id===${JSON.stringify(language)})?.loader?.();const sample=qa.monaco.editor.createModel(${JSON.stringify(text)},${JSON.stringify(language)});await new Promise(resolve=>setTimeout(resolve,100));sample.tokenization.forceTokenization(sample.getLineCount());const colors=new Set();for(let line=1;line<=sample.getLineCount();line++){const tokens=sample.tokenization.getLineTokens(line);for(let i=0;i<tokens.getCount();i++)colors.add(tokens.getForeground(i));}sample.dispose();return [...colors];})()`);assert(colors.length>=3,language+'基础语法分类');samples.push({language,lexical_colors:colors});
 }
 checks.push('Python Java Bash PowerShell C# Rust actual Monaco lexical tokenization');
 checks.push('four official palettes rendered in source and preview; C TextMate tokens, selection and font retained');
 await ev(`document.documentElement.style.setProperty('--workspace-code-theme','dark_2026');qa.sync_monaco_code_theme();window.binding=qa.subscribe_document_symbols(model,${JSON.stringify(path.join(root,'source.c'))},${JSON.stringify(root)},value=>window.state=value);void 0`);
 await wait('state&&!state.loading&&qa.source_semantics(model)?.data.length>0');await delay(700);
 const semantic=await ev(`(()=>{const value=qa.source_semantics(model),encoded=qa.convert_semantic_tokens(value),line=model.tokenization.getLineTokens(5);return {provider:state.provider,types:value.token_types,count:encoded.length/5,line:Array.from({length:line.getCount()},(_,i)=>({text:line.getLineContent().slice(line.getStartOffset(i),line.getEndOffset(i)),fg:line.getForeground(i)})),complete:model.tokenization.hasCompleteSemanticTokens()}})()`);
 assert.equal(semantic.provider,'clangd');assert(semantic.types.includes('parameter'));assert(semantic.count>5);assert(semantic.complete,'Monaco consumes semantic tokens');samples.push({semantic});checks.push('real clangd semantic legend and ranges consumed by Monaco');
 await ev(`source.focused_editor().executeEdits('test',[{range:{startLineNumber:6,startColumn:1,endLineNumber:6,endColumn:1},text:'int unsaved_only;\\n'}]);void 0`);await wait('state.symbols.some(s=>s.name==="unsaved_only")&&!state.loading');assert.equal(fs.readFileSync(path.join(root,'source.c'),'utf8'),code);checks.push('unsaved text reanalysis preserves disk');
 await ev(`qa.save_language_service_profiles(${JSON.stringify(root)},'user',{c:{provider:'disabled'}});void 0`);await wait('state.provider==="disabled"&&!state.loading');assert(await ev('!qa.source_semantics(model)'));checks.push('settings change cancels analysis and clears obsolete semantic colors');
 await ev('binding.dispose();source.dispose();preview.dispose();void 0');assert.equal(await ev('qa.monaco.editor.getModels().length'),0);assert.deepEqual(await ev('errors'),[]);checks.push('model disposal and no unhandled errors');
 fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks,samples},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence:root}));win.destroy();app.exit(0);
}).catch(error=>{fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'FAIL',checks,samples,error:String(error.stack)},null,2));console.error(error);win?.destroy();app.exit(1);});
