// 真实 Electron 运行常驻工作台入口与全部编排模块；宿主核心仅提供可核查的注册表和原生文件容器。
const { app, BrowserWindow } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { build } = require('esbuild');
const { editor_plugins } = require('./editor_bundle.cjs');
const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_workspace_startup_'));
const repository=path.join(evidence,'repository');fs.mkdirSync(repository);
const source_path = path.join(repository, 'source.ts');fs.writeFileSync(source_path, 'const original = 1;\n');
const git=(...args)=>require('node:child_process').execFileSync('git',args,{cwd:repository,windowsHide:true,stdio:'pipe'});fs.writeFileSync(path.join(repository,'second.ts'),'const second = 2;\n');git('init','-b','main');git('add','source.ts','second.ts');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture');
app.setPath('userData', path.join(evidence, 'profile'));app.disableHardwareAcceleration();
let test_window;const checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async source=>{try{return await test_window.webContents.executeJavaScript(source)}catch(error){console.error("Failed renderer expression: "+source.slice(0,600));throw error}};
const capture=async name=>{await delay(100);fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());};
const wait=async source=>{for(let i=0;i<200;i++){if(await evaluate(source))return;await delay(30);}throw new Error('Timeout: '+source+'; '+await evaluate('JSON.stringify({errors:fixture_errors,state:document.documentElement.dataset.linuxNoteTyporaEnhancements})'));};
app.whenReady().then(async()=>{
 await (await import("./build_source_symbol_assets.mjs")).build_source_symbol_assets(path.join(evidence,"typora_code"));
 require("electron").ipcMain.handle("setting.put",(_event,key,value)=>{assert.equal(key,"framelessWindow");assert.equal(value,true);return true;});
 const {build_workspace_styles,static_workspace_css_plugin}=await import(require('node:url').pathToFileURL(path.join(__dirname,'build_workspace_styles.mjs')).href);await build_workspace_styles({outdir:evidence});
 test_window=new BrowserWindow({show:false,width:1100,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,`<!doctype html><meta charset="utf-8"><link id="typora-code-workspace-styles" rel="stylesheet" href="workspace.css"><style>html,body{height:100%;margin:0;overflow:hidden;font:13px "Segoe UI",sans-serif;--bg-color:#fff;--text-color:#333}#typora-sidebar{position:absolute;left:48px;top:35px;width:240px;bottom:22px}#sidebar-content{position:absolute;inset:0}.typ-ribbon{width:48px;position:absolute;inset:0 auto 22px 0}.typ-ribbon-item{height:48px;display:flex;align-items:center;justify-content:center}.typ-ribbon-item svg{width:24px;height:24px}.typ-ribbon>.group.top{flex:1}.typ-ribbon{display:flex;flex-direction:column}.typ-workspace-tabs{height:100%;min-height:0}.typ-workspace-root{position:absolute;top:35px;left:288px;right:0;bottom:22px}content{height:100%;overflow:auto;display:block}.typ-workspace-tab-content{height:calc(100% - 35px)}.typ-tabs{display:flex;height:35px}.typ-tab{display:flex;align-items:center;padding:0 12px;border-right:1px solid #8884}.typ-tab.active{border-top:1px solid #007fd4}.typ-workspace-tab-content>.linux-note-git-graph,.typ-workspace-tab-content>.linux-note-source-editor{height:100%;min-height:0}#write{font:16px/1.6 sans-serif;padding:30px;box-sizing:border-box}footer{position:absolute;bottom:0;left:288px;right:0;height:22px}</style><body class="unibody-window show-footer"><div id="top-titlebar"><span id="w-titlebar-left"><span id="title-text">fixture</span></span><span id="w-traffic-lights"><span class="btn toolbar-icon" id="w-min">_</span><span id="w-max-group"><span class="btn toolbar-icon" id="w-max">□</span></span><span class="btn toolbar-icon" id="w-restore">▣</span><span class="btn toolbar-icon" id="w-close">×</span></span></div><aside class="typ-ribbon"><div class="group top"><div class="typ-ribbon-item" data-id="core.file-explorer"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M8 3h12v16H8zM4 7v16h12"/></svg></div><div class="typ-ribbon-item" data-id="core.search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="10" cy="10" r="7"/><path d="m15 15 7 7"/></svg></div><div class="typ-ribbon-item" data-id="core.outline">Outline</div></div><div class="group bottom"></div></aside><aside id="typora-sidebar"><div id="sidebar-content"><div id="native-outline-home"><div id="outline-content"><div class="outline-item"><span class="outline-label">Native Markdown</span></div></div><span id="outline-anchor"></span></div></div><div id="ty-sidebar-footer"></div></aside><div id="typora-sidebar-resizer"></div><main class="typ-workspace-root"><div class="typ-workspace-tabs"><div class="typ-workspace-tab-header"><div class="typ-tabs"></div></div><div class="typ-workspace-tab-content"><content><div id="write"><h1 cid="n1">Native Markdown</h1></div></content></div></div></main><footer class="ty-footer"><span class="footer-item-right">words</span></footer>`);
 await test_window.loadFile(html);
 await evaluate(`window.fixture_root=${JSON.stringify(repository)};window.fixture_source=${JSON.stringify(source_path)};`);
 await evaluate(fs.readFileSync(path.join(__dirname,'../fixtures/workspace_host.js'),'utf8'));await evaluate(`window._options.userDataPath=${JSON.stringify(evidence)};void 0`);await evaluate('window.original_outline=document.querySelector("#outline-content");window.original_outline_parent=original_outline.parentNode');
 const bundle=await build({stdin:{contents:'export {start_typora_code,shutdown_typora_code} from "./src/workspace_startup";export {get_workspace_files} from "./src/workspace_files";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},plugins:[static_workspace_css_plugin(),...editor_plugins()],bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text','.svg':'text','.png':'dataurl','.wasm':'binary'},define:{'process.env.NODE_ENV':'"production"'}});
 await evaluate(bundle.outputFiles[0].text);
 // Monaco 的 ContextKey/Clipboard 单例是宿主窗口级；先显式预热并销毁临时 editor，避免把首次惰性初始化误算为插件泄漏。
 await evaluate('(()=>{const node=document.createElement("div");document.body.append(node);const editor=qa.monaco.editor.create(node,{value:"warmup",language:"plaintext"});const model=editor.getModel();editor.dispose();model.dispose();node.remove();})()');await delay(50);
 await evaluate('window.baseline_listeners=fixture_listener_count();void qa.start_typora_code().catch(error=>{fixture_errors.push(String(error));console.error(error)});void 0');
 await delay(80);
 assert.equal(await evaluate('document.documentElement.dataset.linuxNoteWorkspace'),'loading');
 await evaluate('qa.shutdown_typora_code();void qa.start_typora_code().catch(error=>{fixture_errors.push(String(error));console.error(error)});fixture_core.app.settings=fixture_settings;void 0');
 await delay(150);
 assert.equal(await evaluate('document.documentElement.dataset.linuxNoteTyporaEnhancements'),'loading');
 assert.equal(await evaluate('fixture_commands.size'),0,'waiting for disconnected root must not register workbench commands');
 await evaluate('qa.shutdown_typora_code();void qa.start_typora_code().catch(error=>{fixture_errors.push(String(error));console.error(error)});document.body.append(fixture_root_element);void 0');
 await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"');
 assert.equal(await evaluate('fixture_errors.length'),0,await evaluate('fixture_errors.join("\\n")'));
 assert(await evaluate('fixture_commands.has("linux_note:terminal")&&fixture_commands.has("linux_note:search")&&fixture_factories.has("linux_note.source_file")'));
 assert(await evaluate('[...fixture_registration_counts.values()].every(count=>count===1)'),'aborted initialization callbacks must not create duplicate registrations');
 checks.push('aborting while core settings and then root mount are pending leaves only the latest startup generation active');
 // Real workspace_files save path: native load completes after tab selection, not inside toggleTab.
 await evaluate('window.saved_native_paths=[];window.original_native_save=ClientCommand.save;ClientCommand.save=()=>saved_native_paths.push(File.bundle.filePath);window.native_target=fixture_native_leaf.state.path;File.bundle.filePath="previous.md";fixture_core.app.workspace.activeLeaf=fixture_native_leaf;window.native_save_done=false;window.native_save_promise=qa.get_workspace_files().save_active().then(value=>{native_save_done=true;return value});void 0');
 await delay(50);assert.deepEqual(await evaluate('saved_native_paths'),[]);assert(!await evaluate('native_save_done'));
 await evaluate('File.bundle.filePath=native_target;fixture_emit("file:open","previous.md");void 0');await delay(30);assert(!await evaluate('native_save_done'),'matching bundle path without the matching load event cannot save');
 await evaluate('fixture_emit("file:open",native_target);void 0');assert(await evaluate('native_save_promise'));assert.deepEqual(await evaluate('saved_native_paths'),[await evaluate('native_target')]);
 await evaluate('File.bundle.filePath="previous.md";fixture_core.app.workspace.activeLeaf=fixture_native_leaf;window.cancelled_save=qa.get_workspace_files().save_leaf(fixture_native_leaf);fixture_core.app.workspace.activeLeaf=null;fixture_emit("file:open",native_target);void 0');assert.equal(await evaluate('cancelled_save'),false,'user selection cancels pending native save even if its load event arrives later');assert.equal(await evaluate('saved_native_paths.length'),1);
 await evaluate('window.activated_save=qa.get_workspace_files().save_leaf(fixture_native_leaf);void 0');await delay(30);assert(await evaluate('fixture_core.app.workspace.activeLeaf===fixture_native_leaf'));assert.equal(await evaluate('saved_native_paths.length'),1,'save_leaf activates the target but never saves before its asynchronous load completes');
 await evaluate('File.bundle.filePath=native_target;fixture_emit("file:open",native_target);void 0');assert(await evaluate('activated_save'));assert.equal(await evaluate('saved_native_paths.length'),2);
 await evaluate('window.original_is_editor=fixture_native_leaf.view.isEditor;fixture_native_leaf.view.isEditor=()=>false;void 0');assert.equal(await evaluate('qa.get_workspace_files().save_leaf(fixture_native_leaf)'),false,'read-only Markdown preview must not save another native editor');assert.equal(await evaluate('saved_native_paths.length'),2);await evaluate('fixture_native_leaf.view.isEditor=original_is_editor;void 0');
 await evaluate('fixture_core.app.workspace.activeLeaf=fixture_native_leaf;File.bundle.filePath=native_target;fixture_emit("file:open",native_target);ClientCommand.save=original_native_save;void 0');
 checks.push('native saves wait for the matching loaded path and abort on user selection instead of saving the previous Markdown');

 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');
 assert(await evaluate('!document.querySelector(".workspace-explorer-outline-content")'),'Explorer contains no duplicate bottom Outline section');
 await capture('plugin_explorer_default');
 const open_outline_menu=async()=>{await evaluate('fixture_commands.get("linux_note:outline").callback();void 0');await wait('fixture_core.app.workspace.sidebar.activePanel?.ribbonButton?.id==="core.outline"&&fixture_core.app.workspace.sidebar.isShown');};
 await open_outline_menu();
 assert(await evaluate('document.querySelector("#outline-content")===original_outline&&original_outline.parentNode===original_outline_parent&&document.querySelector(".workspace-outline-empty").hidden'),'Markdown uses the identical native outline node in its original parent');
 await evaluate('window.outline_leaf=fixture_core.app.workspace.activeLeaf;window.outline_scroll=document.querySelector("content").scrollTop;[...document.querySelectorAll(".typ-ribbon-item")].find(item=>item.dataset.id==="core.outline").click();void 0');
 assert(await evaluate('!fixture_core.app.workspace.sidebar.isShown'), 'same Outline activity toggles sidebar closed');
 await open_outline_menu();await open_outline_menu();
 assert(await evaluate('fixture_core.app.workspace.sidebar.isShown&&fixture_core.app.workspace.activeLeaf===outline_leaf&&document.querySelector("content").scrollTop===outline_scroll'), 'repeated Outline command keeps the same document and reading position');
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');
 await wait('document.querySelectorAll(".workspace-explorer-row").length>=2');await evaluate('[...document.querySelectorAll(".workspace-explorer-row")].find(row=>row.dataset.path===fixture_source).click();void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 await evaluate('window.first_source=fixture_core.app.workspace.activeLeaf;void 0');assert(await evaluate('!first_source.state.workspace_preview'),'frozen Explorer single click keeps its editor open');
 await evaluate('[...document.querySelectorAll(".workspace-explorer-row")].find(row=>row.dataset.path.endsWith("second.ts")).click();void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 assert(await evaluate('fixture_leaves.includes(first_source)&&!fixture_core.app.workspace.activeLeaf.state.workspace_preview'),'opening another source preserves the first editor');
 await evaluate('qa.get_workspace_files().open_file(fixture_source);void 0');await wait('fixture_core.app.workspace.activeLeaf===first_source');
 await evaluate('window.edit_preview=first_source;edit_preview.view.editor.models[0].setValue("const preview_edit = 3;\\n");void 0');
 await open_outline_menu();await wait('Boolean(document.querySelector(\'[data-symbol-name="preview_edit"]\'))');assert(await evaluate('document.querySelector("#typora-sidebar").dataset.documentOutline==="false"&&document.querySelector(".workspace-outline-empty").hidden'),'source editors display syntax symbols without stale Markdown headings');
 await evaluate('edit_preview.parent.removeTab(edit_preview.state.path);void 0');await wait('Boolean(document.querySelector("[data-workspace-tab-close]"))');assert(await evaluate('fixture_leaves.includes(edit_preview)&&edit_preview.view.dirty()'),'closing the native source tab uses its dirty guard');
 await evaluate('[...document.querySelectorAll("[data-workspace-tab-close] button")].find(button=>button.textContent==="不保存并关闭").click();void 0');await wait('!fixture_leaves.includes(edit_preview)');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(fixture_root,"second.ts"),{},"right");void 0');await wait('fixture_leaves.filter(leaf=>leaf.state.path.includes("second.ts")).length===2');
 await evaluate('window.active_second=fixture_core.app.workspace.activeLeaf;const inactive=fixture_leaves.find(leaf=>leaf.state.path.includes("second.ts")&&leaf.parent!==fixture_second_group);inactive.parent.removeTab(inactive.state.path);void 0');assert(await evaluate('fixture_core.app.workspace.activeLeaf===active_second'),'closing an inactive group preserves the active leaf');
 assert(await evaluate('!document.querySelector(".workspace-open-editor-row")'),'retired Open Editors UI stays absent');
 await evaluate('for(const leaf of [...fixture_leaves])if(leaf!==fixture_native_leaf)leaf.parent.removeTab(leaf.state.path);fixture_core.app.workspace.activeLeaf=fixture_native_leaf;void 0');await delay(50);
 checks.push('frozen Explorer keeps source tabs open; native tab close retains dirty guards; independent groups and native Outline preserve document state');
 await capture('plugin_markdown');
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');await wait('document.querySelectorAll(".workspace-explorer-row").length>0');await capture('plugin_explorer');
 await evaluate('fixture_commands.get("linux_note:search").callback();const input=document.querySelector(".workspace-search-query-box textarea");input.value="original";input.dispatchEvent(new Event("input",{bubbles:true}));void 0');await wait('document.querySelectorAll(".workspace-search-match").length>0');await capture('plugin_search');
 await evaluate('fixture_commands.get("linux_note:source_control").callback();void 0');await wait('Boolean(document.querySelector(".git-scm-title"))');await capture('plugin_scm');
 await evaluate('fixture_commands.get("linux_note:git_graph").callback();void 0');await wait('document.querySelectorAll(".git-graph-row").length>0');await capture('plugin_graph');
 await evaluate('window.graph_size=document.querySelector(".git-graph-row").getBoundingClientRect().height;for(const node of [document.documentElement,document.body]){node.style.setProperty("--bg-color","#1e1e1e");node.style.setProperty("--text-color","#cccccc");}void 0');await delay(100);
 assert(await evaluate('document.querySelector(".git-graph-row").getBoundingClientRect().height===graph_size'),'host dark theme retains Graph row geometry');await capture('workspace_graph_dark');
 await evaluate('for(const node of [document.documentElement,document.body]){node.style.removeProperty("--bg-color");node.style.removeProperty("--text-color");}void 0');
 await evaluate('fixture_commands.get("linux_note:terminal").callback();void 0');await wait('Boolean(document.querySelector(".linux-note-terminal .xterm"))');await capture('workspace_terminal');
 assert(await evaluate('fixture_core.app.workspace.activeLeaf.view.containerEl.classList.contains("linux-note-terminal")&&!document.querySelector(".typora-terminal-panel")'),'terminal opens in the existing editor group without a bottom Panel');
 assert.equal(await evaluate('getComputedStyle(document.querySelector(".linux-note-terminal .xterm-viewport")).backgroundColor'),'rgba(0, 0, 0, 0)','terminal viewport does not expose an upstream black fallback');
 checks.push('workbench switches through Explorer Search SCM Graph and editor-group Terminal with screenshot evidence');
 await evaluate('window.active_registration_count=fixture_commands.size;window.active_factory_count=fixture_factories.size;void 0');
 await evaluate('qa.get_workspace_files().open_file(fixture_source);void 0');
 await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 await capture('plugin_source');
 await evaluate('window.source_view=fixture_core.app.workspace.activeLeaf.view;source_view.editor.models[0].setValue("const changed = 2;\\n");void 0');
 await delay(50);
 assert(await evaluate('source_view.dirty()'));
 await evaluate('window.resident_files=qa.get_workspace_files();window.resident_core=fixture_core;window.resident_title=document.querySelector(".workspace-titlebar-menu");window.resident_model=source_view.editor.models[0];window.resident_start=qa.start_typora_code();window.folder_probe=require("path").join(fixture_root,"folder_probe");require("fs").mkdirSync(folder_probe,{recursive:true});File.setMountFolder(folder_probe);fixture_emit("file:open",fixture_core.app.workspace.activeLeaf);void 0');await delay(100);
 assert(await evaluate('qa.get_workspace_files()===resident_files&&resident_files.context_root()===folder_probe&&fixture_core===resident_core&&document.querySelector(".workspace-titlebar-menu")===resident_title&&source_view.editor.models[0]===resident_model&&source_view.dirty()&&qa.start_typora_code()===resident_start'),'folder/file events update context without rebuilding workbench, editor model or dirty draft');
 await evaluate('File.setMountFolder(fixture_root);fixture_emit("file:open",fixture_core.app.workspace.activeLeaf);void 0');await delay(100);
 assert(await evaluate('fixture_commands.size===active_registration_count&&fixture_factories.size===active_factory_count&&[...fixture_registration_counts.values()].every(count=>count===1)'), 'returning to prior folder preserves one registration per feature');

 const rejected=await evaluate('(()=>{try{qa.shutdown_typora_code();return false}catch{return true}})()');
 assert(rejected,'window teardown must reject while an unsaved source model exists');
 assert(await evaluate('fixture_commands.size===active_registration_count&&fixture_factories.size===active_factory_count&&document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"'));
 assert(await evaluate('qa.start_typora_code()===qa.start_typora_code()'),'repeated startup must return the same resident instance');
 assert.equal(fs.readFileSync(source_path,'utf8'),'const original = 1;\n');
 checks.push('unsaved Monaco source blocks window teardown; repeated startup retains the same workbench');
 assert(await evaluate("qa.get_workspace_files().save_active()"), "saving the fixture source through the production host clears its dirty guard");
 assert.equal(fs.readFileSync(source_path,"utf8"),"const changed = 2;\n");
 await evaluate('qa.shutdown_typora_code();void 0');await delay(200);
 assert(await evaluate('fixture_commands.size===0&&fixture_factories.size===0&&fixture_subscription_count()===0&&fixture_ribbon.size===0&&fixture_core.app.workspace.sidebar.panels.length===2'));
 assert(await evaluate('fixture_leaves.length===1&&!document.querySelector(".workspace-titlebar-menu")&&!document.querySelector(".workspace-quick-open")&&!document.documentElement.hasAttribute("data-linux-note-typora-enhancements")'));
 assert(await evaluate('fixture_core.app.openFile===fixture_original_app_open&&File.editor.library.openFile===fixture_original_library_open'));
 assert(await evaluate('original_outline.parentNode===original_outline_parent&&original_outline.nextSibling.id==="outline-anchor"'),'unload restores original native Outline ownership and sibling position');
 checks.push('clean unload removes commands views subscriptions ribbon panels and source leaves and restores native file routes');
 const remaining=await evaluate('fixture_listener_snapshot()');
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'),'global DOM listeners must return to baseline: '+JSON.stringify(remaining));
 checks.push('document and window listeners return to their pre-activation baseline including AbortSignal-owned listeners');
 await evaluate('void qa.start_typora_code().catch(error=>{fixture_errors.push(String(error));console.error(error)});void 0');await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"');
 assert(await evaluate('fixture_commands.size===active_registration_count&&fixture_factories.size===active_factory_count&&document.querySelectorAll(".workspace-titlebar-menu").length===1'));
 await evaluate('qa.shutdown_typora_code()');await delay(100);
 assert.equal(await evaluate('fixture_commands.size'),0);
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'));
 assert.equal(await evaluate('qa.monaco.editor.getModels().length'),0);
 checks.push('a full reload restores one set of commands, views and the single titlebar and unloads cleanly again');
 await evaluate('window.fixture_throw_view="linux_note.search_results";void qa.start_typora_code().catch(error=>{fixture_errors.push(String(error));console.error(error)});void 0');
 await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="failed"');await delay(100);
 assert(await evaluate('fixture_errors.some(error=>error.includes("Injected view registration failure"))'));
 assert(await evaluate('fixture_commands.size===0&&fixture_factories.size===0&&fixture_subscription_count()===0&&fixture_ribbon.size===0&&fixture_core.app.workspace.sidebar.panels.length===2'));
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'));
 await evaluate('qa.shutdown_typora_code();window.fixture_throw_view=undefined;fixture_errors.length=0;void 0');
 checks.push('a host view-registration exception mid-browser construction rolls back root and all acquired workbench resources');
 console.log(JSON.stringify({status:'PASS',checks,evidence}));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);if(test_window&&!test_window.isDestroyed()){console.error(await evaluate('JSON.stringify({errors:fixture_errors,listeners:fixture_listener_snapshot(),commands:[...fixture_commands.keys()],factories:[...fixture_factories.keys()],subscriptions:fixture_subscription_count()})'));test_window.destroy();}console.error(evidence);app.exit(1);});
