// 独立 QuickPick 使用 Chromium 真实鼠标和键盘；范围确认只调用控制器刷新，不触碰 Git 仓库。
const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_branch_picker_'));
app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();
let test_window,pointer_calls=0;const checks=[],metrics=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const verify=async(condition,label)=>{assert(await evaluate(condition),label);checks.push(label);};
const key=async(keyCode,modifiers=[])=>{test_window.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});test_window.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(50);};
const pointer=async(selector)=>{pointer_calls++;const point=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw new Error('Missing '+${JSON.stringify(selector)});node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect(),x=Math.round(r.x+r.width/2),y=Math.round(r.y+r.height/2);return{x,y,hit:node.contains(document.elementFromPoint(x,y))};})()`);assert(point.hit,selector+' must be hit-testable');for(const type of ['mouseMove','mouseDown','mouseUp']){test_window.webContents.sendInputEvent({type,x:point.x,y:point.y,button:'left',clickCount:1});await delay(15);}};

const query=async value=>{await pointer('.git-scm-ref-filter');await key('A',['control']);await key('Backspace');if(value)test_window.webContents.insertText(value);await delay(40);};
const open=async()=>{await evaluate(`picker.close(false);panel.root=state.root;panel.runner=runner;panel.writer=writer;panel.state=state;panel.pending=false;panel.writing=false;panel.disposed=false;document.querySelector('#trigger').focus();picker.open();void 0`);await delay(60);};
const capture=async name=>fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());
app.whenReady().then(async()=>{
 test_window=new BrowserWindow({show:false,width:940,height:740,webPreferences:{contextIsolation:false,nodeIntegration:true,offscreen:true,backgroundThrottling:false}});
 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>body{font:13px "Segoe UI";background:var(--bg-color,#fff);color:var(--text-color,#222)}#trigger{position:fixed;bottom:25px}#outside{position:fixed;bottom:60px}#write{position:fixed;top:520px}</style><button id="trigger">分支</button><button id="outside">其他</button><article id="write">正文保持</article>');
 await test_window.loadFile(html);test_window.webContents.debugger.attach();await test_window.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
 const bundle=await build({stdin:{contents:'export {git_branch_picker} from "./src/git_branch_picker";',resolveDir:path.join(__dirname,'..')},bundle:true,format:'iife',globalName:'qa',loader:{'.css':'text'},write:false});await evaluate(bundle.outputFiles[0].text);
 await evaluate(`window._options={displayLang:'zh-CN'};window.state={root:'isolated',head:'1'.repeat(40)};window.refs=[['refs/heads/main','Main subject'],['refs/heads/topic/nested','Topic subject'],['refs/remotes/team/origin/topic/nested','Remote subject'],['refs/tags/release','Release subject'],['refs/heads/long_'+ 'name_'.repeat(35),'long subject']];window.runner={run:async(root,args)=>args[0]==='for-each-ref'?refs.map(([name,subject])=>[name,'1'.repeat(40),'','commit','','','', 'QA author','','1789700000','',subject,'',''].join('\\0')).join('\\n'):''};window.writer={};window.accepted=0;window.panel={state,root:state.root,runner,writer,pending:false,writing:false,disposed:false,repository_epoch:1,ref_picker:{close(){}},prepare_and_execute_action:async()=>{accepted++;return 'done';},report(message){window.reported=String(message);}};window.picker=new qa.git_branch_picker(panel);void 0`);
 await open();await verify('document.activeElement.matches(".git-scm-ref-filter")','focus input on opening');await verify('document.querySelectorAll("[data-checkout-id]").length===8','3 commands plus local remote tag refs');await verify('document.querySelector("[data-checkout-id=\\"refs/remotes/team/origin/topic/nested\\"] [data-git-icon=cloud]")!==null','remote official icon');await verify('document.querySelector(".git-branch-detail").textContent.includes("QA author")','real metadata detail');await key('Escape');await verify('accepted===0&&document.activeElement.id==="trigger"','Escape zero writes restores focus');
 await open();await query('topic/nested');await verify('document.querySelector("[data-checkout-id]").dataset.checkoutId==="refs/heads/topic/nested"','search matching refs before commands');await key('Enter');await verify('accepted===1&&!document.querySelector(".git-branch-picker")','Enter accepts once without extra confirmation');
 await open();await pointer('[data-checkout-id="detached"]');await verify('document.querySelector(".git-branch-picker").dataset.checkoutMode==="detached"&&!document.querySelector("[data-checkout-id=\\"refs/tags/release\\"]")','detached second step hides tags');await key('Escape');
 await open();await pointer('[data-checkout-id="from"]');await pointer('[data-checkout-id="refs/tags/release"]');await verify('document.querySelector(".git-branch-picker").dataset.checkoutMode==="name"','create from ref moves to name input');await query('feature/new');await key('Enter');await verify('accepted===2','name accepts create once');
 await open();await pointer('[data-checkout-id="create"]');await query('main');await key('Enter');await verify('accepted===2&&document.querySelector(".git-branch-status").textContent.includes("已存在")','duplicate name stays open with feedback');await key('Escape');
 await open();await evaluate(`document.querySelector('.git-scm-ref-filter').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));void 0`);await verify('accepted===2&&!!document.querySelector(".git-branch-picker")','IME Enter does not execute');await pointer('#outside');await verify('!document.querySelector(".git-branch-picker")&&accepted===2','outside cancel zero writes');
 for(const mutation of ['panel.root="other"','panel.runner={}','panel.writer={}','panel.state={...state}','panel.pending=true','panel.disposed=true']){await open();await evaluate(`window.old=document.querySelector('[data-checkout-id="refs/heads/main"]');${mutation};picker.update_state();old.click();void 0`);await verify('!document.querySelector(".git-branch-picker")&&accepted===2','stale '+mutation+' cannot execute');}
 await open();await evaluate('picker.close();window.old_run=runner.run;runner.run=()=>new Promise(resolve=>window.late=resolve);picker.open();picker.close();late("");runner.run=old_run;void 0');await delay(40);await verify('!document.querySelector(".git-branch-picker")','late read cannot resurrect closed picker');
 for(const width of [320,940])for(const dark of [false,true]){test_window.setContentSize(width,620);await evaluate(`document.documentElement.dataset.workspaceFileIconTheme='${dark?'dark':'light'}';document.documentElement.style.cssText='--bg-color:${dark?'#202020':'#fff'};--side-bar-bg-color:${dark?'#202020':'#f8f8f8'};--text-color:${dark?'#eee':'#222'};--active-file-bg-color:#0066bf;--active-file-text-color:#fff;--item-hover-bg-color:${dark?'#444':'#eee'};'`);await open();const geometry=await evaluate(`(()=>{const r=document.querySelector('.git-branch-picker'),b=r.getBoundingClientRect();return {viewport:innerWidth,width:b.width,left:b.left,right:b.right,top:b.top,overflow:r.scrollWidth-r.clientWidth,rows:[...r.querySelectorAll('[data-checkout-id]')].map(n=>({height:n.getBoundingClientRect().height,detail:n.classList.contains('has-detail'),icons:[...n.querySelectorAll('svg')].map(x=>x.getBoundingClientRect().width)}))}})()`);assert.equal(geometry.width,Math.min(600,geometry.viewport-12));assert.equal(geometry.top,6);assert(geometry.overflow<=1);for(const row of geometry.rows){assert.equal(row.height,row.detail?44:22);assert(row.icons.every(x=>x===16));}await verify(`[...document.querySelectorAll('.git-branch-detail')].every(node=>getComputedStyle(node).textAlign==='left'&&Math.abs(node.getBoundingClientRect().left+parseFloat(getComputedStyle(node).paddingLeft)-node.parentElement.querySelector('.git-scm-ref-label').getBoundingClientRect().left)<1)`, 'detail shares label start');metrics.push({width,dark,...geometry});await capture('branches_'+width+'_'+(dark?'night':'light'));await key('Escape');}
 const iterations=process.env.TYPORA_TEST_PURPOSE==='stress'?Number(process.env.TYPORA_STRESS_ITERATIONS):20;
 await evaluate(`for(let i=0;i<${iterations};i++){picker.open();picker.close(false);}void 0`);await delay(40);await verify('!document.querySelector(".git-branch-picker")&&!document.querySelector("style[id*=git-branch-picker]")&&accepted===2','repeated open/cancel clears DOM styles and writes nothing');checks.push(iterations+' lifecycle cycles');
 await verify('document.querySelector("#write").textContent==="正文保持"','body unchanged');fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({status:'PASS',checks,metrics,iterations},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence},null,2));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(test_window&&!test_window.isDestroyed()){await capture('failure');test_window.destroy();}app.exit(1);});
