// 隐藏 Electron 检查菜单、键盘、主题与资源清理；原生事务另在 Typora 隔离副本中验证。
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_markdown_color_'));
app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();
let test_window;const checks=[],delay=ms=>new Promise(r=>setTimeout(r,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const wait=async expression=>{for(let i=0;i<80;i++){if(await evaluate(expression))return;await delay(30);}throw Error('Timeout: '+expression);};
const key=async code=>{test_window.webContents.sendInputEvent({type:'keyDown',keyCode:code});test_window.webContents.sendInputEvent({type:'keyUp',keyCode:code});await delay(50);};
app.whenReady().then(async()=>{
 const fixture=path.join(evidence,'fixture.html');
 fs.writeFileSync(fixture,'<!doctype html><meta charset="utf-8"><style>'+fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8')+'</style><style id="theme">:root{--bg-color:#fff;--text-color:#333}html,body{margin:0;background:#fff;color:#333}#context-menu .hide{display:none}.workspace-font-color-item{list-style:none}#write{padding:10px}</style><main id="write"><p cid="n1"><span class="md-plain">hello world</span></p></main><ul id="context-menu"><li id="native" data-key="block-style">Paragraph</li></ul>');
 test_window=new BrowserWindow({show:false,width:900,height:700,webPreferences:{contextIsolation:false,backgroundThrottling:false}});await test_window.loadFile(fixture);
 const bundle=await build({stdin:{contents:'export {bind_markdown_color_menu} from "./src/markdown_color_menu"; export {bind_markdown_color_theme} from "./src/markdown_color_theme"; export {color_contrast} from "./src/markdown_text_color";',resolveDir:path.join(__dirname,'..')},bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text'}});await evaluate(bundle.outputFiles[0].text);
 await evaluate(`window.model='hello world';window.registered=[];window.notices=[];window.original=document.querySelector('#native');window.native_calls=0;
 window.select=()=>{const t=document.querySelector('#write .md-plain').firstChild,r=document.createRange();r.setStart(t,0);r.setEnd(t,5);getSelection().removeAllRanges();getSelection().addRange(r);};
 window.native_show=function(){native_calls++;document.querySelector('#context-menu').classList.add('show');};
 window.File={bundle:{},editor:{getMarkdown:()=>model,getNode:id=>({cid:id,get:key=>key==='text'?model:'paragraph'}),sourceView:{inSourceMode:false},selection:{buildUndo:()=>({type:'cursor',id:'n1',start:0,end:5})},contextMenu:{show:native_show,hide(){document.querySelector('#context-menu').classList.remove('show');}},undo:{endSnap(){},exeCommand(command){if(command.type==='replace')model=command.json.content.text;},register(command){registered.push(command);},UndoManager:{buildReplaceUndo:node=>({type:'replace',id:node.cid,json:{content:{text:model}}})}}}};
 window.core={app:{workspace:{activeLeaf:{}}},Notice:class{constructor(message){notices.push(message);}}};window.binding=qa.bind_markdown_color_menu(core);
 window.show_menu=()=>File.editor.contextMenu.show(new MouseEvent('contextmenu'),document.querySelector('#write p'));
 window.open=()=>{select();show_menu();document.querySelector('.workspace-font-color-item a').click();};void 0;`);
 await evaluate('show_menu()');assert(await evaluate("document.querySelector('.workspace-font-color-item').classList.contains('hide')"));
 await evaluate('open()');await delay(80);assert(await evaluate("original===document.querySelector('#native')&&native_calls===2"));
 assert.equal(await evaluate("document.activeElement.dataset.textColor"),'b42318');
 await key('Right');assert.equal(await evaluate('document.activeElement.dataset.textColor'),'b54708');
 await key('Down');assert.equal(await evaluate('document.activeElement.dataset.textColor'),'175cd3');
 assert.equal(await evaluate('getComputedStyle(document.activeElement).borderRadius'),'4px');
 await key('Escape');assert.equal(await evaluate('model'),'hello world');assert.equal(await evaluate('registered.length'),0);
 checks.push('native menu identity and calls remain; empty selection hides color; rounded palette uses arrows and Escape with no edit');
 await evaluate('open()');await delay(60);
 await evaluate(`document.querySelector('.workspace-color-custom input[type=text]').value='invalid';document.querySelector('.workspace-color-custom button').click()`);
 assert.equal(await evaluate('notices.length'),1);assert(await evaluate("!!document.querySelector('.workspace-color-dialog')"));
 await evaluate(`document.querySelector('.workspace-color-custom input[type=text]').value='#FF0088';document.querySelector('.workspace-color-custom button').click()`);
 assert.equal(await evaluate('registered.length'),1);assert.equal(await evaluate('model'),'<span style="color:var(--typora-code-color-ff0088, #ff0088)">hello</span> world');
 checks.push('custom input rejects invalid values in place and applies a valid color through exactly one native transaction');
 await evaluate(`model='hello world';open();core.app.workspace.activeLeaf={};document.querySelector('[data-text-color=b42318]').click()`);
 assert.equal(await evaluate('registered.length'),1);assert.equal(await evaluate('model'),'hello world');assert.equal(await evaluate('notices.length'),2);
 checks.push('changing the active document while the palette is open rejects stale formatting');
 await evaluate(`open();window.samples=document.querySelector('[data-workspace-color-preview]');window.before_style=samples.getAttribute('style');`);
 await evaluate(`document.querySelector('#theme').textContent=':root{--bg-color:#363b40;--text-color:#ddd}html,body{margin:0;background:#363b40;color:#ddd}#context-menu .hide{display:none}#write{padding:10px}'`);
 await wait("samples.style.getPropertyValue('--typora-code-color-b42318')!=='#b42318'");
 const palette=await evaluate(`[...document.querySelectorAll('.workspace-color-sample')].map(node=>getComputedStyle(node).color.match(/\\d+/g).map(Number))`);
 for(const rgb of palette)assert(await evaluate(`qa.color_contrast(${JSON.stringify(rgb)},[54,59,64])>=4.5`));
 checks.push('all palette samples adapt to the actual dark panel background with at least 4.5 contrast');
 test_window.setSize(360,530);await delay(80);const bounds=await evaluate(`(()=>{const p=document.querySelector('.workspace-color-dialog .git-graph-dialog'),r=p.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight,overflow:p.scrollWidth-p.clientWidth};})()`);
 assert(bounds.left>=0&&bounds.right<=bounds.width+.5&&bounds.top>=0&&bounds.bottom<=bounds.height+.5);assert(bounds.overflow<=1);
 fs.writeFileSync(path.join(evidence,'dark_narrow.png'),(await test_window.webContents.capturePage()).toPNG());
 checks.push('palette and custom controls stay inside a narrow viewport without horizontal overflow');
 await evaluate('binding.dispose()');assert(await evaluate("!document.querySelector('.workspace-font-color-item,.workspace-color-dialog')&&File.editor.contextMenu.show===native_show&&original===document.querySelector('#native')"));
 assert.equal(await evaluate("[...samples.style].filter(x=>x.startsWith('--typora-code-color-')).length"),0);
 await evaluate('binding.dispose();binding=qa.bind_markdown_color_menu(core);void 0');assert.equal(await evaluate("document.querySelectorAll('.workspace-font-color-item').length"),1);
 await evaluate(`File.editor.sourceView.inSourceMode=true;select();show_menu()`);assert(await evaluate("document.querySelector('.workspace-font-color-item').classList.contains('hide')"));
 await evaluate('binding.dispose()');checks.push('disposal restores owned variables and the native menu once; rebind remains single and source mode stays excluded');
 console.log(JSON.stringify({status:'PASS',checks,evidence}));test_window.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(evidence);test_window?.destroy();app.exit(1);});
