'use strict';
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {build}=require('esbuild'),{editor_plugins}=require('./editor_bundle.cjs');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_ssh_directory_'));let win;app.disableHardwareAcceleration();app.setPath('userData',path.join(evidence,'profile'));
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1100,height:800,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 await win.loadURL('data:text/html,'+encodeURIComponent('<style>body{margin:0;font:13px Segoe UI;--bg-color:white;--text-color:#222}.workspace-ssh-sidebar{width:300px;height:760px}</style><div class="workspace-ssh-sidebar"></div>'));
 const run=source=>win.webContents.executeJavaScript(source,true),pause=()=>new Promise(resolve=>setTimeout(resolve,100));
 const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export * from "./src/remote_ssh_directory";export {create_ssh_authentication} from "./src/remote_ssh_authentication";export {default as css} from "./src/workspace_remote_ssh.css";',resolveDir:path.join(__dirname,'..')},loader:{'.css':'text'},bundle:true,format:'iife',globalName:'qa',write:false});await run(bundle.outputFiles[0].text+';void 0');
 assert(await run(`(async()=>{const login=new Map([['alice@legacy.test','legacy-fixture']]);let viewed=0;const directory={list:async()=>[]};const credential_api={create_credential_store:()=>({supported:true,read:async key=>login.get(key),save:async(key,value)=>login.set(key,value),remove:async key=>login.delete(key)}),create_password_vault:()=>({remember:async()=>{viewed++}})};const runtime={_options:{userDataPath:require('node:os').tmpdir()},reqnode:name=>name.endsWith('remote_ssh_service.cjs')?{resolve_connection_identity:async()=>({key:'resolved-account',user:'alice',hostname:'legacy.test'})}:name.endsWith('remote_ssh_connections.cjs')?{create_connection_store:()=>directory}:name.endsWith('remote_ssh_credentials.cjs')?credential_api:require(name)};const coordinator=qa.create_ssh_authentication(runtime,'fixture','node');try{const attempt=await coordinator.attempt('alice@legacy.test',0,()=>true);const answer=await attempt.authenticate("alice@legacy.test's password:",()=>false);await attempt.complete();return answer==='legacy-fixture'&&login.get('resolved-account')==='legacy-fixture'&&!login.has('alice@legacy.test')&&viewed===0;}finally{coordinator.dispose();}})()`),'legacy login migration does not resurrect cleared viewing records');
 await run(`const style=document.createElement('style');style.textContent=qa.css;document.head.append(style);window.records=[{id:'a',host_name:'开发虚拟机',name:'开发账号',target:'alice@server.test',port:2222,folder:'/home/alice'},{id:'b',host_name:'开发虚拟机',name:'管理员',target:'root@server.test',port:2222,folder:'/root'},{id:'c',host_name:'测试服务器',name:'日常账号',target:'alice@other.test',port:22,folder:'/tmp'}];window.calls=[];window.errors=[];window.auth={directory:{list:async()=>records,save:async value=>{records=records.filter(r=>r.id!==value.id);records.push({...value,id:value.id||'new'});return value},remove:async id=>{records=records.filter(r=>r.id!==id)}},credentials:{supported:true},identity:async(target,port)=>({key:target+':'+port}),save:async()=>{},forget:async(...args)=>calls.push(['forget',...args]),vault:{state:async()=>({configured:false,reset:false}),setup:async()=>calls.push(['vault-setup'])}};window.binding=qa.create_ssh_directory(auth,async record=>calls.push(['connect',record.target,record.port]),error=>errors.push(String(error)));document.querySelector('.workspace-ssh-sidebar').append(binding.root);void 0`);await pause();
 assert.equal(await run('document.querySelectorAll(".workspace-ssh-host").length'),2);
 await run(`document.querySelector('.workspace-ssh-account-open').click()`);assert.deepEqual(await run('calls'),[['connect','alice@server.test',2222]]);
 await run(`document.querySelector('.workspace-ssh-account-open').focus()`);win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return'});win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return'});await pause();assert.equal(await run('calls.length'),2,'keyboard activates focused connection');
 await run(`binding.set_active('a','connected');document.querySelector('input[aria-label="搜索SSH连接"]').value='管理员';document.querySelector('input[aria-label="搜索SSH连接"]').dispatchEvent(new Event('input'));`);assert.equal(await run('document.querySelectorAll(".workspace-ssh-account").length'),1);
 await run(`document.querySelector('input').value='';document.querySelector('input').dispatchEvent(new Event('input'));document.querySelector('[title="新建SSH连接"]').click();`);await pause();
 assert(await run(`!!document.querySelector('input[aria-label="电脑别名"]')&&!!document.querySelector('input[aria-label="账号别名"]')&&!!document.querySelector('[role=dialog] .workspace-dialog-close')`));
 await run(`const fill=(name,value)=>document.querySelector('[aria-label="'+name+'"]').value=value;fill('主机地址或OpenSSH别名','new.test');fill('电脑别名','我的服务器');fill('用户名','bob');fill('账号别名','实验用户');[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent==='保存').click();`);await pause();assert.equal(await run('records.length'),4);assert.equal(await run('records.at(-1).target'),'bob@new.test');
 await run(`document.querySelector('[title="管理 实验用户"]').click();[...document.querySelectorAll('[role=menuitem]')].find(b=>b.textContent.includes('删除连接记录')).click();`);await pause();await run(`document.querySelector('[role=dialog] .workspace-dialog-close').click()`);assert.equal(await run('records.length'),4,'cancel deletion preserves record');
 await run(`auth.vault.state=async()=>({configured:true});auth.vault.reveal=async(key,master)=>{if(master!=='unlock-fixture')throw Error('保险密码不正确');return 'view-fixture'};document.hasFocus=()=>true;document.querySelector('[title="管理 实验用户"]').click();[...document.querySelectorAll('[role=menuitem]')].find(b=>b.textContent.includes('查看密码')).click();`);await pause();
 await run(`document.querySelector('input[aria-label="保险密码"]').value='wrong';[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent==='显示30秒').click();`);await pause();assert.equal(await run('document.querySelector("input[data-secret]").value'),'');
 await run(`document.querySelector('input[aria-label="保险密码"]').value='unlock-fixture';[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent==='显示30秒').click();`);await pause();assert.equal(await run('document.querySelector("input[data-secret]").value'),'view-fixture');
 await run(`window.dispatchEvent(new Event('blur'));void 0`);assert.equal(await run('document.querySelector("input[data-secret]").value'),'');await run(`document.querySelector('[role=dialog] .workspace-dialog-close').click();void 0`);
 for(const zoom of [0.8,1,1.5]){win.webContents.setZoomFactor(zoom);for(const dark of [false,true]){await run(`document.body.style.setProperty('--bg-color','${dark?'#202020':'white'}');document.body.style.setProperty('--text-color','${dark?'#ddd':'#222'}');document.body.style.background='${dark?'#202020':'white'}';document.body.style.color='${dark?'#ddd':'#222'}';`);await pause();assert(await run(`(()=>{const root=binding.root;return root.scrollWidth<=root.clientWidth+1&&[...root.querySelectorAll('button')].every(b=>{const r=b.getBoundingClientRect();return r.width>0&&r.right<=root.getBoundingClientRect().right+1})})()`),'narrow sidebar layout');}}
 win.webContents.setZoomFactor(1);await run(`document.body.style.setProperty('--bg-color','white');document.body.style.setProperty('--text-color','#222');document.body.style.background='white';document.body.style.color='#222';`);await pause();fs.writeFileSync(path.join(evidence,'directory.png'),(await win.webContents.capturePage()).toPNG());
 await run('binding.dispose();void 0');assert.equal(await run('document.querySelectorAll("[role=dialog],.workspace-ssh-directory").length'),0);assert.deepEqual(await run('errors'),[]);
 console.log(JSON.stringify({status:'PASS',evidence,checks:['电脑分组、账号一键连接及真实Enter按键','别名搜索、新建与删除取消','系统密码表单及公共关闭','窄侧栏明暗与80/100/150%缩放','销毁清理']}));win.destroy();app.quit();
}).catch(error=>{console.error(error);win?.destroy();app.exit(1);});
