// 正式主题文件、共享预览与真实Chromium排版；不以颜色相同代替字体验收。
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'typora-theme-pair-')),root=path.join(__dirname,'../..');app.setPath('userData',path.join(base,'profile'));app.disableHardwareAcceleration();let win;
const checks=[],samples=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
app.whenReady().then(async()=>{
 for(const name of ['cpp_github-consolas.css','cpp_github-consolas_light.css','cpp_github-consolas_dark.css'])fs.copyFileSync(path.join(root,name),path.join(base,name));
 fs.writeFileSync(path.join(base,'test.html'),`<!doctype html><link rel=stylesheet id=theme_css href=cpp_github-consolas.css><style>${fs.readFileSync(path.join(root,'enhancements/dist/workspace.css'),'utf8')}</style><body><content><div id=write><h1>标题 Typography gyp</h1><h2>二级标题</h2><h3>三级标题</h3><h4>四级标题</h4><h5>五级标题</h5><h6>六级标题</h6><p>正文 中英字体 Consolas 0123 <a href=#link>跳转</a> <code>printf()</code></p><blockquote>引用</blockquote><table><thead><tr><th>表头</th></tr></thead><tbody><tr><td>内容</td></tr><tr><td>隔行</td></tr></tbody></table><pre class=md-fences><div class="CodeMirror cm-s-inner"><span class=cm-tm-string>字符串</span></div></pre></div></content><div class=workspace-titlebar-popup style="position:fixed;top:0;right:0;width:400px"><button class=workspace-titlebar-entry><span class=workspace-titlebar-label>CppGithubConsoles_Dark Night gyp 格式</span><span class=workspace-titlebar-shortcut>Ctrl+Shift+F</span></button></div></body>`);
 win=new BrowserWindow({show:false,width:1400,height:1000,webPreferences:{offscreen:true,contextIsolation:false,backgroundThrottling:false}});await win.loadFile(path.join(base,'test.html'));
 const ev=s=>win.webContents.executeJavaScript(s),bundle=await require('esbuild').build({plugins:require('./editor_bundle.cjs').editor_plugins(),stdin:{contents:`export {bind_workspace_colors} from './src/workspace_colors';export {markdown_theme_rules} from './src/workspace_markdown_theme';`,resolveDir:path.join(root,'enhancements')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await ev(bundle.outputFiles[0].text);
 await ev(`window.binding=qa.bind_workspace_colors();window.original=document.querySelector('#write').innerHTML;window.host=document.body.appendChild(document.createElement('div'));window.shadow=host.attachShadow({mode:'open'});window.geometry=(scope=document)=>Object.fromEntries(['p','h1','h2','h3','h4','h5','h6','a','code','blockquote','th','td','pre','.CodeMirror'].map(q=>{const c=getComputedStyle(scope.querySelector('#write '+q));return[q,Object.fromEntries(['font-family','font-size','font-style','font-weight','line-height','letter-spacing','padding-top','padding-left','margin-top','margin-bottom','border-top-width','border-left-width','border-top-style'].map(k=>[k,c.getPropertyValue(k)]))]}));void 0`);
 let reference;
 for(const theme of ['cpp_github-consolas.css','cpp_github-consolas_light.css','cpp_github-consolas_dark.css']){
  await ev(`new Promise(resolve=>{const link=document.getElementById('theme_css');if(link.getAttribute('href')===${JSON.stringify(theme)})return resolve();link.onload=()=>resolve();link.href=${JSON.stringify(theme)}})`);await pause(120);
  const actual=await ev('geometry()');if(!reference)reference=actual;assert.deepEqual(actual,reference,theme+' fonts/geometry');checks.push(theme+' 正文/六级标题/代码/表格等14类排版相同');
  await ev(`shadow.innerHTML='<style>'+qa.markdown_theme_rules()+'</style><div id=write>'+original+'</div>';void 0`);
  const preview=await ev('geometry(shadow)');
  // Shadow使用实际正文继承；容器宽度由各视图拥有，这里只比较文字与块几何属性。
  assert.deepEqual(preview,actual,theme+' shadow');checks.push(theme+' CSS导入后Shadow字体/边线/间距一致');
  const colors=await ev(`Object.fromEntries(['p','h1','a','th','td','pre'].map(q=>{const c=getComputedStyle(document.querySelector('#write '+q));return[q,{color:c.color,bg:c.backgroundColor}]}))`);samples.push({theme,geometry:actual,colors});
  if(theme.endsWith('_dark.css')){assert.equal(colors.p.color,'rgb(184, 191, 198)');assert.equal(colors.pre.bg,'rgb(51, 51, 51)');assert.equal(await ev('getComputedStyle(document.body).backgroundColor'),'rgb(54, 59, 64)');checks.push('Dark实际Night正文/背景/围栏配色');}
  for(const zoom of [1,1.25]){win.webContents.setZoomFactor(zoom);await pause(60);assert(await ev(`[...document.querySelectorAll('.workspace-titlebar-label,.workspace-titlebar-shortcut')].every(node=>{const range=document.createRange();range.selectNodeContents(node);const r=range.getBoundingClientRect(),b=node.getBoundingClientRect();return r.top>=b.top-0.5&&r.bottom<=b.bottom+0.5})`),'menu glyph');checks.push(theme+' '+zoom+' 菜单真实文字行盒完整');}
  win.webContents.setZoomFactor(1);
 }
 assert.equal(await ev(`document.querySelector('#write').innerHTML`),await ev('original'));checks.push('主题切换不改正文DOM');
 await ev('binding.dispose()');fs.writeFileSync(path.join(base,'checks.json'),JSON.stringify({status:'PASS',checks,samples},null,2));console.log(JSON.stringify({status:'PASS',count:checks.length,evidence:base}));win.destroy();app.exit(0);
}).catch(error=>{fs.writeFileSync(path.join(base,'checks.json'),JSON.stringify({status:'ERROR',error:String(error.stack),checks,samples},null,2));console.error(error);win?.destroy();app.exit(1);});
