// 全局底栏的活动编辑器归属、窄布局及退订；只创建隔离隐藏窗口。
const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_editor_status_'));app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();let test_window;const checks=[];
const evaluate=source=>test_window.webContents.executeJavaScript(source);const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));const check=(condition,label)=>{assert(condition,label);checks.push(label)};
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:1050,height:700,webPreferences:{contextIsolation:false,offscreen:true,backgroundThrottling:false}});
  const html=path.join(evidence,'status.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;font:13px system-ui}main{position:absolute;left:240px;right:0;top:0;bottom:28px;display:flex}.pane{flex:1;border-left:1px solid #8884}footer.ty-footer{position:absolute;bottom:0;left:240px;right:0;height:28px;background:#eee}.linux-note-git-status{display:flex;white-space:nowrap;overflow:hidden;max-width:65%}#typora-sidebar{position:absolute;left:40px;top:0;bottom:0;width:200px}#ty-sidebar-footer{position:absolute;bottom:0;width:100%;height:28px}.sidebar-footer-main-item{flex:1}.sidebar-footer-main-item-label{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sidebar-footer-item{display:flex}.footer-btn{padding:0 5px}#sidebar-files-menu{display:none}.footer-item-left{float:left}.footer-item-right{float:right}</style><body class="show-footer"><div id="typora-sidebar" class="active-tab-files use-file-tree-style"><div id="sidebar-content"></div><div class="sidebar-footer" id="ty-sidebar-footer"><div style="display:flex"><div class="sidebar-footer-item" id="sidebar-new-file-btn">+</div><div class="sidebar-footer-main-item" id="sidebar-menu-btn"><span class="sidebar-footer-item"><span class="sidebar-footer-main-item-label" id="sidebar-footer-main-item-label">workspace_folder</span><span class="footer-btn">⋮</span></span><ul id="sidebar-files-menu"></ul></div><div class="sidebar-footer-item" id="switch-file-list-btn">☷</div></div></div></div><main><div class="pane" id="pane_a">a.py</div><div class="pane" id="pane_b">b.ts</div></main><footer class="ty-footer"><div class="footer-item footer-item-left linux-note-git-status">master ↓ 0 ↑ 0 提交图</div><div class="footer-item footer-item-left">&lt;/&gt;</div><div class="footer-item footer-item-right" id="footer-word-count">100 词</div></footer></body>');await test_window.loadFile(html);
  const bundle=await build({stdin:{contents:'export {bind_workspace_editor_status} from "./src/workspace_editor_status";export {install_workspace_footer} from "./src/workspace_footer";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'status_qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{window.events=new Set();window.active=null;window.core={app:{workspace:{get activeLeaf(){return active},on(name,callback){events.add(callback);return()=>events.delete(callback)}}}};window.status_binding=status_qa.bind_workspace_editor_status(core);window.footer_binding=status_qa.install_workspace_footer();window.calls=[];
  window.make_owner=(name,language,encoding,eol)=>{const leaf={state:{path:name}};const controls=document.createElement('div');controls.className='workspace-editor-status-controls';controls.innerHTML='<span class="workspace-file-status"></span><span class="workspace-file-location">行 1，列 1</span><button aria-label="保存编码">'+encoding+'</button><button aria-label="行尾序列">'+eol+'</button><button aria-label="语言模式">'+language+'</button>';controls.querySelectorAll('button').forEach(button=>button.onclick=()=>calls.push(name+':'+button.getAttribute('aria-label')));controls.oncontextmenu=event=>{event.preventDefault();calls.push(name+':menu')};status_binding.register(leaf,controls);return{leaf,controls}};
  window.a=make_owner('a.py','python','UTF-8','LF');window.b=make_owner('b.ts','typescript','UTF-16LE BOM','CRLF');window.activate=leaf=>{active=leaf;events.forEach(callback=>callback(leaf))};activate(a.leaf);})()`);
  check(await evaluate('status_binding.container.parentElement.matches("footer.ty-footer")&&status_binding.container.firstChild===a.controls&&document.querySelectorAll(".linux-note-editor-status").length===1'),'one global owner container shows the active editor original controls');
  check(await evaluate('!document.querySelector("main .workspace-editor-status-controls")&&b.controls.isConnected===false'),'split panes retain no local state row and background controls stay detached');
  await evaluate('activate(b.leaf);status_binding.container.querySelector("[aria-label=保存编码]").click();status_binding.container.dispatchEvent(new Event("focusin",{bubbles:true}));b.controls.dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true}));a.controls.querySelector(".workspace-file-location").textContent="行 200，列 80";');await delay(60);
  check(await evaluate('status_binding.container.firstChild===b.controls&&status_binding.container.textContent.includes("UTF-16LE BOM")&&calls.join("|")==="b.ts:保存编码|b.ts:menu"'),'buttons and context menu route to the active editor while background updates cannot steal status');
  await evaluate('b.controls.querySelector(".workspace-file-location").textContent="行 5，列 9";b.controls.querySelector(".workspace-file-status").textContent="磁盘已变化，请先处理外部修改"');await delay(60);
  check(await evaluate('status_binding.container.textContent.includes("行 5，列 9")&&b.controls.querySelector(".workspace-file-status").title.includes("磁盘已变化")'),'current caret and asynchronous message update without reparenting or losing the full error tooltip');
  for(const type of ['markdown','git','terminal']){await evaluate(`activate({state:{path:${JSON.stringify(type)}}})`);check(await evaluate('status_binding.container.hidden&&status_binding.container.children.length===0&&getComputedStyle(document.querySelector("#footer-word-count")).display!=="none"'),type+' activation hides old source format and restores native status');}
  await evaluate('activate(a.leaf)');check(await evaluate('status_binding.container.firstChild===a.controls&&status_binding.container.textContent.includes("行 200，列 80")'),'returning to a source pane shows its own latest position');
  await evaluate('status_binding.release(a.leaf);activate(b.leaf)');check(await evaluate('status_binding.container.firstChild===b.controls'),'closing the active source switches to the next owner without stale controls');
  await evaluate(`(()=>{const footer=document.querySelector('footer.ty-footer'),controls=status_binding.container.firstElementChild,information=[...controls.querySelectorAll('.workspace-file-location,.workspace-file-detail,button')].reduce((width,node)=>width+node.scrollWidth,32),other=[...footer.children].filter(node=>node!==status_binding.container&&node.id!=='ty-sidebar-footer'&&node.id!=='footer-word-count'&&node.id!=='footer-spell-check'),reserved=other.reduce((width,node)=>width+node.scrollWidth,0),actions=document.querySelector('#ty-sidebar-footer').getBoundingClientRect().width;footer.style.left=(innerWidth-(information+reserved+actions+8))+'px';})()`);await delay(100);
  check(await evaluate('document.querySelector("footer.ty-footer").dataset.editorStatus==="ready"&&getComputedStyle(document.querySelector("footer.ty-footer")).getPropertyValue("--workspace-native-actions-width").trim()===""'),'editor status reserves the measured native action width instead of a 210px estimate');
  await evaluate('document.querySelector("footer.ty-footer").style.left=(innerWidth-220)+"px"');await delay(100);
  check(await evaluate('document.querySelector("footer.ty-footer").dataset.editorStatus==="compact"'),'a narrow footer compacts only editor information');
  check(await evaluate('(()=>{const source=status_binding.container.getBoundingClientRect(),actions=document.querySelector("#ty-sidebar-footer").getBoundingClientRect(),menu=document.querySelector("#sidebar-menu-btn").getBoundingClientRect();return source.width>40&&source.right<=actions.left+1&&actions.right<=innerWidth&&Math.abs(actions.width-78)<=1&&Math.abs(menu.width-26)<=1&&getComputedStyle(document.querySelector("#sidebar-new-file-btn")).display!=="none"&&getComputedStyle(document.querySelector("#switch-file-list-btn")).display!=="none"})()'),'native file actions remain visible at content width without overlapping source information in 220px');
  check(await evaluate('getComputedStyle(document.querySelector(".workspace-editor-status-controls")).overflowX==="auto"'),'very narrow source formats remain reachable by horizontal scrolling');
  fs.writeFileSync(path.join(evidence,'status_narrow.png'),(await test_window.webContents.capturePage()).toPNG());
  await evaluate('status_binding.dispose();footer_binding.dispose()');check(await evaluate('events.size===0&&!document.querySelector(".linux-note-editor-status")'),'dispose unsubscribes core events and removes only the shared status host');
  console.log(JSON.stringify({status:'PASS',checks,evidence}));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);if(test_window&&!test_window.isDestroyed()){fs.writeFileSync(path.join(evidence,'failure.png'),(await test_window.webContents.capturePage()).toPNG());test_window.destroy();}console.error(evidence);app.exit(1)});
