// 隐藏 Electron 中以真实 pointer capture 验证原生侧栏分界线，无需安装 Typora。
const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_sidebar_sash_'));
app.setPath('userData',path.join(evidence,'user_data'));app.disableHardwareAcceleration();
let test_window;const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const wait=async(source)=>{for(let index=0;index<160;index++){if(await evaluate(source))return;await delay(20)}throw new Error('Timed out: '+source)};
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:1280,height:800,webPreferences:{contextIsolation:false,nodeIntegration:true,backgroundThrottling:false,offscreen:true}});
  const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,`<!doctype html><meta charset="utf-8"><style>
  :root{--sidebar-width:300px}html,body{height:100%;margin:0;overflow:hidden}body{--typ-ribbon-width:48px;--typ-sidedock-width:0px;font:13px Arial;color:#333}.typ-ribbon{position:fixed;left:0;top:0;bottom:0;width:48px;background:#f3f3f3}.typ-ribbon button{display:block;width:48px;height:48px;border:0}
  #typora-sidebar{position:fixed;top:0;bottom:0;left:-30000px;width:var(--sidebar-width);background:#fafafa;transition:left .3s}.pin-outline #typora-sidebar{left:48px}#sidebar-content{height:100%;overflow:hidden}.panel{white-space:nowrap;padding:14px}
  .typ-workspace-root{position:absolute;left:48px;right:var(--typ-sidedock-width);top:0;bottom:0;background:white;transition:left .3s}.pin-outline .typ-workspace-root{left:calc(48px + var(--sidebar-width))}
  #typora-sidebar-resizer{display:none;position:fixed;top:0;bottom:0;left:var(--sidebar-width);width:6px;margin-left:-2px;z-index:99;cursor:col-resize}.pin-outline #typora-sidebar-resizer{display:block;left:calc(48px + var(--sidebar-width))}#typora-sidebar-resizer.dragging{left:0;right:0;width:100%;margin-left:0}.typora-sidebar-resizer-bar{height:100%;width:3px;opacity:.4}
  </style><body class="typ-ribbon--enable typora-node pin-outline"><div class="typ-workspace-root">编辑区</div><div id="typora-sidebar"><div id="sidebar-content"></div></div><div aria-hidden="true" id="typora-sidebar-resizer"><div class="typora-sidebar-resizer-bar"></div></div><nav class="typ-ribbon"></nav>`);
  await test_window.loadFile(html);
  const bundle=await build({stdin:{contents:'export * from "./src/workspace_sidebar_sash";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'sash_qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{
    window.saved=[];window.native_mouse=0;window.panel_changes=[];window.active_panel='文件';window.shows=0;window.hides=0;window.resize_count=0;
    const panel=document.createElement('div');panel.className='panel';panel.textContent=active_panel;document.querySelector('#sidebar-content').append(panel);
    window.sidebar={get isShown(){return document.body.classList.contains('pin-outline')},show(){shows++;document.body.classList.add('pin-outline');document.querySelector('#sidebar-content').append(panel)},hide(){hides++;document.body.classList.remove('pin-outline');panel.remove()}};
    for(const name of ['文件','搜索','大纲','源代码管理','跳转预览']){const button=document.createElement('button');button.textContent=name;button.dataset.panel=name;button.onclick=()=>{if(active_panel===name&&sidebar.isShown)sidebar.hide();else{active_panel=name;panel.textContent=name;sidebar.show()}panel_changes.push(name)};document.querySelector('.typ-ribbon').append(button)}
    document.querySelector('#typora-sidebar-resizer').addEventListener('mousedown',()=>native_mouse++);window.addEventListener('resize',()=>resize_count++);
    window.sash_events=[];for(const type of ['pointerdown','pointermove','pointerup','pointercancel','lostpointercapture','blur'])window.addEventListener(type,event=>sash_events.push({type,x:event.clientX,target:event.target.id,pointer:event.pointerId}),true);
    window.binding=sash_qa.install_workspace_sidebar_sash({sidebar,save_width:width=>saved.push(width)});
    window.state=()=>({visible:sidebar.isShown,width:parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--sidebar-width')),editor:document.querySelector('.typ-workspace-root').getBoundingClientRect().width,ribbon:document.querySelector('.typ-ribbon').getBoundingClientRect().width,viewport:document.documentElement.clientWidth,dragging:document.body.classList.contains('linux-note-sidebar-dragging'),sash:document.querySelector('#typora-sidebar-resizer').getBoundingClientRect().left});
  })()`);
  await delay(100);const initial=await evaluate('state()');assert.equal(initial.width,300);assert.equal(initial.ribbon,48);
  let mouse_down=false;
  const input=async(type,point,button='left')=>{if(type==='mouseDown')mouse_down=true;if(type==='mouseUp')mouse_down=false;test_window.webContents.sendInputEvent({type,...point,button,clickCount:1,modifiers:mouse_down?['leftButtonDown']:[]});await delay(35)};
  const start_drag=async()=>{const point=await evaluate('(()=>{const r=binding.element.getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:100,width:sidebar.isShown?state().width:0}})()');await input('mouseMove',{x:point.x,y:point.y});await input('mouseDown',{x:point.x,y:point.y});return point};
  const move_drag=async(start,width)=>input('mouseMove',{x:start.x+width-start.width,y:start.y});
  const end_drag=async(start,width)=>{await input('mouseUp',{x:start.x+width-start.width,y:start.y});await delay(70)};
  const click_panel=async(name)=>{const point=await evaluate(`(()=>{const r=document.querySelector('[data-panel="${name}"]').getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()`);await input('mouseMove',point);await input('mouseDown',point);await input('mouseUp',point);await delay(350)};
  let drag=await start_drag();await move_drag(drag,210);assert.equal((await evaluate('state()')).width,210,'live drag updates before release');assert.equal(await evaluate('saved.length'),0);
  await move_drag(drag,160);assert.equal((await evaluate('state()')).width,170);await move_drag(drag,85);assert((await evaluate('state()')).visible);await move_drag(drag,84);assert(!(await evaluate('state()')).visible);assert.equal((await evaluate('state()')).ribbon,48);assert.equal((await evaluate('state()')).sash,45);
  assert(await evaluate('binding.element.hasPointerCapture(1)'),'captured pointer survives sidebar collapse');
  await move_drag(drag,85);assert((await evaluate('state()')).visible);assert.equal((await evaluate('state()')).width,170);await move_drag(drag,250);await end_drag(drag,250);assert.equal((await evaluate('state()')).width,250);assert.deepEqual(await evaluate('saved'),[250]);assert.equal(await evaluate('native_mouse'),0,'native drag-shadow handlers do not run in parallel');
  drag=await start_drag();await move_drag(drag,170);await move_drag(drag,84);await end_drag(drag,84);assert(!(await evaluate('state()')).visible);assert.equal((await evaluate('state()')).width,250,'collapsed drag retains its original visible width');
  fs.writeFileSync(path.join(evidence,'sidebar_collapsed.png'),(await test_window.webContents.capturePage()).toPNG());
  for(const name of ['文件','搜索','大纲','源代码管理','跳转预览']){await click_panel(name);assert((await evaluate('state()')).visible);assert.equal((await evaluate('state()')).width,250);assert.equal(await evaluate('document.querySelector(".panel").textContent'),name);await click_panel(name);assert(!(await evaluate('state()')).visible)}
  drag=await start_drag();await move_drag(drag,84);assert(!(await evaluate('state()')).visible);await move_drag(drag,85);assert((await evaluate('state()')).visible);await move_drag(drag,200);await end_drag(drag,200);assert.equal((await evaluate('state()')).width,200,'new drag from collapsed boundary restores the same panel');
  const key=async(key,modifiers=[])=>{await evaluate('binding.element.focus()');test_window.webContents.sendInputEvent({type:'keyDown',keyCode:key,modifiers});test_window.webContents.sendInputEvent({type:'keyUp',keyCode:key,modifiers});await delay(80)};
  await key('Home');assert.equal((await evaluate('state()')).width,170);await key('Right');assert.equal((await evaluate('state()')).width,180);await key('Enter');assert(!(await evaluate('state()')).visible);await key('Right');assert((await evaluate('state()')).visible);assert.equal((await evaluate('state()')).width,180);
  drag=await start_drag();const viewport=(await evaluate('state()')).viewport;await move_drag(drag,viewport-50);await end_drag(drag,viewport-50);await delay(350);const maximum=await evaluate('state()');assert.equal(maximum.width,maximum.viewport-48-220);assert(Math.abs(maximum.editor-220)<2);
  await evaluate('document.body.style.setProperty("--typ-sidedock-width","300px")');await delay(350);const docked=await evaluate('state()');assert.equal(docked.width,docked.viewport-48-300-220);assert(Math.abs(docked.editor-220)<2,'right dock retains editor space');
  await evaluate('document.body.style.setProperty("--typ-sidedock-width","0px")');await delay(350);await key('Home');await key('Right',['shift']);assert.equal((await evaluate('state()')).width,220);
  test_window.setContentSize(400,700);await wait('!sidebar.isShown');await delay(350);assert.equal((await evaluate('state()')).ribbon,48);assert((await evaluate('state()')).editor>=220);test_window.setContentSize(1280,800);await delay(200);assert(!(await evaluate('state()')).visible);await click_panel('跳转预览');assert.equal((await evaluate('state()')).width,220,'window size clamp does not overwrite last user width');
  fs.writeFileSync(path.join(evidence,'sidebar_narrow.png'),(await test_window.webContents.capturePage()).toPNG());
  const events_before=await evaluate('resize_count');await delay(350);assert.equal(await evaluate('resize_count'),events_before,'resize observer has no self-sustaining event loop');
  assert.equal(await evaluate('binding.element.getAttribute("aria-valuenow")'),'220');assert.equal(await evaluate('binding.element.getAttribute("aria-hidden")'),null);
  await evaluate('binding.dispose()');assert.equal(await evaluate('binding.element.getAttribute("aria-hidden")'),'true');assert.equal(await evaluate('binding.element.dataset.workspaceSidebarSash'),undefined);assert(!(await evaluate('state()')).dragging);
  console.log(JSON.stringify({status:'PASS',checks:['170px minimum and 85px snap threshold match VS Code','drag resizes immediately before release','same pointer drag collapses and expands without losing capture','activity bar stays visible while all panels hide','width persists only after a completed expanded drag','collapsed drag preserves pre-drag width','all five panel activity entries restore the previous width','new drag from collapsed boundary expands the retained panel','native drag-shadow handlers are suppressed','keyboard arrows, Home and Enter operate the separator','editor retains 220px at maximum width','right dock is included in maximum width','narrow window collapses sidebar without overwriting remembered width','resize observation does not loop','dispose restores native accessibility and removes listeners'],initial,maximum,docked,evidence},null,2));
  test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);if(test_window)console.error(await evaluate('JSON.stringify({state:state(),saved,sash_events})'));test_window?.destroy();app.exit(1)});
