// 隔离 Electron 验证阅读/路径模块卸载、重载与异步取消，无真实 Typora 文件写入。
const { app, BrowserWindow } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { build } = require('esbuild');
const { editor_plugins } = require('./editor_bundle.cjs');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_reading_lifecycle_'));
app.setPath('userData', path.join(root, 'user_data')); app.disableHardwareAcceleration();
let test_window;
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const evaluate = source => test_window.webContents.executeJavaScript(source);
app.whenReady().then(async () => {
  test_window = new BrowserWindow({ show: false, width: 900, height: 600, webPreferences: { contextIsolation: false, backgroundThrottling: false, offscreen: true } });
  const filename = path.join(root, 'test.html');
  fs.writeFileSync(filename, '<!doctype html><meta charset="utf-8"><style>content{display:block;height:300px;overflow:auto}#write{height:3000px}#menu{display:block}</style><content><div id="write"><p>Reading content</p></div></content><ul id="menu"></ul>');
  await test_window.loadFile(filename);
  const bundle = await build({ plugins:editor_plugins(), stdin:{contents:'export { bind_reading_minimap } from "./src/reading_minimap"; export { bind_file_path_actions } from "./src/file_path_actions"; export { bind_reading_navigation, navigate_reading_target } from "./src/reading_navigation"; export { register_navigation_editor, notify_navigation_selection } from "./src/reading_navigation_ports"; export { create_reading_workspace } from "./src/reading_workspace"; export { reveal_markdown_location } from "./src/workspace_markdown_location";', resolveDir:path.join(__dirname,'..')}, bundle:true, loader:{'.css':'text'}, format:'iife', globalName:'qa', write:false });
  await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(() => {
    window.subscriptions=new Map(); window.commands=new Map(); window.notices=[]; window.copy_count=0;
    const on=(name,callback)=>{let set=subscriptions.get(name);if(!set)subscriptions.set(name,set=new Set());set.add(callback);return()=>set.delete(callback)};
    window.emit=(name,data)=>{for(const callback of subscriptions.get(name)||[])callback(data)};
    class View { onOpen(){} getState(){return {original:true}} setState(){} isEditor(){return true} }
    const leaf={state:{path:'/test/project-docs/P01.md'},containerEl:document.querySelector('content'),view:new View()};leaf.containerEl.classList.add('mod-active');leaf.view.leaf=leaf;leaf.view.containerEl=document.querySelector('#write');leaf.parent={activeLeaf:leaf,toggleTab(){return leaf}};
    window.leaf=leaf;window.original_methods={onOpen:View.prototype.onOpen,getState:View.prototype.getState,setState:View.prototype.setState};
    window.opened_paths=[];window.host={openFile(path){opened_paths.push(path)},commands:{register(command){commands.set(command.id,command);return()=>commands.delete(command.id)},run(){}},workspace:{activeLeaf:leaf,eachLeaves(callback){callback(leaf)},rootSplit:{on},on,activeEditor:{openFile(){}}}};
    window[Symbol.for('typora-code:workspace')]={app:host,Notice:class{constructor(message){notices.push(message)}}};
    window.File={bundle:{filePath:'/test/project-docs/P01.md'},getMountFolder(){return '/test'},editor:{tryOpenUrl(){},library:{openFile(path){opened_paths.push(path)}},selection:{buildUndo(){return null}},sourceView:{inSourceMode:false}}};
    window.reqnode=name=>name==='fs'?{statSync(path){if(path.endsWith('/missing.md'))throw Error('ENOENT');return{isFile:()=>true}}}:({normalize:p=>p,isAbsolute:p=>p.startsWith('/'),resolve:(...p)=>p.join('/'),dirname:p=>p.substring(0,p.lastIndexOf('/')),relative:(base,p)=>p.slice(base.length+1),basename:p=>p.split('/').pop(),sep:'/'});
    window.JSBridge={invoke(){copy_count++;return new Promise(resolve=>window.finish_copy=resolve)}};
    window.original_url=File.editor.tryOpenUrl;window.original_file=File.editor.library.openFile;window.original_app=host.openFile;window.original_editor=host.workspace.activeEditor.openFile;
  })()`);
  await evaluate('window.dispose_nav=qa.bind_reading_navigation(); window.dispose_paths=qa.bind_file_path_actions();window.dispose_map=qa.bind_reading_minimap();void 0;');
  assert(await evaluate('dispose_nav===qa.bind_reading_navigation()&&dispose_paths===qa.bind_file_path_actions()&&dispose_map===qa.bind_reading_minimap()'));
  assert.equal(await evaluate('commands.size'),2);
  await evaluate(`host.openFile('hardware.md')`);
  assert.equal(await evaluate('opened_paths.pop()'),'/test/project-docs/hardware.md','relative Markdown links use the source document directory');
  const missing_before=await evaluate('({html:document.querySelector("#write").innerHTML,path:File.bundle.filePath,leaf:leaf.state.path,scroll:document.querySelector("content").scrollTop,opens:opened_paths.length})');
  assert(await evaluate(`qa.navigate_reading_target('missing.md').then(()=>false,()=>true)`));
  assert.deepEqual(await evaluate('({html:document.querySelector("#write").innerHTML,path:File.bundle.filePath,leaf:leaf.state.path,scroll:document.querySelector("content").scrollTop,opens:opened_paths.length})'),missing_before,'missing target cannot clear or switch the current Markdown before failing');

  // 单次取消在原生打开之前生效，不能等其他导航完成后再打开已经取消的移交目标。
  await evaluate(`window.cancelled_open=new AbortController();cancelled_open.abort();window.cancelled_result=qa.navigate_reading_target('/test/cancelled.md',{signal:cancelled_open.signal}).then(()=>false,error=>/取消/.test(error.message));void 0;`);
  assert(await evaluate('cancelled_result'));
  assert.equal(await evaluate('opened_paths.length'),missing_before.opens,'pre-aborted navigation never enters the native opener');
  await evaluate(`window.blocking_open=new AbortController();window.blocking_result=qa.navigate_reading_target('/test/blocking.md',{signal:blocking_open.signal}).then(()=>false,error=>/取消/.test(error.message));window.queued_open=new AbortController();window.queued_result=qa.navigate_reading_target('/test/queued.md',{signal:queued_open.signal}).then(()=>false,error=>/取消/.test(error.message));void 0;`);
  await delay(70);
  assert.deepEqual(await evaluate('opened_paths.slice(-1)'),['/test/blocking.md']);
  await evaluate('queued_open.abort();void 0;');
  assert(await evaluate('queued_result'),'queued cancellation settles while the earlier native load is still pending');
  await evaluate('blocking_open.abort();void 0;');
  assert(await evaluate('blocking_result'));
  await delay(100);
  assert(!await evaluate(`opened_paths.includes('/test/queued.md')`),'cancelled queued target cannot open late');
  assert.deepEqual(await evaluate('({html:document.querySelector("#write").innerHTML,path:File.bundle.filePath,leaf:leaf.state.path,scroll:document.querySelector("content").scrollTop})'),{html:missing_before.html,path:missing_before.path,leaf:missing_before.leaf,scroll:missing_before.scroll},'cancelled transfer preserves current text, file identity and scroll');
  await evaluate(`window.locate_abort=new AbortController();window.locate_signal=null;window.locate_finished=false;window.locate_result=qa.navigate_reading_target('/test/project-docs/P01.md',{signal:locate_abort.signal,locate:signal=>{locate_signal=signal;return new Promise(resolve=>signal.addEventListener('abort',()=>{locate_finished=true;resolve()},{once:true}))}}).then(()=>false,error=>/取消/.test(error.message));void 0;`);
  for(let attempt=0;attempt<50&&!await evaluate('Boolean(locate_signal)');attempt++)await delay(20);
  assert(await evaluate('Boolean(locate_signal)'));
  await evaluate('locate_abort.abort();void 0;');
  assert(await evaluate('locate_result'));assert(await evaluate('locate_signal.aborted&&locate_finished'),'per-operation cancellation reaches the location callback');
  await evaluate(`document.querySelector('content').scrollTop=360;window.restore_abort=new AbortController();window.transfer_restore=qa.navigate_reading_target('/test/project-docs/P01.md',{signal:restore_abort.signal}).then(()=>false,error=>/取消/.test(error.message));void 0;`);
  await delay(160);
  await evaluate(`restore_abort.abort();document.querySelector('content').scrollTop=740;void 0;`);
  assert(await evaluate('transfer_restore'));await delay(100);
  assert.equal(await evaluate(`document.querySelector('content').scrollTop`),740,'cancelled operation cannot continue the target position restoration loop');

  await evaluate(`emit('file-menu',{menu:{containerEl:document.querySelector('#menu')},path:'/test/project-docs/P01.md'});commands.values().next().value.callback();`);
  await delay(30);
  assert.equal(await evaluate('copy_count'),1);
  assert.equal(await evaluate('document.querySelectorAll(".linux-note-path-item").length'),3);
  await evaluate(`window.pending_navigation=qa.navigate_reading_target('/test/b.md').then(()=>false,()=>true);dispose_nav();dispose_nav();dispose_paths();dispose_paths();dispose_map();dispose_map();finish_copy();`);
  assert(await evaluate('pending_navigation'));
  await delay(220);
  assert(await evaluate('File.editor.tryOpenUrl===original_url&&File.editor.library.openFile===original_file&&host.openFile===original_app&&host.workspace.activeEditor.openFile===original_editor'));
  assert(await evaluate('leaf.view.onOpen===original_methods.onOpen&&leaf.view.getState===original_methods.getState&&leaf.view.setState===original_methods.setState'));
  assert.equal(await evaluate('[...subscriptions.values()].reduce((sum,set)=>sum+set.size,0)'),0);
  assert.equal(await evaluate('commands.size'),0);assert.equal(await evaluate('notices.length'),0);
  assert.equal(await evaluate('document.querySelectorAll(".linux-note-path-item,.linux-note-reading-minimap,#linux-note-reading-minimap-style").length'),0);
  assert(await evaluate('![...document.documentElement.attributes].some(a=>/data-linux-note-(reading|copy-path|history)/.test(a.name))'));
  await evaluate(`window.workspace=qa.create_reading_workspace(()=>File.bundle.filePath,()=>false);window.restore_pending=workspace.restore(workspace.active(),{scroll_top:600,scroll_left:0});workspace.dispose();workspace.dispose();document.querySelector('content').scrollTop=900;`);
  assert.equal(await evaluate('restore_pending'),false);await delay(100);assert.equal(await evaluate("document.querySelector('content').scrollTop"),900);
  await evaluate('window.dispose_nav2=qa.bind_reading_navigation();window.dispose_paths2=qa.bind_file_path_actions();window.dispose_map2=qa.bind_reading_minimap();void 0;');
  assert.equal(await evaluate('commands.size'),2);assert.equal(await evaluate('document.querySelectorAll(".linux-note-reading-minimap").length'),1);
  await evaluate('dispose_nav2();dispose_paths2();dispose_map2();');
  // 同时存在内外两个原生链接入口时，真实点击可能直接进入内部方法。
  await evaluate(`File.editor.tryOpenUrl_=function(){document.querySelector('content').scrollTop=1200;};window.native_inner=File.editor.tryOpenUrl_;window.dispose_inner=qa.bind_reading_navigation();void 0;`);
  await delay(400);
  await evaluate(`document.querySelector('content').scrollTop=120;File.editor.tryOpenUrl_('#target');void 0;`);
  await delay(320);
  assert.equal(await evaluate("document.querySelector('content').scrollTop"),1200);
  await evaluate(`document.querySelector('#write').contentEditable='true';document.querySelector('#write').focus();void 0`);
  test_window.webContents.sendInputEvent({type:'keyDown',keyCode:'Left',modifiers:['alt']});
  test_window.webContents.sendInputEvent({type:'keyUp',keyCode:'Left',modifiers:['alt']});
  await delay(600);
  assert.equal(await evaluate("document.querySelector('content').scrollTop"),120,'内部链接入口可由Alt后退恢复来源');
  await evaluate('dispose_inner();void 0');
  assert(await evaluate('File.editor.tryOpenUrl_===native_inner'),'销毁恢复真实内部链接入口');
  // Monaco以textarea接收键盘，不能被普通表单的Alt保护误拦截。
  await evaluate(`window.source_position={kind:'source',file_path:'/test/code.c',view_id:-1,line:10,cursor:{startLineNumber:10},scroll_top:10,scroll_left:0};window.release_port=qa.register_navigation_editor({capture:()=>source_position,restore:async location=>{source_position=location;qa.notify_navigation_selection();return true}});window.dispose_source_nav=qa.bind_reading_navigation();qa.notify_navigation_selection();source_position={...source_position,line:11,cursor:{startLineNumber:11}};qa.notify_navigation_selection(true);const source_panel=document.createElement('section');source_panel.className='linux-note-source-file';source_panel.innerHTML='<textarea></textarea>';document.body.append(source_panel);source_panel.firstChild.focus();void 0;`);
  test_window.webContents.sendInputEvent({type:'keyDown',keyCode:'Left',modifiers:['alt']});
  test_window.webContents.sendInputEvent({type:'keyUp',keyCode:'Left',modifiers:['alt']});await delay(50);
  assert.equal(await evaluate('source_position.line'),10,'源码输入面中的Alt后退走共同历史');
  test_window.webContents.sendInputEvent({type:'keyDown',keyCode:'Right',modifiers:['alt']});
  test_window.webContents.sendInputEvent({type:'keyUp',keyCode:'Right',modifiers:['alt']});await delay(50);
  assert.equal(await evaluate('source_position.line'),11,'恢复引起的选区事件不污染前进历史');
  await evaluate(`dispose_source_nav();release_port();document.querySelector('.linux-note-source-file').remove();void 0;`);
  // 原生定位跨帧等待期间取消：不得滚动新视口或恢复旧选区。
  await evaluate(`(() => {
    const wrapper=document.createElement('div');wrapper.className='CodeMirror';wrapper.tabIndex=0;document.querySelector('#write').append(wrapper);
    let cursor={line:0,ch:0};window.undo_count=0;
    wrapper.CodeMirror={getCursor:()=>cursor,getRange:()=> 'a',setSelection(){},focus(){wrapper.focus()},scrollIntoView(){},charCoords:()=>({top:100,bottom:120})};
    File.editor.getMarkdown=()=> 'a';File.editor.sourceView.gotoLine=p=>{cursor={line:p.line,ch:p.ch};wrapper.focus()};File.editor.selection.buildUndo=()=>({type:'cursor',id:'p1',start:0});File.editor.undo={exeCommand(){undo_count++}};
    window.cancel_location=new AbortController();window.location_pending=qa.reveal_markdown_location({line:1,column:1,end_line:1,end_column:2,expected_text:'a'},cancel_location.signal).then(()=>false,error=>error.name==='AbortError');
    cancel_location.abort();document.querySelector('content').scrollTop=1000;
  })()`);
  assert(await evaluate('location_pending'));await delay(50);assert.equal(await evaluate('undo_count'),0);assert.equal(await evaluate("document.querySelector('content').scrollTop"),1000);
  console.log('PASS: reading/path dispose, rebind, command/event/DOM cleanup and cancelled navigation/position/reveal.');
  test_window.destroy();app.quit();
}).catch(error=>{console.error(error);test_window?.destroy();app.exit(1)});
