const {app,BrowserWindow}=require('electron'),{build}=require('esbuild'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_recent_ui_'));app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();let win;
app.whenReady().then(async()=>{
 win=new BrowserWindow({width:1000,height:750,show:false,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 await win.loadURL('data:text/html,<body><input id="draft" value="unsaved draft"><div id="bar"></div></body>');
 const run=async source=>{const result=await win.webContents.executeJavaScript(`(async()=>{try{return {ok:true,value:await (0,eval)(${JSON.stringify(source)})}}catch(error){return {ok:false,error:error.stack}}})()`);if(!result.ok)throw Error(result.error);return result.value;};
 const bundle=await build({stdin:{contents:'export {bind_workspace_recents} from "./src/workspace_recent";export {install_workspace_shortcuts} from "./src/workspace_shortcuts";export {begin_workspace_context_switch,finish_workspace_context_switch} from "./src/workspace_context";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},write:false,format:'iife',globalName:'qa'});await run(bundle.outputFiles[0].text);
 await run(`window.history_data={folders:[{path:'C:/project/Z',date:9},{path:'C:/project/A',date:2}],files:[{path:'C:/project/Z/new.md',date:8},{path:'C:/project/A/old.md',date:1}]};for(const group of ['folders','files'])history_data[group].forEach(item=>item.path=require('path').win32.normalize(item.path));window.operations=[];window.messages=[];window.stat_error=null;window.read_delay=0;window.JSBridge={invoke:async(name,target)=>{if(name==='setting.getRecentFiles'){await new Promise(r=>setTimeout(r,read_delay));return structuredClone(history_data);}operations.push([name,target]);const group=name==='setting.removeRecentFolder'?'folders':'files';history_data[group]=history_data[group].filter(i=>i.path!==target);}};window.files={fs:{promises:{stat:async target=>{if(stat_error&&target.length>3)throw Object.assign(Error(stat_error),{code:stat_error});return {isFile:()=>target.endsWith('.md'),isDirectory:()=>!target.endsWith('.md')};}}},path_api:require('path').win32,open_file:async target=>operations.push(['open',target]),core:{Notice:class {constructor(message){messages.push(message);}}}};window.binding=qa.bind_workspace_recents(files,async target=>operations.push(['folder',target]));window.shortcuts=qa.install_workspace_shortcuts({commands:{run:id=>{if(id==='linux_note:open_recent')binding.open();}},workspace:{}},{});window.picker=()=>document.querySelector('.workspace-recent-open');window.pause=()=>new Promise(r=>setTimeout(r,60));void 0`);
 const menu=await run(`binding.entries().then(entries=>entries.map(e=>e.label||'separator'))`);assert.deepEqual(menu,['C:\\project\\Z','C:\\project\\A','separator','C:\\project\\Z\\new.md','C:\\project\\A\\old.md','separator','更多…','清空最近打开记录…']);
 await run(`document.querySelector('#draft').focus();window.dispatchEvent(new KeyboardEvent('keydown',{key:'r',code:'KeyR',ctrlKey:true,bubbles:true,cancelable:true}));pause()`);
 assert.equal(await run('picker().hidden'),false);assert.deepEqual(await run(`[...picker().querySelectorAll('.workspace-recent-group')].map(n=>n.textContent)`),['文件夹','文件']);
 assert.equal(await run('picker().getBoundingClientRect().width'),600);assert.equal(await run(`picker().querySelector('.workspace-recent-row').getBoundingClientRect().height`),22);
 await run(`const input=picker().querySelector('input');input.value='new project';input.dispatchEvent(new Event('input'));void 0`);
 assert.equal(await run(`picker().querySelectorAll('.workspace-recent-row').length`),1);assert(await run(`picker().querySelectorAll('.workspace-quick-open-highlight').length>0`));
 await run(`picker().querySelector('input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));pause()`);assert.equal(await run('picker().hidden'),true);assert.deepEqual(await run('operations'),[['open','C:\\project\\Z\\new.md']]);
 await run(`document.querySelector('#draft').focus();binding.open();pause()`);await run(`picker().querySelector('.workspace-recent-remove').click();pause()`);assert.equal(await run('history_data.folders.length'),1);assert.equal(await run('operations.filter(item=>item[0]==="folder").length'),0,'removing does not open');
 await run(`stat_error='ENOENT';picker().querySelector('.workspace-recent-target').click();pause()`);assert.equal(await run('history_data.folders.length'),0);assert.equal(await run('messages.length'),1);assert.equal(await run('picker().querySelectorAll(".workspace-recent-row").length'),2);
 await run(`stat_error='EACCES';picker().querySelector('.workspace-recent-target').click();pause()`);assert.equal(await run('history_data.files.length'),2);assert.match(await run('picker().querySelector("[role=status]").textContent'),/EACCES/);assert(await run('picker().querySelector("[role=status]").classList.contains("is-visible")'));
 await run(`stat_error=null;for(const type of ['keydown','keyup'])picker().querySelector('input').dispatchEvent(new KeyboardEvent(type,{key:'Escape',code:'Escape',bubbles:true,cancelable:true}));pause()`);assert.equal(await run('picker().hidden'),true);assert.equal(await run('document.activeElement.id'),'draft');
 await run(`(async()=>{(await binding.entries()).at(-1).action();await pause()})()`);await run(`[...document.querySelectorAll('.git-graph-dialog-footer button')].find(b=>b.textContent==='取消').click();void 0`);assert.equal(await run('history_data.files.length'),2);
 await run(`(async()=>{(await binding.entries()).at(-1).action();await pause()})()`);await run(`history_data.files.push({path:'C:/concurrent.md',date:10});[...document.querySelectorAll('.git-graph-dialog-footer button')].find(b=>b.textContent==='清空记录').click();pause()`);assert.deepEqual(await run('history_data.files.map(i=>i.path)'),['C:/concurrent.md']);
 await run(`read_delay=100;binding.open();qa.begin_workspace_context_switch();qa.finish_workspace_context_switch();new Promise(r=>setTimeout(r,150))`);assert.equal(await run('picker().hidden'),true);assert.equal(await run('picker().querySelectorAll(".workspace-recent-row").length'),0);
 for(const theme of ['light','dark']){await run(`read_delay=0;document.documentElement.dataset.workspaceFileIconTheme=${JSON.stringify(theme)};binding.open();pause()`);win.webContents.setZoomFactor(1.25);assert.equal(await run('picker().querySelector(".workspace-recent-row").getBoundingClientRect().height'),22);assert.equal(await run(`getComputedStyle(picker().querySelector('.workspace-recent-remove svg')).width`),'16px');await run(`for(const type of ['keydown','keyup'])picker().querySelector('input').dispatchEvent(new KeyboardEvent(type,{key:'Escape',code:'Escape',bubbles:true,cancelable:true}));void 0`);}
 await run('shortcuts.dispose();binding.dispose();void 0');assert.equal(await run('document.querySelectorAll(".workspace-recent-open").length'),0);assert.equal(await run('document.querySelector("#draft").value'),'unsaved draft');
 console.log(JSON.stringify({status:'PASS',evidence,checks:['real-CtrlR','group-MRU','full-menu-paths','highlight','open','remove','missing','permission-visible','clear-cancel-concurrent','epoch-late','light-dark-125','focus-dispose-draft']}));win.destroy();app.quit();
}).catch(error=>{console.error(error.stack);if(win&&!win.isDestroyed())win.destroy();app.exit(1);});
