const { app, BrowserWindow } = require('electron');
const { build } = require('esbuild');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_workspace_widgets_'));
app.setPath('userData', path.join(evidence, 'profile'));
app.disableHardwareAcceleration();
let test_window;
const checks = [];
const evaluate = source => test_window.webContents.executeJavaScript(source);
const delay = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));
const key = async (key_code, modifiers = []) => {
  test_window.webContents.sendInputEvent({type: 'keyDown', keyCode: key_code, modifiers});
  test_window.webContents.sendInputEvent({type: 'keyUp', keyCode: key_code, modifiers});
  await delay(35);
};
const focus_is = async (selector, label) => {
  assert(await evaluate(`document.activeElement === document.querySelector(${JSON.stringify(selector)})`), label);
  checks.push(label);
};

app.whenReady().then(async () => {
  const fixture = path.join(evidence, 'fixture.html');
  fs.writeFileSync(fixture, '<!doctype html><meta charset="utf-8"><style>.git-graph-dialog-shade{position:fixed;inset:0;background:#eee}.git-graph-dialog{padding:20px}.git-graph-dialog-content{display:grid;gap:8px}.css-hidden{display:none}</style><button id="opener">Open settings</button><button id="outside">Outside</button>');
  test_window = new BrowserWindow({show: false, width: 800, height: 600, webPreferences: {contextIsolation: false, backgroundThrottling: false}});
  await test_window.loadFile(fixture);
  const bundle = await build({stdin: {contents: 'export { workspace_dialog, dispose_workspace_widgets } from "./src/workspace_widgets";', resolveDir: path.join(__dirname, '..')}, bundle: true, format: 'iife', globalName: 'widgets_qa', write: false});
  await evaluate(bundle.outputFiles[0].text);
  await evaluate(`document.querySelector('#opener').focus();window.dialog=widgets_qa.workspace_dialog('Settings');dialog.content.innerHTML='<input type=hidden><input disabled><fieldset disabled><input></fieldset><section hidden><input></section><input class=css-hidden><input style="visibility:hidden"><section inert><input></section><input id=first aria-label=Search><input id=second aria-label=Value><section id=filtered hidden><input id=filtered-input></section>';dialog.footer.querySelector('button').id='close';`);
  await delay(60);
  await focus_is('#first', 'autofocus skips hidden, disabled, fieldset-disabled and inert controls');
  await key('Tab', ['shift']);
  await focus_is('#close', 'Shift Tab from first visible field reaches the visible close button');
  await key('Tab');
  await focus_is('#first', 'Tab at the end returns to the first visible control');
  await key('Tab');
  await focus_is('#second', 'native Tab traverses the next available field');
  await evaluate("document.querySelector('#second').disabled=true");
  await key('Tab');
  await focus_is('#first', 'disabling the focused input returns lost focus to the active modal');
  await evaluate("document.querySelector('#first').focus();document.querySelector('#first').hidden=true");
  await key('Tab', ['shift']);
  await focus_is('#close', 'filtering the focused field cannot move focus behind the modal');
  await evaluate("document.querySelector('#first').hidden=false;document.querySelector('#filtered').hidden=false;document.querySelector('#first').focus()");
  await key('Tab');
  await focus_is('#filtered-input', 'unfiltering a field immediately restores its keyboard accessibility');
  await evaluate("window.nested=widgets_qa.workspace_dialog('Nested');nested.content.innerHTML='<input id=nested-first>'");
  await delay(50);
  await focus_is('#nested-first', 'a nested modal owns initial focus');
  await key('Escape');
  assert.equal(await evaluate("document.querySelectorAll('.git-graph-dialog-shade').length"), 1);
  await focus_is('#filtered-input', 'Escape closes only the top dialog and restores its opener');
  await evaluate("dialog.root.querySelectorAll('input,button').forEach(node=>node.disabled=true)");
  await key('Tab');
  await focus_is('.git-graph-dialog', 'a dialog with no enabled controls retains focus on its panel');
  await key('Escape');
  await focus_is('#opener', 'closing an empty-control dialog restores the original page focus');
  await evaluate("document.querySelector('#outside').focus();dialog.close()");
  await focus_is('#outside', 'repeated close is idempotent and does not steal focus');
  await evaluate("window.pending=widgets_qa.workspace_dialog('Cancelled before focus');widgets_qa.dispose_workspace_widgets()");
  await delay(50);
  await focus_is('#outside', 'disposal cancels pending autofocus and restores prior focus');
  await key('Tab', ['shift']);
  await focus_is('#opener', 'disposal removes modal key handlers and restores ordinary Tab navigation');
  assert.equal(await evaluate("document.querySelectorAll('.git-graph-dialog-shade').length"), 0);
  console.log(JSON.stringify({status: 'PASS', checks, evidence}));
  test_window.destroy(); app.exit(0);
}).catch(error => { console.error(error); console.error(evidence); test_window?.destroy(); app.exit(1); });
