const {app,BrowserWindow}=require('electron');const {build}=require('esbuild');const {editor_plugins}=require('./editor_bundle.cjs');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_breadcrumbs_'));app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();
let win;const checks=[],ev=code=>{fs.writeFileSync(path.join(evidence,"last_eval.js"),code);return win.webContents.executeJavaScript(code)},pause=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async(code)=>{for(let i=0;i<160;i++){if(await ev(code))return;await pause(40);}throw Error('timeout '+code+' '+await ev('JSON.stringify({text:document.body.innerText,errors,geometry:[...document.querySelectorAll(".workspace-breadcrumbs")].map(n=>[n.getBoundingClientRect().height,n.scrollWidth,n.clientWidth,n.firstChild.scrollHeight,n.firstChild.getBoundingClientRect().height,[...n.firstChild.querySelectorAll("*")].map(c=>({tag:c.tagName,cls:c.className.baseVal||c.className,text:c.textContent,rect:c.getBoundingClientRect().toJSON(),line:getComputedStyle(c).lineHeight}))])})'));};
app.whenReady().then(async()=>{
 await (await import('./build_source_symbol_assets.mjs')).build_source_symbol_assets(path.join(evidence,'typora_code'));
 const project=path.join(evidence,'project');fs.mkdirSync(path.join(project,'docs'),{recursive:true});fs.writeFileSync(path.join(project,'docs','one.md'),'# One\n');fs.writeFileSync(path.join(project,'docs','two.md'),'# Two\n');
 win=new BrowserWindow({show:false,width:1100,height:740,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});

 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;font:13px Segoe UI}#groups{display:flex;height:660px}#left,#right{display:flex;flex:1;flex-direction:column;min-width:0}.workspace-tab-strip{height:32px;flex:0 0 32px;background:#fafafd}#editor,#second{flex:1;min-height:0}#native{height:600px;overflow:auto}.typ-markdown-view h1,.typ-markdown-view h2{margin:0;padding-top:14px}#sidebar-content{display:none}</style><button id="outside">外部操作</button><div id="groups"><div id="left"><div class="workspace-tab-strip">one.md</div><div id="editor"></div></div><div id="right"><div class="workspace-tab-strip">two.md</div><div id="second"></div></div></div><div id="typora-sidebar" class="active-tab-outline open"><div id="sidebar-content"><div id="outline-content"></div></div></div>');await win.loadFile(html);
 win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
 const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export {bind_workspace_breadcrumbs} from "./src/workspace_breadcrumbs";export * from "./src/workspace_breadcrumbs_settings";export {install_workspace_source_outline} from "./src/workspace_source_outline";export {source_file_uri} from "./src/workspace_file_uri";export * from "./src/workspace_document_symbols";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.css':'text'},format:'iife',globalName:'qa'});await ev(bundle.outputFiles[0].text);
 await ev(String.raw`window.reqnode=require;window._options={userDataPath:${JSON.stringify(evidence)}};window.project=${JSON.stringify(project)};window.errors=[];window.addEventListener('error',e=>errors.push(String(e.error||e.message)));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));window.store={};window.fail_save=false;window.commands={};window.listeners=new Set();window.editor=qa.monaco.editor.create(document.querySelector('#editor'),{automaticLayout:true});window.second=qa.monaco.editor.create(document.querySelector('#second'),{automaticLayout:true});window.left={containerEl:document.querySelector('#left')},right={containerEl:document.querySelector('#right')};window.leaves=[];window.workspace={activeLeaf:null,eachLeaves:f=>leaves.forEach(f),on:(event,f)=>{listeners.add(f);return()=>listeners.delete(f)}};window.core={Notice:class{constructor(m){errors.push(m)}},app:{workspace,commands:{register:c=>{commands[c.id]=c;return()=>delete commands[c.id]},run:id=>commands[id]?.callback()},settings:{get:k=>store[k],set_and_save:(k,v)=>{if(fail_save)throw Error('fixture settings denied');store[k]=v}}}};window[Symbol.for('typora-code:workspace')]=core;window.opened=[];window.files={core,fs:require('fs'),path_api:require('path'),context_root:()=>project,copy:t=>window.copied=t,open_file:async(...args)=>{opened.push([args[0],args[1],args[2]===left?'left':'right'])},reopen_leaf:async()=>true};window.set_file=(group,editor,name,language,text)=>{if(!qa.monaco.languages.getLanguages().some(l=>l.id===language))qa.monaco.languages.register({id:language});const model=qa.monaco.editor.createModel(text,language);editor.setModel(model);const leaf={state:{path:qa.source_file_uri(require('path').join(project,'docs',name))},parent:group,view:{editor:{focused_editor:()=>editor}},containerEl:editor.getDomNode()};group.activeLeaf=leaf;leaves=leaves.filter(l=>l.parent!==group);leaves.push(leaf);workspace.activeLeaf=leaf;for(const f of listeners)f();return leaf};window.NativeWorker=Worker;window.parse_requests=0;window.Worker=class extends NativeWorker{postMessage(m,...a){if(m.language)parse_requests++;return super.postMessage(m,...a)}};window.first=set_file(left,editor,'one.md','markdown','# 根标题\r\n\r\n## 第一节\r\n正文\r\n\r\n~~~md\r\n# 假标题\r\n~~~\r\n\r\n## 第二节\r\n正文\r\n');window.other=set_file(right,second,'two.md','markdown','# 独立文件\n\n## 独立标题\n');workspace.activeLeaf=first;window.binding=qa.bind_workspace_breadcrumbs(core,files);void 0`);
 const check=async(label,code)=>{assert(await ev(code),label+' '+await ev('JSON.stringify({text:document.body.innerText,errors,geometry:[...document.querySelectorAll(".workspace-breadcrumbs")].map(n=>[n.getBoundingClientRect().height,n.scrollWidth,n.clientWidth,n.firstChild.scrollHeight,n.firstChild.getBoundingClientRect().height,[...n.firstChild.querySelectorAll("*")].map(c=>({tag:c.tagName,cls:c.className.baseVal||c.className,text:c.textContent,rect:c.getBoundingClientRect().toJSON(),line:getComputedStyle(c).lineHeight}))])})'));checks.push(label);};
 await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('根标题')`);
 await check('one 22px row per group and relative file path',`document.querySelectorAll('.workspace-breadcrumbs').length===2&&document.querySelector('#left .workspace-breadcrumbs').getBoundingClientRect().height===22&&document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('one.md')`);
 await ev(String.raw`editor.setPosition({lineNumber:10,column:4});editor.focus();void 0`);await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('第二节')`);
 await check('cursor follows nested Markdown and groups stay independent',`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('# 根标题')&&document.querySelector('#right .workspace-breadcrumb-trail').textContent.includes('独立文件')`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click()`);await wait(`document.querySelector('.workspace-breadcrumb-tree')?.textContent.includes('第一节')`);
 await check('picker lists real Markdown headings and ignores fenced fake headings',`!document.querySelector('.workspace-breadcrumb-tree').textContent.includes('假标题')&&document.querySelectorAll('.workspace-breadcrumb-item').length===3`);
 await ev(String.raw`[...document.querySelectorAll('.workspace-breadcrumb-item')].find(n=>n.textContent.includes('第一节')).click()`);await pause(100);
 await check('heading selection reveals exact CRLF model line and retains editor',`editor.getSelection().startLineNumber===3&&editor.hasTextFocus()&&!document.querySelector('.workspace-breadcrumb-picker')&&editor.getModel().getValue().includes('假标题')`);
 await ev(String.raw`editor.setSelection({startLineNumber:4,startColumn:1,endLineNumber:4,endColumn:3});editor.focus();document.querySelector('#left .workspace-breadcrumb-segment:last-child').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,cancelable:true}));document.querySelector('#left .workspace-breadcrumb-segment:last-child').click()`);await pause(100);win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(100);
 await check('Escape returns to Monaco selection without a mouse refocus',`!document.querySelector('.workspace-breadcrumb-picker')&&editor.hasTextFocus()&&editor.getSelection().startLineNumber===4&&editor.getSelection().endColumn===3`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click()`);await pause(60);await ev(String.raw`document.querySelector('#outside').dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));document.querySelector('#outside').focus()`);await pause(80);
 await check('outside click closes picker and leaves focus at clicked target',`!document.querySelector('.workspace-breadcrumb-picker')&&document.activeElement.id==='outside'`);
 await ev(String.raw`document.querySelectorAll('#left .workspace-breadcrumb-segment')[1].click()`);await wait(`document.querySelector('.workspace-breadcrumb-tree')?.textContent.includes('two.md')`);await ev(String.raw`[...document.querySelectorAll('.workspace-breadcrumb-item')].find(n=>n.querySelector('.workspace-breadcrumb-label').textContent==='two.md').click()`);await pause(80);
 await check('file picker uses owning group and opens only on selection',`opened.length===1&&opened[0][0].endsWith('two.md')&&opened[0][2]==='left'`);
 await ev(String.raw`first=set_file(left,editor,'one.ts','typescript','class Device {\n  reset() { const counter = 1; return counter; }\n}\nfunction stop() {}');workspace.activeLeaf=first;window.outline=qa.install_workspace_source_outline(document.querySelector('#typora-sidebar'),()=>project);void 0`);await wait(`document.querySelector('.workspace-source-outline').textContent.includes('reset')&&document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('Device')`);
 await check('outline and breadcrumb share one actual parser request',`parse_requests===1`);
 await ev(String.raw`editor.setPosition({lineNumber:2,column:14});editor.focus()`);await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('reset')`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click()`);await wait(`document.querySelector('.workspace-breadcrumb-tree')?.textContent.includes('stop')`);await ev(String.raw`[...document.querySelectorAll('.workspace-breadcrumb-item')].find(n=>n.textContent==='stop').click()`);await pause(80);
 await check('ordinary source editor does not show an unavailable editor switch',`!document.querySelector('#left .workspace-breadcrumb-editor-type').textContent`);
 await check('function selection uses exact grammar range',`editor.getModel().getValueInRange(editor.getSelection())==='stop'&&editor.hasTextFocus()`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'user','file_path','last');qa.update_breadcrumb_settings(project,'workspace','icons',false);qa.update_breadcrumb_settings(project,'user','symbol_sort_order','name','typescript');void 0`);await pause(100);
 await check('settings resolve defaults user workspace and language scope',`qa.read_breadcrumb_settings(project,'typescript').file_path==='last'&&qa.read_breadcrumb_settings(project,'typescript').symbol_sort_order==='name'&&qa.read_breadcrumb_settings(project,'markdown').symbol_sort_order==='position'&&!document.querySelector('#left .workspace-breadcrumb-segment .git-standard-icon')`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'user','symbol_path_separator','::','typescript');qa.update_breadcrumb_settings(project,'workspace','symbol_path_separator','','typescript');void 0`);
 await check('language separator follows workspace override and preserves empty string',`qa.read_breadcrumb_settings(project,'typescript').symbol_path_separator===''&&qa.read_breadcrumb_settings('','typescript').symbol_path_separator==='::'&&qa.read_breadcrumb_settings(project,'markdown').symbol_path_separator==='.'`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'workspace','symbol_path_separator',undefined,'typescript');void 0`);
 await check('language separator reset inherits user language setting',`qa.read_breadcrumb_settings(project,'typescript').symbol_path_separator==='::'`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'workspace','icons',undefined);window.before=JSON.stringify(store);fail_save=true;try{qa.update_breadcrumb_settings(project,'user','enabled',false)}catch{}fail_save=false;void 0`);await pause(80);
 await check('reset inherits defaults and failed save preserves effective state',`qa.read_breadcrumb_settings(project).icons===true&&JSON.stringify(store)===before&&qa.read_breadcrumb_settings(project).enabled===true`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click();editor.getModel().setValue('function replacement() {}');void 0`);await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('replacement')`);
 await check('edit invalidates old picker and publishes one new shared snapshot',`!document.querySelector('.workspace-breadcrumb-picker')&&document.querySelector('.workspace-source-outline').textContent.includes('replacement')&&parse_requests===2`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'user','enabled',false);void 0`);await pause(80);await check('disabled removes the entire navigation row',`[...document.querySelectorAll('.workspace-breadcrumbs')].every(n=>n.getBoundingClientRect().height===0)`);
 await ev(String.raw`editor.focus();window.dispatchEvent(new KeyboardEvent('keydown',{key:'.',code:'Period',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true}));void 0`);await wait(`document.querySelector('.workspace-breadcrumb-picker')`);await check('Ctrl Shift period enables focuses and opens the current symbol',`qa.read_breadcrumb_settings(project).enabled&&document.activeElement.matches('.workspace-breadcrumb-filter input')`);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(100);
 // 延迟目录不能在窗口和文件切换后重新打开。
 await ev(String.raw`window.real_readdir=files.fs.promises.readdir;window.resolve_directory=null;files.fs={promises:{readdir:()=>new Promise(r=>resolve_directory=r)}};document.querySelector('#left .workspace-breadcrumb-segment').click();void 0`);await pause(80);await ev(String.raw`first=set_file(left,editor,'fresh.md','markdown','# 新文档');workspace.activeLeaf=first;void 0`);await pause(100);await ev(String.raw`resolve_directory([{name:'stale.md',isFile:()=>true,isDirectory:()=>false,isSymbolicLink:()=>false}]);files.fs=require('fs');void 0`);await pause(150);
 await check('late directory result cannot revive stale file picker',`!document.querySelector('.workspace-breadcrumb-picker')&&!document.body.textContent.includes('stale.md')`);

 // 工作区开关优先级和同一位置边界，验证命令与配置不是两份私有状态。
 await check('next heading owns its exact first offset',String.raw`qa.document_symbol_chain(qa.markdown_document_symbols('# A\n## B\n## C\n'),9).at(-1)?.name==='C'`);
 await ev(String.raw`qa.update_breadcrumb_settings(project,'workspace','enabled',false);qa.set_breadcrumb_enabled(project,true);qa.open_breadcrumb_settings(project,'markdown');void 0`);await pause(100);
 await check('toggle updates workspace override and settings uses selected scope',`qa.read_breadcrumb_settings(project).enabled&&document.querySelector('[aria-label="设置作用域"]').value==='user'`);
 await ev(String.raw`document.querySelector('[aria-label="设置作用域"]').value='workspace';document.querySelector('[aria-label="设置作用域"]').dispatchEvent(new Event('change'));document.querySelector('[aria-label="显示面包屑"]').click();void 0`);await pause(100);
 await check('settings UI saves current scope without mutating user preference',`qa.read_breadcrumb_settings(project).enabled===false&&qa.read_breadcrumb_settings('').enabled===true`);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(80);await ev(String.raw`qa.set_breadcrumb_enabled(project,true);editor.focus();void 0`);await pause(100);
 const point=await ev(`(()=>{const r=document.querySelector('#left .workspace-breadcrumb-segment:last-child').getBoundingClientRect();return{x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);
 win.webContents.sendInputEvent({type:'mouseMove',...point});win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...point});await wait(`document.querySelector('.workspace-breadcrumb-picker')`);
 await check('real Chromium pointer opens the entire breadcrumb button',`document.querySelector('.workspace-breadcrumb-picker').textContent.includes('新文档')`);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(80);
 await ev(String.raw`first=set_file(left,editor,'headings.md','markdown','# Root\n\n## First\n\n## Last');workspace.activeLeaf=first;editor.setPosition({lineNumber:3,column:4});editor.focus();void 0`);await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('First')`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click();void 0`);await pause(80);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Down'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Down'});win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return'});await pause(100);
 await check('picker arrow and Enter navigate sibling headings',`editor.getSelection().startLineNumber===5&&editor.hasTextFocus()`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click();void 0`);await pause(60);await ev(String.raw`const input=document.querySelector('.workspace-breadcrumb-filter input');input.value='First';input.dispatchEvent(new Event('input'));void 0`);await pause(70);
 await check('filter retains hierarchy while excluding unrelated headings',`document.querySelector('.workspace-breadcrumb-tree').textContent.includes('Root')&&document.querySelector('.workspace-breadcrumb-tree').textContent.includes('First')&&!document.querySelector('.workspace-breadcrumb-tree').textContent.includes('Last')`);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(80);

 // 原生正文身份不依赖另一编辑组的键盘焦点；选择后才切换活动组。
 await ev(String.raw`window.original_File=window.File;window.native_content=document.createElement('content');native_content.innerHTML='<div id="write" contenteditable="true"><h1>Native root</h1><h2>Native child</h2></div>';document.body.append(native_content);window.native_path=files.path_api.join(project,'docs','native.md');window.File={bundle:{filePath:native_path},isFileLoading:()=>false};window.native_leaf={state:{path:native_path},parent:left,view:{isEditor:()=>true,containerEl:editor.getDomNode()},containerEl:editor.getDomNode()};left.activeLeaf=native_leaf;leaves=[native_leaf,other];workspace.activeLeaf=other;for(const f of listeners)f();void 0`);await pause(150);
 await check('inactive native group keeps headings by document identity',`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('Native root')&&workspace.activeLeaf===other`);
 await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click();void 0`);await wait(`document.querySelector('.workspace-breadcrumb-tree')?.textContent.includes('Native child')`);await ev(String.raw`[...document.querySelectorAll('.workspace-breadcrumb-item')].find(n=>n.textContent.includes('Native child')).click();void 0`);await pause(100);
 await check('native heading selection activates its owning editor and caret',`workspace.activeLeaf===native_leaf&&document.querySelector('#write h2').contains(getSelection().anchorNode)&&document.activeElement.id==='write'`);
 await ev(String.raw`window.File=original_File;native_content.remove();first=set_file(left,editor,'headings.md','markdown','# Root\n\n## First\n\n## Last');editor.setPosition({lineNumber:5,column:4});editor.focus();void 0`);await wait(`document.querySelector('#left .workspace-breadcrumb-trail').textContent.includes('Last')`);

 for(const zoom of [1,1.25])for(const theme of ['light','dark']){win.webContents.setZoomFactor(zoom);await ev(String.raw`document.querySelector('#left').style.maxWidth='260px';document.documentElement.dataset.workspaceFileIconTheme='${theme}';document.body.style.backgroundColor='${theme==='dark'?'#202122':'white'}';document.body.style.setProperty('--bg-color','${theme==='dark'?'#202122':'white'}');document.body.style.setProperty('--text-color','${theme==='dark'?'#ddd':'#222'}');void 0`);await pause(120);await check('bounded single row '+theme+' '+zoom,`(()=>{const bar=document.querySelector('#left .workspace-breadcrumbs'),trail=bar.firstChild;return bar.getBoundingClientRect().height===22&&bar.scrollWidth<=bar.clientWidth+1&&trail.scrollHeight<=22})()`);await check('full-width non-intercepting bottom divider '+theme+' '+zoom,`[...document.querySelectorAll('.workspace-breadcrumbs:not([hidden])')].every(n=>{const line=getComputedStyle(n,'::after'),r=n.getBoundingClientRect();return line.content==='\"\"'&&line.position==='absolute'&&line.bottom==='0px'&&line.left==='0px'&&line.right==='0px'&&line.height==='1px'&&line.pointerEvents==='none'&&line.backgroundColor==='${theme==='dark'?'rgb(42, 43, 44)':'rgb(228, 229, 230)'}'&&r.height===22&&n.firstChild.getBoundingClientRect().height===22})`);await ev(String.raw`document.querySelector('#left .workspace-breadcrumb-segment:last-child').click();void 0`);await wait(`document.querySelector('.workspace-breadcrumb-item[aria-selected=true]')`);
 const point=await ev(`(()=>{const r=document.querySelector('.workspace-breadcrumb-item[aria-selected=true]').getBoundingClientRect();return{x:Math.round((r.x+r.width/2)*${zoom}),y:Math.round((r.y+r.height/2)*${zoom})}})()`);win.webContents.sendInputEvent({type:'mouseMove',...point});await pause(60);
 await check('selected text remains readable including hover '+theme+' '+zoom,`(()=>{const row=document.querySelector('.workspace-breadcrumb-item[aria-selected=true]');if(!row.matches(':hover'))return false;const s=getComputedStyle(row),rgb=c=>c.match(/[0-9.]+/g).map(Number),fg=rgb(s.color),bg=rgb(s.backgroundColor),base=rgb(getComputedStyle(document.body).getPropertyValue('--bg-color')==='white'?'rgb(255,255,255)':'rgb(32,33,34)'),alpha=bg[3]??1;const luminance=c=>c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),a=luminance(fg),b=luminance(bg.map((v,i)=>v*alpha+base[i]*(1-alpha)));return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5})()`);
 fs.writeFileSync(path.join(evidence,theme+'_'+zoom+'.png'),(await win.webContents.capturePage()).toPNG());win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(70);}
 await ev(String.raw`outline.dispose();binding.dispose();editor.getModel().setValue('# after dispose');void 0`);await pause(200);await check('dispose cleans rows parsers and listeners',`!document.querySelector('.workspace-breadcrumbs,.workspace-breadcrumb-picker')&&errors.length===0`);
 fs.writeFileSync(path.join(evidence,'result.json'),JSON.stringify({checks},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence}));win.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(win&&!win.isDestroyed()){fs.writeFileSync(path.join(evidence,'failure.png'),(await win.webContents.capturePage()).toPNG());win.destroy();}app.exit(1);});
