import assert from "node:assert/strict";
import fs from "node:fs";
import { transform } from "esbuild";

const compiled = await transform(fs.readFileSync('src/reading_history.ts', 'utf8'), { loader: 'ts', format: 'esm' });
const { create_reading_history } = await import(`data:text/javascript;base64,${Buffer.from(compiled.code).toString('base64')}`);
const location = (file_path, scroll_top) => ({ file_path, scroll_top, scroll_left: 0, cursor: null });
const history = create_reading_history(3);
let current = location('chapter_a.md', 10);
const restore = async (target) => { current = target; return true; };
assert.equal(history.can_travel(-1), false);
assert.equal(history.can_travel(1), false);
assert.equal(await history.travel(-1, current, restore), false);
history.record_jump(current, location('chapter_a.md', 800));
assert.equal(history.can_travel(-1), true);
assert.equal(history.can_travel(1), false);
current = location('chapter_a.md', 920);
assert.equal(await history.travel(-1, current, restore), true);
assert.equal(history.can_travel(-1), false);
assert.equal(history.can_travel(1), true);
assert.equal(current.scroll_top, 10);
assert.equal(await history.travel(1, current, restore), true);
assert.equal(current.scroll_top, 920, '前进恢复离开目标时的阅读位置');
history.record_jump(current, location('chapter_b.md', 50));
current = location('chapter_b.md', 50);
assert.equal(await history.travel(-1, current, async () => false), false, '取消文件打开');
assert.equal(await history.travel(-1, current, restore), true, '取消后历史索引不变');
assert.equal(current.file_path, 'chapter_a.md');
history.record_jump(current, location('chapter_c.md', 70));
current = location('chapter_c.md', 70);
assert.equal(await history.travel(1, current, restore), false, '新跳转清除旧前进分支');
await assert.rejects(history.travel(-1, current, async () => { throw new Error('open failed'); }));
assert.equal(await history.travel(-1, current, restore), true, '打开异常后可再次导航');
history.record_jump(current, current);
let finish;
const pending = history.travel(-1, current, () => new Promise((resolve) => { finish = resolve; }));
assert.equal(history.can_travel(-1), false, '导航期间禁用历史按钮');
assert.equal(history.can_travel(1), false, '导航期间禁用前进按钮');
assert.equal(await history.travel(-1, current, restore), false, '导航期间不重复打开文件');
finish(false);
await pending;
const pane_history = create_reading_history();
const left_pane = { ...location('chapter_a.md', 80), view_id: 1 };
const right_pane = { ...left_pane, view_id: 2 };
pane_history.record_jump(left_pane, right_pane);
let restored_pane;
assert.equal(await pane_history.travel(-1, right_pane, async (target) => { restored_pane = target.view_id; return true; }), true);
assert.equal(restored_pane, 1, '同一文件同一滚动位置也要区分来源栏');
console.log('reading history: anchors, files, scroll restoration, branching, cancellation and reentrancy passed');
const source = (line, view_id = -1) => ({...location('code.c', line * 10), kind:'source', view_id, line, cursor:{startLineNumber:line,startColumn:1}});
const cursor_history = create_reading_history();
cursor_history.record_selection(source(1));
cursor_history.record_selection(source(5));
assert.equal(cursor_history.can_travel(-1),false,'普通光标近邻替换');
cursor_history.record_selection(source(6),true);
let selection;
assert(await cursor_history.travel(-1,source(6),async target=>{selection=target;return true;}));
assert.equal(selection.line,5,'明确定位即使相邻仍可返回');
cursor_history.record_selection(source(7));
assert(cursor_history.can_travel(1),'返回后普通近邻移动保留前进');
cursor_history.record_selection(source(25));
assert(!cursor_history.can_travel(1),'新的远距离移动截断前进');
const bounded=create_reading_history();for(let i=0;i<1000;i++)bounded.record_selection(source(i*10+1));
let count=0;while(await bounded.travel(-1,source(9991-count*10),async()=>true))count++;
assert.equal(count,49,'连续1000次定位只保留50项');
console.log('navigation selection: near/far, explicit, forward branch and 50-entry bound passed');
for(const count of [20,100,1000]){
  const switched=create_reading_history();
  for(let iteration=0;iteration<count;iteration++){
    switched.record_jump(location('old/a',0),location('old/b',0));
    let complete_old;
    const old=switched.travel(-1,location('old/b',0),()=>new Promise(resolve=>{complete_old=resolve;}));
    switched.clear();
    assert.equal(switched.can_travel(-1),false);
    switched.record_jump(location('new/a',0),location('new/b',0));
    let complete_new;
    const next=switched.travel(-1,location('new/b',0),()=>new Promise(resolve=>{complete_new=resolve;}));
    complete_old(true);assert.equal(await old,false);
    assert.equal(switched.is_navigating(),true,'old completion cannot unlock the new navigation');
    complete_new(true);assert.equal(await next,true);
    assert.equal(switched.can_travel(-1),false);
    switched.clear();
  }
  console.log(`workspace navigation invalidation: ${count} pending old/new callbacks passed`);
}
