// 隐藏Electron与真实Monaco；跨窗快照只走内存，文件写入限临时夹具。
const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {build}=require('esbuild');
const {editor_plugins}=require('./editor_bundle.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_document_transfer_'));
const workspace=path.join(root,'project');fs.mkdirSync(workspace);
const file=path.join(workspace,'draft.c'),markdown=path.join(workspace,'note.md'),background=path.join(workspace,'background.md');
const other=path.join(workspace,'other.c'),third=path.join(workspace,'third.c');fs.writeFileSync(other,'int other;\n');fs.writeFileSync(third,'int third;\n');
const initial='int value = 1; // 😀\n';fs.writeFileSync(file,initial);fs.writeFileSync(markdown,'# Title\n\nBaseline\n');fs.writeFileSync(background,'# Background\n');
app.setPath('userData',path.join(root,'profile'));app.disableHardwareAcceleration();
app.on('window-all-closed',()=>{});
const windows=new Set(),checks=[];let bundle;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=async(win,code)=>{const result=await win.webContents.executeJavaScript(`Promise.resolve().then(()=>eval(${JSON.stringify(code)})).then(value=>({ok:true,value}),error=>({ok:false,message:String(error),stack:error?.stack}))`);if(!result.ok)throw Error(result.message);return result.value;};
const wait=async(win,code)=>{for(let i=0;i<250;i++){if(await evaluate(win,code))return;await delay(20);}throw Error('Timed out: '+code);};
const close=win=>{windows.delete(win);win.destroy();};
async function create_window(){
 const win=new BrowserWindow({show:false,width:1000,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false,offscreen:true}});windows.add(win);
 const html=path.join(root,'fixture.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{height:100%;margin:0}#tabs{height:30px}#editor{height:620px}content{display:block;height:600px;overflow:auto}footer{height:24px}.leaf{height:100%}</style><div id="tabs" class="typ-workspace-tab-header"></div><div id="editor"></div><content><div id="write"></div></content><footer class="ty-footer"><span id="footer-word-count">0</span></footer>');
 await win.loadFile(html);await win.webContents.executeJavaScript(bundle);
 await evaluate(win,`(()=>{
  window.root_path=${JSON.stringify(workspace)};window.leaves=[];window.factories=new Map();window.events=new Map();window.native_text='';window.native_dirty=false;window.native_saves=0;window.reload_calls=[];window.native_load_wait=null;window.native_load_started=false;window.no_other_window=true;window.shared_native_snapshot=null;window.shared_query_wait=null;window.shared_query_started=false;
  window.transfer_fs={...require('fs'),promises:{...require('fs').promises}};
  window.reqnode=name=>name==='fs'?transfer_fs:name==='electron'?{shell:{},clipboard:{writeText(){}},ipcRenderer:{invoke:async()=>{}}}:require(name);
  window.JSBridge={invoke:async command=>{if(command!=='document.noOtherWindow')throw Error('Unexpected bridge command');shared_query_started=true;if(shared_query_wait)await shared_query_wait;return no_other_window;}};window.ClientCommand={save(){native_saves++},saveAll(){native_saves++}};
  window.File={getMountFolder:()=>root_path,setMountFolder:path=>root_path=path,bundle:{filePath:'',savedContent:''},option:{enableAutoSave:false},changeCounter:{isDocumentEdited:()=>native_dirty},editor:{getMarkdown:()=>native_text,library:{openFile:()=>{}}},ChangeType:{NSChangeDone:0},updateChangeCount(){native_dirty=true},reloadContent(text,options){reload_calls.push({text,options});native_text=text;native_dirty=true;document.querySelector('#write').textContent=text}};
  class base_view{constructor(leaf){this.leaf=leaf;this.containerEl=document.createElement('section')}onOpen(){}onClose(){}}
  window.group={containerEl:document.querySelector('#tabs'),get activeLeaf(){return active?.parent===this?active:this.children[0]},get children(){return leaves.filter(leaf=>leaf.parent===this)},insertChild(index,leaf){const children=this.children;leaf.parent=this;const at=children[index];leaves.splice(at?leaves.indexOf(at):leaves.length,0,leaf);this.add_tab(leaf,index)},appendChild(leaf){this.insertChild(this.children.length,leaf)},add_tab(leaf,index){const tab=document.createElement('div');tab.className='typ-tab';tab.dataset.id=leaf.state.path;tab.innerHTML='<span class="typ-file-basename"></span>';this.containerEl.insertBefore(tab,this.containerEl.children[index]||null)},toggleTab(path){return this.children.find(leaf=>leaf.state.path===path)},removeTab(path){const leaf=this.children.find(leaf=>leaf.state.path===path);if(!leaf)return;if(!path.startsWith('typ://')&&native_dirty&&no_other_window){native_saves++;throw Error('unsafe native close would save');}leaves.splice(leaves.indexOf(leaf),1);[...this.containerEl.children].find(tab=>tab.dataset.id===path)?.remove();leaf.view.onClose?.();if(active===leaf)active=empty;}};
  let active;const empty={state:{path:'typ://core.empty/'},parent:group,view:{containerEl:document.createElement('div')},containerEl:document.createElement('div')};group.appendChild(empty);active=empty;window.make_group=()=>{const containerEl=document.createElement('div');document.body.append(containerEl);const next=Object.create(group);Object.defineProperty(next,'containerEl',{value:containerEl});const leaf={state:{path:'typ://core.empty/'},parent:next,view:{containerEl:document.createElement('div')},containerEl:document.createElement('div')};next.appendChild(leaf);return next};
  const workspace={activeFile:'',sidebar:{},get activeLeaf(){return active},set activeLeaf(leaf){active?.view.onClose?.();active=leaf;document.querySelector('#editor').replaceChildren(leaf.view.containerEl);leaf.view.onOpen?.();events.get('active-leaf:change')?.forEach(fn=>fn(leaf))},eachLeaves(fn){leaves.forEach(fn)},createLeaf(descriptor){const leaf={...descriptor,parent:group,containerEl:document.createElement('div')};leaf.view=factories.get(descriptor.type)(leaf);return leaf},on(event,fn){if(!events.has(event))events.set(event,new Set());events.get(event).add(fn);return()=>events.get(event).delete(fn)}};
  window.core={WorkspaceView:base_view,app:{workspace,openFile:async()=>{},commands:{register:()=>()=>{},run:()=>{}},viewManager:{registerView(type,factory){factories.set(type,factory);return()=>factories.delete(type)}}}};
  window.make_markdown=(file_path,text,dirty,activate=true)=>{const leaf={state:{path:file_path},parent:group,containerEl:document.createElement('div'),view:{containerEl:document.createElement('div'),getScroll:()=>({scrollTop:123}),isEditor:()=>activate,onOpen(){},onClose(){}}};group.appendChild(leaf);if(activate){File.bundle={filePath:file_path,savedContent:require('fs').readFileSync(file_path,'utf8')};native_text=text;native_dirty=dirty;workspace.activeFile=file_path;workspace.activeLeaf=leaf;document.querySelector('#write').textContent=text;}return leaf;};
  factories.set('core.markdown',leaf=>({containerEl:document.createElement('div'),getScroll:()=>({scrollTop:123}),isEditor:()=>true,onOpen(){},onClose(){}}));window.transfer_native_open=async(file_path,options={})=>{window.native_load_started=true;if(native_load_wait)await native_load_wait;if(options.signal?.aborted)throw Error('导航已取消');const existing=leaves.find(leaf=>leaf.state.path===file_path);if(existing){File.bundle={filePath:file_path,savedContent:require('fs').readFileSync(file_path,'utf8')};native_text=File.bundle.savedContent;native_dirty=false;workspace.activeFile=file_path;workspace.activeLeaf=existing;}else make_markdown(file_path,require('fs').readFileSync(file_path,'utf8'),false);if(shared_native_snapshot){native_text=shared_native_snapshot.text;native_dirty=shared_native_snapshot.dirty;File.bundle.savedContent=shared_native_snapshot.saved;};events.get('file:open')?.forEach(fn=>fn(file_path));};
  window.files=transfer_qa.bind_workspace_files(core);window.view=()=>core.app.workspace.activeLeaf.view;window.editor=()=>view().editor?.focused_editor();
 })()`);
 return win;
}
async function source_window(text=initial+'int draft = 2;\n'){
 const win=await create_window();await evaluate(win,`files.open_file(${JSON.stringify(file)})`);await wait(win,'view().loaded&&!view().loading');
 await evaluate(win,`editor().executeEdits('fixture',[{range:editor().getModel().getFullModelRange(),text:${JSON.stringify(text)}}]);window.source_leaf=core.app.workspace.activeLeaf;void 0`);return win;
}
const capture=win=>evaluate(win,'files.capture_transfer(core.app.workspace.activeLeaf)');
const receive=(win,snapshot)=>evaluate(win,`files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length}).then(leaf=>leaf.state.path)`);
app.whenReady().then(async()=>{
 bundle=(await build({plugins:[{name:'isolated_native_navigation',setup(build){build.onResolve({filter:/^\.\/reading_navigation$/},args=>({path:'reading_navigation',namespace:'native_fixture'}));build.onLoad({filter:/.*/,namespace:'native_fixture'},()=>({contents:'export const navigate_reading_target=(path,options)=>window.transfer_native_open(path,options);export const rename_reading_paths=()=>{};',loader:'js'}));}},...editor_plugins()],stdin:{contents:'export {bind_workspace_files} from "./src/workspace_files";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'transfer_qa',write:false})).outputFiles[0].text;
 let source=await source_window(),target=await create_window();
 await evaluate(source,"transfer_qa.monaco.editor.setModelLanguage(editor().getModel(),'cpp');view().format.encoding='utf-16be';view().format.bom=true;view().format.eol='CRLF';editor().setSelection({startLineNumber:1,startColumn:5,endLineNumber:1,endColumn:10});void 0");
 let snapshot=await capture(source);assert.equal(snapshot.dirty,true);assert.equal(snapshot.source_format.encoding,'utf-16be');assert.equal(snapshot.source_baseline_format.encoding,'utf-8');assert.equal(snapshot.source_baseline,initial);
 await evaluate(target,`root_path=${JSON.stringify(root)};void 0`);await receive(target,snapshot);assert.equal(await evaluate(target,'files.context_root()'),root);assert.equal(await evaluate(target,'editor().getModel().getLanguageId()'),'cpp');assert.equal(await evaluate(target,'editor().getValue()'),snapshot.text);assert.equal(await evaluate(target,'view().dirty()'),true);assert.deepEqual(await evaluate(target,'({encoding:view().format.encoding,bom:view().format.bom,eol:view().format.eol})'),snapshot.source_format);assert.equal(await evaluate(target,'editor().getSelection().startColumn'),5);assert.equal(fs.readFileSync(file,'utf8'),initial);
 assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),true);assert.equal(fs.readFileSync(file,'utf8'),initial);assert.equal(await evaluate(source,'native_saves'),0);checks.push('dirty source transfers current text, pending format, language and selection while preserving the target project root; ACK release writes no file');assert.equal(await evaluate(target,'files.save_active()'),true);const saved_bytes=fs.readFileSync(file);assert.deepEqual([...saved_bytes.subarray(0,2)],[0xfe,0xff]);assert.equal(Buffer.from(saved_bytes.subarray(2)).swap16().toString('utf16le'),snapshot.text.replace(/\r?\n/g,'\r\n'));checks.push('explicit target Save inherits the original conflict baseline and writes the selected BOM/encoding/EOL');close(source);close(target);fs.writeFileSync(file,initial);
 source=await source_window('');target=await create_window();snapshot=await capture(source);await receive(target,snapshot);assert.equal(await evaluate(target,'editor().getValue()'),'');assert.equal(await evaluate(target,'view().dirty()'),true);checks.push('empty unsaved source text remains an unsaved empty draft');close(source);close(target);
 source=await source_window();snapshot=await capture(source);await evaluate(source,"editor().executeEdits('later',[{range:editor().getModel().getFullModelRange(),text:'newer input'}]);void 0");assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),false);assert.equal(await evaluate(source,'editor().getValue()'),'newer input');checks.push('source edits after capture retain the original tab');close(source);
 source=await source_window();snapshot=await capture(source);await evaluate(source,"window.release_abort=new AbortController();const original=view().text_document.prepare_relocation;view().text_document.prepare_relocation=async(...args)=>{await new Promise(resolve=>window.release_gate=resolve);return original(...args)};window.releasing=files.release_transfer(source_leaf,"+JSON.stringify(snapshot)+",release_abort.signal);void 0");await wait(source,'typeof release_gate==="function"');await evaluate(source,'release_abort.abort();release_gate();void 0');assert.equal(await evaluate(source,'releasing'),false);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),true);checks.push('release cancellation during baseline verification cannot close the source later');close(source);
 source=await source_window();snapshot=await capture(source);fs.writeFileSync(file,'externally changed\n');target=await create_window();await assert.rejects(()=>receive(target,snapshot),/磁盘文件发生变化/u);await assert.rejects(()=>capture(source),/其他进程/u);assert.equal(await evaluate(source,'view().dirty()'),true);assert.equal(await evaluate(target,'leaves.length'),1);checks.push('external disk changes reject both capture and reception without modifying either draft');close(source);close(target);fs.writeFileSync(file,initial);
 source=await source_window();snapshot=await capture(source);target=await source_window('target own draft');await assert.rejects(()=>receive(target,snapshot),/已打开同一文件/u);assert.equal(await evaluate(target,'editor().getValue()'),'target own draft');checks.push('duplicate path in target window never overwrites its own draft');close(source);close(target);
 source=await source_window();snapshot=await capture(source);target=await create_window();await evaluate(target,'window.receive_abort=new AbortController();receive_abort.abort();void 0');await assert.rejects(()=>evaluate(target,`files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length},receive_abort.signal)`),/取消/u);assert.equal(await evaluate(target,'leaves.length'),1);checks.push('cancelled receiver does not open or edit a file');close(source);close(target);
 source=await source_window();snapshot=await capture(source);target=await create_window();
 await evaluate(target,`(()=>{const key=[...factories.keys()].find(key=>key!=='core.markdown'),factory=factories.get(key);factories.set(key,leaf=>{const view=factory(leaf);let current=view.text_document;Object.defineProperty(view,'text_document',{get:()=>current,set:document=>{current=document;const original=document.prepare_relocation;document.prepare_relocation=async(...args)=>{await new Promise(resolve=>window.receive_gate=resolve);return original(...args)}}});return view});window.receiving=files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length}).then(()=>'',error=>error.message)})();void 0`);
 await wait(target,'typeof receive_gate==="function"&&!!editor()');await evaluate(target,"editor().executeEdits('new-window-input',[{range:editor().getModel().getFullModelRange(),text:'new target input'}]);receive_gate();void 0");assert.match(await evaluate(target,'receiving'),/草稿发生变化/u);assert.equal(await evaluate(target,'editor().getValue()'),'new target input');assert.equal(fs.readFileSync(file,'utf8'),initial);checks.push('input in receiving editor while baseline verification is pending is retained, never overwritten by payload');close(source);close(target);
 source=await source_window();snapshot=await capture(source);await evaluate(source,"view().format.eol='CRLF';void 0");assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),false);assert.equal(await evaluate(source,'view().format.eol'),'CRLF');checks.push('format-only changes after capture also prevent source release');close(source);
 source=await source_window();await evaluate(source,'view().saving=true;void 0');await assert.rejects(()=>capture(source),/正在读取或保存/u);await evaluate(source,'view().saving=false;view().loading=true;void 0');await assert.rejects(()=>capture(source),/正在读取或保存/u);checks.push('loading and saving source models cannot be captured');close(source);
 source=await source_window();await evaluate(source,`window.capture_abort=new AbortController();window.reads=0;window.handles=0;window.transfer_open_count=0;const original=transfer_fs.promises.open;transfer_fs.promises.open=async(...args)=>{const handle=await original(...args);if(++transfer_open_count!==2)return handle;handles++;const read=handle.read.bind(handle),close=handle.close.bind(handle);handle.read=async(...args)=>{reads++;await new Promise(resolve=>window.read_gate=resolve);return read(...args)};handle.close=async()=>{handles--;return close()};return handle};window.capturing=files.capture_transfer(source_leaf,capture_abort.signal).then(()=>'',error=>error.message);void 0`);
 await wait(source,'typeof read_gate==="function"');assert.equal(await evaluate(source,'1+1'),2);await evaluate(source,'capture_abort.abort();read_gate();void 0');assert.match(await evaluate(source,'capturing'),/取消/u);assert.equal(await evaluate(source,'handles'),0);assert.equal(await evaluate(source,'reads'),1);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),true);assert.equal(fs.readFileSync(file,'utf8'),initial);checks.push('slow asynchronous file read stays responsive and cancellation closes its handle without later reads or source removal');close(source);
 source=await source_window();await evaluate(source,`window.transfer_open_count=0;const original=transfer_fs.promises.open;transfer_fs.promises.open=async(...args)=>{const handle=await original(...args);if(++transfer_open_count!==2)return handle;const read=handle.read.bind(handle);let pending=true;handle.read=async(...args)=>{if(pending){pending=false;await new Promise(resolve=>window.read_gate=resolve)}return read(...args)};return handle};window.capturing=files.capture_transfer(source_leaf).then(()=>'',error=>error.message);void 0`);await wait(source,'typeof read_gate==="function"');await evaluate(source,"editor().executeEdits('read-race',[{range:editor().getModel().getFullModelRange(),text:'typed while reading'}]);read_gate();void 0");assert.match(await evaluate(source,'capturing'),/捕获期间发生变化/u);assert.equal(await evaluate(source,'editor().getValue()'),'typed while reading');checks.push('source input while disk verification runs invalidates capture and preserves the newer draft');close(source);
 source=await source_window();snapshot=await capture(source);target=await create_window();await evaluate(target,`const original=transfer_fs.promises.open;transfer_fs.promises.open=async(...args)=>{const handle=await original(...args),read=handle.read.bind(handle);let pending=true;handle.read=async(...args)=>{if(pending){pending=false;await new Promise(resolve=>window.read_gate=resolve)}return read(...args)};return handle};window.receiving=files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length}).then(()=>'',error=>error.message);void 0`);await wait(target,'typeof read_gate==="function"');await evaluate(target,"native_text='new empty-window draft';native_dirty=true;read_gate();void 0");assert.match(await evaluate(target,'receiving'),/草稿/u);assert.equal(await evaluate(target,'native_text'),'new empty-window draft');assert.equal(await evaluate(target,'leaves.length'),1);checks.push('new target draft entered during initial asynchronous file validation prevents opening the transferred file');close(source);close(target);


 source=await source_window();snapshot=await capture(source);target=await create_window();
 await evaluate(target,`files.open_file(${JSON.stringify(other)})`);await wait(target,'view().loaded&&!view().loading');
 await evaluate(target,`editor().executeEdits('own-draft',[{range:editor().getModel().getFullModelRange(),text:'target source draft'}]);window.own_leaf=core.app.workspace.activeLeaf;window.other_group=make_group();core.app.workspace.activeLeaf=other_group.children[0];void 0`);
 await evaluate(target,`files.open_file(${JSON.stringify(third)})`);await wait(target,'view().loaded&&!view().loading');await evaluate(target,'window.third_leaf=core.app.workspace.activeLeaf;core.app.workspace.activeLeaf=own_leaf;void 0');
 await evaluate(target,`files.receive_transfer(${JSON.stringify(snapshot)},{group:other_group,index:1}).then(leaf=>window.received_leaf=leaf);void 0`);await wait(target,'!!window.received_leaf');
 assert.deepEqual(await evaluate(target,'({group:received_leaf.parent===other_group,index:other_group.children.indexOf(received_leaf),own:own_leaf.view.editor.models[0].getValue(),third:third_leaf.view.editor.models[0].getValue(),dirty:own_leaf.view.dirty()})'),{group:true,index:1,own:'target source draft',third:'int third;\n',dirty:true});assert.equal(fs.readFileSync(other,'utf8'),'int other;\n');checks.push('existing window receives into the specified nonactive group and insertion index while retaining other source drafts');close(source);close(target);
 source=await source_window();snapshot=await capture(source);target=await create_window();await evaluate(target,`make_markdown(${JSON.stringify(markdown)},'# Native target draft\\n',true);void 0`);await receive(target,snapshot);assert.equal(await evaluate(target,'native_text'),'# Native target draft\n');assert.equal(await evaluate(target,'native_dirty'),true);assert.equal(await evaluate(target,'native_saves'),0);assert.equal(await evaluate(target,'editor().getValue()'),snapshot.text);checks.push('source reception retains an unrelated native Markdown draft without opening or saving a native document');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},'# Title\\n\\nBaseline\\n',false);void 0`);snapshot=await capture(source);target=await create_window();await evaluate(target,`make_markdown(${JSON.stringify(background)},'# Unsaved target\\n',true);void 0`);await assert.rejects(()=>receive(target,snapshot),/未保存的Markdown草稿/u);assert.equal(await evaluate(target,'native_text'),'# Unsaved target\n');assert.equal(await evaluate(target,'native_load_started'),false);assert.equal(await evaluate(target,'native_saves'),0);checks.push('Markdown reception explicitly refuses an unrelated target native draft before any native switch');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Title\n\nBaseline\n')},false);void 0`);snapshot=await capture(source);target=await create_window();await evaluate(target,`files.open_file(${JSON.stringify(other)})`);await wait(target,'view().loaded&&!view().loading');await evaluate(target,"editor().executeEdits('existing',[{range:editor().getModel().getFullModelRange(),text:'keep existing source'}]);window.own_leaf=core.app.workspace.activeLeaf;window.other_group=make_group();void 0");await evaluate(target,`files.receive_transfer(${JSON.stringify(snapshot)},{group:other_group,index:0}).then(leaf=>window.received_leaf=leaf);void 0`);await wait(target,'!!window.received_leaf');assert.equal(await evaluate(target,'received_leaf.parent===other_group&&other_group.children.indexOf(received_leaf)===0'),true);assert.equal(await evaluate(target,'own_leaf.view.editor.models[0].getValue()'),'keep existing source');assert.equal(await evaluate(target,'native_text'),'# Title\n\nBaseline\n');checks.push('clean Markdown merges at an explicit index in another group and leaves source models intact');close(source);close(target);
 source=await source_window();snapshot=await capture(source);target=await create_window();await evaluate(target,'window.invalid_group=make_group();leaves.splice(leaves.indexOf(invalid_group.children[0]),1);void 0');await assert.rejects(()=>evaluate(target,`files.receive_transfer(${JSON.stringify(snapshot)},{group:invalid_group,index:0})`),/编辑组/u);assert.equal(await evaluate(target,'leaves.length'),1);checks.push('removed target group is rejected without creating a leaf');close(source);close(target);
 source=await source_window();snapshot=await capture(source);target=await create_window();await evaluate(target,`const original=transfer_fs.promises.open;transfer_fs.promises.open=async(...args)=>{const handle=await original(...args),read=handle.read.bind(handle);let pending=true;handle.read=async(...args)=>{if(pending){pending=false;await new Promise(resolve=>window.read_gate=resolve)}return read(...args)};return handle};window.receiving=files.receive_transfer(${JSON.stringify(snapshot)},{group,index:0}).then(()=>'',error=>error.message);void 0`);await wait(target,'typeof read_gate==="function"');await evaluate(target,`make_markdown(${JSON.stringify(background)},'',false,false);read_gate();void 0`);assert.match(await evaluate(target,'receiving'),/标签顺序/u);assert.equal(await evaluate(target,'leaves.length'),2);checks.push('target insertion order changed during disk verification cancels instead of inserting at a stale position');close(source);close(target);
 source=await source_window();snapshot=await capture(source);await evaluate(source,`make_markdown(${JSON.stringify(markdown)},'# Retained native draft\\n',true);void 0`);assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),true);assert.equal(await evaluate(source,'native_dirty'),true);assert.equal(await evaluate(source,'native_saves'),0);assert.equal(await evaluate(source,'native_text'),'# Retained native draft\n');assert.equal(fs.readFileSync(file,'utf8'),initial);checks.push('ACK can release an inactive source leaf while an unrelated native Markdown draft remains untouched');close(source);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},'',true);void 0`);snapshot=await capture(source);assert.equal(snapshot.text,'');target=await create_window();await receive(target,snapshot);assert.equal(await evaluate(target,'native_text'),'');assert.equal(await evaluate(target,'native_dirty'),true);assert.equal(await evaluate(target,'reload_calls[0].options.skipChangeCount'),false);assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),false);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),true);assert.equal(await evaluate(source,'native_saves'),0);assert.equal(fs.readFileSync(markdown,'utf8'),'# Title\n\nBaseline\n');checks.push('empty dirty Markdown restores via verified object signature and retains source without unsafe native close');close(source);close(target);

 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Shared dirty draft\n')},true);void 0`);snapshot=await capture(source);target=await create_window();await evaluate(target,`window.shared_native_snapshot={text:${JSON.stringify(snapshot.text)},dirty:true,saved:${JSON.stringify(snapshot.markdown_baseline)}};void 0`);await receive(target,snapshot);assert.equal(await evaluate(target,'native_text'),snapshot.text);assert.equal(await evaluate(target,'native_dirty'),true);assert.equal(await evaluate(target,'reload_calls.length'),0);await evaluate(source,'no_other_window=false;void 0');assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),true);assert.equal(await evaluate(source,'native_saves'),0);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),false);assert.equal(fs.readFileSync(markdown,'utf8'),'# Title\n\nBaseline\n');checks.push('native shared dirty snapshot is accepted without reloading and ACK releases the source only after native shared ownership confirmation');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Shared dirty draft\n')},true);void 0`);snapshot=await capture(source);target=await create_window();await evaluate(target,`window.shared_native_snapshot={text:${JSON.stringify(snapshot.text)},dirty:true,saved:'wrong baseline'};void 0`);await assert.rejects(()=>receive(target,snapshot),/磁盘基线不同/u);assert.equal(await evaluate(target,'reload_calls.length'),0);assert.equal(await evaluate(target,'native_text'),snapshot.text);checks.push('inherited native draft with an inconsistent saved-content baseline is rejected without another reload');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Shared dirty draft\n')},true);void 0`);snapshot=await capture(source);await evaluate(source,`no_other_window=false;shared_query_wait=new Promise(resolve=>window.shared_query_gate=resolve);window.release_abort=new AbortController();window.releasing=files.release_transfer(source_leaf,${JSON.stringify(snapshot)},release_abort.signal);void 0`);await wait(source,'shared_query_started===true');await evaluate(source,'release_abort.abort();shared_query_gate();void 0');assert.equal(await evaluate(source,'releasing'),false);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),true);assert.equal(await evaluate(source,'native_saves'),0);checks.push('cancellation while waiting for native shared ownership cannot remove the source later');close(source);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Shared dirty draft\n')},true);void 0`);snapshot=await capture(source);await evaluate(source,`no_other_window=false;shared_query_wait=new Promise(resolve=>window.shared_query_gate=resolve);window.releasing=files.release_transfer(source_leaf,${JSON.stringify(snapshot)});void 0`);await wait(source,'shared_query_started===true');await evaluate(source,"native_text='new input while ownership query pending';shared_query_gate();void 0");assert.equal(await evaluate(source,'releasing'),false);assert.equal(await evaluate(source,'leaves.includes(source_leaf)'),true);assert.equal(await evaluate(source,'native_text'),'new input while ownership query pending');checks.push('native edits during shared ownership verification retain the original leaf and new input');close(source);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Draft\n')},true);File.option.enableAutoSave=true;void 0`);await assert.rejects(()=>capture(source),/自动保存/u);await evaluate(source,'File.option.enableAutoSave=false;void 0');snapshot=await capture(source);target=await create_window();await evaluate(target,'File.option.enableAutoSave=true;void 0');await assert.rejects(()=>receive(target,snapshot),/自动保存/u);assert.equal(await evaluate(target,'reload_calls.length'),0);checks.push('native automatic saving blocks dirty Markdown transfer before any reload');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Draft\n')},true);void 0`);snapshot=await capture(source);target=await create_window();
 await evaluate(target,`native_load_wait=new Promise(resolve=>window.native_load_gate=resolve);window.receiving=files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length}).then(()=>'',error=>error.message);void 0`);await wait(target,'native_load_started===true');await evaluate(target,'File.option.enableAutoSave=true;native_load_gate();void 0');assert.match(await evaluate(target,'receiving'),/自动保存/u);assert.equal(await evaluate(target,'reload_calls.length'),0);assert.equal(fs.readFileSync(markdown,'utf8'),'# Title\n\nBaseline\n');checks.push('automatic saving enabled during native load rejects the payload before reload');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Draft\n')},true);void 0`);snapshot=await capture(source);target=await create_window();
 await evaluate(target,`window.receive_abort=new AbortController();native_load_wait=new Promise(resolve=>window.native_load_gate=resolve);window.receiving=files.receive_transfer(${JSON.stringify(snapshot)},{group,index:group.children.length},receive_abort.signal).then(()=>'',error=>error.message);void 0`);await wait(target,'native_load_started===true');await evaluate(target,'receive_abort.abort();native_load_gate();void 0');assert.match(await evaluate(target,'receiving'),/取消/u);assert.equal(await evaluate(target,'reload_calls.length'),0);assert.equal(await evaluate(target,'File.bundle.filePath'),'');checks.push('native navigation receives the transfer cancellation signal before opening');close(source);close(target);

 source=await create_window();await evaluate(source,`make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Current unsaved\n')},true);window.background_leaf=make_markdown(${JSON.stringify(background)},'',false,false);void 0`);snapshot=await evaluate(source,'files.capture_transfer(background_leaf)');assert.equal(snapshot.text,'# Background\n');assert.equal(snapshot.dirty,false);assert.equal(snapshot.reading_position.scroll_top,123);assert.equal(await evaluate(source,'native_text'),'# Current unsaved\n');target=await create_window();await receive(target,snapshot);assert.equal(await evaluate(target,'native_text'),'# Background\n');assert.equal(await evaluate(target,'reload_calls.length'),0);assert.equal(await evaluate(source,`files.release_transfer(background_leaf,${JSON.stringify(snapshot)})`),false);checks.push('background Markdown captures its own disk text and scroll while preserving unrelated active native draft');close(source);close(target);
 source=await create_window();await evaluate(source,`window.source_leaf=make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Title\n\nBaseline\n')},false);void 0`);snapshot=await capture(source);assert.equal(await evaluate(source,`files.release_transfer(source_leaf,${JSON.stringify(snapshot)})`),true);assert.equal(await evaluate(source,'native_saves'),0);checks.push('clean Markdown can release without invoking native Save');close(source);
 source=await create_window();await evaluate(source,`make_markdown(${JSON.stringify(markdown)},${JSON.stringify('# Draft\n')},true);File.bundle.savedContent='wrong baseline';void 0`);await assert.rejects(()=>capture(source),/加载基线不同/u);assert.equal(await evaluate(source,'native_text'),'# Draft\n');checks.push('native saved-content mismatch refuses a misleading Markdown baseline');close(source);
 console.log(JSON.stringify({checks,passed:checks.length,scope:'hidden Electron, real Monaco, real temporary files, native Markdown API contract fixture'},null,2));
}).then(()=>app.exit(0)).catch(error=>{console.error(error);app.exit(1)}).finally(()=>{for(const win of windows)if(!win.isDestroyed())win.destroy();});
