import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {build} from 'esbuild';
const require=createRequire(import.meta.url),source=path.resolve('src');
const result=await build({stdin:{contents:`export * from './remote_workspace_files';export * from './workspace_text_document';export * from './workspace_rename';export * from './workspace_file_operations';export * from './git_graph_runtime';export * from './workspace_native_save';export * from './workspace_search_engine';export * from './git_ignore';`,resolveDir:source},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'search-worker-placeholder',setup(build){build.onResolve({filter:/^linux_note_search_worker$/},()=>({path:'worker',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export default "";',loader:'js'}));}}]});
const api=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const remote_api=require(path.join(source,'remote_ssh_service.cjs'));const node_version=JSON.parse(fs.readFileSync('node_runtime.json')).version;
const service=remote_api.create_remote_ssh({asset_root:source,node_path:path.join(process.env.APPDATA,'Typora/linux_note_enhancements/terminal_runtime/node',node_version,'node.exe'),authenticate:async prompt=>{if(/yes\/no|fingerprint/i.test(prompt))throw Error('Untrusted fixture host');return process.env.TYPORA_TEST_SSH_PASSWORD;}});
const checks=[];let release;
try{
 const hello=await service.connect(process.env.TYPORA_TEST_SSH_TARGET);const root=hello.home+'/.typora-workspace-'+crypto.randomUUID();await service.request('mkdir',{path:root});
 const provider=new api.remote_file_provider({target:process.env.TYPORA_TEST_SSH_TARGET,connected:()=>service.state()==='connected',request:service.request},fs,path,fs.mkdtempSync(path.join(os.tmpdir(),'typora-remote-workspace-')),Buffer);release=api.register_remote_files(provider);
 const local_root=await provider.mount(root);provider.root=local_root;api.select_remote_files(provider);const routed=api.workspace_resource_fs(fs);
 const text='# 标题\n\n[下一页](sub/目标.md#目标)\n';await service.request('create',{path:root+'/first.md',data:Buffer.from(text).toString('base64')});
 const first=provider.local_path(root+'/first.md');assert.equal(await routed.promises.readFile(first,'utf8'),text);assert(!fs.existsSync(first));checks.push('remote read does not materialize or read local disk');
 await provider.prepare(first);assert.equal(fs.readFileSync(first,'utf8'),text);checks.push('native adapter materializes one file');
 const document=api.create_text_document({fs:routed,path_api:path},first);assert.equal((await document.load()).text,text);await document.save(text+'new\n');assert(Buffer.from((await service.request('read',{path:root+'/first.md'})).data,'base64').toString().endsWith('new\n'));checks.push('shared source document atomic save executes remotely');
 const sub=await api.create_workspace_entry({fs:routed,path_api:path},local_root,local_root,'sub',true);const second=await api.create_workspace_entry({fs:routed,path_api:path},local_root,sub,'目标.md',false);checks.push('shared explorer create folder and file');
 const renamed=await api.prepare_workspace_rename({fs:routed,path_api:path},local_root,second,'重命名.md');await renamed.apply();assert((await routed.promises.readdir(sub)).includes('重命名.md'));checks.push('shared explorer rename preserves remote identity');
 const runner=api.create_git_runner({child_process:require('node:child_process'),process},{writable:true});await runner.run(local_root,['init','-q']);const top=await runner.run(local_root,['rev-parse','--show-toplevel']);assert.equal(top.trim(),local_root);await assert.rejects(runner.run(local_root,['rev-parse','HEAD']),e=>e.code===128);checks.push('remote git init root mapping and original error code');
 await runner.run(local_root,['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','add','--','first.md']);await runner.run(local_root,['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','fixture']);assert.equal((await runner.run(local_root,['status','--porcelain'])).includes('sub/'),true);checks.push('remote git stage and commit separate temporary repository');await api.append_git_ignore({fs:routed,path_api:path},runner.run,local_root,'sub/重命名.md');assert((await routed.promises.readFile(path.join(local_root,'.gitignore'),'utf8')).includes('/sub/重命名.md'));checks.push('shared Git ignore writes remote file');
 const archive=path.join(local_root,'snapshot.zip');await runner.run(local_root,['archive','--format=zip','--output='+archive,'HEAD']);assert((await routed.promises.stat(archive)).size>0);checks.push('remote Git archive output maps to remote path');
 const signature=await service.request('filesystem',{action:'watch_signature',path:root});await service.request('create',{path:root+'/watch.txt',data:Buffer.from('changed').toString('base64')});assert.notEqual(await service.request('filesystem',{action:'watch_signature',path:root}),signature);checks.push('remote watcher sees direct child changes');
 const search=api.create_workspace_search_engine({fs:routed,path_api:path,git_run:runner.run,platform:'linux'});
 const found=await search.search(local_root,{query:'标题',use_ignore:false});assert.equal(found.counts.matches,1);checks.push('shared content search reads remote Markdown');
 const copy_dir=await api.create_workspace_entry({fs:routed,path_api:path},local_root,local_root,'copy',true);await api.transfer_workspace_entries({fs:routed,path_api:path},local_root,[first],copy_dir);assert.equal(await routed.promises.readFile(path.join(copy_dir,'first.md'),'utf8'),text+'new\n');checks.push('shared explorer recursive copy reads and writes remote handles');const incoming=await api.create_workspace_entry({fs:routed,path_api:path},local_root,local_root,'incoming',true);await api.transfer_workspace_entries({fs:routed,path_api:path},local_root,[first],incoming,undefined,true);checks.push('clipboard copy validates remote namespace rather than local cache ancestors');
 const snapshot=await service.request('read',{path:root+'/first.md'});await service.request('write',{path:root+'/first.md',version:snapshot.version,data:Buffer.from('external').toString('base64')});await assert.rejects(document.save('draft'),/其他进程/);checks.push('remote source save conflict preserves external write');
 await provider.prepare(first,true);service.disconnect();await assert.rejects(routed.promises.readFile(first),/断开/);await assert.rejects(provider.save_native(first,'draft'),/断开/);checks.push('disconnect never falls back to materialized file');
 console.log(JSON.stringify({status:'PASS',checks,environment:'真实SSH临时目录；主机和凭据仅由环境提供'}));
}catch(error){console.error(error);process.exitCode=1;}finally{release?.();service.dispose();}
