// 隔离 Electron 验证真实 Git 比较顶栏、Monaco 选区和事务边界。
const {app,BrowserWindow}=require('electron');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_diff_toolbar_'));app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();
let test_window;app.whenReady().then(async()=>{const win=test_window=new BrowserWindow({show:false,width:1100,height:780,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true}});win.webContents.on('console-message',(_e,_l,m)=>console.log(m));const html=path.join(root,'host.html');fs.writeFileSync(html,'<!doctype html><body><div id="typora-sidebar"><div id="sidebar-content"><div id="outline-content"></div><div id="file-library"></div><div id="file-library-search"><div><input id="file-library-search-input"></div></div><div id="file-library-search-result"></div></div></div><div id="typora-sidebar-resizer"></div><content><div id="write"></div></content><footer id="footer"><span id="footer-word-count"></span></footer>','utf8');await win.loadFile(html);win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
await win.webContents.executeJavaScript(`window.$=window.jQuery=require(${JSON.stringify(require.resolve('jquery'))});window.fixture_errors=[];window.fixture_keys=[];window.addEventListener('keydown',event=>{const record={key:event.key,ctrl:event.ctrlKey,alt:event.altKey,target:event.target?.className};fixture_keys.push(record);queueMicrotask(()=>record.prevented=event.defaultPrevented);},true);window.addEventListener('error',e=>(fixture_errors.push(String(e.error?.stack||e.error)),console.log(e.error?.stack)));window.addEventListener('unhandledrejection',e=>{const message=String(e.reason?.stack||e.reason);fixture_errors.push(message);console.error('Unhandled diff failure at '+window.fixture_stage+': '+message)});window.reqnode=name=>require(name);window._options={userDataPath:${JSON.stringify(root)},mountFolder:${JSON.stringify(path.join(root,'one'))},appLocale:'en',locale:'en'};window.fixture_noop=()=>{};window.fixture_object=()=>new Proxy(function(){},{get(target,key){if(key in target)return target[key];if(key==='then'||typeof key==='symbol')return undefined;return target[key]=fixture_object();}});window.editor=fixture_object();editor.writingArea=document.querySelector('#write');editor.library=fixture_object();editor.selection=fixture_object();editor.sourceView=fixture_object();editor.nodeMap={allNodes:{_set:[],first:()=>null}};editor.getMarkdown=()=>'';window.File=fixture_object();File.isNode=true;File.isMac=false;File.isWin=true;File.filePath='';File.bundle={filePath:''};File.option={};File.getMountFolder=()=>_options.mountFolder;File.setMountFolder=path=>_options.mountFolder=path;File.editor=editor;window.JSBridge=fixture_object();window.bridge=fixture_object();window.ClientCommand=fixture_object();window.CodeMirror=fixture_object();window.gettext=value=>value;void 0`);
// Only host APIs are substituted; runtime production bundle and settings/fs implementation are real.
fs.mkdirSync(path.join(root,'typora_code','locales'),{recursive:true});for(const name of fs.readdirSync(path.join(__dirname,'../dist/locales')))fs.copyFileSync(path.join(__dirname,'../dist/locales',name),path.join(root,'typora_code','locales',name));
await win.webContents.executeJavaScript(`window.fixture_registrations=[];window.fixture_add=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(type,listener,options){fixture_registrations.push({target:this,type,listener,options});return fixture_add.call(this,type,listener,options)};void 0`);
await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.js'),'utf8'));
await win.webContents.executeJavaScript(`window.runtime=window[Symbol.for('typora-code:workspace')];runtime.ready.then(()=>'ready').catch(error=>{console.log(fixture_errors.join('\\n'));throw error})`);


// 真实 core + Monaco + Git 事务；仅宿主空文档 API 使用夹具，仓库和配置均在本测试临时目录。
const {execFileSync}=require('node:child_process');
const repo=path.join(root,'repo');fs.mkdirSync(repo);
const git=(args,encoding='utf8')=>execFileSync('git',['-c','core.hooksPath=.git/unused_hooks',...args],{cwd:repo,encoding,windowsHide:true,stdio:['pipe','pipe','pipe']});
git(['init','-b','main']);for(const [name,value]of [['user.name','Diff UI QA'],['user.email','diff@example.invalid'],['commit.gpgsign','false'],['core.autocrlf','false']])git(['config',name,value]);
const filename='selected ranges 中文 long name.test.ts',target=path.join(repo,filename),peername='peer.ts';
const base_lines=Array.from({length:90},(_,i)=>'const row_'+(i+1)+' = '+(i+1)+';');
fs.writeFileSync(target,base_lines.join('\r\n')+'\r\n');fs.writeFileSync(path.join(repo,peername),'const peer = 1;\n');git(['add','.']);git(['commit','-m','Diff toolbar fixture']);
const head=git(['rev-parse','HEAD']);
const index_lines=[...base_lines];index_lines[69]='const staged_before = 700;';const index_text=index_lines.join('\r\n')+'\r\n';fs.writeFileSync(target,index_text);git(['add','--',filename]);
const changed_lines=[...index_lines];changed_lines[9]='const chosen = 100;';changed_lines[10]='const unselected_neighbor = 110;';changed_lines[39]='const other_hunk = 400;';changed_lines[59]='    '+index_lines[59]+'  ';const work_text=changed_lines.join('\r\n')+'\r\n';fs.writeFileSync(target,work_text);fs.writeFileSync(path.join(repo,peername),'const peer = 2;\n');
const checks=[],evaluate=async source=>{try{return await win.webContents.executeJavaScript(source)}catch(error){console.error(source);throw error}},delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const wait=async source=>{for(let i=0;i<240;i++){if(await evaluate(source))return;await delay(35)}throw Error('Timed out: '+source)};
const check=async(source,label)=>{await evaluate('window.fixture_stage='+JSON.stringify(label));assert(await evaluate(source),label);checks.push(label)};
const click=async(selector,mouse='left')=>{const p=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw Error('Missing '+${JSON.stringify(selector)});node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;return{x:Math.round(x),y:Math.round(y),hit:node.contains(document.elementFromPoint(x,y)),width:r.width}})()`);assert(p.hit&&p.width>0,JSON.stringify({selector,...p}));const zoom=win.webContents.getZoomFactor();for(const type of ['mouseMove','mouseDown','mouseUp']){win.webContents.sendInputEvent({type,x:Math.round(p.x*zoom),y:Math.round(p.y*zoom),button:mouse,clickCount:1});await delay(25)}};
const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});if(keyCode==='Enter')win.webContents.sendInputEvent({type:'char',keyCode:'\r',modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(70)};
const capture=async name=>fs.writeFileSync(path.join(root,name+'.png'),(await win.webContents.capturePage()).toPNG());
await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.css'),'utf8'));
await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'));
await win.webContents.insertCSS('html,body{width:100%;height:100%;margin:0;overflow:hidden;color:#24292f;background:#fff}#typora-sidebar,.typ-ribbon,content{display:none!important}.typ-workspace-root{z-index:1!important;position:fixed!important;inset:0 0 28px!important}.typ-workspace-split{min-width:0}.typ-workspace-tabs{min-width:0}.typ-workspace-tab-header{height:35px}.typ-tabs{display:flex}.typ-tab{height:35px;max-width:230px}footer{position:fixed;bottom:0}.typ-close{font:16px system-ui}.typ-close:before{content:"×"}');
const {editor_plugins}=require('./editor_bundle.cjs');
const bundle=await require('esbuild').build({plugins:editor_plugins(),stdin:{contents:'export {git_graph_panel} from "./src/git_graph_panel";export {create_graph_host} from "./src/git_graph_host";export {bind_workspace_files} from "./src/workspace_files";export {bind_workspace_editor_actions} from "./src/workspace_editor_actions";export {bind_workspace_tab_controls} from "./src/workspace_tab_controls";export * from "./src/git_diff_settings";export * from "./src/workspace_editor_settings";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.css':'text'},format:'iife',globalName:'qa'});await evaluate(bundle.outputFiles[0].text);
await evaluate(`window.repo=${JSON.stringify(repo)};window.filename=${JSON.stringify(filename)};window.peername=${JSON.stringify(peername)};File.getMountFolder=()=>repo;File.changeCounter={isDocumentEdited:()=>false};File.isFileLoading=()=>false;File.inSavingProcess=false;File._onFileSwitching=false;File._onInitParse=false;File.editor.library.openFile=()=>{};JSBridge.invoke=async()=>null;window.notices=[];window.original_notice=runtime.Notice;runtime.Notice=class extends original_notice{constructor(message,...args){super(message,...args);notices.push(String(message));}};
window.files=qa.bind_workspace_files(runtime);window.actions=qa.bind_workspace_editor_actions(files,{open:()=>{}});window.tabs=qa.bind_workspace_tab_controls(runtime);window.host=qa.create_graph_host(runtime);host.avatar=async()=>'';window.panel=new qa.git_graph_panel(host,repo);document.querySelector('#sidebar-content').append(panel.workbench.sidebar);window.ws=runtime.app.workspace;window.leaves=()=>{const result=[];ws.eachLeaves(leaf=>result.push(leaf));return result};window.select=leaf=>{ws.activeLeaf=leaf.parent.toggleTab(leaf.state.path)};window.applies=[];window.read_blocked=false;window.write_original=panel.writer.run;panel.writer.run=async(...args)=>{if(args[1][0]==='apply'&&!args[1].includes('--check'))applies.push(args);if(window.hold_read&&args[1][0]==='ls-files'){window.hold_read=false;window.read_blocked=true;await new Promise(resolve=>window.release_read=resolve);window.read_blocked=false;}return write_original(...args)};void panel.refresh();`);
await wait('!!panel.state&&!panel.pending');
const open_diff=async(name=filename,from='INDEX',to='WORKTREE')=>{await evaluate(`panel.workbench.open_file({path:${JSON.stringify(name)},status:'M'},${JSON.stringify(from)},${JSON.stringify(to)},[{path:filename,status:'M'},{path:peername,status:'M'}])`);await wait('ws.activeLeaf?.view.editor?.editor.getLineChanges()!==null');await evaluate('window.leaf=ws.activeLeaf;window.diff=leaf.view.editor;document.querySelectorAll("[data-test-toolbar]").forEach(node=>delete node.dataset.testToolbar);diff.toolbar.dataset.testToolbar="current";window.right=diff.editor.getModifiedEditor();window.left=diff.editor.getOriginalEditor();void 0');await delay(80)};
const more=async()=>{await click('[data-test-toolbar=current] [data-diff-action=more]');await wait('!!document.querySelector(".git-diff-title-menu")')};
const select_line=async line=>{await evaluate(`right.focus();right.setPosition({lineNumber:${line},column:1});right.revealLineInCenter(${line});void 0`);await key('Down',['shift']);await check(`right.getSelection().startLineNumber===${line}&&right.getSelection().endLineNumber===${line+1}&&right.getSelection().endColumn===1`,'native Shift+Down selects only modified line '+line)};
await open_diff();await evaluate('window.primary_leaf=leaf;window.primary_diff=diff;void 0');
await check('diff.toolbar.parentElement.classList.contains("workspace-tab-strip")&&!diff.container.querySelector(".git-diff-toolbar")','production host attaches one toolbar to the owning editor group without an extra body row');
await more();
const required=['hide_unchanged','diff_view','show_moves','ignore_whitespace','accessible_diff','stage','open_file','refresh_diff','previous_file','next_file','stage_ranges','revert_ranges','show_opened_editors','close_all','close_saved','enable_preview_editors','lock_group','configure_editors'];
for(const id of required)assert(await evaluate(`!!document.querySelector('[data-action=${id}]')`),'title action '+id);
assert(!await evaluate('!!document.querySelector(".git-diff-title-menu [data-action=copy]")'),'ordinary text Copy stays out of the title menu');checks.push('title menu exposes actual diff, Git file, selected range and contributed group actions');
await check('document.querySelector("[data-action=stage_ranges]").disabled&&document.querySelector("[data-action=revert_ranges]").disabled','empty selection disables both range actions');await key('Escape');
await select_line(10);await more();await click('[data-action=stage_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&applies.length===1');
const staged_lines=[...index_lines];staged_lines[9]=changed_lines[9];assert.equal(git(['show',':'+filename]),staged_lines.join('\r\n')+'\r\n');assert.equal(fs.readFileSync(target,'utf8'),work_text);assert.equal(git(['rev-parse','HEAD']),head);
await check('diff.models[0].getValue().includes("const chosen = 100;")&&diff.models[1].getValue().includes("unselected_neighbor")','selected-line stage refreshes the actual comparison without changing its leaf');checks.push('selected stage changes only the chosen line and preserves same-hunk neighbor, other hunks, prior staged content, CRLF, worktree and HEAD');
await select_line(11);await more();await click('[data-action=revert_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&applies.length===2');
const reverted_lines=[...changed_lines];reverted_lines[10]=index_lines[10];assert.equal(fs.readFileSync(target,'utf8'),reverted_lines.join('\r\n')+'\r\n');assert.equal(git(['show',':'+filename]),staged_lines.join('\r\n')+'\r\n');checks.push('selected revert restores only its row and leaves the index and unselected whitespace/hunks intact');
// 左侧／无更改选区不得绕过实际修改侧语义。
await evaluate('left.focus();left.setSelection({startLineNumber:40,startColumn:1,endLineNumber:41,endColumn:1});void 0');await more();await check('document.querySelector("[data-action=stage_ranges]").disabled','original-side selection cannot execute modified-side ranges');await key('Escape');
await select_line(2);await more();await click('[data-action=stage_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending');assert.equal(await evaluate('applies.length'),2);await check('panel.workbench.notice.textContent.includes("选区")','unchanged selection reports why it cannot write');
// 菜单已捕获快照后，磁盘变化必须被现有 hash 事务拒绝。
await select_line(40);await more();const external_lines=[...reverted_lines];external_lines[39]='const external_change = 401;';fs.writeFileSync(target,external_lines.join('\r\n')+'\r\n');await click('[data-action=revert_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending');assert.equal(await evaluate('applies.length'),2);assert.equal(fs.readFileSync(target,'utf8'),external_lines.join('\r\n')+'\r\n');await check('panel.workbench.notice.textContent.length>0','stale worktree produces an error without applying the captured menu snapshot');
fs.writeFileSync(target,reverted_lines.join('\r\n')+'\r\n');await open_diff();
await select_line(40);await more();const external_index=[...staged_lines];external_index[74]='const externally_staged = 750;';fs.writeFileSync(target,external_index.join('\r\n')+'\r\n');git(['add','--',filename]);fs.writeFileSync(target,reverted_lines.join('\r\n')+'\r\n');await click('[data-action=stage_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending');assert.equal(await evaluate('applies.length'),2);assert.equal(git(['show',':'+filename]),external_index.join('\r\n')+'\r\n');checks.push('external index change rejects the stale selected-range model without overwriting new staged content');
fs.writeFileSync(target,staged_lines.join('\r\n')+'\r\n');git(['add','--',filename]);fs.writeFileSync(target,reverted_lines.join('\r\n')+'\r\n');await open_diff();
await evaluate(`files.open_file(${JSON.stringify(target)});`);await wait('ws.activeLeaf.view.loaded');await evaluate('window.source_leaf=ws.activeLeaf;window.source_editor=source_leaf.view.editor.focused_editor();source_editor.executeEdits("dirty fixture",[{range:source_editor.getModel().getFullModelRange(),text:"unsaved draft"}]);select(primary_leaf);window.diff=primary_leaf.view.editor;window.right=diff.editor.getModifiedEditor();window.left=diff.editor.getOriginalEditor();void 0');
await check('source_leaf.view.dirty()&&source_editor.getValue()==="unsaved draft"','the real source model is dirty before invoking the diff action');
await wait('!panel.writing&&!panel.pending');await select_line(40);await more();await check('!document.querySelector("[data-action=stage_ranges]").disabled&&!host.can_change_files()','dirty range fixture invokes an enabled range action while the real file guard rejects unsaved state');await evaluate('window.dirty_notice_count=notices.length;void 0');await click('[data-action=stage_ranges]');await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&notices.length>dirty_notice_count');assert.equal(await evaluate('applies.length'),2);await check('source_leaf.view.dirty()&&source_editor.getValue()==="unsaved draft"','dirty source blocks range writes and preserves its unsaved model');await check('/unsaved|未保存/u.test(notices.at(-1))&&[...document.querySelectorAll(".typ-notice__content")].some(node=>node.textContent===panel.workbench.notice.textContent&&node.getBoundingClientRect().height>0)','range rejection displays a real visible core Notice even with the source-control sidebar hidden');await capture('dirty_range_notice');
// 使用现有关闭确认明确丢弃测试草稿，磁盘正文并未被修改。
await evaluate('void files.close_leaf(source_leaf)');await wait('!!document.querySelector("[data-workspace-tab-close]")');await evaluate('[...document.querySelectorAll("[data-workspace-tab-close] button")].find(node=>node.textContent.includes("不保存")).click();void 0');await wait('!leaves().includes(source_leaf)');
await open_diff();await select_line(40);await evaluate('window.hold_read=true;void 0');await more();await click('[data-action=stage_ranges]');await wait('read_blocked&&panel.writing');await more();await check('document.querySelector("[data-action=stage_ranges]").disabled&&document.querySelector("[data-action=revert_ranges]").disabled','range preparation disables duplicate range actions immediately');await key('Escape');await evaluate('release_read();void 0');await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&applies.length===3');
checks.push('slow preparation uses the shared writing guard and executes one Git apply');
// 顶栏公布的组合键必须从真实键盘进入同一事务，缺少前缀和 Escape 取消均不写。
if(await evaluate('diff.ignore_whitespace'))await click('[data-test-toolbar=current] [data-diff-action=ignore_whitespace]');await wait('!diff.ignore_whitespace&&diff.editor.getLineChanges()?.length>0');
await select_line(60);await key('s',['control','alt']);await delay(80);assert.equal(await evaluate('applies.length'),3);await key('k',['control']);await key('Escape');await key('s',['control','alt']);await delay(80);assert.equal(await evaluate('applies.length'),3);
await select_line(60);await key('k',['control']);await key('s',['control','alt']);await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&applies.length===4');assert.equal(git(['show',':'+filename]),reverted_lines.join('\r\n')+'\r\n');checks.push('Ctrl+K Ctrl+Alt+S stages the actual selected whitespace row; missing or cancelled chord does not write');
const keyboard_work=[...reverted_lines];keyboard_work[19]='const keyboard_revert = 200;';fs.writeFileSync(target,keyboard_work.join('\r\n')+'\r\n');await open_diff();await select_line(20);await key('k',['control']);await key('r',['control','alt']);await wait('!panel.writing&&!panel.pending&&!diff.range_pending&&applies.length===5');assert.equal(fs.readFileSync(target,'utf8'),reverted_lines.join('\r\n')+'\r\n');assert.equal(git(['show',':'+filename]),reverted_lines.join('\r\n')+'\r\n');checks.push('Ctrl+K Ctrl+Alt+R restores only the selected worktree row through the same transaction');
const final_work=[...reverted_lines];final_work[79]='const navigation_change = 800;';fs.writeFileSync(target,final_work.join('\r\n')+'\r\n');

await open_diff(filename,head.trim(),'INDEX');await more();await check('!document.querySelector("[data-action=stage_ranges],[data-action=revert_ranges]")&&!!document.querySelector("[data-action=unstage]")','index comparison offers file unstage and does not invent unsupported selected-range unstage');await key('Escape');
await open_diff(filename,head.trim(),head.trim());await more();await check('!document.querySelector("[data-action=stage_ranges],[data-action=revert_ranges],[data-action=stage],[data-action=unstage]")','historical comparison has no Git range or file write actions');await key('Escape');
await open_diff();await evaluate('window.primary_leaf=leaf;window.primary_diff=diff;void 0');
await open_diff(peername);await evaluate('window.peer_leaf=leaf;window.peer_diff=diff;select(primary_leaf);window.leaf=primary_leaf;window.diff=primary_diff;window.right=diff.editor.getModifiedEditor();document.querySelectorAll("[data-test-toolbar]").forEach(node=>delete node.dataset.testToolbar);diff.toolbar.dataset.testToolbar="current";void 0');
await select_line(40);await evaluate('window.selection_before=JSON.stringify(right.getSelection());window.scroll_before=right.getScrollTop();void 0');
await more();await click('[data-action=diff_view]');await click('[data-action=diff_mode_inline]');await wait('!primary_diff.side_by_side&&!peer_diff.side_by_side');
await check('JSON.stringify(right.getSelection())===selection_before&&Math.abs(right.getScrollTop()-scroll_before)<2','shared inline preference preserves the active selection and scroll');
if(!await evaluate('diff.ignore_whitespace'))await click('[data-test-toolbar=current] [data-diff-action=ignore_whitespace]');await wait('primary_diff.ignore_whitespace&&peer_diff.ignore_whitespace');
await more();await click('[data-action=ignore_whitespace]');await wait('!primary_diff.ignore_whitespace&&!peer_diff.ignore_whitespace');
await more();await click('[data-action=show_moves]');await wait('primary_diff.show_moves&&peer_diff.show_moves');
await more();await click('[data-action=hide_unchanged]');await wait('primary_diff.collapsed&&peer_diff.collapsed');
await check('(()=>{const value=qa.read_git_diff_preferences();return !value.render_side_by_side&&!value.ignore_trim_whitespace&&value.show_moves&&value.hide_unchanged})()','all comparison views use one persisted diff preference record');
await more();await click('[data-action=lock_group]');await wait('qa.workspace_editor_group_locked(primary_leaf.parent)');
await evaluate('window.new_diff_data={title:"new view",file:"new.ts",left:"one\\ntwo\\n",right:"one\\nchanged\\n"};host.open_document(new_diff_data,"active",{root:repo,key:"new_preferences"});window.new_leaf=ws.activeLeaf;void 0');await wait('!!new_leaf.view.editor');await check('new_leaf.parent!==primary_leaf.parent&&!qa.workspace_editor_group_locked(new_leaf.parent)','new Git comparison respects the shared locked-group routing helper');await check('!new_leaf.view.editor.side_by_side&&!new_leaf.view.editor.ignore_whitespace&&new_leaf.view.editor.collapsed&&new_leaf.view.editor.show_moves','newly constructed comparison restores the same persisted preference values');await evaluate('new_leaf.parent.removeTab(new_leaf.state.path);select(primary_leaf);void 0');await more();await click('[data-action=lock_group]');await wait('!qa.workspace_editor_group_locked(primary_leaf.parent)');
await more();await click('[data-action=hide_unchanged]');await more();await click('[data-action=diff_view]');await click('[data-action=diff_mode_auto]');await wait('primary_diff.side_by_side&&primary_diff.inline_when_narrow');
await click('[data-test-toolbar=current] [data-diff-action=split_editor]');await wait('ws.activeLeaf!==primary_leaf&&ws.activeLeaf.state.path===primary_leaf.state.path&&!!ws.activeLeaf.view.editor');await evaluate('window.split_leaf=ws.activeLeaf;void 0');
await check('split_leaf.parent!==primary_leaf.parent&&split_leaf.view.editor.models.every((model,index)=>!model.isDisposed()&&model.getValue()===primary_diff.models[index].getValue())&&split_leaf.view.editor.toolbar.parentElement===split_leaf.parent.containerEl.querySelector(".workspace-tab-strip")','real Split Editor button opens the same read-only comparison in a distinct owning group');await evaluate('split_leaf.parent.removeTab(split_leaf.state.path);select(primary_leaf);void 0');await delay(100);

// 比较叶子通过既有共享组移动动作上下搬移，不重建模型或丢失工具栏归属。
await evaluate('window.original_group=primary_leaf.parent;window.lower_group=runtime.split_workspace_group(peer_leaf,"down");runtime.move_workspace_leaf(peer_leaf,lower_group,0);select(primary_leaf);primary_leaf.parent.tabHeader.getTabById(primary_leaf.state.path).dataset.diffTestTab="primary";window.range_models=[...diff.models];void 0');await delay(140);
await click('[data-diff-test-tab=primary]','right');await wait('!!document.querySelector(".workspace-editor-menu")');await click('[data-action=split_move]');await click('[data-action=move_down]');await wait('primary_leaf.parent===lower_group');
await check('range_models.every((model,index)=>diff.models[index]===model&&!model.isDisposed())&&diff.toolbar.parentElement===lower_group.containerEl.querySelector(".workspace-tab-strip")','moving the comparison down preserves model identity and reattaches its toolbar to the destination group');
await evaluate('primary_leaf.parent.tabHeader.getTabById(primary_leaf.state.path).dataset.diffTestTab="primary";void 0');await click('[data-diff-test-tab=primary]','right');await wait('!!document.querySelector(".workspace-editor-menu")');await click('[data-action=split_move]');await click('[data-action=move_up]');await wait('primary_leaf.parent===original_group');
await check('range_models.every((model,index)=>diff.models[index]===model&&!model.isDisposed())&&diff.toolbar.parentElement===original_group.containerEl.querySelector(".workspace-tab-strip")','moving the comparison up restores its group without replacing its models');await evaluate('peer_leaf.parent.removeTab(peer_leaf.state.path);select(primary_leaf);void 0');await delay(100);
for(const [width,height,zoom,dark]of [[1100,780,1,false],[420,520,1.25,false],[1100,780,1,true],[420,520,1.25,true]]){
 win.setSize(width,height);win.webContents.setZoomFactor(zoom);await evaluate(`document.body.style.backgroundColor='${dark?'#191a1b':'#fff'}';document.body.style.color='${dark?'#ddd':'#24292f'}';document.documentElement.style.setProperty('--bg-color','${dark?'#191a1b':'#fff'}');document.documentElement.style.setProperty('--text-color','${dark?'#ddd':'#24292f'}');diff.sync_theme();void 0`);await delay(150);
 await more();await check('(()=>{const menu=document.querySelector(".git-diff-title-menu"),r=menu.getBoundingClientRect();return r.width>0&&r.left>=0&&r.top>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1})()','diff title menu fits '+width+'px at '+zoom+' in '+(dark?'dark':'light'));
 await capture('diff_title_'+width+'_'+zoom+'_'+(dark?'dark':'light'));await key('Escape');
 await check('(()=>{const r=diff.toolbar.getBoundingClientRect();return [...diff.toolbar.querySelectorAll("button")].filter(node=>getComputedStyle(node).display!=="none").every(node=>{const b=node.getBoundingClientRect();return b.width>0&&b.left>=r.left-1&&b.right<=r.right+1&&node.contains(document.elementFromPoint(b.left+b.width/2,b.top+b.height/2))})})()','all visible toolbar targets remain unobstructed at '+width+'px '+(dark?'dark':'light'));
 await capture('diff_toolbar_'+width+'_'+zoom+'_'+(dark?'dark':'light'));
}
win.webContents.setZoomFactor(1);win.setSize(1100,780);await delay(100);await evaluate('right.focus();right.setPosition({lineNumber:60,column:1});void 0');await key('F7');await wait('diff.body.querySelector(".diff-review")?.getBoundingClientRect().height>0');await key('Escape');await wait('!diff.body.querySelector(".diff-review")||getComputedStyle(diff.body.querySelector(".diff-review")).visibility!=="visible"||diff.body.querySelector(".diff-review").getBoundingClientRect().height===0');await check('right.hasTextFocus()','native F7 opens accessible diff and Escape restores the modified editor focus');
await evaluate('window.saved_range_action=diff.range_action;window.saved_range_snapshot={original_text:diff.models[0].getValue(),modified_text:diff.models[1].getValue(),line_changes:diff.editor.getLineChanges(),selections:[]};panel.dispose();void 0');await check('!diff.range_available()','disposing the source-control owner disables retained comparison range actions');
const apply_count=await evaluate('applies.length');await evaluate('diff.run_ranges("stage",saved_range_snapshot)');assert.equal(await evaluate('applies.length'),apply_count);assert.equal(git(['rev-parse','HEAD']),head);checks.push('retained range callback cannot write after its owner is disposed');
await evaluate('host.dispose();actions.dispose();tabs.dispose();void 0');
assert.deepEqual(await evaluate('fixture_errors'),[]);fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence:root},null,2));win.destroy();app.exit(0);
}).catch(async error=>{console.error(error.stack||error);console.error(root);if(test_window&&!test_window.isDestroyed()){console.error(await test_window.webContents.executeJavaScript('JSON.stringify({errors:window.fixture_errors,keys:window.fixture_keys?.slice(-18),selection:window.right?.getSelection(),available:window.diff?.range_available(),snapshot:!!window.diff?.range_snapshot(),status:window.diff?.status.textContent,notice:window.panel?.workbench.notice.textContent,writing:window.panel?.writing,pending:window.panel?.pending,applies:window.applies?.length,active:window.ws?.activeLeaf?.state.path})'));fs.writeFileSync(path.join(root,'failure.png'),(await test_window.webContents.capturePage()).toPNG());}app.exit(1)});
