const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_outline_settings_'));
const base=path.resolve(__dirname,'..'),core=path.join(base,'vendor/workspace_core');
app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
  const bundle=await require('esbuild').build({stdin:{contents:'export * from "./src/source_outline_settings"; export {Settings} from "./vendor/workspace_core/src/settings/settings"; export {ConfigRepository} from "./vendor/workspace_core/src/io/config-repository";',resolveDir:base},bundle:true,write:false,loader:{'.css':'text'},format:'iife',globalName:'settings_qa',tsconfigRaw:{compilerOptions:{experimentalDecorators:true}},plugins:[...require('./editor_bundle.cjs').editor_plugins(),{name:'settings-fixture',setup(ctx){
    ctx.onResolve({filter:/.*/,namespace:'fixture'},args=>path.isAbsolute(args.path)?{path:args.path,namespace:'file'}:undefined);
    ctx.onResolve({filter:/clangd_symbol_service$/},()=>({path:'discovery',namespace:'fixture'}));
    ctx.onResolve({filter:/^src\/common\/constants$/},()=>({path:'constants',namespace:'fixture'}));
    ctx.onResolve({filter:/^src\/common\/service$/},()=>({path:'service',namespace:'fixture'}));
    ctx.onResolve({filter:/^src\/utils$/},()=>({path:'utils',namespace:'fixture'}));
    ctx.onLoad({filter:/.*/,namespace:'fixture'},({path:entry})=>({contents:entry==='constants'?'export const globalConfigDir=()=>window.settings_store_root;':entry==='service'?'export function useService(){throw new Error("unexpected service lookup");}':entry==='discovery'?'export const discover_clangd_environment=options=>window.fixture_discovery(options);':`export {Store} from ${JSON.stringify(path.join(core,'src/utils/store.ts'))};export {debounced} from ${JSON.stringify(path.join(core,'src/utils/decorator/debounced.ts'))};`,loader:'js'}));
    ctx.onResolve({filter:/^src\//},args=>({path:path.join(core,args.path)+'.ts'}));
  }}]});
  const win=new BrowserWindow({show:false,width:1000,height:760,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true}});
  win.webContents.on('console-message',(_e,_l,message)=>console.log(message));
  const html=path.join(root,'fixture.html');fs.writeFileSync(html,'<!doctype html><body style="margin:0"><button id="opener">语言服务配置</button></body>','utf8');await win.loadFile(html);
  let evaluation_number=0; const evaluate=async source=>{evaluation_number++;try{return await win.webContents.executeJavaScript(source)}catch(error){fs.writeFileSync(path.join(root,'failed_evaluation.js'),source,'utf8');console.error('Evaluation',evaluation_number,source.slice(0,200));throw error}},pause=()=>new Promise(resolve=>setTimeout(resolve,35));
  await evaluate(`window.reqnode=name=>require(name);window.settings_store_root=${JSON.stringify(path.join(root,'settings'))};window.workspace_one=${JSON.stringify(path.join(root,'project-one'))};window.workspace_two=${JSON.stringify(path.join(root,'project-two'))};window.fixture_discovery=options=>Promise.resolve({executable:'resolved-clangd',compile_commands_dir:require('path').join(options.workspace_root,'build','debug'),candidates:['resolved-clangd']});void 0`);
  await evaluate(bundle.outputFiles[0].text);
  await evaluate(`window.config=new settings_qa.ConfigRepository();window.store=new settings_qa.Settings({filename:'workspace',version:1},{debug(){}},config);window[Symbol.for('typora-code:workspace')]={app:{settings:store}};store.set_and_save('unrelated',{retained:42});void 0`);
  const settings_file=path.join(root,'settings/workspace.json');
  assert.deepEqual(await evaluate('settings_qa.read_source_outline_settings(workspace_one)'),{clangd_path:'',compile_commands_dir:'',fallback_flags:[]},'defaults select automatic discovery');
  await evaluate(`settings_qa.save_source_outline_settings(workspace_one,{clangd_path:'custom-clangd',compile_commands_dir:require('path').join(workspace_one,'build','debug'),fallback_flags:['-Iinclude with spaces','-DFEATURE=1']});settings_qa.save_source_outline_settings(workspace_two,{clangd_path:'custom-clangd',compile_commands_dir:'out',fallback_flags:['-std=c++20']});void 0`);
  assert.deepEqual(await evaluate('settings_qa.read_source_outline_settings(workspace_one)'),{clangd_path:'custom-clangd',compile_commands_dir:path.join('build','debug'),fallback_flags:['-Iinclude with spaces','-DFEATURE=1']});
  assert.deepEqual(JSON.parse(fs.readFileSync(settings_file,'utf8')).settings.unrelated,{retained:42});
  if(process.platform==='win32')assert.deepEqual(await evaluate('settings_qa.read_source_outline_settings(workspace_one.toUpperCase())'),await evaluate('settings_qa.read_source_outline_settings(workspace_one)'),'case aliases share Windows workspace settings');
  const previous=fs.readFileSync(settings_file,'utf8');
  await evaluate(`window.failure_mode='rename';window.reqnode=name=>name!=='fs'?require(name):new Proxy(require('fs'),{get(target,key){if(key==='renameSync'&&failure_mode==='rename')return()=>{throw new Error('fixture rename denied')};if(key==='writeFileSync'&&failure_mode==='write')return(fd)=>{target.writeFileSync(fd,'partial','utf8');throw new Error('fixture partial write')};return target[key];}});void 0`);
  assert.match(await evaluate(`(()=>{try{settings_qa.save_source_outline_settings(workspace_one,{clangd_path:'bad',compile_commands_dir:'bad',fallback_flags:[]});return 'no error'}catch(error){return error.message}})()`),/rename denied/);
  assert.equal(fs.readFileSync(settings_file,'utf8'),previous,'rename failure preserves original bytes');
  assert.equal(await evaluate('settings_qa.read_source_outline_settings(workspace_one).clangd_path'),'custom-clangd','failed persistence never publishes new settings');
  await evaluate(`failure_mode='write';void 0`);
  assert.match(await evaluate(`(()=>{try{store.set_and_save('unrelated',{retained:false});return 'no error'}catch(error){return error.message}})()`),/partial write/);
  assert.equal(fs.readFileSync(settings_file,'utf8'),previous,'partial temporary write preserves original bytes');
  assert.deepEqual(fs.readdirSync(path.dirname(settings_file)),['workspace.json'],'failed saves clean only their owned temporary files');
  await evaluate(`failure_mode='';window.saved_calls=0;document.querySelector('#opener').focus();window.dialog=settings_qa.open_source_outline_settings(workspace_one,()=>saved_calls++);void 0`);await pause();
  assert.equal(await evaluate(`document.querySelector('[data-field="fallback_flags"]').value`),'-Iinclude with spaces\n-DFEATURE=1');
  assert.equal(await evaluate(`getComputedStyle(dialog.root.querySelector('input')).fontSize`),'13px');
  await evaluate(`dialog.root.querySelector('[data-action="detect"]').click();void 0`);await pause();
  const status=await evaluate(`dialog.root.querySelector('[role="status"]').textContent`);assert.match(status,/resolved-clangd/);assert(!status.includes(root),'detected database displayed relative to project');
  await evaluate(`window.pending_detection_resolve=null;fixture_discovery=()=>new Promise(resolve=>pending_detection_resolve=resolve);dialog.root.querySelector('[data-action="detect"]').click();dialog.root.querySelector('[data-field="clangd_path"]').value='changed-after-detection';dialog.root.querySelector('[data-field="clangd_path"]').dispatchEvent(new Event('input',{bubbles:true}));pending_detection_resolve({executable:'stale',compile_commands_dir:''});void 0`);await pause();
  assert.equal(await evaluate(`dialog.root.querySelector('[role="status"]').textContent`),'','stale detection result does not overwrite edited form status');
  await evaluate(`failure_mode='rename';dialog.root.querySelector('[data-action="save"]').click();void 0`);
  assert(await evaluate(`dialog.root.isConnected&&saved_calls===0&&dialog.root.querySelector('[role="status"]').textContent.includes('保存失败')`),'failed save remains reviewable and never reports success');
  await evaluate(`failure_mode='';dialog.root.querySelector('[data-field="fallback_flags"]').value=${JSON.stringify('-Iinclude with spaces\n-DFEATURE=2')};dialog.root.querySelector('[data-action="save"]').click();void 0`);await pause();
  assert.equal(await evaluate('saved_calls'),1);assert.equal(await evaluate('dialog.root.isConnected'),false);assert.equal(await evaluate('document.activeElement.id'),'opener');
  assert.equal(await evaluate('settings_qa.read_source_outline_settings(workspace_one).fallback_flags[0]'),'-Iinclude with spaces','parameters retain whitespace within one argument');
  assert.deepEqual(await evaluate('settings_qa.read_source_outline_settings(workspace_two).fallback_flags'),['-std=c++20'],'other workspace unchanged');
  const saved_bytes=fs.readFileSync(settings_file,'utf8');
  await evaluate(`dialog=settings_qa.open_source_outline_settings(workspace_one);dialog.root.querySelector('[data-field="clangd_path"]').value='cancelled';window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));window.dispatchEvent(new KeyboardEvent('keyup',{key:'Escape',bubbles:true,cancelable:true}));void 0`);await pause();
  assert.equal(fs.readFileSync(settings_file,'utf8'),saved_bytes,'Escape does not save drafts');
  assert.equal(await evaluate(`document.querySelectorAll('.source-outline-settings').length`),0);
  await evaluate(`dialog=settings_qa.open_source_outline_settings(workspace_one);settings_qa.save_source_outline_settings(workspace_two,{clangd_path:'new-global',compile_commands_dir:'out',fallback_flags:['-std=c++20']});dialog.root.querySelector('[data-field="compile_commands_dir"]').value='different-build';dialog.root.querySelector('[data-action="save"]').click();void 0`);await pause();
  assert.equal(await evaluate('settings_qa.read_source_outline_settings(workspace_one).clangd_path'),'new-global','unchanged global field preserves concurrent update');
  await evaluate(`dialog=settings_qa.open_source_outline_settings(workspace_one);window.reloaded=new settings_qa.Settings({filename:'workspace',version:1},{debug(){}},new settings_qa.ConfigRepository());void 0`);
  assert.deepEqual(await evaluate(`reloaded.get('source_outline')`),JSON.parse(fs.readFileSync(settings_file,'utf8')).settings.source_outline,'fresh settings instance loads successful persistent settings');
  win.setSize(400,340);await pause();
  assert(await evaluate(`(()=>{const rect=dialog.root.querySelector('.git-graph-dialog').getBoundingClientRect();const footer=dialog.footer.getBoundingClientRect();return rect.left>=0&&rect.right<=innerWidth&&rect.top>=0&&rect.bottom<=innerHeight&&footer.bottom<=innerHeight})()`),'small viewport preserves footer and bounded content scroll');
  await evaluate(`document.body.style.setProperty('--bg-color','#181818');document.body.style.setProperty('--text-color','#eee');void 0`);
  assert.equal(await evaluate(`getComputedStyle(dialog.root.querySelector('input')).backgroundColor`),'rgb(24, 24, 24)','input follows host dark theme');
  await evaluate(`dialog.close();void 0`);await pause();
  assert.equal(await evaluate(`document.getElementById('typora-code-source-outline-settings')===null`),true,'closing last dialog releases module style');
  assert(!fs.existsSync(path.join(root,'project-one'))&&!fs.existsSync(path.join(root,'project-two')),'no writes within user project paths');
  console.log(JSON.stringify({status:'PASS',checks:['automatic defaults','project and global scope','per-line arguments','atomic rename/partial-write failure','no false success','reload persistence','stale discovery','cancel/focus restore','small viewport and dark theme','no project writes'],evidence:root}));
  win.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(root);app.exit(1)});
