// 实际 Monaco 差异与源码视图共同使用唯一底栏；文件只放在临时目录。
const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {build}=require('esbuild');const {editor_plugins}=require('./editor_bundle.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_diff_status_'));app.setPath('userData',path.join(root,'user_data'));app.disableHardwareAcceleration();
const source_path=path.join(root,'source.ts');fs.writeFileSync(source_path,'const value = 1;\r\nconst next = 2;\r\n');
let test_window;const checks=[],runtime_errors=[];const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const check=async(source,label)=>{const passed=await evaluate(source);if(!passed)console.error(await evaluate('({text:binding.container.textContent,last:diff?.last_focused_editor===right,leftfocus:left?.hasTextFocus(),rightfocus:right?.hasTextFocus(),position:right?.getPosition(),eol:JSON.stringify(right?.getModel()?.getEOL())})'));assert(passed,label);checks.push(label)};
const wait=async source=>{for(let index=0;index<250;index++){if(await evaluate(source))return;await delay(30)}throw new Error('Timed out: '+source)};
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:1100,height:750,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false,offscreen:true}});
  test_window.webContents.on('console-message',(_event,level,message)=>{if(level>=2)console.error(message);if(level>=3)runtime_errors.push(message)});
  const html=path.join(root,'test.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{height:100%;margin:0;overflow:hidden;background:white;color:#222;font-family:Arial}main{position:absolute;inset:0 0 28px;display:flex;flex-direction:column}.fixture-tab-content{flex:1;min-height:0}.typ-workspace-tab-header{overflow:hidden;display:flex}.typ-tab{flex:none}footer.ty-footer{position:absolute;bottom:0;left:0;right:0;height:28px;background:#eee}</style><body class="show-footer"><main class="typ-workspace-tabs mod-active"><div class="workspace-tab-strip"><div class="typ-workspace-tab-header"></div></div><div class="fixture-tab-content"></div></main><footer class="ty-footer"><span id="footer-word-count">100 词</span></footer></body>');await test_window.loadFile(html);
  const bundle=await build({plugins:editor_plugins(),stdin:{contents:'export {git_diff_editor} from "./src/git_diff_editor";export {create_graph_host} from "./src/git_graph_host";export {bind_workspace_files} from "./src/workspace_files";export {bind_workspace_editor_status} from "./src/workspace_editor_status";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'status_qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{
    const style=document.createElement('style');style.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'../src/workspace_tab_controls.css'),'utf8'))};document.head.append(style);
    window.reqnode=name=>name==='electron'?{shell:{}}:require(name);window._options={userDataPath:${JSON.stringify(root)}};window.JSBridge={invoke:async()=>{}};
    window.File={getMountFolder:()=>${JSON.stringify(root)},bundle:{filePath:${JSON.stringify(source_path)}},changeCounter:{isDocumentEdited:()=>false},editor:{library:{}}};
    window.factories=new Map();window.listeners=new Map();window.leaves=[];let active=null;
    class view{constructor(leaf){this.leaf=leaf;this.containerEl=document.createElement('div')}onOpen(){}onClose(){}}
    window.tab_root=document.querySelector('.typ-workspace-tab-header');window.parent_group={containerEl:document.querySelector('main'),tabHeader:{getTabById:uri=>[...tab_root.children].find(tab=>tab.dataset.id===uri)},appendChild(leaf){leaves.push(leaf);const tab=document.createElement('div');tab.className='typ-tab';tab.dataset.id=leaf.state.path;tab.innerHTML='<i class="typ-file-icon fa fa-code-fork"></i><span class="typ-file-basename"></span>';tab_root.append(tab)},toggleTab(uri){return leaves.find(leaf=>leaf.state.path===uri)}};
    const workspace={activeFile:${JSON.stringify(source_path)},get activeLeaf(){return active},set activeLeaf(leaf){active?.view.onClose?.();active=leaf;document.querySelector('.fixture-tab-content').replaceChildren(leaf.view.containerEl);leaf.view.onOpen?.();listeners.get('active-leaf:change')?.forEach(callback=>callback(leaf))},eachLeaves(callback){leaves.forEach(callback)},createLeaf(descriptor){const leaf={...descriptor,parent:parent_group,containerEl:document.createElement('div')};leaf.view=factories.get(descriptor.type)(leaf);return leaf},on(name,callback){if(!listeners.has(name))listeners.set(name,new Set());listeners.get(name).add(callback);return()=>listeners.get(name).delete(callback)},ribbon:{addButton(){}},sidebar:{toggle(){}}};
    window.core={WorkspaceView:view,app:{workspace,openFile(){},viewManager:{registerView:(type,factory)=>factories.set(type,factory)},commands:{register(){},run(){}}}};
    const placeholder={state:{path:'placeholder'},parent:parent_group,view:{containerEl:document.createElement('div')}};leaves.push(placeholder);workspace.activeLeaf=placeholder;
    window.files=status_qa.bind_workspace_files(core);window.host=status_qa.create_graph_host(core);window.binding=status_qa.bind_workspace_editor_status(core);
    window.active_editor=()=>core.app.workspace.activeLeaf.view.editor;
  })()`);
  await evaluate(`files.open_file(${JSON.stringify(source_path)})`);await wait('core.app.workspace.activeLeaf.view.loaded');
  await evaluate('window.source_leaf=core.app.workspace.activeLeaf;source_leaf.view.editor.focused_editor().setPosition({lineNumber:2,column:7})');
  await check('document.querySelectorAll(".linux-note-editor-status").length===1 && status_qa.bind_workspace_editor_status(core)===binding','source and Git host factories reuse one shared status instance');
  await check('binding.container.firstChild===source_leaf.view.status_controls && binding.container.textContent.includes("行 2，列 7")','real source view owns the initial global status');
  const diff_data={title:'test.ts 的更改',file:'test.ts',left:'const a = 1;\r\nconst old_value = 2;\r\n',right:'const a = 1;\nconst new_value = 20;\nconst added = 3;\n',left_label:'提交 abc',right_label:'工作区'};
  await evaluate(`window.open_file_disabled=false;window.open_file_calls=0;host.open_document(${JSON.stringify(diff_data)},'active',{root:${JSON.stringify(root)},menu:()=>[{id:'open_file',title:'打开文件',disabled:open_file_disabled,action:()=>{open_file_calls++;void files.open_file(${JSON.stringify(source_path)});}}]});window.diff_leaf=core.app.workspace.activeLeaf;window.diff=active_editor();void 0;`);
  await wait('diff?.editor.getLineChanges()!==null');await delay(120);

  await check('diff.toolbar.parentElement===tab_root.parentElement && !diff.container.querySelector(".git-diff-toolbar") && diff.toolbar.getBoundingClientRect().top===tab_root.getBoundingClientRect().top','production host mounts actions beside this group tab header with no duplicate content toolbar row');
  await check('(()=>{const buttons=[...diff.toolbar.querySelectorAll("button")];return buttons.length===5&&buttons.every(button=>{const box=button.getBoundingClientRect(),icon=button.querySelector("svg");return box.width===24&&box.height===24&&icon?.getBoundingClientRect().width===16&&button.textContent===""&&button.title===button.getAttribute("aria-label")})&&getComputedStyle(diff.toolbar).fontSize==="13px"&&getComputedStyle(diff.labels).fontSize==="13px"&&diff.labels.getBoundingClientRect().height===26})()','tab-row actions use 24px hitboxes and official 16px icons; revision labels are 13px in a 26px row');
  await evaluate('document.body.style.fontSize="24px"');await check('getComputedStyle(diff.toolbar).fontSize==="13px"&&getComputedStyle(diff.labels).fontSize==="13px"','document font enlargement does not enlarge editor actions or revision headings');await evaluate('document.body.style.fontSize=""');
  for(const [width,layout] of [[901,"split"],[900,"inline"],[899,"inline"],[901,"split"]]){
    await evaluate(`document.querySelector('main').style.width='${width}px';void 0`);await wait(`Math.round(diff.body.getBoundingClientRect().width)===${width}&&diff.labels.dataset.diffLayout===${JSON.stringify(layout)}`);
    await check(`diff.body.querySelector('.monaco-diff-editor').classList.contains('side-by-side')===${layout==='split'}`,'actual editor-group width '+width+'px selects '+layout+' at the upstream 900px boundary');
  }
  await evaluate('diff.set_side_by_side(false);document.querySelector("main").style.width="1050px"');await wait('diff.labels.dataset.diffLayout==="inline"');
  await check('diff.labels.querySelectorAll(":scope > div").length===1&&diff.labels.textContent.includes("提交 abc ↔ 工作区")&&!!diff.labels.querySelector(".git-diff-mode")','manual inline persists in a wide group and displays both revisions in one compact row with mode selector');
  await evaluate('diff.labels.querySelector(".git-diff-mode").click();document.querySelector("[data-action=diff_mode_split]").click();');await wait('diff.labels.dataset.diffLayout==="split"');
  await check('diff.side_by_side&&diff.labels.querySelectorAll(":scope > div").length===2&&diff.labels.firstChild.title==="提交 abc"&&diff.labels.children[1].title==="工作区"','mode selector restores two version labels without discarding either revision');
  await evaluate('diff.toolbar.querySelector("[data-git-icon=more]").closest("button").click();document.querySelector("[data-action=show_moves]").click();');await check('diff.show_moves===true','overflow menu enables the actual Monaco moved-code option');
  await evaluate('diff.toolbar.querySelector("[data-git-icon=more]").closest("button").click();document.querySelector("[data-action=inline_when_narrow]").click();document.querySelector("main").style.width="899px";');await wait('diff.labels.dataset.diffLayout==="inline"');
  await check('diff.inline_when_narrow===true&&diff.side_by_side===true','automatic inline is a distinct setting and leaves manual side-by-side preference intact');
  await evaluate('document.querySelector("main").style.width="";');await wait('diff.labels.dataset.diffLayout==="split"');
  await evaluate('diff.container.dispatchEvent(new KeyboardEvent("keydown",{key:"F7",bubbles:true,cancelable:true}));');
  await wait('diff.body.querySelector(".diff-review")?.getBoundingClientRect().height>0');
  await check('!!diff.body.querySelector(".diff-review")','F7 opens Monaco accessible diff rather than masquerading as ordinary next-change navigation');
  await evaluate('diff.body.querySelector(".close-diff-review")?.click();void 0');await delay(150);

  await evaluate(String.raw`(()=>{const peer=document.createElement('div');peer.className='typ-workspace-tabs mod-active';peer.style.cssText='position:absolute;top:100px;left:0;width:960px;height:420px;display:flex;flex-direction:column';peer.innerHTML='<div class="workspace-tab-strip"><div class="typ-workspace-tab-header"><span class="typ-tab">peer.ts</span></div></div><div class="peer-content" style="flex:1;min-height:0"></div>';document.body.append(peer);window.peer_group=peer;const lines=Array.from({length:500},(_,i)=>'const row_'+i+' = '+i+';');const changed=[...lines];changed[349]='const row_349 = 999;';window.peer_diff=new status_qa.git_diff_editor({title:'peer.ts',file:'peer.ts',left:lines.join('\n'),right:changed.join('\n'),left_label:'peer.ts (old)',right_label:'peer.ts (new)'});peer.querySelector('.peer-content').append(peer_diff.container);peer_diff.attach_toolbar(peer.querySelector('.typ-workspace-tab-header'));})()`);await wait('peer_diff.editor.getLineChanges()!==null&&peer_diff.labels.dataset.diffLayout==="split"');
  await check('peer_diff.toolbar.parentElement===peer_group.querySelector(".workspace-tab-strip")&&diff.toolbar.parentElement===tab_root.parentElement','each editor group owns its own action slot without stealing another diff toolbar');
  await evaluate('window.peer_right=peer_diff.editor.getModifiedEditor();peer_right.focus();peer_right.setSelection({startLineNumber:200,startColumn:3,endLineNumber:200,endColumn:7});peer_right.setScrollTop(3000);window.peer_selection=JSON.stringify(peer_right.getSelection());window.peer_scroll=peer_right.getScrollTop();peer_group.style.width="899px";');await wait('peer_diff.labels.dataset.diffLayout==="inline"');
  await check('JSON.stringify(peer_right.getSelection())===peer_selection&&Math.abs(peer_right.getScrollTop()-peer_scroll)<2&&diff.labels.dataset.diffLayout==="split"','shrinking one editor group preserves its selection and scroll while the other group remains split');
  await evaluate('peer_group.style.width="960px";');await wait('peer_diff.labels.dataset.diffLayout==="split"');await check('JSON.stringify(peer_right.getSelection())===peer_selection&&Math.abs(peer_right.getScrollTop()-peer_scroll)<2','growing the editor group restores split rendering without moving the retained selection or scroll');
  await evaluate('peer_diff.set_side_by_side(false);peer_diff.set_side_by_side(true);');await wait('peer_diff.labels.dataset.diffLayout==="split"');await check('JSON.stringify(peer_right.getSelection())===peer_selection&&Math.abs(peer_right.getScrollTop()-peer_scroll)<2','manual inline and split switching preserves view state');
  await evaluate('peer_diff.detach_toolbar();peer_diff.dispose();peer_group.remove();');await check('diff.toolbar.isConnected&&diff.toolbar.parentElement===tab_root.parentElement','disposing another group removes only its own actions');
  await check(`(()=>{const icon=[...tab_root.querySelectorAll('.typ-tab')].find(tab=>tab.dataset.id===diff_leaf.state.path)?.querySelector('.workspace-file-theme-icon');return icon?.dataset.vscodeFileIcon==='_typescript'&&icon.dataset.fileIconPath==='test.ts'})()`,'real diff tab uses file type association instead of Git glyph');
  await check('binding.container.firstChild===diff.readonly_status && !binding.container.querySelector("[aria-label=保存编码]") && binding.container.textContent.includes("只读")','Git diff registers read-only model state without inventing a file encoding');
  await evaluate('window.left=diff.editor.getOriginalEditor();window.right=diff.editor.getModifiedEditor();left.focus();left.setPosition({lineNumber:2,column:5});');await delay(50);
  await check('binding.container.textContent.includes("原始版本") && binding.container.textContent.includes("行 2，列 5") && binding.container.querySelector("[aria-label=行尾序列]").textContent==="CRLF"','focusing the original pane shows its actual position and CRLF');
  await evaluate('right.focus();right.setPosition({lineNumber:3,column:8});');await delay(50);
  await check('binding.container.textContent.includes("修改版本") && binding.container.textContent.includes("行 3，列 8") && binding.container.querySelector("[aria-label=行尾序列]").textContent==="LF"','focusing the modified pane switches the global position and LF');
  await evaluate('left.setPosition({lineNumber:1,column:1});status_qa.monaco.editor.setModelLanguage(right.getModel(),"javascript");');await delay(60);
  await check('binding.container.textContent.includes("行 3，列 8") && binding.container.querySelector("[aria-label=语言模式]").textContent==="javascript"','background pane cursor changes do not steal status and active language changes refresh');
  await evaluate('diff.toolbar.querySelector("button").focus();right.setPosition({lineNumber:2,column:4});');await delay(60);
  await check('diff.focused_editor()===right && binding.container.textContent.includes("修改版本") && binding.container.textContent.includes("行 2，列 4")','toolbar focus retains the last active comparison side');
  await evaluate('core.app.workspace.activeLeaf=source_leaf;right.setPosition({lineNumber:1,column:2});');await delay(60);
  await check('!diff.toolbar.isConnected && binding.container.firstChild===source_leaf.view.status_controls && binding.container.textContent.includes("行 2，列 7")','returning to source restores its own state despite later background diff events');
  await evaluate('core.app.workspace.activeLeaf=diff_leaf;void 0;');await delay(50);
  await check('binding.container.firstChild===diff.readonly_status && binding.container.textContent.includes("修改版本")','reopening a retained diff tab restores its last selected side');
  await check('(()=>{const toolbar=diff.toolbar.getBoundingClientRect(),button=diff.toolbar.querySelector("[data-diff-open-file]").getBoundingClientRect();return button.width>0&&button.right<=toolbar.right&&toolbar.right-button.right<12})()','Open File remains visible at the comparison toolbar right edge');
  fs.writeFileSync(path.join(root,'diff_open_file.png'),(await test_window.webContents.capturePage()).toPNG());
  await evaluate('diff.toolbar.querySelector("[data-diff-open-file]").click()');await wait('core.app.workspace.activeLeaf===source_leaf');
  await check('open_file_calls===1 && source_leaf.view.loaded && diff.models.every(model=>!model.isDisposed())','diff Open File button invokes the existing real file route and retains comparison models');
  await evaluate('open_file_disabled=true;core.app.workspace.activeLeaf=diff_leaf;void 0;');
  await check('diff.toolbar.querySelectorAll("[data-diff-open-file]").length===1 && diff.toolbar.querySelector("[data-diff-open-file]").disabled','retained diff refreshes unavailable current-file state without duplicate toolbar buttons');
  await evaluate('diff.toolbar.querySelector("[data-diff-open-file]").click()');
  await check('open_file_calls===1 && core.app.workspace.activeLeaf===diff_leaf','disabled Open File cannot switch from a deleted or unavailable comparison');
  await evaluate('leaves.splice(leaves.indexOf(diff_leaf),1);core.app.workspace.activeLeaf=source_leaf;void 0;');await delay(80);
  await check('diff.models.every(model=>model.isDisposed()) && binding.container.firstChild===source_leaf.view.status_controls && document.querySelectorAll(".linux-note-editor-status").length===1','closing diff disposes its models and restores source with one global bar');
  for(const [name,id] of [['docs/guide.md','_markdown'],['boards/board.yml','_yml'],['README.md','_info'],['removed.custom_extension','_default']]) {
    await evaluate(`host.open_document({title:${JSON.stringify(name)},file:${JSON.stringify(name)},left:'old',right:'new'},'active');void 0`);
    await check(`(()=>{const leaf=core.app.workspace.activeLeaf;const slot=[...tab_root.querySelectorAll('.typ-tab')].find(tab=>tab.dataset.id===leaf.state.path)?.querySelector('.typ-file-icon');return slot?.querySelector('.workspace-file-theme-icon')?.dataset.vscodeFileIcon===${JSON.stringify(id)}&&!slot.querySelector('svg')})()`,'diff association '+name);
  }
  await evaluate(`host.open_document({title:'Command output',left:'log'},'active');void 0`);
  await check(`(()=>{const leaf=core.app.workspace.activeLeaf;return [...tab_root.querySelectorAll('.typ-tab')].find(tab=>tab.dataset.id===leaf.state.path)?.querySelector('[data-git-icon="compare-changes"]')!==null})()`,'non-file output keeps its tool glyph');
  await evaluate('binding.dispose()');
  assert.deepEqual(runtime_errors,[],'no uncaught editor lifecycle errors');console.log(JSON.stringify({status:'PASS',checks,evidence:root},null,2));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);if(test_window&&!test_window.isDestroyed()){fs.writeFileSync(path.join(root,'failure.png'),(await test_window.webContents.capturePage()).toPNG());test_window.destroy()}console.error(root);app.exit(1)});
