const {app,BrowserWindow}=require('electron');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora_editor_actions_'));app.setPath('userData',path.join(root,'electron'));app.disableHardwareAcceleration();
let test_window;app.whenReady().then(async()=>{const win=test_window=new BrowserWindow({show:false,width:1100,height:780,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true}});win.webContents.on('console-message',(_e,_l,m)=>console.log(m));const html=path.join(root,'host.html');fs.writeFileSync(html,'<!doctype html><body><div id="typora-sidebar"><div id="sidebar-content"><div id="outline-content"></div><div id="file-library"></div><div id="file-library-search"><div><input id="file-library-search-input"></div></div><div id="file-library-search-result"></div></div></div><div id="typora-sidebar-resizer"></div><content><div id="write"></div></content><footer id="footer"><span id="footer-word-count"></span></footer>','utf8');await win.loadFile(html);win.webContents.debugger.attach();await win.webContents.debugger.sendCommand('Emulation.setFocusEmulationEnabled',{enabled:true});
await win.webContents.executeJavaScript(`window.$=window.jQuery=require(${JSON.stringify(require.resolve('jquery'))});window.fixture_errors=[];window.addEventListener('error',e=>(fixture_errors.push(String(e.error?.stack||e.error)),console.log(e.error?.stack)));window.addEventListener('unhandledrejection',e=>fixture_errors.push(String(e.reason)));window.reqnode=name=>require(name);window._options={userDataPath:${JSON.stringify(root)},mountFolder:${JSON.stringify(path.join(root,'one'))},appLocale:'en',locale:'en'};window.fixture_noop=()=>{};window.fixture_object=()=>new Proxy(function(){},{get(target,key){if(key in target)return target[key];if(key==='then'||typeof key==='symbol')return undefined;return target[key]=fixture_object();}});window.editor=fixture_object();editor.writingArea=document.querySelector('#write');editor.library=fixture_object();editor.selection=fixture_object();editor.sourceView=fixture_object();editor.nodeMap={allNodes:{_set:[],first:()=>null}};editor.getMarkdown=()=>'';window.File=fixture_object();File.isNode=true;File.isMac=false;File.isWin=true;File.filePath='';File.bundle={filePath:''};File.option={};File.getMountFolder=()=>_options.mountFolder;File.setMountFolder=path=>_options.mountFolder=path;File.editor=editor;window.JSBridge=fixture_object();window.bridge=fixture_object();window.ClientCommand=fixture_object();window.CodeMirror=fixture_object();window.gettext=value=>value;void 0`);
// Only host APIs are substituted; runtime production bundle and settings/fs implementation are real.
fs.mkdirSync(path.join(root,'typora_code','locales'),{recursive:true});for(const name of fs.readdirSync(path.join(__dirname,'../dist/locales')))fs.copyFileSync(path.join(__dirname,'../dist/locales',name),path.join(root,'typora_code','locales',name));
await win.webContents.executeJavaScript(`window.fixture_registrations=[];window.fixture_add=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(type,listener,options){fixture_registrations.push({target:this,type,listener,options});return fixture_add.call(this,type,listener,options)};void 0`);
await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.js'),'utf8'));
await win.webContents.executeJavaScript(`window.runtime=window[Symbol.for('typora-code:workspace')];runtime.ready.then(()=>'ready').catch(error=>{console.log(fixture_errors.join('\\n'));throw error})`);

const checks=[];
const evaluate=source=>win.webContents.executeJavaScript(source);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const wait=async source=>{for(let i=0;i<200;i++){if(await evaluate(source))return;await delay(25);}throw Error('Timeout: '+source);};
const check=async(source,title)=>{assert(await evaluate(source),title);checks.push(title);};
const click=async(selector,button='left')=>{const point=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw Error('missing node');node.scrollIntoView({block:'nearest'});const r=node.getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()`);point.x=Math.round(point.x*win.webContents.getZoomFactor());point.y=Math.round(point.y*win.webContents.getZoomFactor());for(const type of ['mouseMove','mouseDown','mouseUp']){win.webContents.sendInputEvent({type,...point,button,clickCount:1});await delay(25);}};
const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});if(keyCode==='Enter'&&!modifiers.length)win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(50);};
await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../dist/workspace_core.css'),'utf8'));
await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'));
await win.webContents.insertCSS('html,body{width:100%;height:100%;margin:0;overflow:hidden;color:#24292f;background:#fff}#typora-sidebar,.typ-ribbon,content{display:none!important}.typ-workspace-root{z-index:1!important;position:fixed!important;inset:0!important}.typ-workspace-split{min-width:0}.typ-workspace-tabs{min-width:0}.typ-workspace-tab-header{height:35px}.typ-tabs{display:flex}.typ-tab{height:35px;max-width:200px}footer{position:fixed;bottom:0}.typ-close{font:16px system-ui}.typ-close:before{content:"×"}');
const {editor_plugins}=require('./editor_bundle.cjs');
const bundle=await require('esbuild').build({plugins:editor_plugins(),stdin:{contents:'export {create_workspace_quick_open} from "./src/workspace_quick_open";export {bind_workspace_settings_view} from "./src/workspace_settings_view";export {bind_workspace_settings_sections} from "./src/workspace_settings_sections";export {bind_workspace_files} from "./src/workspace_files";export {bind_workspace_editor_actions,request_workspace_editor_title_entries} from "./src/workspace_editor_actions";export * from "./src/workspace_editor_settings";export {workspace_menu} from "./src/workspace_widgets";export {bind_workspace_tab_controls} from "./src/workspace_tab_controls";export {install_workspace_shortcuts} from "./src/workspace_shortcuts";export {bind_workspace_file_commands} from "./src/workspace_file_commands";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.css':'text'},format:'iife',globalName:'editor_qa'});
await evaluate(bundle.outputFiles[0].text);
const folder=path.join(root,'one');fs.mkdirSync(folder,{recursive:true});const first=path.join(folder,'中文 draft.c'),second=path.join(folder,'second.c'),third=path.join(folder,'third.c');for(const file of [first,second,third])fs.writeFileSync(file,'int original = 1;\n');
await evaluate(`window.first_path=${JSON.stringify(first)};window.second_path=${JSON.stringify(second)};window.third_path=${JSON.stringify(third)};window.window_requests=[];window.copied=[];window.revealed=[];window.notices=[];runtime.Notice=class{constructor(text){notices.push(text)}};
File.changeCounter={isDocumentEdited:()=>false};File.isFileLoading=()=>false;File.inSavingProcess=false;File._onFileSwitching=false;File._onInitParse=false;window.native_calls=[];window.native_result={native:true};window.native_callback_receiver={native_callback:true};File.editor.library.openFile=function(target,...args){native_calls.push({target,args,receiver:this,group:runtime.app.workspace.activeLeaf.parent});if(typeof args[0]==='function')args[0].call(native_callback_receiver,'loaded',71);return native_result;};
JSBridge.invoke=async(command,payload)=>{if(command==='clipboard.write')copied.push(JSON.parse(payload).text);return null;};
window.base_reqnode=reqnode;window.reqnode=name=>name==='electron'?{clipboard:{writeText:value=>copied.push(value)},shell:{showItemInFolder:value=>revealed.push(value),openPath:async()=>''},ipcRenderer:{invoke:async()=>{}}}:base_reqnode(name);
window.files=editor_qa.bind_workspace_files(runtime);window.tab_controls=editor_qa.bind_workspace_tab_controls(runtime);window.quick=editor_qa.create_workspace_quick_open(files);window.sections=editor_qa.bind_workspace_settings_sections(files);window.settings_view=editor_qa.bind_workspace_settings_view(runtime);
window.actions=editor_qa.bind_workspace_editor_actions(files,{open:(leaf,copy=false)=>window_requests.push({leaf,copy})});
window.file_commands=editor_qa.bind_workspace_file_commands(files,()=>{});window.shortcut_binding=editor_qa.install_workspace_shortcuts(runtime.app,window);
window.ws=runtime.app.workspace;window.leaves=()=>{const list=[];ws.eachLeaves(leaf=>{list.push(leaf);});return list;};
window.select=leaf=>{ws.activeLeaf=leaf.parent.toggleTab(leaf.state.path);};
window.edit=(leaf,text)=>{const editor=leaf.view.editor.focused_editor();editor.pushUndoStop();editor.executeEdits('test',[{range:editor.getModel().getFullModelRange(),text}]);editor.pushUndoStop();};
window.entry=(leaf,id)=>actions.entries(leaf).find(item=>item.id===id);
window.close_dialog=label=>{const target=[...document.querySelectorAll('.git-graph-dialog-footer button')].find(button=>button.textContent===label);if(!target)throw Error('missing '+label);target.click();};void 0;`);
await evaluate('files.open_file(first_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.first=ws.activeLeaf;void 0');
await evaluate('files.open_file(second_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.second=ws.activeLeaf;void 0');
await evaluate('files.open_file(third_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.third=ws.activeLeaf;window.group=first.parent;group.removeTab("");void 0');
await delay(150);
// 标题菜单通过真实同步贡献协议取得当前组动作，用指针验证其调用入口。
await evaluate(`window.title_leaf=first;window.title_button=document.createElement('button');title_button.dataset.editorTitleTest='true';title_button.textContent='编辑器组';title_button.style.cssText='position:fixed;right:12px;top:46px;z-index:10000';title_button.onclick=event=>editor_qa.workspace_menu(event,editor_qa.request_workspace_editor_title_entries(title_leaf),'workspace-menu-compact workspace-editor-title-test');document.body.append(title_button);void 0`);
const open_title=async owner=>{await evaluate('title_leaf='+owner+';void 0');await click('[data-editor-title-test]');await wait('!!document.querySelector(".workspace-editor-title-test")');};
await open_title('first');
await check("[...document.querySelectorAll('.workspace-editor-title-test>button')].map(node=>node.dataset.action).join(',')==='show_opened_editors,close_all,close_saved,enable_preview_editors,lock_group,configure_editors'",'title entries follow fixed upstream groups with actual close, preview, lock and settings actions');
await check("document.querySelector('[data-action=enable_preview_editors]').getAttribute('aria-checked')==='true'&&document.querySelector('[data-action=lock_group]').getAttribute('aria-checked')==='false'",'preview defaults on and group lock defaults off');
await click('[data-action=show_opened_editors]');await wait('document.querySelectorAll(".workspace-quick-open-result").length===3');
await check('quick.input.value==="edt active "&&ws.activeLeaf===third','Show Opened Editors uses the current-group QuickPick and preserves activation until selection');
await evaluate('quick.input.value="edt active second";quick.input.dispatchEvent(new Event("input"));void 0');await wait('document.querySelectorAll(".workspace-quick-open-result").length===1');await key('Enter');await wait('ws.activeLeaf===second');checks.push('filtered QuickPick activates the existing leaf without reopening');
await open_title('first');await click('[data-action=show_opened_editors]');await wait('!quick.root.hidden');await key('Down');await key('Enter');await wait('quick.root.hidden');checks.push('opened editors QuickPick supports native keyboard navigation');
await open_title('first');await click('[data-action=show_opened_editors]');await evaluate('quick.input.value="edt active third";quick.input.dispatchEvent(new Event("input"));void 0');await wait('document.querySelectorAll(".workspace-quick-open-result").length===1');await click('.workspace-quick-open-close');await wait('!leaves().includes(third)');await check('!quick.root.hidden','closing a QuickPick row keeps the picker open and removes only its target');await key('Escape');
await evaluate('files.open_file(third_path)');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.third=ws.activeLeaf;quick.open();quick.input.value="edt active ";quick.input.dispatchEvent(new Event("input"));void 0');await wait('document.querySelectorAll(".workspace-quick-open-result").length===3');await check('!!document.querySelector(".workspace-quick-open-close")','typing edt active routes to the same group provider');await key('Escape');
await check('editor_qa.request_workspace_editor_title_entries({state:{path:"invalid"},parent:group}).length===0','invalid leaves receive no title contribution');
const preview_paths=['preview_a.c','preview_b.c','preview_c.c','preview_d.c'].map(name=>path.join(folder,name));for(const file of preview_paths)fs.writeFileSync(file,'int preview = 1;\n');
await evaluate(`window.preview_paths=${JSON.stringify(preview_paths)};files.open_file(preview_paths[0],{preview:true})`);await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.preview_a=ws.activeLeaf;void 0');
await open_title('preview_a');await click('[data-action=enable_preview_editors]');await wait('!editor_qa.read_workspace_editor_settings().enable_preview');
await check('!preview_a.state.workspace_preview&&runtime.app.settings.get("workspace_editor").enable_preview===false','disabling preview persists through real settings and keeps existing preview tabs open');
await check('JSON.parse(reqnode("fs").readFileSync(reqnode("path").join(runtime.app.settings._settingsDir,runtime.app.settings.filename+".json"),"utf8")).settings.workspace_editor.enable_preview===false','preview preference is written to the real user configuration file');
await evaluate('files.open_file(preview_paths[1],{preview:true})');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.preview_b=ws.activeLeaf;void 0');
await check('!preview_b.state.workspace_preview&&leaves().includes(preview_a)','all file preview requests respect the disabled setting');
await open_title('preview_b');await click('[data-action=configure_editors]');await wait('!!document.querySelector(".workspace-settings-modal")');
await evaluate(`document.querySelector('.workspace-settings>input').value='enable_preview';document.querySelector('.workspace-settings>input').dispatchEvent(new Event('input'));void 0`);await click('[data-setting="editor.enable_preview"]');await wait('editor_qa.read_workspace_editor_settings().enable_preview');await key('Escape');await wait('!document.querySelector(".workspace-settings-modal")');
await evaluate('files.open_file(preview_paths[2],{preview:true})');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.preview_c=ws.activeLeaf;void 0');
await evaluate('files.open_file(preview_paths[3],{preview:true})');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.preview_d=ws.activeLeaf;void 0');
await check('preview_d.state.workspace_preview&&!leaves().includes(preview_c)&&leaves().includes(preview_a)&&leaves().includes(preview_b)','re-enabling preview replaces only later preview tabs');
await evaluate('window.real_set_and_save=runtime.app.settings.set_and_save;runtime.app.settings.set_and_save=()=>{throw Error("fixture save failed")};void 0');
await open_title('preview_d');await click('[data-action=enable_preview_editors]');await wait('notices.some(text=>text.includes("fixture save failed"))');
await check('editor_qa.read_workspace_editor_settings().enable_preview&&preview_d.state.workspace_preview','failed preference persistence keeps the old effective setting and tab state');
await evaluate('runtime.app.settings.set_and_save=real_set_and_save;notices.length=0;void 0');
for(const name of ['preview_a','preview_b','preview_d'])await evaluate('files.close_leaf('+name+')');
await evaluate('select(first);actions.split(first,"right")');await wait('ws.activeLeaf!==first&&ws.activeLeaf.view.loaded');await evaluate('window.lock_other=ws.activeLeaf;window.other_group=lock_other.parent;void 0');
await open_title('first');await click('[data-action=lock_group]');await wait('editor_qa.workspace_editor_group_locked(group)');
const lock_paths=['locked_route_a.c','locked_route_b.c'].map(name=>path.join(folder,name));for(const file of lock_paths)fs.writeFileSync(file,'int locked_route = 1;\n');
await evaluate(`window.lock_paths=${JSON.stringify(lock_paths)};select(third);files.open_file(lock_paths[0])`);await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.lock_a=ws.activeLeaf;void 0');
await check('lock_a.parent===other_group&&first.parent===group&&third.parent===group','new files skip a locked group and use an existing unlocked group');
await evaluate('select(third);files.open_file(third_path)');await check('ws.activeLeaf===third&&third.parent===group','existing documents in a locked group retain leaf identity');
const native_markdown=path.join(folder,'native locked route.md');fs.writeFileSync(native_markdown,'# Native locked route\n');
await evaluate(`window.native_markdown=${JSON.stringify(native_markdown)};window.native_callback=function(...args){window.callback_observed={receiver:this,args}};select(third);window.native_return=File.editor.library.openFile(native_markdown,native_callback,true,'extra');void 0`);
await check("native_return===native_result&&native_calls.at(-1).group===other_group&&native_calls.at(-1).target===native_markdown&&native_calls.at(-1).receiver===File.editor.library&&native_calls.at(-1).args[0]===native_callback&&native_calls.at(-1).args[1]===true&&native_calls.at(-1).args[2]==='extra'&&callback_observed.receiver===native_callback_receiver&&callback_observed.args.join(',')==='loaded,71'",'native Markdown lock routing preserves synchronous return, receiver, all arguments and callback semantics');

await open_title('lock_other');await click('[data-action=lock_group]');await wait('editor_qa.workspace_editor_group_locked(other_group)');
await evaluate('select(third);window.native_all_locked_return=File.editor.library.openFile(native_markdown,native_callback);window.native_placeholder=ws.activeLeaf;void 0');
await check('native_all_locked_return===native_result&&native_placeholder.parent!==group&&native_placeholder.parent!==other_group&&native_placeholder.state.path.startsWith("typ://core.empty/")&&!editor_qa.workspace_editor_group_locked(native_placeholder.parent)','native Markdown opening creates an unlocked group when every existing group is locked');
await evaluate('select(third);void 0');await wait('!leaves().includes(native_placeholder)');
await check('ws.activeLeaf===third&&leaves().includes(first)&&leaves().includes(lock_a)','leaving an incomplete native open removes only its empty placeholder and preserves existing document identity');

await evaluate('select(third);files.open_file(lock_paths[1])');await wait('ws.activeLeaf.view.loaded&&!ws.activeLeaf.view.loading');await evaluate('window.lock_b=ws.activeLeaf;void 0');
await check('lock_b.parent!==group&&lock_b.parent!==other_group&&!editor_qa.workspace_editor_group_locked(lock_b.parent)','all locked groups cause a new unlocked group to receive the file');
await open_title('first');await click('[data-action=lock_group]');await open_title('lock_other');await click('[data-action=lock_group]');
await open_title('lock_b');await click('[data-action=close_saved]');await wait('!leaves().includes(lock_b)');await check('leaves().includes(lock_a)&&leaves().includes(first)','title Close Saved uses the existing close batch and stays within its group');
await open_title('lock_other');await click('[data-action=close_all]');await wait('!leaves().includes(lock_a)&&!leaves().includes(lock_other)');await check('leaves().includes(first)&&leaves().includes(second)&&leaves().includes(third)','title Close All closes its group without touching other group documents');
await evaluate('select(third);void 0');
await evaluate('group.tabHeader.getTabById(first.state.path).dataset.testTab="first";void 0');
await click('[data-test-tab="first"]','right');await wait('!!document.querySelector(".workspace-editor-menu")');
await check('ws.activeLeaf===third','right-clicking a background tab preserves the active document');
await check('!document.querySelector("[data-action=close_right]").disabled&&document.querySelector("[data-action=keep_open]").disabled','menu availability follows the context tab, not the active last tab');
await click('[data-action=copy_path]');await wait('copied.length===1');await check('copied[0]===first_path&&ws.activeLeaf===third','path copy targets the background document without activation');
await evaluate('actions.pin(second,true);void 0');await check('group.children[0]===second&&second.state.workspace_pinned&&ws.activeLeaf===third','pin moves the target to the fixed prefix while preserving active identity');
await check('!!group.tabHeader.getTabById(second.state.path).querySelector("[data-git-icon=pinned]")','fixed tab uses the official pin in the existing close slot');
await evaluate('first.state.workspace_preview=true;files.keep_open(first);void 0');await check('!first.state.workspace_preview&&!first.state.workspace_pinned','Keep Open and Pin are independent states');
await evaluate('edit(first,"int draft = 2; // 当前草稿\\n");window.original_model=first.view.editor.models[0];window.original_view=first.view;void 0');
await evaluate('actions.split(first,"right")');await wait('ws.activeLeaf!==first&&!!ws.activeLeaf.view.editor');
await evaluate('window.duplicate=ws.activeLeaf;void 0');
await check('first.view.editor.models[0]===duplicate.view.editor.models[0]&&duplicate.view.dirty()','splitting source shares the current dirty model');
assert.equal(fs.readFileSync(first,'utf8'),'int original = 1;\n');
await evaluate('edit(duplicate,"int changed_from_split = 3;\\n");void 0');
await check('first.view.editor.models[0].getValue()===duplicate.view.editor.models[0].getValue()','edits from a split update both views');
await evaluate('files.save_leaf(duplicate)');await check('!first.view.dirty()&&!duplicate.view.dirty()','saving a split updates the shared baseline and modified markers');
assert.equal(fs.readFileSync(first,'utf8'),'int changed_from_split = 3;\n');
await evaluate('edit(first,"unsaved after save\\n");void 0');
assert.equal(await evaluate('files.close_leaf(duplicate)'),true);await delay(100);
await check('!original_model.isDisposed()&&first.view.dirty()&&!document.querySelector("[data-workspace-tab-close]")','closing one split preserves the shared dirty model without a redundant prompt');
await evaluate('select(first);window.batch_done=false;void actions.close_batch(first,"all").then(()=>batch_done=true)');await wait('!!document.querySelector("[data-workspace-tab-close]")');
await check('leaves().includes(third)&&leaves().includes(second)','batch close waits for the current unsaved document and preserves fixed tabs');
await evaluate('close_dialog("取消")');await wait('batch_done');await check('leaves().includes(first)&&leaves().includes(third)&&first.view.dirty()','Cancel stops the remaining close batch');
await evaluate('window.saved_method=first.view.save;first.view.save=async()=>false;void actions.close_batch(first,"all")');await wait('!!document.querySelector("[data-workspace-tab-close]")');await evaluate('close_dialog("保存并关闭")');await delay(80);
await check('leaves().includes(first)&&leaves().includes(third)&&!!document.querySelector("[data-workspace-tab-close]")','failed save keeps the target and later tabs');await evaluate('close_dialog("取消");first.view.save=saved_method;void 0');await delay(50);
await evaluate('actions.close_batch(first,"saved")');await check('leaves().includes(first)&&leaves().includes(second)&&!leaves().includes(third)','Close Saved skips dirty and fixed tabs');
await evaluate('actions.split(first,"down")');await wait('ws.activeLeaf!==first&&!!ws.activeLeaf.view.editor');await evaluate('window.bottom=ws.activeLeaf;void 0');
await check('bottom.parent!==first.parent&&bottom.view.editor.models[0]===original_model','split down creates a group while retaining shared model identity');
await evaluate('actions.move(second,"down");void 0');await delay(80);
await check('second.parent===bottom.parent&&second.parent.children[0]===second&&second.state.workspace_pinned','moving to an adjacent group preserves fixed ordering');
await evaluate('entry(first,"copy_window").action();void 0');await wait('window_requests.length===1');await check('window_requests[0].leaf===first&&window_requests[0].copy&&leaves().includes(first)','Copy into New Window binds the original target and requests copy semantics');
await evaluate('select(bottom);void 0');await key('k',['control']);await key('Enter',['shift']);await wait('bottom.state.workspace_pinned===true');checks.push('Ctrl+K Shift+Enter uses the same pin action');
await key('k',['control']);await key('Enter',['shift']);await wait('bottom.state.workspace_pinned===false');
// 各主题／缩放／小窗口里用真实右键打开，菜单在视口内滚动，Esc 恢复焦点。
for(const [width,height,zoom,dark] of [[1100,780,1,false],[420,430,1.25,false],[1100,780,1,true],[420,430,1.25,true]]){
 win.setSize(width,height);win.webContents.setZoomFactor(zoom);
 await evaluate(`document.documentElement.style.setProperty('--bg-color',${JSON.stringify(dark?'#191a1b':'#fff')});document.documentElement.style.setProperty('--text-color',${JSON.stringify(dark?'#ddd':'#24292f')});document.body.style.background=${JSON.stringify(dark?'#191a1b':'#fff')};document.body.style.color=${JSON.stringify(dark?'#ddd':'#24292f')};group.tabHeader.getTabById(first.state.path).dataset.testTab='first';void 0`);await delay(120);
 await click('[data-test-tab="first"]','right');await wait('!!document.querySelector(".workspace-editor-menu")');
 await check(`(()=>{const menu=document.querySelector('.workspace-editor-menu'),r=menu.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1&&getComputedStyle(menu).borderRadius!=='0px'})()`,`menu fits ${width}x${height}, zoom ${zoom}, ${dark?'dark':'light'} with shared rounded geometry`);
 await key('Escape');await wait('!document.querySelector(".workspace-editor-menu")');
 await open_title('first');await check(`(()=>{const r=document.querySelector('.workspace-editor-title-test').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1})()`,`title menu fits ${width}x${height}, zoom ${zoom}, ${dark?'dark':'light'}`);
 fs.writeFileSync(path.join(root,`title_menu_${width}_${zoom}_${dark?'dark':'light'}.png`),(await win.webContents.capturePage()).toPNG());
 await click('[data-action=configure_editors]');await wait('!!document.querySelector(".workspace-settings-modal")');
 await check(`(()=>{const r=document.querySelector('.workspace-settings-modal .git-graph-dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1})()`,`editor settings fits ${width}x${height}, zoom ${zoom}, ${dark?'dark':'light'}`);
 fs.writeFileSync(path.join(root,`editor_settings_${width}_${zoom}_${dark?'dark':'light'}.png`),(await win.webContents.capturePage()).toPNG());await key('Escape');await wait('!document.querySelector(".workspace-settings-modal")');
}
win.webContents.setZoomFactor(1);win.setSize(1100,780);
await evaluate('window.cancelled=false;void files.close_leaf(first).then(()=>cancelled=true)');await delay(100); // 另一个分屏仍持有草稿，直接关闭。
await check('!leaves().includes(first)&&bottom.view.dirty()&&!original_model.isDisposed()','closing the original leaves the split draft alive');
await evaluate('window.final_close=false;void files.close_leaf(bottom).then(value=>final_close=value)');await wait('!!document.querySelector("[data-workspace-tab-close]")');await evaluate('close_dialog("保存并关闭")');await wait('final_close');
await check('original_model.isDisposed()','the final document close releases the shared model exactly once');
assert.equal(fs.readFileSync(first,'utf8'),'unsaved after save\n');
await check('leaves().includes(second)','explicit final close does not remove another fixed document');
// 同一文档的另存为必须更新每个分屏身份，并保留共享撤销栈。
await evaluate('select(second);actions.split(second,"right")');await wait('ws.activeLeaf!==second&&!!ws.activeLeaf.view.editor');
await evaluate('window.save_as_split=ws.activeLeaf;window.second_model=second.view.editor.models[0];window.saved_as_path=second_path.replace("second.c","renamed.c");JSBridge.invoke=async command=>command==="dialog.showSaveDialog"?{filePath:saved_as_path}:null;edit(save_as_split,"shared save as text");void 0');
await evaluate('files.save_as_active()');
await check('second.view.file_path===saved_as_path&&save_as_split.view.file_path===saved_as_path&&second.view.editor.models[0]===second_model&&!second.view.dirty()&&!save_as_split.view.dirty()','Save As updates both split identities and shared saved state');
await check('second.parent.tabHeader.getTabById(second.state.path).querySelector(".typ-file-basename").textContent==="renamed.c"','Save As refreshes inactive split labels');
assert.equal(fs.readFileSync(second,'utf8'),'int original = 1;\n');
assert.equal(fs.readFileSync(path.join(folder,'renamed.c'),'utf8'),'shared save as text');
await open_title('second');await click('[data-action=lock_group]');await wait('editor_qa.workspace_editor_group_locked(second.parent)');
await evaluate('window.stale_title=editor_qa.request_workspace_editor_title_entries(second).find(entry=>entry.id==="configure_editors");void 0');
await evaluate('actions.dispose();settings_view.dispose();sections.dispose();quick.dispose();tab_controls.dispose();shortcut_binding.dispose();stale_title.action();title_button.remove();void 0');
await check('!editor_qa.workspace_editor_group_locked(second.parent)&&!document.querySelector(".workspace-settings-modal")','dispose releases owned group locks and retained callbacks cannot reopen settings');
await check('!document.querySelector(".workspace-tab-pin")','unbinding removes menu listeners and owned pin decoration');
await check('editor_qa.request_workspace_editor_title_entries(second).length===0','unbinding removes the title contribution listener');
const errors=await evaluate('fixture_errors');assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({status:'PASS',checks},null,2));console.log(JSON.stringify({status:'PASS',checks,evidence:root}));win.destroy();app.exit(0);
}).catch(async error=>{console.error(error.stack||error);console.error(root);if(test_window&&!test_window.isDestroyed()){console.error(await test_window.webContents.executeJavaScript(`JSON.stringify({errors:fixture_errors,notices:window.notices,menus:document.querySelectorAll('.git-graph-menu').length,tab:[...document.querySelectorAll('.typ-tab')].map(node=>{const r=node.getBoundingClientRect();return{path:node.dataset.id,r:r.toJSON(),top:document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)?.outerHTML.slice(0,300)}})})`));fs.writeFileSync(path.join(root,'failure.png'),(await test_window.webContents.capturePage()).toPNG());}app.exit(1)});
