// 独立 Chromium 指针/键盘验证活动栏，不启动 Typora、不访问用户仓库。
const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {build}=require('esbuild');
const evidence=fs.mkdtempSync(path.join(os.tmpdir(),'typora_workspace_activity_'));
app.setPath('userData',path.join(evidence,'user_data')); app.disableHardwareAcceleration();
let test_window;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const wait=async source=>{for(let index=0;index<100;index++){if(await evaluate(source))return;await delay(30);}throw new Error('Timed out: '+source);};
const capture=async name=>fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());
const point=selector=>evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)};})()`);
const click=async(selector,button='left')=>{const position=await point(selector);for(const type of ['mouseMove','mouseDown','mouseUp']){test_window.webContents.sendInputEvent({type,...position,button,clickCount:1});await delay(35);}await delay(160);};
const key=async(key_code,modifiers=[])=>{test_window.webContents.sendInputEvent({type:'keyDown',keyCode:key_code,modifiers});if(key_code==='Enter'&&!modifiers.length)test_window.webContents.sendInputEvent({type:'char',keyCode:'\r'});test_window.webContents.sendInputEvent({type:'keyUp',keyCode:key_code,modifiers});await delay(100);};
const item=id=>'[data-id="'+id+'"]';
app.whenReady().then(async()=>{
  test_window=new BrowserWindow({show:false,width:720,height:600,webPreferences:{contextIsolation:false,offscreen:true,backgroundThrottling:false}});
  const html=path.join(evidence,'test.html');fs.writeFileSync(html,'<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;font:14px system-ui}body{display:flex;--typ-ribbon-width:48px;--control-text-color:#616161;--bg-color:white}.typ-ribbon{width:48px;display:flex;flex-direction:column;flex:none;background:#f7f7f7;border-right:1px solid #ddd}.group.top{flex:1}.typ-ribbon-item{height:48px;display:flex;align-items:center;justify-content:center;box-sizing:border-box;cursor:pointer}.typ-ribbon-item.active{border-left:2px solid blue}.typ-ribbon-item .fa::before{font-size:1.5rem}.typ-ribbon-item .fa.typ-lighter-icon{-webkit-text-stroke:1px var(--bg-color)}.fa{display:inline-block;font-style:normal;line-height:1}.fa-list::before{content:"\\f03a"}.git-standard-icon{width:16px;height:16px}svg,svg path{stroke:#333;fill:none}.fixed-spacer{height:8px;border-top:1px solid #ddd;box-sizing:border-box}#typora-sidebar{padding:18px;flex:1}h2{margin-top:0}</style><div class="typ-ribbon"><div class="group top"></div><div class="group bottom"></div></div><aside id="typora-sidebar"><h2>源代码管理</h2><p>活动栏功能项：选中高亮、拖动排序、键盘菜单。</p></aside>');await test_window.loadFile(html);
  test_window.webContents.debugger.attach('1.3');await test_window.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  const bundle=await build({stdin:{contents:'export {install_workspace_activity} from "./src/workspace_activity";export {git_icon} from "./src/git_icons";',resolveDir:path.join(__dirname,'..')},bundle:true,loader:{'.css':'text'},format:'iife',globalName:'activity_qa',write:false});await evaluate(bundle.outputFiles[0].text);
  await evaluate(`(()=>{
    window.ids=['core.file-explorer','core.search','core.outline','linux_note:source_control'];window.labels=['文件','搜索','大纲','源代码管理'];window.state={active_id:ids[3],sidebar_visible:true};window.clicks=0;window.legacy_down=0;window.legacy_menu=0;window.fixed_clicks=0;window.ribbon=document.querySelector('.typ-ribbon');const top=ribbon.querySelector('.top'),bottom=ribbon.querySelector('.bottom');
    ids.forEach((id,index)=>{const node=document.createElement('div');node.className='typ-ribbon-item';node.dataset.id=id;node.title=labels[index];node.draggable=true;if(id==='core.outline'){window.native_outline_icon=document.createElement('i');native_outline_icon.className='fa fa-list typ-lighter-icon';node.append(native_outline_icon);}else node.append(activity_qa.git_icon(['diff-multiple','target','history','source-control'][index]));node.onclick=()=>{clicks++;state.sidebar_visible=state.active_id===id?!state.sidebar_visible:true;state.active_id=id;ribbon.querySelectorAll('.active').forEach(item=>item.classList.remove('active'));node.classList.add('active');document.querySelector('h2').textContent=node.title;};top.append(node);});
    const spacer=document.createElement('div');spacer.className='fixed-spacer';spacer.dataset.fixed='top';top.children[2].before(spacer);
    for(const [id,title]of[['core.settings','设置'],['linux_note:terminal','终端']]){const node=document.createElement('div');node.className='typ-ribbon-item';node.dataset.id=id;node.title=title;node.draggable=true;node.append(activity_qa.git_icon(id==='core.settings'?'more':'git-commit'));node.onclick=()=>fixed_clicks++;bottom.append(node);}
    top.addEventListener('mousedown',()=>legacy_down++);top.addEventListener('contextmenu',event=>{legacy_menu++;event.preventDefault();});top.children[0].classList.add('active');window.original_children=[...top.children];
    window.outline_metrics=()=>{const box=native_outline_icon.getBoundingClientRect(),outer=native_outline_icon.parentElement.getBoundingClientRect();return {width:box.width,height:box.height,font_size:getComputedStyle(native_outline_icon,'::before').fontSize,center_x:box.left+box.width/2-outer.left-outer.width/2,center_y:box.top+box.height/2-outer.top-outer.height/2}};
    window.original_outline_metrics=outline_metrics();
    window.activity=activity_qa.install_workspace_activity({ribbon,item_ids:ids,read_state:()=>state});
    window.order=()=>[...top.querySelectorAll('.workspace-activity-item')].map(node=>node.dataset.id);window.selected=()=>[...ribbon.querySelectorAll('[data-activity-active=true]')].map(node=>node.dataset.id);
  })()`);
  assert.deepEqual(await evaluate('ids.filter(id=>id!=="core.outline").map(id=>{const svg=ribbon.querySelector(`[data-id="${id}"] svg`),box=svg.getBoundingClientRect();return[svg.dataset.gitIcon,box.width,box.height]})'),[['files',24,24],['search',24,24],['source-control',24,24]]);
  assert.equal(await evaluate('native_outline_icon.parentElement.dataset.id==="core.outline" && native_outline_icon.parentElement.firstElementChild===native_outline_icon'),true,'original core Outline icon node is not replaced');
  assert.deepEqual(await evaluate('outline_metrics()'),await evaluate('original_outline_metrics'),'native Outline size and centering are preserved');
  assert.equal(await evaluate('native_outline_icon.className'),'fa fa-list typ-lighter-icon');
  // Fixed 88e44fa theme.ts: Modern active foreground inherits list.inactiveSelectionForeground; Dark 2026 is #ededed.
  assert.equal(await evaluate('ids.filter(id=>id!=="core.outline").every(id=>{const item=ribbon.querySelector(`[data-id="${id}"]`),svg=item.querySelector("svg"),box=svg.getBoundingClientRect(),outer=item.getBoundingClientRect(),style=getComputedStyle(svg);return Math.abs(box.left+box.width/2-outer.left-outer.width/2)<.1&&Math.abs(box.top+box.height/2-outer.top-outer.height/2)<.1&&style.stroke==="none"&&style.fill===style.color&&[...svg.querySelectorAll("path")].every(path=>getComputedStyle(path).stroke==="none")})'),true,'activity owns 24px centered official glyphs despite native 16px sizing and SVG stroke pollution');
  for (const [theme,background,selected,border,active_icon,inactive_icon] of [['light','rgb(250, 250, 253)','rgba(218, 218, 218, 0.6)','rgb(0, 0, 0)','rgb(32, 32, 32)','rgb(96, 96, 96)'],['dark','rgb(25, 26, 27)','rgb(44, 45, 46)','rgb(191, 191, 191)','rgb(237, 237, 237)','rgb(140, 140, 140)']]) {
    await evaluate(`document.body.style.setProperty('--bg-color','${theme==='light'?'#fff':'#1e1e1e'}')`);
    await evaluate(`ribbon.style.background='${background}';ribbon.style.setProperty('--workspace-activity-active-background','${selected}');ribbon.style.setProperty('--workspace-activity-active-foreground','${active_icon}');ribbon.style.setProperty('--workspace-activity-active-border','${border}');ribbon.style.setProperty('--workspace-activity-foreground','${inactive_icon}')`); await delay(180);
    assert.deepEqual(await evaluate('(()=>{const selected=ribbon.querySelector("[data-activity-active=true]"),inactive=ribbon.querySelector("[data-activity-active=false]"),style=getComputedStyle(selected);return{background:getComputedStyle(ribbon).backgroundColor,selected:style.backgroundColor,border:style.borderLeftColor,border_width:style.borderLeftWidth,active_icon:getComputedStyle(selected.querySelector("svg")).color,inactive_icon:getComputedStyle(inactive.querySelector("svg")).color}})()'),{background,selected,border,border_width:'3px',active_icon,inactive_icon});
    await capture('official_activity_'+theme);
  }
  assert.deepEqual(await evaluate('selected()'),['linux_note:source_control']);assert(!await evaluate('document.querySelector("[data-id=\\"core.file-explorer\\"]").classList.contains("active")'));
  const selected_metrics=await evaluate(`(()=>{const node=ribbon.querySelector('[data-activity-active=true]'),style=getComputedStyle(node);return {border:style.borderLeftColor,border_width:style.borderLeftWidth,background:style.backgroundColor,color:style.color,label:node.getAttribute('aria-label'),title:node.title};})()`);
  assert.equal(selected_metrics.color,'rgb(237, 237, 237)');assert.equal(selected_metrics.border_width,'3px');assert.equal(selected_metrics.background,'rgb(44, 45, 46)');assert.equal(selected_metrics.label,'源代码管理');assert.equal(selected_metrics.label,selected_metrics.title);await capture('selected');
  assert.deepEqual(await evaluate(`(()=>{const node=ribbon.querySelector('[data-activity-active=true]'),r=node.getBoundingClientRect(),indicator=getComputedStyle(node,'::after');return {width:r.width,height:r.height,indicator_width:indicator.width,indicator_height:indicator.height,radius:indicator.borderRadius}})()`),{width:48,height:48,indicator_width:'auto',indicator_height:'auto',radius:'0px'});
  await click(item('core.file-explorer'));assert.deepEqual(await evaluate('selected()'),['core.file-explorer']);await click(item('core.file-explorer'));assert.deepEqual(await evaluate('selected()'),[]);
  await click(item('core.search'));assert.deepEqual(await evaluate('selected()'),['core.search']);await key('Down');await key('Enter');assert.deepEqual(await evaluate('selected()'),['core.outline']);
  const outline_clicks=await evaluate('clicks');await click(item('core.outline'));assert.deepEqual(await evaluate('selected()'),[]);await click(item('core.outline'));assert.deepEqual(await evaluate('selected()'),['core.outline']);assert.equal(await evaluate('clicks'),outline_clicks+2);assert.equal(await evaluate('native_outline_icon.parentElement.firstElementChild===native_outline_icon'),true,'native Outline click handler and icon survive selection toggles');
  await evaluate('state.active_id="linux_note:source_control";state.sidebar_visible=true;activity.refresh();document.querySelector("[data-id=\\"core.search\\"]").classList.add("active")');await delay(100);assert.deepEqual(await evaluate('selected()'),['linux_note:source_control']);assert.equal(await evaluate('ribbon.querySelectorAll(".top .active").length'),1);
  const before_drag=await evaluate('clicks');const start=await point(item('linux_note:source_control'));const destination=await point(item('core.file-explorer'));
  test_window.webContents.sendInputEvent({type:'mouseDown',...start,button:'left',clickCount:1});await delay(30);test_window.webContents.sendInputEvent({type:'mouseMove',x:start.x,y:destination.y-15,button:'left'});await delay(35);
  assert(await evaluate('ribbon.dataset.activityDragging === "true"'));const moving_animations=await evaluate('[...ribbon.querySelectorAll(".workspace-activity-item")].reduce((count,node)=>count+node.getAnimations().length,0)');assert(moving_animations>0);
  test_window.webContents.sendInputEvent({type:'mouseUp',x:start.x,y:destination.y-15,button:'left',clickCount:1});await delay(220);
  const reordered=['linux_note:source_control','core.file-explorer','core.search','core.outline'];assert.deepEqual(await evaluate('order()'),reordered);assert.equal(await evaluate('clicks'),before_drag);assert.equal(await evaluate('legacy_down'),0);assert.equal(await evaluate('[...ribbon.querySelector(".top").children].indexOf(document.querySelector("[data-fixed=top]"))'),2);assert.deepEqual(await evaluate('[...ribbon.querySelector(".bottom").children].map(node=>node.dataset.id)'),['core.settings','linux_note:terminal']);
  assert.deepEqual(await evaluate('JSON.parse(localStorage.getItem("linux-note:workspace:activity-order:v1"))'),reordered);await capture('reordered');
  await click(item('linux_note:source_control'),'right');assert(await evaluate('document.querySelector("[data-activity-move=up]").disabled'));assert.equal(await evaluate('legacy_menu'),0);await capture('reorder_menu');await key('Enter');await delay(220);assert.deepEqual(await evaluate('order()'),['core.file-explorer','linux_note:source_control','core.search','core.outline']);
  await evaluate('activity.dispose();ribbon.querySelector(".top").replaceChildren(...original_children);void(activity=activity_qa.install_workspace_activity({ribbon,item_ids:ids,read_state:()=>state}))');assert.deepEqual(await evaluate('order()'),['core.file-explorer','linux_note:source_control','core.search','core.outline']);
  await evaluate('document.querySelector("[data-id=\\"core.search\\"]").focus()');await key('F10',['shift']);assert(await evaluate('!!document.querySelector(".workspace-activity-menu")'));await key('Escape');await key('Up',['alt']);await delay(220);assert.deepEqual(await evaluate('order()'),['core.file-explorer','core.search','linux_note:source_control','core.outline']);
  const saved_before_cancel=await evaluate('order()');const cancel_start=await point(item('core.outline'));const cancel_end=await point(item('core.file-explorer'));test_window.webContents.sendInputEvent({type:'mouseDown',...cancel_start,button:'left',clickCount:1});test_window.webContents.sendInputEvent({type:'mouseMove',x:cancel_start.x,y:cancel_end.y-15,button:'left'});await delay(35);await key('Escape');test_window.webContents.sendInputEvent({type:'mouseUp',x:cancel_start.x,y:cancel_end.y-15,button:'left',clickCount:1});await delay(220);assert.deepEqual(await evaluate('order()'),saved_before_cancel);assert.deepEqual(await evaluate('JSON.parse(localStorage.getItem("linux-note:workspace:activity-order:v1"))'),saved_before_cancel);
  await test_window.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await wait('matchMedia("(prefers-reduced-motion: reduce)").matches');await evaluate('activity.move("core.search",-1)');
  const reduced_metrics=await evaluate('({animations:[...ribbon.querySelectorAll(".workspace-activity-item")].reduce((count,node)=>count+node.getAnimations().length,0),transition:getComputedStyle(ribbon.querySelector(".workspace-activity-item")).transitionDuration})');assert.equal(reduced_metrics.animations,0);assert.equal(reduced_metrics.transition,'0s');
  await click(item('core.settings'));assert.equal(await evaluate('fixed_clicks'),1);assert(!await evaluate('document.querySelector("[data-id=\\"core.settings\\"]").hasAttribute("data-activity-active")'));
  await evaluate('state.sidebar_visible=false;activity.refresh()');assert.deepEqual(await evaluate('selected()'),[]);await evaluate('activity.dispose()');assert(!await evaluate('ribbon.hasAttribute("data-workspace-activity") || document.querySelector("[data-workspace-activity-style]")'));
  assert.deepEqual(await evaluate('ids.filter(id=>id!=="core.outline").map(id=>ribbon.querySelector(`[data-id="${id}"] svg`).dataset.gitIcon)'),['diff-multiple','target','source-control'],'dispose restores the exact native icon nodes');
  assert.equal(await evaluate('native_outline_icon.isConnected && native_outline_icon.className==="fa fa-list typ-lighter-icon"'),true,'dispose retains the exact original Outline node');
  console.log(JSON.stringify({status:'PASS',checks:['active ID overrides stale native selection','active border background foreground and Chinese title','same activity click hides sidebar without stale highlight','file search outline and Git switch without double selection','keyboard navigation opens the intended activity','real pointer drag persists top-item order','drag does not click or invoke legacy sorting','fixed top slot and bottom actions retain positions','reorder animates with real Web Animations','Chinese context menu moves item with keyboard','saved order restores after reinstall','Shift F10 and Alt Arrow provide keyboard sorting','Escape cancels drag without changing saved order','reduced motion removes transition and reorder animation','bottom settings keeps its original click','hidden sidebar clears selection and dispose removes enhancement'],selected_metrics,moving_animations,reduced_metrics,evidence}));
  test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(test_window&&!test_window.isDestroyed()){await capture('failure');console.error(await evaluate('({active:document.activeElement?.outerHTML.slice(0,300),order:window.order?.(),text:document.body.innerText})'));test_window.destroy();}app.exit(1);});
