// 隐藏Electron；服务替身只替换网络和安装，不写真实用户目录。
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'typora-update-ui-'));app.setPath('userData',path.join(root,'profile'));app.disableHardwareAcceleration();
let win;const checks=[];
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:900,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});await win.loadURL('about:blank');
 const evaluate=code=>win.webContents.executeJavaScript(code),delay=ms=>new Promise(r=>setTimeout(r,ms)),check=async(code,label)=>{assert(await evaluate(code),label);checks.push(label);};
 await win.webContents.insertCSS(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'));
 const bundle=await require('esbuild').build({stdin:{contents:'export {bind_workspace_update} from "./src/workspace_update";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,loader:{'.css':'text'},globalName:'update_qa'});await evaluate(bundle.outputFiles[0].text);
 const current=JSON.parse(fs.readFileSync(path.join(__dirname,'../release.json'),'utf8'));
 await evaluate(`window.commands=new Map();window.calls=[];window.service={update_paths:user_data=>({state_root:require("path").join(user_data,"temp","typora_code_updates")}),installed_identity:()=>window.identity||null,release_info:value=>value,session_identity:async()=>'12-34',claim_startup:()=>{calls.push('claim');return true;},check_update:async()=>{calls.push('check');return {commit:'a'.repeat(40),commit_message:'固定提交ZIP更新',release:{releases:[{sequence:${current.releases[0].sequence+1},version:'next',date:'2026-09-20',notes:['<img src=x onerror=alert(1)>','修复目录刷新']}]}};},start_update:()=>{calls.push('install');return 'job';},status_of:()=>({phase:window.phase||'downloading',message:'进度'}),cancel_update:()=>calls.push('cancel')};window.reqnode=name=>name.endsWith('workspace_update_service.cjs')?service:name==='process'?{platform:'win32',ppid:12,execPath:'X:/Typora/Typora.exe'}:name==='fs'?{readFileSync:file=>{if(file.endsWith('active_job.json'))throw Error('ENOENT');return JSON.stringify(file.endsWith('runtime.json')?{node_version:'24.20.0'}:${JSON.stringify(current)});},mkdirSync(){},appendFileSync(){}}:require(name);window._options={userDataPath:${JSON.stringify(root)}};window[Symbol.for('typora-code:workspace')]={app:{commands:{register(command){commands.set(command.id,command.callback);return ()=>commands.delete(command.id);}}}};window.binding=update_qa.bind_workspace_update();void 0;`);
 await delay(2150);await check("calls.filter(x=>x==='check').length===1&&document.querySelectorAll('[role=dialog]').length===1",'启动异步检查一次并打开公告');
 await check("document.querySelector('[role=dialog]').textContent.includes('<img src=x onerror=alert(1)>')&&!document.querySelector('[role=dialog] img')",'公告作为纯文本，不执行HTML');
 await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent==='稍后').click()");await check("!document.querySelector('[role=dialog]')&&!calls.includes('install')",'稍后关闭不下载或安装');
 await evaluate("commands.get('typora_code:check_update')();commands.get('typora_code:check_update')();");await delay(30);await check("document.querySelectorAll('[role=dialog]').length===1&&calls.filter(x=>x==='check').length===2",'重复手动检查只开一个弹窗');
 await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent==='立即更新').click()");await delay(30);await check("calls.filter(x=>x==='install').length===1&&document.querySelector('[role=dialog]').textContent.includes('取消下载')",'选择更新一次启动任务并显示进度');
 await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent==='取消下载').click();window.phase='installing'");await delay(400);await check("calls.includes('cancel')&&[...document.querySelectorAll('button')].find(b=>b.textContent==='取消下载').disabled",'只在下载校验阶段可取消，安装阶段禁用取消');
 await evaluate("window.phase='succeeded'");await delay(400);await check("![...document.querySelectorAll('button')].some(b=>b.textContent==='取消下载')",'成功停止轮询与取消入口');
 await evaluate("document.querySelector('[role=dialog] button').click();window.identity={commit:'b'.repeat(40),basis:'installed-archive'};commands.get('typora_code:check_update')()");await delay(30);await check("document.querySelector('[role=dialog]').textContent.includes('手动重启')",'同版本提交变化提示手动重启');await evaluate('window.identity=null');
 await evaluate('binding.dispose()');await check("!document.querySelector('[role=dialog]')&&commands.size===0",'销毁清理弹窗、命令及定时器');
 await evaluate("service.check_update=async()=>{throw Error('offline')};window.binding=update_qa.bind_workspace_update();commands.get('typora_code:check_update')()");await delay(30);await check("document.querySelector('[role=dialog]').textContent.includes('offline')",'手动失败展示错误');await evaluate("document.querySelector('[role=dialog] button').click();commands.get('typora_code:check_update')()");await delay(30);await check("document.querySelector('[role=dialog]').textContent.includes('offline')",'关闭失败弹窗后可以再次检查');await evaluate('binding.dispose()');
 fs.writeFileSync(path.join(root,'checks.json'),JSON.stringify({checks}));console.log(JSON.stringify({status:'PASS',checks,evidence:root},null,2));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);console.error(root);win?.destroy();app.exit(1)});
