// 真实 Electron 运行插件入口与全部编排模块；宿主核心仅提供可核查的注册表和原生文件容器。
const { app, BrowserWindow } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { build } = require('esbuild');
const { editor_plugins } = require('./editor_bundle.cjs');
const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_plugin_lifecycle_'));
const repository=path.join(evidence,'repository');fs.mkdirSync(repository);
const source_path = path.join(repository, 'source.ts');fs.writeFileSync(source_path, 'const original = 1;\n');
const git=(...args)=>require('node:child_process').execFileSync('git',args,{cwd:repository,windowsHide:true,stdio:'pipe'});fs.writeFileSync(path.join(repository,'second.ts'),'const second = 2;\n');git('init','-b','main');git('add','source.ts','second.ts');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture');
app.setPath('userData', path.join(evidence, 'profile'));app.disableHardwareAcceleration();
let test_window;const checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const evaluate=source=>test_window.webContents.executeJavaScript(source);
const capture=async name=>{await delay(100);fs.writeFileSync(path.join(evidence,name+'.png'),(await test_window.webContents.capturePage()).toPNG());};
const wait=async source=>{for(let i=0;i<200;i++){if(await evaluate(source))return;await delay(30);}throw new Error('Timeout: '+source+'; '+await evaluate('JSON.stringify({errors:fixture_errors,state:document.documentElement.dataset.linuxNoteTyporaEnhancements})'));};
app.whenReady().then(async()=>{
 test_window=new BrowserWindow({show:false,width:1100,height:700,webPreferences:{nodeIntegration:true,contextIsolation:false,offscreen:true,backgroundThrottling:false}});
 const html=path.join(evidence,'fixture.html');fs.writeFileSync(html,`<!doctype html><meta charset="utf-8"><style>html,body{height:100%;margin:0;overflow:hidden;font:13px "Segoe UI",sans-serif;--bg-color:#fff;--text-color:#333}#typora-sidebar{position:absolute;left:48px;top:35px;width:240px;bottom:22px}#sidebar-content{position:absolute;inset:0}.typ-ribbon{width:48px;position:absolute;inset:0 auto 22px 0}.typ-ribbon-item{height:48px;display:flex;align-items:center;justify-content:center}.typ-ribbon-item svg{width:24px;height:24px}.typ-ribbon>.group.top{flex:1}.typ-ribbon{display:flex;flex-direction:column}.typ-workspace-tabs{height:100%;min-height:0}.typ-workspace-root{position:absolute;top:35px;left:288px;right:0;bottom:22px}content{height:100%;overflow:auto;display:block}.typ-workspace-tab-content{height:calc(100% - 35px)}.typ-tabs{display:flex;height:35px}.typ-tab{display:flex;align-items:center;padding:0 12px;border-right:1px solid #8884}.typ-tab.active{border-top:1px solid #007fd4}.typ-workspace-tab-content>.linux-note-git-graph,.typ-workspace-tab-content>.linux-note-source-editor{height:100%;min-height:0}#write{font:16px/1.6 sans-serif;padding:30px;box-sizing:border-box}footer{position:absolute;bottom:0;left:288px;right:0;height:22px}</style><body class="unibody-window show-footer"><div id="top-titlebar"><span id="w-titlebar-left"><span id="title-text">fixture</span></span><span id="w-traffic-lights"><span class="btn toolbar-icon" id="w-min">_</span><span id="w-max-group"><span class="btn toolbar-icon" id="w-max">□</span></span><span class="btn toolbar-icon" id="w-restore">▣</span><span class="btn toolbar-icon" id="w-close">×</span></span></div><aside class="typ-ribbon"><div class="group top"><div class="typ-ribbon-item" data-id="core.file-explorer"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M8 3h12v16H8zM4 7v16h12"/></svg></div><div class="typ-ribbon-item" data-id="core.search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="10" cy="10" r="7"/><path d="m15 15 7 7"/></svg></div><div class="typ-ribbon-item" data-id="core.outline">Outline</div></div><div class="group bottom"></div></aside><aside id="typora-sidebar"><div id="sidebar-content"><div id="native-outline-home"><div id="outline-content"><div class="outline-item"><span class="outline-label">Native Markdown</span></div></div><span id="outline-anchor"></span></div></div><div id="ty-sidebar-footer"></div></aside><div id="typora-sidebar-resizer"></div><main class="typ-workspace-root"><div class="typ-workspace-tabs"><div class="typ-workspace-tab-header"><div class="typ-tabs"></div></div><div class="typ-workspace-tab-content"><content><div id="write"><h1 cid="n1">Native Markdown</h1></div></content></div></div></main><footer class="ty-footer"><span class="footer-item-right">words</span></footer>`);
 await test_window.loadFile(html);
 await evaluate(`window.fixture_root=${JSON.stringify(repository)};window.fixture_source=${JSON.stringify(source_path)};`);
 await evaluate(fs.readFileSync(path.join(__dirname,'../fixtures/plugin_lifecycle_host.js'),'utf8'));await evaluate('window.original_outline=document.querySelector("#outline-content");window.original_outline_parent=original_outline.parentNode');
 const bundle=await build({stdin:{contents:'export {default as plugin_type} from "./src/community_plugin";export {activate_typora_enhancements,deactivate_typora_enhancements} from "./src/typora_enhancements";export {get_workspace_files} from "./src/workspace_files";export * as monaco from "monaco-editor/editor/editor.api";',resolveDir:path.join(__dirname,'..')},plugins:[{name:'community-host',setup(builder){builder.onResolve({filter:/^@typora-community-plugin\/core$/},()=>({path:'core',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const Plugin = window.fixture_plugin_base;',loader:'js'}));}},...editor_plugins()],bundle:true,format:'iife',globalName:'qa',write:false,loader:{'.css':'text','.svg':'text','.png':'dataurl','.wasm':'binary'},define:{'process.env.NODE_ENV':'"production"'}});
 await evaluate(bundle.outputFiles[0].text);
 // Monaco 的 ContextKey/Clipboard 单例是宿主窗口级；先显式预热并销毁临时 editor，避免把首次惰性初始化误算为插件泄漏。
 await evaluate('(()=>{const node=document.createElement("div");document.body.append(node);const editor=qa.monaco.editor.create(node,{value:"warmup",language:"plaintext"});const model=editor.getModel();editor.dispose();model.dispose();node.remove();})()');await delay(50);
 await evaluate('window.baseline_listeners=fixture_listener_count();window.plugin=new qa.plugin_type();plugin.onload();void 0');
 await delay(80);
 assert.equal(await evaluate('document.documentElement.dataset.linuxNoteWorkspace'),'loading');
 await evaluate('plugin.onunload();window.plugin=new qa.plugin_type();plugin.onload();fixture_core.app.settings=fixture_settings;void 0');
 await delay(150);
 assert.equal(await evaluate('document.documentElement.dataset.linuxNoteTyporaEnhancements'),'loading');
 assert.equal(await evaluate('fixture_commands.size'),0,'waiting for disconnected root must not register workbench commands');
 await evaluate('plugin.onunload();window.plugin=new qa.plugin_type();plugin.onload();document.body.append(fixture_root_element);void 0');
 await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"');
 assert.equal(await evaluate('fixture_errors.length'),0,await evaluate('fixture_errors.join("\\n")'));
 assert(await evaluate('fixture_commands.has("linux_note:terminal")&&fixture_commands.has("linux_note:search")&&fixture_factories.has("linux_note.source_file")'));
 assert(await evaluate('[...fixture_registration_counts.values()].every(count=>count===1)'),'aborted initialization callbacks must not create duplicate registrations');
 checks.push('aborting while core settings and then root mount are pending leaves only the latest plugin generation active');
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');
 assert(await evaluate('document.querySelector(".workspace-explorer-outline-content").hidden'),'Outline starts collapsed in the default Explorer layout');
 await capture('plugin_explorer_default');
 const open_outline_menu=async()=>{await evaluate('[...document.querySelectorAll(".workspace-titlebar-menu>button")].find(button=>button.textContent.trim()==="视图").click();void 0');await wait('Boolean(document.querySelector(".workspace-titlebar-popup"))');await evaluate('[...document.querySelectorAll(".workspace-titlebar-popup button")].find(button=>button.textContent.trim()==="大纲").click();void 0');await wait('!document.querySelector(".workspace-explorer-outline-content").hidden&&document.querySelector(".workspace-explorer-outline-content").getBoundingClientRect().height>0');};
 await open_outline_menu();
 assert(await evaluate('document.querySelector(".workspace-explorer-outline-content #outline-content")===original_outline&&document.querySelector(".workspace-outline-empty").hidden'),'Markdown embeds the identical native outline node');
 await wait('document.querySelectorAll(".workspace-explorer-row").length>=2');await evaluate('[...document.querySelectorAll(".workspace-explorer-row")].find(row=>row.dataset.path===fixture_source).click();void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 await evaluate('window.first_preview=fixture_core.app.workspace.activeLeaf;void 0');assert(await evaluate('first_preview.state.workspace_preview'));
 await evaluate('[...document.querySelectorAll(".workspace-explorer-row")].find(row=>row.dataset.path.endsWith("second.ts")).click();void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 assert(await evaluate('!fixture_leaves.includes(first_preview)&&fixture_core.app.workspace.activeLeaf.state.workspace_preview'),'single-click preview replaces the previous clean preview');
 await evaluate('[...document.querySelectorAll(".workspace-explorer-row")].find(row=>row.dataset.path.endsWith("second.ts")).dispatchEvent(new MouseEvent("dblclick",{bubbles:true}));void 0');assert(await evaluate('!fixture_core.app.workspace.activeLeaf.state.workspace_preview'),'double clicking a preview keeps it open');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(fixture_root,"second.ts"),{preview:true});void 0');assert(await evaluate('!fixture_core.app.workspace.activeLeaf.state.workspace_preview'),'single click must not downgrade an existing permanent source tab');
 await evaluate('qa.get_workspace_files().open_file(fixture_source,{preview:true});void 0');await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 await evaluate('window.edit_preview=fixture_core.app.workspace.activeLeaf;edit_preview.view.editor.models[0].setValue("const preview_edit = 3;\\n");void 0');await wait('!edit_preview.state.workspace_preview');
 await wait('document.querySelectorAll(".workspace-open-editor-row").length===fixture_leaves.length');
 await evaluate('document.querySelector(".workspace-explorer-outline-toggle").click()');await open_outline_menu();
 assert(await evaluate('document.querySelector(".workspace-explorer-outline-content").dataset.documentOutline==="false"&&!document.querySelector(".workspace-outline-empty").hidden'),'source editors display an outline placeholder');
 await evaluate('[...document.querySelectorAll(".workspace-open-editor-row")].find(row=>row.querySelector(".workspace-open-editor-name").title===fixture_source).querySelector(".workspace-open-editor-close").click();void 0');
 await wait('Boolean(document.querySelector("[data-workspace-tab-close]"))');assert(await evaluate('fixture_leaves.includes(edit_preview)&&edit_preview.view.dirty()'),'Open Editors close goes through the production dirty guard');
 await evaluate('[...document.querySelectorAll("[data-workspace-tab-close] button")].find(button=>button.textContent==="不保存并关闭").click();void 0');await wait('!fixture_leaves.includes(edit_preview)');
 await evaluate('qa.get_workspace_files().open_file(require("path").join(fixture_root,"second.ts"),{preview:true},"right");void 0');await wait('fixture_leaves.filter(leaf=>leaf.state.path.includes("second.ts")).length===2');
 await wait('document.querySelectorAll(".workspace-open-editor-group").length===2');
 assert(await evaluate('(()=>{const leaves=fixture_leaves.filter(leaf=>leaf.state.path.includes("second.ts"));return !leaves[0].state.workspace_preview&&leaves[1].state.workspace_preview&&!leaves[0].parent.tabHeader.getTabById(leaves[0].state.path).classList.contains("is-workspace-preview")&&leaves[1].parent.tabHeader.getTabById(leaves[1].state.path).classList.contains("is-workspace-preview")})()'),'duplicate paths keep independent preview state and native tab styling by group');

 await evaluate('[...document.querySelectorAll(".workspace-open-editor-name")].filter(button=>button.textContent==="second.ts")[0].click();void 0');assert(await evaluate('fixture_core.app.workspace.activeLeaf.parent!==fixture_second_group'),'Open Editors selects the requested group for duplicate paths');
 await evaluate('[...document.querySelectorAll(".workspace-open-editor-name")].filter(button=>button.textContent==="second.ts")[1].click();void 0');assert(await evaluate('fixture_core.app.workspace.activeLeaf.parent===fixture_second_group'));
 await evaluate('document.querySelectorAll(".workspace-open-editor-name")[document.querySelectorAll(".workspace-open-editor-name").length-1].dispatchEvent(new MouseEvent("dblclick",{bubbles:true}));void 0');assert(await evaluate('!fixture_core.app.workspace.activeLeaf.state.workspace_preview'),'Open Editors double-click promotes its selected group leaf');
 await capture('plugin_open_editors_groups');
 await evaluate('const inactive=fixture_leaves.find(leaf=>leaf.state.path.includes("second.ts")&&leaf.parent!==fixture_second_group);inactive.parent.removeTab(inactive.state.path);void 0');await wait('document.querySelectorAll(".workspace-open-editor-row").length===fixture_leaves.length');

 await evaluate('for(const leaf of [...fixture_leaves])if(leaf!==fixture_native_leaf)leaf.parent.removeTab(leaf.state.path);fixture_core.app.workspace.activeLeaf=fixture_native_leaf;void 0');await delay(50);
 await evaluate('qa.get_workspace_files().open_file(fixture_native_leaf.state.path,{preview:true})');assert(await evaluate('!fixture_native_leaf.state.workspace_preview'),'single click must not downgrade an existing permanent Markdown tab');
 checks.push('preview replacement and double-click/edit promotion preserve permanent tabs; Open Editors locates duplicate paths by group and uses dirty close guards; native Outline follows the active document');
 await capture('plugin_markdown');
 await evaluate('fixture_commands.get("linux_note:file_explorer").callback();void 0');await wait('document.querySelectorAll(".workspace-explorer-row").length>0');await capture('plugin_explorer');
 await evaluate('fixture_commands.get("linux_note:search").callback();const input=document.querySelector(".workspace-search-query-box textarea");input.value="original";input.dispatchEvent(new Event("input",{bubbles:true}));void 0');await wait('document.querySelectorAll(".workspace-search-match").length>0');await capture('plugin_search');
 await evaluate('fixture_commands.get("linux_note:source_control").callback();void 0');await wait('Boolean(document.querySelector(".git-scm-title"))');await capture('plugin_scm');
 await evaluate('fixture_commands.get("linux_note:git_graph").callback();void 0');await wait('document.querySelectorAll(".git-graph-row").length>0');await capture('plugin_graph');
 await evaluate('fixture_commands.get("linux_note:terminal").callback();void 0');await wait('Boolean(document.querySelector(".typora-terminal-panel .xterm"))');await capture('plugin_terminal');assert.equal(await evaluate('getComputedStyle(document.querySelector(".typora-terminal-panel .xterm-viewport")).backgroundColor'),'rgba(0, 0, 0, 0)','xterm viewport must not expose its upstream black fallback below a light terminal screen');
 await evaluate('fixture_commands.get("linux_note:terminal_toggle_panel").callback();void 0');assert(await evaluate('document.querySelector(".typora-terminal-panel").hidden'));
 await evaluate('fixture_commands.get("linux_note:terminal_toggle_panel").callback();void 0');assert(await evaluate('!document.querySelector(".typora-terminal-panel").hidden'));
 await evaluate('fixture_commands.get("linux_note:terminal_move_to_editor").callback();void 0');assert(await evaluate('document.querySelector(".typora-terminal-panel").hidden'));
 await evaluate('fixture_commands.get("linux_note:terminal_toggle_panel").callback();void 0');assert(await evaluate('!document.querySelector(".typora-terminal-panel").hidden'),'toggle must recover an empty Panel after moving its last terminal into the editor');
 checks.push('full plugin switches through real Explorer Search SCM Graph and default Terminal Panel with screenshot evidence');
 await evaluate('window.active_registration_count=fixture_commands.size;window.active_factory_count=fixture_factories.size;window.original_disable=fixture_manager.disablePlugin;void 0');
 await evaluate('qa.get_workspace_files().open_file(fixture_source);void 0');
 await wait('Boolean(fixture_core.app.workspace.activeLeaf.view.editor?.models?.[0])');
 await capture('plugin_source');
 await evaluate('window.source_view=fixture_core.app.workspace.activeLeaf.view;source_view.editor.models[0].setValue("const changed = 2;\\n");void 0');
 await delay(50);
 assert(await evaluate('source_view.dirty()'));
 for(const action of ['disablePlugin','unloadPlugin','uninstallPlugin','updatePlugin']){
  const rejected=await evaluate(`(()=>{try{fixture_manager[${JSON.stringify(action)}](fixture_plugin_id);return false}catch{return true}})()`);
  assert(rejected,action+' must reject before changing manager state');
  assert(await evaluate('fixture_manager.enabled&&fixture_manager.mutations===0&&fixture_commands.size===active_registration_count&&fixture_factories.size===active_factory_count&&document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"'));
 }
 assert.equal(fs.readFileSync(source_path,'utf8'),'const original = 1;\n');
 checks.push('real unsaved Monaco source model blocks disable unload uninstall and update before manager enabled state changes');
 assert(await evaluate("qa.get_workspace_files().save_active()"), "saving the fixture source through the production host clears its dirty guard");
 assert.equal(fs.readFileSync(source_path,"utf8"),"const changed = 2;\n");
 await evaluate('fixture_manager.disablePlugin(fixture_plugin_id);void 0');await delay(200);
 assert(await evaluate('!fixture_manager.enabled&&fixture_manager.mutations===1&&Object.entries(fixture_manager_originals).every(([name,original])=>fixture_manager[name]===original)'));
 assert(await evaluate('fixture_commands.size===0&&fixture_factories.size===0&&fixture_subscription_count()===0&&fixture_ribbon.size===0&&fixture_core.app.workspace.sidebar.panels.length===2'));
 assert(await evaluate('fixture_leaves.length===1&&!document.querySelector(".workspace-titlebar-menu")&&!document.querySelector(".workspace-quick-open")&&!document.documentElement.hasAttribute("data-linux-note-typora-enhancements")'));
 assert(await evaluate('fixture_core.app.openFile===fixture_original_app_open&&File.editor.library.openFile===fixture_original_library_open'));
 assert(await evaluate('original_outline.parentNode===original_outline_parent&&original_outline.nextSibling.id==="outline-anchor"'),'unload restores original native Outline ownership and sibling position');
 checks.push('clean unload removes commands views subscriptions ribbon panels and source leaves and restores native file routes');
 const remaining=await evaluate('fixture_listener_snapshot()');
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'),'global DOM listeners must return to baseline: '+JSON.stringify(remaining));
 checks.push('document and window listeners return to their pre-activation baseline including AbortSignal-owned listeners');
 await evaluate('fixture_manager.enabled=true;window.plugin=new qa.plugin_type();plugin.onload();void 0');await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="ready"');
 assert(await evaluate('fixture_commands.size===active_registration_count&&fixture_factories.size===active_factory_count&&document.querySelectorAll(".workspace-quick-open").length===1'));
 await evaluate('plugin.onunload()');await delay(100);
 assert.equal(await evaluate('fixture_commands.size'),0);
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'));
 assert.equal(await evaluate('qa.monaco.editor.getModels().length'),0);
 checks.push('a full reload restores one set of commands views and titlebar UI and unloads cleanly again');
 await evaluate('window.fixture_throw_view="linux_note.search_results";window.plugin=new qa.plugin_type();plugin.onload();void 0');
 await wait('document.documentElement.dataset.linuxNoteTyporaEnhancements==="failed"');await delay(100);
 assert(await evaluate('fixture_errors.some(error=>error.includes("Injected view registration failure"))'));
 assert(await evaluate('fixture_commands.size===0&&fixture_factories.size===0&&fixture_subscription_count()===0&&fixture_ribbon.size===0&&fixture_core.app.workspace.sidebar.panels.length===2'));
 assert.equal(await evaluate('fixture_listener_count()'),await evaluate('baseline_listeners'));
 await evaluate('plugin.onunload();window.fixture_throw_view=undefined;fixture_errors.length=0;void 0');
 checks.push('a host view-registration exception mid-browser construction rolls back root and all acquired workbench resources');
 console.log(JSON.stringify({status:'PASS',checks,evidence}));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);if(test_window&&!test_window.isDestroyed()){console.error(await evaluate('JSON.stringify({errors:fixture_errors,listeners:fixture_listener_snapshot(),commands:[...fixture_commands.keys()],factories:[...fixture_factories.keys()],subscriptions:fixture_subscription_count()})'));test_window.destroy();}console.error(evidence);app.exit(1);});
