import assert from 'node:assert/strict';
import path from 'node:path';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
const events=new EventTarget();globalThis.addEventListener=events.addEventListener.bind(events);globalThis.removeEventListener=events.removeEventListener.bind(events);
const compiled=await build({stdin:{contents:`export * from './src/workspace_directory_service';export {workspace_resource_fs,register_remote_files} from './src/remote_workspace_files';export {discover_git_repositories} from './src/git_repository_discovery';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',write:false});
const module={exports:{}};new Function('require','module','exports',compiled.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);
const {acquire_workspace_directories,read_workspace_directory,subscribe_workspace_directory_changes,workspace_resource_fs,register_remote_files,discover_git_repositories}=module.exports;
const file=name=>({name,isFile:()=>true,isDirectory:()=>false,isSymbolicLink:()=>false});
const folder=name=>({name,isFile:()=>false,isDirectory:()=>true,isSymbolicLink:()=>false});
let reads=0,watchers=0,notify,fail=false,release;
const entries=new Map([['/project',[folder('src'),folder('.git'),file('README.md')]],['/project/src',[file('main.c')]]]);
const native={promises:{readdir:async directory=>{reads++;if(release==='pending')await new Promise(resolve=>release=resolve);if(fail)throw Error('denied');return [...(entries.get(directory)||[])];},writeFile:async target=>{entries.get(path.posix.dirname(target)).push(file(path.posix.basename(target)));}},watch(_root,_options,callback){watchers++;notify=callback;return{close(){watchers--;},on(){return this;}};}};
const fs=workspace_resource_fs(native);assert.equal(workspace_resource_fs(native),fs,'全部模块取得同一文件系统身份');
const explorer=acquire_workspace_directories(fs,path.posix),quick=acquire_workspace_directories(fs,path.posix),service=explorer.service;assert.equal(service,quick.service);
let changes=0;const unsubscribe=subscribe_workspace_directory_changes(()=>changes++);
await Promise.all(Array.from({length:1000},()=>read_workspace_directory(fs,path.posix,'/project','/project')));assert.equal(reads,1,'1000并发目录读合并');assert.equal(watchers,1);
const first=await service.catalogue('/project');assert.deepEqual(first.files.map(item=>item.name).sort(),['README.md','main.c']);assert.equal(reads,2,'扫描复用资源树根目录');
for(let i=0;i<100;i++)assert.equal(await service.catalogue('/project'),first);assert.equal(reads,2,'100次重开不重新统计');assert.equal(service.cached_catalogue('/project'),first);
const discovered=await discover_git_repositories({fs,path:path.posix,root:'/project',depth:1,run:async()=>'/project'});assert.deepEqual(discovered.roots,['/project']);assert.equal(reads,2,'Git发现复用相同目录');
notify('change','src/main.c');assert.equal(service.cached_catalogue('/project'),first,'正文修改不清空名称目录');assert(changes>0,'内容变化通知Git消费者');
entries.get('/project/src').push(file('added.c'));notify('rename','src/added.c');const second=await service.catalogue('/project');assert.equal(second.files.length,3);assert.equal(reads,3,'只重读变化的目录');
await fs.promises.writeFile('/project/new.md','');assert.equal(service.cached_catalogue('/project'),undefined,'自有写操作在返回前统一失效');assert.equal((await service.catalogue('/project')).files.length,4);
service.invalidate('/project','/project/src');fail=true;await assert.rejects(service.read('/project','/project/src'),/denied/);fail=false;assert.equal((await service.read('/project','/project/src')).length,2,'失败不作为有效缓存');
service.invalidate('/project','/project/src');release='pending';const pending=service.read('/project','/project/src');await new Promise(resolve=>setTimeout(resolve,0));service.invalidate('/project','/project/src');entries.get('/project/src').push(file('late.c'));const resume=release;release=undefined;resume();assert.equal((await pending).length,3,'失效中的读取重新合并');
service.invalidate('/project');release='pending';const stale=service.catalogue('/project');await new Promise(resolve=>setTimeout(resolve,0));events.dispatchEvent(new Event('linux-note-workspace-context-changed'));const resume_stale=release;release=undefined;resume_stale();await assert.rejects(stale,{name:'AbortError'});assert.equal(watchers,0,'切库关闭原监听');
await service.catalogue('/project');assert.equal(watchers,1);explorer.dispose();assert.equal(watchers,1,'一个消费者关闭不终止其他消费者');quick.dispose();assert.equal(watchers,0,'最后持有者释放监听与快照');unsubscribe();
let fallback_reads=0;const unavailable={promises:{readdir:async()=>{fallback_reads++;return[file('fresh.md')];}},watch(){throw Error('unsupported');}};const fallback=acquire_workspace_directories(unavailable,path.posix);await fallback.service.catalogue('/offline');await fallback.service.catalogue('/offline');assert.equal(fallback_reads,2,'无监听能力不保留永久过期快照');fallback.dispose();
let remote_reads=0,remote_watches=0;const provider={owns:value=>value.startsWith('/remote'),connection:{connected:()=>true},dispose(){},fs:{promises:{readdir:async directory=>{remote_reads++;return directory==='/remote'?[folder('sub')]:[file('server.md')];}},watch(){remote_watches++;return{close(){remote_watches--;},on(){return this;}};}}};
const release_remote=register_remote_files(provider),remote=acquire_workspace_directories(fs,path.posix);
await Promise.all(Array.from({length:20},()=>remote.service.catalogue('/remote')));assert.equal(remote_reads,2,'远端并发扫描合并');assert.equal(remote_watches,0,'扫描不创建未展示目录轮询');
await remote.service.catalogue('/remote');assert.equal(remote_reads,4,'远端缺少递归事件时按需读新目录');
const a=remote.service.subscribe('/remote',()=>{},'/remote/sub'),b=remote.service.subscribe('/remote',()=>{},'/remote/sub');assert.equal(remote_watches,1);a();assert.equal(remote_watches,1);b();assert.equal(remote_watches,0);remote.dispose();release_remote();
console.log('PASS shared directory service: 1000 concurrent reads; 100 cached reopen; tree/search/Git shared IO; writes, external changes, failure/retry, stale reads, context cancellation and release; watcher fallback.');
