// 正式静态CSS + 真实Chromium：同层/跨层颜色、正文隔离、状态和主题事件压力。
const {app,BrowserWindow}=require('electron'),{build}=require('esbuild');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'typora_colors_'));app.setPath('userData',path.join(base,'profile'));app.disableHardwareAcceleration();
let win;const checks=[],samples=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
const check=(v,label)=>{assert(v,label);checks.push(label);},read=s=>win.webContents.executeJavaScript(s);
app.whenReady().then(async()=>{
 win=new BrowserWindow({show:false,width:1200,height:800,webPreferences:{offscreen:true,contextIsolation:false,backgroundThrottling:false}});
 const css=fs.readFileSync(path.join(__dirname,'../dist/workspace.css'),'utf8');
 fs.writeFileSync(path.join(base,'test.html'),`<!doctype html><style>${css}</style><style>body{margin:0;background:#fff7df;--bg-color:#fff7df;--text-color:#192939;color:#192939}body.dark{background:#263238;--bg-color:#263238;--text-color:#ddefdf;color:#ddefdf}#write,#native,.plugin{background:var(--bg-color);color:var(--text-color)}#write{width:400px;height:80px;overflow:auto}#typora-sidebar{position:relative;width:280px;height:220px}.linux-note-workspace-explorer{position:static;height:auto}.workspace-settings{height:220px}.git-graph-dialog{position:relative}.workspace-tab-strip{width:500px}.sample{height:25px}.workspace-settings-body{height:120px}</style><body class="typ-ribbon--enable"><main id="write" contenteditable="true">保留正文 <div style="height:300px">段落</div></main><section id="native">原生设置</section><aside id="typora-sidebar"><div class="linux-note-workspace-explorer"><div class="workspace-section-header">资源</div><input id="rename" class="workspace-explorer-rename"></div><div class="linux-note-git-source-control"><textarea class="git-scm-message"></textarea></div></aside><div class="workspace-tab-strip"><div class="typ-tabs"><div class="typ-tab active">文件</div></div></div><div class="workspace-settings"><div class="workspace-settings-content"><nav class="workspace-settings-categories"><button aria-pressed="true">设置</button></nav><div class="workspace-settings-body"><div class="workspace-setting-row"><label class="workspace-setting-label">字号<input id="setting" value="14"><small>说明</small></label></div></div></div></div><div class="git-graph-dialog"><div class="workspace-dialog-header">对话框</div><input id="dialog-input"><button id="primary" data-workspace-interaction="primary">确定</button><button disabled>禁用</button><div class="plugin" data-workspace-interaction="none"><input id="plugin-input" style="background:var(--bg-color);color:var(--text-color)"></div></div><div class="terminal-panel-header sample">终端</div><div class="linux-note-terminal sample">日志</div><div class="workspace-ssh-sidebar sample">远端</div><div class="workspace-community-manager sample">扩展</div><div class="workspace-link-preview"><div role="toolbar">预览</div></div><div class="git-graph-menu sample">菜单</div><footer class="ty-footer sample">状态</footer></body>`);
 await win.loadFile(path.join(base,'test.html'));
 const bundle=await build({stdin:{contents:'export {bind_workspace_colors} from "./src/workspace_colors";export {observe_terminal_theme} from "./src/terminal_theme";export {acquire_workspace_interaction} from "./src/workspace_interaction";',resolveDir:path.join(__dirname,'..')},bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});await read(bundle.outputFiles[0].text);
 await read(`window.snap=selector=>{const el=document.querySelector(selector),s=getComputedStyle(el);return {bg:s.backgroundColor,fg:s.color,border:s.borderTopColor,box:el.getBoundingClientRect().toJSON()}};window.original=snap('#write');window.plugin=snap('#plugin-input');window.term_updates=[];window.stop_term=qa.observe_terminal_theme(t=>term_updates.push(t));window.binding=qa.bind_workspace_colors();window.interaction=qa.acquire_workspace_interaction(document.querySelector('.git-graph-dialog'));window.writes=0;window.monitor=new MutationObserver(r=>writes+=r.length);monitor.observe(document.documentElement,{attributes:true,attributeFilter:['data-workspace-colors']});void 0`);await pause(150);
 check(await read(`snap('#write').bg===original.bg&&snap('#write').fg===original.fg&&snap('#plugin-input').bg===plugin.bg&&snap('#plugin-input').fg===plugin.fg`),'正文与嵌套第三方设置主题保持');
 for(const dark of [false,true]){
  await read(`document.body.classList.toggle('dark',${dark});void 0`);await pause(120);
  const data=await read(`({mode:document.documentElement.dataset.workspaceColors,frames:['#typora-sidebar','.linux-note-git-source-control','.terminal-panel-header','.linux-note-terminal','.workspace-ssh-sidebar','.workspace-community-manager','.workspace-settings-categories','.workspace-tab-strip'].map(snap),contents:['.workspace-settings','.git-graph-dialog','.git-graph-menu'].map(snap),input:snap('#setting'),title:snap('.workspace-link-preview>[role=toolbar]'),term:term_updates.at(-1),body:snap('#write')})`);samples.push(data);
  const chrome=dark?'rgb(24, 24, 24)':'rgb(248, 248, 248)',content=dark?'rgb(31, 31, 31)':'rgb(255, 255, 255)';
  check(data.mode===(dark?'dark':'light')&&data.frames.every(s=>s.bg===chrome),'同层框架共享背景 '+dark+' '+JSON.stringify(data.frames.map(s=>s.bg)));
  check(data.contents.every(s=>s.bg===content)&&data.title.bg===chrome,'功能内容与工具层区分 '+dark);
  check(data.input.bg===(dark?'rgb(49, 49, 49)':'rgb(255, 255, 255)'),'输入控件区分 '+dark);
  check(data.term.background.toLowerCase()===(dark?'#181818':'#f8f8f8'),'终端消费者在颜色更新后收到当前主题 '+dark);
  check(data.body.bg===(dark?'rgb(38, 50, 56)':'rgb(255, 247, 223)'),'自定义正文底色未被覆盖 '+dark);
  const states=await read(`(()=>{const input=document.querySelector('#setting');input.focus();const primary=document.querySelector('#primary'),disabled=document.querySelector('button:disabled');return{selected:snap('.workspace-settings-categories button'),focused:snap('.workspace-setting-row'),primary:snap('#primary'),disabled:getComputedStyle(disabled).opacity,muted:snap('.workspace-setting-label small'),focus:document.activeElement===input}})()`);
  check(states.focus&&states.focused.bg!==(dark?'rgb(31, 31, 31)':'rgb(255, 255, 255)')&&states.selected.bg!==chrome,'输入焦点与当前分类有独立状态 '+dark);
  check(states.primary.bg===(dark?'rgb(0, 120, 212)':'rgb(0, 95, 184)')&&states.primary.fg==='rgb(255, 255, 255)'&&Number(states.disabled)<1,'主操作成对着色且禁用保持 '+dark);
  const luminance=value=>{const channels=value.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722;};
  const contrast=(fg,bg)=>{const a=luminance(fg),b=luminance(bg);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);};
  check(data.frames.every(s=>contrast(s.fg,s.bg)>=4.5)&&contrast(states.primary.fg,states.primary.bg)>=4.5&&contrast(states.muted.fg,content)>=4.5,'正文以外的主要/次要文字及主操作对比度至少4.5 '+dark);
 }
 await read(`document.querySelector('#setting').focus();document.querySelector('#write').scrollTop=60;window.saved=document.querySelector('#write').scrollTop;window.identity=document.querySelector('#setting');window.before=snap('#write').box;writes=0;window.count=term_updates.length;for(let i=0;i<1000;i++)document.body.setAttribute('class',document.body.className);void 0`);await pause(200);
 check(await read('writes===0&&term_updates.length===count'),'1000次同值通知无调色板写入或终端重绘');
 for(let i=0;i<20;i++){await read(`document.body.classList.toggle('dark');void 0`);await pause(30);}
 check(await read(`identity===document.activeElement&&identity===document.querySelector('#setting')&&document.querySelector('#write').scrollTop===saved&&JSON.stringify(snap('#write').box)===JSON.stringify(before)`),'20次主题切换保持节点、焦点、滚动及几何');
 win.setContentSize(650,550);win.webContents.setZoomFactor(1.25);await pause(60);
 check(await read(`snap('.workspace-settings-categories').bg===snap('.workspace-tab-strip').bg`),'窄窗125%仍按相同角色着色');
 await read(`window.dynamic=document.createElement('div');dynamic.className='workspace-ssh-sidebar';document.body.append(dynamic);void 0`);
 check(await read(`getComputedStyle(dynamic).backgroundColor===snap('#typora-sidebar').bg`),'动态面板立即使用当前色表');
 await read(`binding.dispose();stop_term();interaction.remove();monitor.disconnect();void 0`);
 check(await read(`!document.documentElement.hasAttribute('data-workspace-colors')&&getComputedStyle(document.querySelector('#write')).backgroundColor==='rgb(38, 50, 56)'`),'销毁恢复标记与正文主题');
 fs.writeFileSync(path.join(base,'checks.json'),JSON.stringify({status:'PASS',checks,samples},null,2));console.log(JSON.stringify({status:'PASS',count:checks.length,evidence:base}));win.destroy();app.exit(0);
}).catch(error=>{console.error(error);if(win)win.destroy();app.exit(1)});
