const {app,BrowserWindow}=require('electron');const {build}=require('esbuild');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const cp=require('node:child_process');const assert=require('node:assert/strict');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'typora_graph_visibility_'));const repo=path.join(temp,'repo');fs.mkdirSync(repo);const git=(...args)=>cp.execFileSync('git',args,{cwd:repo,encoding:'utf8',windowsHide:true});git('init','-b','main');git('config','user.name','Test');git('config','user.email','test@example.invalid');for(let index=0;index<12;index++){fs.writeFileSync(path.join(repo,'note.md'),'revision '+index);git('add','.');git('commit','-qm','revision '+index);}app.setPath('userData',path.join(temp,'profile'));app.disableHardwareAcceleration();let window;
app.whenReady().then(async()=>{
 const bundle=await build({stdin:{contents:'export {git_graph_panel} from "./src/git_graph_panel";export {compare_patch} from "./src/git_graph_repository";',resolveDir:path.join(__dirname,'..')},plugins:require('./editor_bundle.cjs').editor_plugins(),bundle:true,write:false,format:'iife',globalName:'qa',loader:{'.css':'text'}});const html=path.join(temp,'index.html');fs.writeFileSync(html,'<!doctype html><html><body></body></html>');window=new BrowserWindow({show:false,width:1000,height:650,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false}});await window.loadFile(html);const run=code=>window.webContents.executeJavaScript(code);const wait=async predicate=>{for(let n=0;n<300;n++){if(await run(predicate))return;await new Promise(resolve=>setTimeout(resolve,20));}throw new Error('timeout: '+predicate+' '+await run('panel.status.textContent'));};await run(bundle.outputFiles[0].text);
 await run(`(()=>{const style=document.createElement('style');style.textContent=${JSON.stringify(fs.readFileSync(path.join(__dirname,'../src/git_graph.css'),'utf8'))}+'body{height:350px}';document.head.append(style);
 window.commands=[];window.cancels=0;window.write_cancels=0;window.block='log';window.release=null;
 const runner=(settings,writing=false)=>({cancel(){if(writing)write_cancels++;else cancels++;},run:async(cwd,args)=>{commands.push(args);let output;try{output=require('node:child_process').execFileSync('git',args,{cwd,encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','pipe']});}catch(error){/* 同步子进程的status映射到正式Git运行器的退出码契约。 */error.code=error.status;throw error;}if(block&&args[0]===block){block='';await new Promise(resolve=>{release=()=>{release=null;resolve()}});}return output;}});
 const host={runner,path_api:require('node:path'),process_api:{platform:'win32'},fs:require('node:fs'),core:{app:{workspace:{sidebar:{toggle(){}},activeLeaf:null}}},operation:value=>value,terminal(){},clear_avatars(){},copy:async()=>{},can_change_files:()=>true,show_output(){},show_history(){},export_file(){},discover:async()=>[]};
 window.test_host=host;window.panel=new qa.git_graph_panel(host,${JSON.stringify(repo)});document.body.append(panel.container);panel.open();})()`);
 await wait('!!release');const initial=await run('({reads:commands.filter(args=>args[0]==="log").length,cancels})');await run('panel.close();panel.open();panel.close();panel.open()');assert.deepEqual(await run('({reads:commands.filter(args=>args[0]==="log").length,cancels})'),initial,'loading tab toggles neither cancel nor restart Git history');await run('release()');await wait('!panel.pending');assert.equal(await run('panel.container.dataset.state'),'ready');
 await run('panel.branches=["refs/heads/main"];panel.branch_select.value="refs/heads/main";panel.selected=panel.state.commits[0].hash;window.comparison=panel.show_comparison(panel.state.commits[0].parents[0],panel.selected)');await run('comparison');await wait('panel.files.length>0');
 await run('panel.list.style.height="100px";panel.list.style.flex="none";panel.list.scrollTop=60;window.saved_row=panel.list.querySelector(".git-graph-row");window.saved_detail=panel.details.firstChild;window.saved_scroll=panel.list.scrollTop;window.saved_count=commands.length;window.saved_cancel=cancels;panel.close();panel.open()');
 assert(await run('saved_row===panel.list.querySelector(".git-graph-row")&&saved_detail===panel.details.firstChild'),'loaded tab switch preserves row and detail DOM identity');assert(await run('saved_scroll>0&&saved_scroll===panel.list.scrollTop'),'loaded tab switch preserves a nonzero scroll offset');assert.deepEqual(await run('panel.branches'),['refs/heads/main']);assert.equal(await run('panel.branch_select.value'),'refs/heads/main');assert(await run('commands.length===saved_count&&cancels===saved_cancel'),'loaded tab switch does not query Git');
 await run('block="log";window.refresh_task=panel.refresh(false);void 0');await wait('!!release');const refresh_counts=await run('({count:commands.length,cancels})');await run('panel.close();panel.open()');assert.deepEqual(await run('({count:commands.length,cancels})'),refresh_counts);await run('release()');await run('refresh_task');assert.equal(await run('panel.container.dataset.state'),'ready','explicit refresh completes across a tab switch');

 // 无变化刷新必须保留真实文件行和焦点；并发调用复用同一笔读取。
 fs.writeFileSync(path.join(repo,'note.md'),'changed alpha');
 await run('document.body.append(panel.workbench.sidebar);panel.refresh(false)');await wait('!panel.pending');
 await run('window.unchanged_graph=panel.list.querySelector(".git-graph-row");window.unchanged_history=panel.workbench.history.list.firstElementChild;window.unchanged_groups=panel.workbench.groups.firstElementChild;window.focused_file=panel.workbench.groups.querySelector(".git-scm-file");focused_file.focus();window.unchanged_snapshot=JSON.stringify(panel.state);window.command_start=commands.length;block="log";window.shared_read=panel.refresh(false);window.shared_read_again=panel.refresh(false);void 0');
 await wait('!!release');assert(await run('shared_read===shared_read_again'),'simultaneous equal requests share the pending promise');await run('release()');await run('shared_read');
 assert(await run('JSON.stringify(panel.state)===unchanged_snapshot'),'fixture repository is unchanged');
 assert(await run('unchanged_graph===panel.list.querySelector(".git-graph-row")&&unchanged_history===panel.workbench.history.list.firstElementChild&&unchanged_groups===panel.workbench.groups.firstElementChild'),'unchanged result retains graph, SCM history and resource DOM');
 assert(await run('focused_file.isConnected&&document.activeElement===focused_file'),'unchanged refresh keeps actual file keyboard focus');
 assert.equal(await run('commands.slice(command_start).filter(args=>args[0]==="status").length'),1,'one shared branch snapshot per read');

 // 相同结果不能取消仍在读取的历史详情，也不能复用已被替换的runner。
 await run('block="show";window.loading_comparison=panel.show_comparison(panel.state.commits[0].parents[0],panel.state.commits[0].hash);void 0');await wait('!!release');await run('loading_comparison');
 await run('window.pending_detail=panel.details.firstChild;window.detail_cancel_count=cancels;panel.refresh(false)');
 assert(await run('pending_detail===panel.details.firstChild&&cancels===detail_cancel_count'),'unchanged refresh leaves in-flight immutable detail alive');
 await run('release()');await wait('panel.details.querySelector(".git-graph-message").textContent.includes("revision")');
 await run('block="log";window.obsolete_read=panel.refresh(false);void 0');await wait('!!release');
 await run('window.obsolete_release=release;panel.runner.cancel();panel.runner=test_host.runner(panel.settings);window.replacement_read=panel.refresh(false);void 0');
 assert(await run('replacement_read!==obsolete_read'),'replaced runner starts a new request even with identical configuration');await run('replacement_read');await run('obsolete_release()');await run('obsolete_read');
 assert(await run('!panel.pending&&panel.container.dataset.state==="ready"&&panel.state.head'),'obsolete completion cannot replace the new snapshot');
 // 同样的M状态仍需更新可变版本比较，不能将文件内容误判成未变化。
 await run('panel.selected="WORKTREE";panel.show_comparison("INDEX","WORKTREE")');await wait('panel.files.length>0');
 await run('window.mutable_snapshot=JSON.stringify(panel.state);window.mutable_reads=0;window.original_comparison=panel.show_comparison.bind(panel);panel.show_comparison=(...args)=>{mutable_reads++;return original_comparison(...args)};void 0');
 fs.writeFileSync(path.join(repo,'note.md'),'changed beta');await run('panel.refresh(false)');await wait('!panel.pending&&panel.files.length>0');
 assert(await run('JSON.stringify(panel.state)===mutable_snapshot&&mutable_reads===1'),'M to M retains status snapshot but refreshes mutable comparison');
 assert((await run('qa.compare_patch(panel.runner.run,panel.state,"INDEX","WORKTREE",panel.files[0])')).includes('+changed beta'),'mutable comparison reads current file content');
 await run('panel.show_comparison=original_comparison;window.before_settings_row=panel.list.querySelector(".git-graph-row");panel.settings.show_author=!panel.settings.show_author;panel.refresh(false)');await wait('!panel.pending');
 assert(await run('before_settings_row!==panel.list.querySelector(".git-graph-row")'),'display settings are not suppressed by repository equality');
 // 相同HEAD和文件组也必须应用另一仓库自己的树形及折叠布局。
 fs.mkdirSync(path.join(repo,'folder'));fs.writeFileSync(path.join(repo,'folder/change.md'),'untracked');await run('panel.refresh(false)');
 const clone=path.join(temp,'clone').replace(/\\/g,'/');cp.execFileSync('git',['clone','--quiet',repo,clone],{windowsHide:true});fs.writeFileSync(path.join(clone,'note.md'),'changed beta');fs.mkdirSync(path.join(clone,'folder'));fs.writeFileSync(path.join(clone,'folder/change.md'),'untracked');
 await run(`localStorage.setItem('linux-note-source-control:v1:layout:'+${JSON.stringify(clone)},JSON.stringify({tree:true,sort_order:'name'}));localStorage.setItem('linux-note-source-control:v1:collapsed:changes:'+${JSON.stringify(clone)},'true');window.previous_groups=panel.workbench.groups.firstElementChild;window.previous_group_state=JSON.stringify(panel.workbench.groups_state);panel.switch_repo(${JSON.stringify(clone)})`);
 assert(await run('JSON.stringify(panel.workbench.groups_state)===previous_group_state'),'clone has identical HEAD and changed paths');
 assert(await run('panel.workbench.groups.firstElementChild!==previous_groups&&!!panel.workbench.groups.querySelector(".git-scm-directory")&&!panel.workbench.groups.querySelector("[data-scm-group=changes]").open'),'repository switch applies its own tree and collapsed groups despite equal resources');
 await run(`panel.switch_repo(${JSON.stringify(repo)})`);assert(await run('!panel.workbench.tree&&!panel.workbench.groups.querySelector(".git-scm-directory")&&panel.workbench.groups.querySelector("[data-scm-group=changes]").open'),'switching back restores original repository layout');
 await run('panel.selected=panel.state.commits[0].hash;panel.show_comparison(panel.state.commits[0].parents[0],panel.selected)');
 await wait('!panel.pending');await run('block="diff";window.late_detail=panel.show_comparison(panel.state.commits[0].parents[0],panel.selected);void 0');await wait('!!release');await run('window.before_dispose={cancels,write_cancels,epoch:panel.epoch,detail:panel.detail_epoch};panel.dispose();window.disposed_html=panel.container.outerHTML;release()');await run('late_detail');assert(await run('cancels>before_dispose.cancels&&write_cancels>before_dispose.write_cancels'),'dispose cancels read and write runners');assert(await run('panel.epoch>before_dispose.epoch&&panel.detail_epoch>before_dispose.detail'),'dispose invalidates history and detail requests');assert(await run('!panel.container.isConnected&&panel.container.outerHTML===disposed_html&&panel.state===undefined&&panel.files.length===0'),'late comparison cannot restore disposed state or DOM');
 await run('panel.open()');assert(await run('!panel.active'),'disposed panel cannot reopen');
 await run(`window.second=new qa.git_graph_panel(test_host,${JSON.stringify(repo)});document.body.append(second.container);block='log';window.second_task=second.refresh(false);void 0`);await wait('!!release');
 await run('window.history_epoch=second.epoch;second.dispose();window.history_html=second.container.outerHTML;release()');
 await run('second_task');
 assert(await run('second.epoch>history_epoch&&second.state===undefined&&!second.loaded&&!second.container.isConnected&&second.container.outerHTML===history_html'),'late history result cannot restore a disposed panel');

 console.log('Git Graph visibility PASS: gated real Git load, pending and loaded tab switches, retained DOM/scroll/filter, explicit refresh, disposal and late detail rejection. '+temp);window.destroy();app.exit(0);
}).catch(error=>{console.error(error);window?.destroy();app.exit(1)});
