// 根据 Typora 1.14.9 的原生选择器与盒模型验证大纲；不读取或修改安装目录。
const {app, BrowserWindow} = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {build} = require('esbuild');
const evidence = fs.mkdtempSync(path.join(os.tmpdir(), 'typora_workspace_outline_'));
app.setPath('userData', path.join(evidence, 'user_data'));
app.disableHardwareAcceleration();
let test_window;
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const evaluate = source => test_window.webContents.executeJavaScript(source);
const checks = [];
const check = (condition, label) => {assert(condition, label); checks.push(label);};
const capture = async name => fs.writeFileSync(path.join(evidence, name + '.png'), (await test_window.webContents.capturePage()).toPNG());
const click = async selector => {
  const point = await evaluate(`(()=>{const rect=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.round(rect.left+rect.width/2),y:Math.round(rect.top+rect.height/2)}})()`);
  for (const type of ['mouseMove', 'mouseDown', 'mouseUp']) test_window.webContents.sendInputEvent({type, ...point, button:'left', clickCount:1});
  await delay(80);
};
app.whenReady().then(async () => {
  test_window = new BrowserWindow({show:false, width:760, height:580, webPreferences:{contextIsolation:false, offscreen:true, backgroundThrottling:false}});
  const html = path.join(evidence, 'test.html');
  fs.writeFileSync(html, `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;height:100%;font:16px/1.4 system-ui}body{display:flex}aside{width:48px;background:#eee;flex:none}#typora-sidebar{width:280px;background:#f7f7f7;flex:none}#sidebar-content{display:flex;flex-direction:column;height:100%}.outline-content{padding:3px 18px;overflow-x:hidden;max-width:100%;flex:auto;overflow-y:auto}.outline-content li,.outline-content ul{margin-left:0;margin-right:0;padding-left:0;padding-right:0;list-style:none;overflow-wrap:anywhere}.outline-content ul{margin-top:0;margin-bottom:0}.outline-item{padding-top:3px;padding-bottom:3px;cursor:pointer}.outline-expander{width:1rem;height:1.428571429rem;position:relative;display:table-cell;vertical-align:middle;cursor:pointer;padding-left:4px}.outline-expander:before{content:'›';font-size:12px}.outline-item-open>.outline-item>.outline-expander:before{content:'⌄'}.outline-h1>.outline-item{padding-left:0}.outline-h2>.outline-item{padding-left:1em}.outline-h3>.outline-item{padding-left:2em}.outline-label{display:table-cell;vertical-align:middle}.outline-item:hover{margin-left:-28px;margin-right:-28px;border-left:28px solid transparent;border-right:28px solid transparent;background:#ddd}.outline-children{display:none}.outline-item-open>.outline-children{display:block}#file-library-search{height:0;overflow:hidden}.ty-show-outline-filter #file-library-search,.ty-show-search #file-library-search{height:50px}.ty-on-outline-filter .outline-item:not(.matched){display:none}.ty-on-outline-filter .outline-expander{display:none}#outline-menu{position:absolute;bottom:0;left:400px;list-style:none;background:#eee;padding:6px}#outline-menu>.divider{height:1px;background:#999;margin:4px 0}#toc-content{position:absolute;left:360px;top:0;width:240px;height:100px}content{display:block;flex:1;min-width:0;height:100%;overflow:auto}main{padding:140px 25px 0;min-height:100%;box-sizing:border-box}#outline-content{height:100%;line-height:1.1rem}.workspace-search-query{display:block;width:160px}
  </style><aside></aside><section id="typora-sidebar" class="active-tab-outline ty-show-outline-filter ty-on-outline-filter"><div id="sidebar-content"><div id="file-library-search"><div id="file-library-search-panel"><input id="file-library-search-input" value="old" style="width:calc(100% - 18px)"><span id="close-outline-filter-btn">×</span></div></div><div id="outline-content" class="outline-content"><li class="outline-item-wrapper outline-h1 outline-item-open"><div class="outline-item matched" id="heading_1"><span class="outline-expander"></span><span class="outline-label">源代码阅读</span></div><ul class="outline-children"><li class="outline-item-wrapper outline-h2 outline-item-open"><div class="outline-item" id="heading_2"><span class="outline-expander"></span><span class="outline-label">Tiny RCU 队列</span></div><ul class="outline-children"><li class="outline-item-wrapper outline-h3"><div class="outline-item" id="heading_3"><span class="outline-expander"></span><span class="outline-label">local_irq_save 与原始状态保存</span></div></li></ul></li></ul></li></div></div></section><div id="toc-content" class="outline-content">正文目录弹层保持原样</div><content><main id="write">正文内容不变。</main></content><ul id="outline-menu"><li data-action="highlight">高亮当前标题</li><li class="divider"></li><li data-action="filter">筛选</li><li class="divider" data-collapse></li><li data-action="collapse-all">全部折叠</li></ul>`);
  await test_window.loadFile(html);
  const bundle = await build({stdin:{contents:'export {install_workspace_outline} from "./src/workspace_outline";', resolveDir:path.join(__dirname,'..')},plugins:require('./editor_bundle.cjs').editor_plugins(),bundle:true,loader:{'.css':'text'},format:'iife',globalName:'outline_qa',write:false});
  await evaluate(bundle.outputFiles[0].text);
  const initial_padding = await evaluate('getComputedStyle(document.querySelector("#outline-content")).paddingLeft');
  check(initial_padding === '18px', 'fixture reproduces the native 18px outline outer padding');
  await evaluate(`(()=>{
    window.sidebar=document.querySelector('#typora-sidebar');window.hide_count=0;window.clear_count=0;window.filter_shown=true;window.selected='';window.original_text=document.querySelector('#write').textContent;
    window.highlight_count=0;window.highlight_args=[];window.native_auto_calls=0;
    // 安装前已存在的原生方法：默认选首个可见标题，显式数组则严格采用调用方给定标题。
    // 入口函数保持不变，测试只切换实现，避免绕过产品安装的协调代理。
    window.native_highlight_impl=function(headings,index,expand,blink){
      highlight_count++;highlight_args=[headings,index,expand,blink];
      const pane=document.querySelector('#outline-content'),content=document.querySelector('content'),visible_top=content.getBoundingClientRect().top;
      const all=[...document.querySelectorAll('#write > :is(h1,h2,h3,h4,h5,h6)')];
      const heading=headings?.[index||0]||all.find(node=>node.getBoundingClientRect().top>=visible_top)||all.at(-1);
      const label=[...pane.querySelectorAll('.outline-label')].find(node=>node.dataset.ref===heading?.getAttribute('cid'));
      if(!label)return;
      pane.querySelectorAll('.outline-active,.outline-item-active').forEach(node=>node.classList.remove('outline-active','outline-item-active'));
      label.classList.add('outline-active');label.parentElement.classList.add('outline-item-active');
      if(expand)for(let wrapper=label.closest('.outline-item-wrapper');wrapper&&pane.contains(wrapper);wrapper=wrapper.parentElement?.closest('.outline-item-wrapper'))wrapper.classList.add('outline-item-open');
    };
    window.original_native_highlight=function(...args){return native_highlight_impl.apply(this,args)};
    window.native_outline={highlightVisibleHeader:original_native_highlight,isSearchShown:()=>filter_shown,hideSearch(){hide_count++;filter_shown=false;sidebar.classList.remove('ty-show-outline-filter');},clearSearch(){clear_count++;sidebar.classList.remove('ty-on-outline-filter');document.querySelectorAll('.ty-outline-hit').forEach(node=>node.replaceWith(...node.childNodes));}};
    window.simulate_native_scroll=top=>{const content=document.querySelector('content');content.scrollTop=top;content.dispatchEvent(new Event('scroll'));setTimeout(()=>{native_auto_calls++;native_outline.highlightVisibleHeader()},100)};
    window.outline=outline_qa.install_workspace_outline({sidebar,outline:native_outline});
    document.querySelectorAll('.outline-expander').forEach(node=>node.onclick=()=>node.closest('.outline-item-wrapper').classList.toggle('outline-item-open'));
    document.querySelectorAll('.outline-label').forEach(node=>node.onclick=()=>{selected=node.textContent});
    window.metrics=()=>{const pane=document.querySelector('#outline-content'),rect=pane.getBoundingClientRect();return{padding:getComputedStyle(pane).paddingLeft,scroll:pane.scrollWidth,client:pane.clientWidth,offsets:[...document.querySelectorAll('#outline-content .outline-expander')].map(node=>node.getBoundingClientRect().left-rect.left),filter:getComputedStyle(document.querySelector('#file-library-search')).display,popup:getComputedStyle(document.querySelector('#toc-content')).paddingLeft};};
  })()`);
  await delay(100);
  check(await evaluate('hide_count===1&&clear_count===1&&!filter_shown&&!sidebar.classList.contains("ty-on-outline-filter")'), 'native hideSearch and clearSearch clear old filtering state');
  check(await evaluate('document.querySelector("#file-library-search-input").value===""&&getComputedStyle(document.querySelector("#close-outline-filter-btn")).display==="none"'), 'old filter text and close button are cleared');
  const compact = await evaluate('metrics()');
  check(compact.padding === '0px' && compact.offsets[0] === 0, 'first heading expander starts at the outline edge without outer blank space');
  check(compact.offsets[1]-compact.offsets[0] === 16 && compact.offsets[2]-compact.offsets[1] === 16, 'second and third heading levels preserve native one-em indentation');
  check(compact.filter === 'none' && compact.popup === '18px', 'outline filter is hidden while the document TOC popup retains its padding');
  check(await evaluate('getComputedStyle(document.querySelector("#outline-menu>[data-action=filter]")).display==="none"&&getComputedStyle(document.querySelector("#outline-menu>.divider")).display==="none"&&getComputedStyle(document.querySelector("#outline-menu>[data-action=collapse-all]")).display!=="none"'), 'only the outline filter menu and its separator are hidden');
  const arrow_visible=id=>evaluate(`getComputedStyle(document.querySelector('#${id} .outline-expander svg')).visibility!=='hidden'`);
  check(await arrow_visible('heading_1')&&await arrow_visible('heading_2')&&!await arrow_visible('heading_3'),'only headings with actual child headings show expansion arrows');
  const leaf_slot=await evaluate('document.querySelector("#heading_3 .outline-expander").getBoundingClientRect().width');
  check(leaf_slot>0,'leaf heading retains its indentation slot while the arrow is hidden');
  await evaluate(`window.dynamic_children=document.createElement('ul');dynamic_children.className='outline-children';dynamic_children.innerHTML='<li class="outline-item-wrapper"><div class="outline-item"><span class="outline-expander"></span><span class="outline-label">Dynamic child</span></div></li>';document.querySelector('#heading_3').parentElement.append(dynamic_children)`);await delay(50);
  check(await arrow_visible('heading_3'),'adding a child heading makes its parent arrow visible');
  await evaluate('dynamic_children.remove()');await delay(50);
  check(!await arrow_visible('heading_3'),'removing the last child hides the arrow without removing the heading');
  await evaluate('sidebar.classList.remove("active-tab-outline");sidebar.classList.add("active-tab-outline")');await delay(50);
  check(!await arrow_visible('heading_3'),'reopening Outline does not resurrect a leaf arrow');
  await click('#heading_1 .outline-expander');
  check(await evaluate('getComputedStyle(document.querySelector("#heading_1").nextElementSibling).display==="none"'), 'native expander still collapses nested headings');
  await click('#heading_1 .outline-expander');await click('#heading_3 .outline-label');
  check(await evaluate('selected==="local_irq_save 与原始状态保存"'), 'native heading navigation remains clickable');
  await evaluate('filter_shown=true;sidebar.classList.add("ty-show-outline-filter","ty-on-outline-filter")');await delay(100);
  check(await evaluate('hide_count===2&&clear_count===2&&!sidebar.classList.contains("ty-show-outline-filter")'), 'a later native filter activation is cleared without leaving filtered headings');
  const idle = await evaluate('hide_count');await delay(100);check(await evaluate('hide_count') === idle, 'native class observer does not loop while idle');
  await evaluate('sidebar.style.width="220px"');await click('#heading_2');const narrow = await evaluate('metrics()');
  check(narrow.scroll === narrow.client && narrow.offsets[0] === 0, 'narrow outline hover does not overflow or restore the outer gap');
  await evaluate(`(()=>{
    const write=document.querySelector('#write'), pane=document.querySelector('#outline-content'), content=document.querySelector('content');
    write.innerHTML=Array.from({length:40},(_,index)=>'<h'+(index%3+1)+' cid="sync_'+index+'" style="height:90px;margin:0">Heading '+index+'</h'+(index%3+1)+'>').join('');
    const children=Array.from({length:39},(_,index)=>'<li class="outline-item-wrapper outline-h2"><div class="outline-item"><span class="outline-expander"></span><span class="outline-label" data-ref="sync_'+(index+1)+'">Heading '+(index+1)+'</span></div></li>').join('');
    window.rebuild_outline=()=>{pane.innerHTML='<li class="outline-item-wrapper outline-h1"><div class="outline-item"><span class="outline-expander"></span><span class="outline-label" data-ref="sync_0">Heading 0</span></div><ul class="outline-children">'+children+'</ul></li>';};
    rebuild_outline(); content.scrollTop=2350;
    // #write 有 140px 顶部内边距；2350 时 Heading 25 完整出现在屏幕顶部下方 40px。
    window.expected_cid='sync_25';
    window.highlight_count=0;window.highlight_args=[];
    pane.scrollTop=0;window.document_scroll_before=content.scrollTop;sidebar.classList.add('open');
  })()`);
  await delay(120);
  check(await evaluate('highlight_count===1&&highlight_args[0]?.length===1&&highlight_args[0][0].getAttribute("cid")===expected_cid&&highlight_args[1]===0&&highlight_args[2]===true'), 'opening passes the single coordinated current heading to the original native method');
  const opening_sync=await evaluate(`(()=>{const pane=document.querySelector('#outline-content'),active=pane.querySelector('.outline-label.outline-active'),row=active?.parentElement,rect=row?.getBoundingClientRect(),bounds=pane.getBoundingClientRect();return{actual:active?.dataset.ref,expected:expected_cid,row_active:row?.classList.contains('outline-item-active'),expanded:active?.closest('.outline-h1').classList.contains('outline-item-open'),top:rect?.top,bottom:rect?.bottom,pane_top:bounds.top,pane_bottom:bounds.bottom};})()`);
  check(opening_sync.actual===opening_sync.expected&&opening_sync.row_active&&opening_sync.expanded&&opening_sync.top>=opening_sync.pane_top-1&&opening_sync.bottom<=opening_sync.pane_bottom+1, 'opening selects, expands and reveals the heading at the current document position: '+JSON.stringify(opening_sync));
  check(await evaluate('document.querySelector("content").scrollTop===document_scroll_before'), 'revealing the outline heading does not move the document');
  check(await evaluate('highlight_args[3]===false'), 'scroll synchronization explicitly disables native blinking');
  await evaluate('document.querySelector("#write").tabIndex=0;document.querySelector("#write").focus({preventScroll:true});window.body_focus=document.activeElement;window.old_label=document.querySelector("#outline-content .outline-active");window.scroll_mutations=0;window.scroll_observer=new MutationObserver(records=>scroll_mutations+=records.length);scroll_observer.observe(document.querySelector("#outline-content"),{subtree:true,childList:true,attributes:true});highlight_count=0;');
  for(let index=0;index<8;index++){await evaluate('simulate_native_scroll(document.querySelector("content").scrollTop+1)');await delay(40);}await delay(170);
  check(await evaluate('native_auto_calls===8&&highlight_count===0&&scroll_mutations===0&&old_label===document.querySelector("#outline-content .outline-active")'), 'scrolling inside one heading and delayed native 100ms callbacks preserve one active node without class rewrites');
  const scroll_to=async top=>{await evaluate(`simulate_native_scroll(${top})`);await delay(180);check(await evaluate(`document.querySelector('content').scrollTop===${top}&&document.activeElement===body_focus`),'outline synchronization preserves document position and focus at '+top);};
  for(const top of [2388,2392,2387,2394])await scroll_to(top);
  check(await evaluate('highlight_count===0&&scroll_mutations===0&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'), 'adjacent H1/H2 boundary micro-motion within a few pixels cannot alternate active rows');
  await scroll_to(2404);
  check(await evaluate('highlight_count===1&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_26"'), 'crossing beyond the downward boundary updates once despite the later native callback');
  const crossed_mutations=await evaluate('scroll_mutations');
  for(const top of [2393,2388,2391,2386])await scroll_to(top);
  check(await evaluate('highlight_count===1&&scroll_mutations==='+crossed_mutations+'&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_26"'), 'reverse micro-motion retains the selected adjacent H2 without rewriting its classes');
  await scroll_to(2376);
  check(await evaluate('highlight_count===2&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'), 'crossing beyond the upward boundary updates exactly once');
  await evaluate('scroll_observer.disconnect()');
  await scroll_to(2470);
  await evaluate('window.explicit_target=[document.querySelector("#write > [cid=sync_26]")];native_outline.highlightVisibleHeader(explicit_target,0,true,false);window.explicit_call_count=highlight_count;setTimeout(()=>native_outline.highlightVisibleHeader(),100)');await delay(180);
  check(await evaluate('highlight_args[0]===explicit_target&&highlight_args[1]===0&&highlight_args[2]===true&&highlight_args[3]===false&&highlight_count===explicit_call_count&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_26"'), 'explicit native heading targets keep their arguments and survive delayed auto-highlighting at the same scroll position');
  await scroll_to(2471);
  check(await evaluate('highlight_count===explicit_call_count&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_26"'), 'a native jump positioned 10px below the top retains its target through a 1px micro-scroll');
  await evaluate('native_outline.highlightVisibleHeader(undefined,undefined,true,true);window.manual_call_count=highlight_count;setTimeout(()=>native_outline.highlightVisibleHeader(),100)');await delay(180);
  check(await evaluate('highlight_args[0]===undefined&&highlight_args[1]===undefined&&highlight_args[2]===true&&highlight_args[3]===true&&highlight_count===manual_call_count'), 'manual native blink requests preserve original arguments without later automatic takeover');
  check(await evaluate('document.querySelector("content").scrollTop===2471&&document.activeElement===body_focus'),'explicit and manual outline highlighting leave document scroll and focus unchanged');
  await evaluate('scroll_observer.disconnect();document.querySelector("content").scrollTop=document_scroll_before;');
  await evaluate('highlight_count=0;rebuild_outline();rebuild_outline();'); await delay(120);
  check(await evaluate('highlight_count===1&&document.querySelector("#outline-content .outline-active")?.dataset.ref===expected_cid'), 'multiple outline child-list rebuilds coalesce into one native synchronization');
  await evaluate('sidebar.classList.remove("active-tab-outline");native_outline.highlightVisibleHeader();void 0');
  check(await evaluate('document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'),'native auto-highlighting outside Outline retains its first-visible-heading behavior');
  await evaluate('sidebar.classList.add("active-tab-outline")');await delay(120);
  check(await evaluate('document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'),'opening Outline does not inherit a false explicit anchor from another sidebar view');
  await evaluate('highlight_count=0;native_outline.highlightVisibleHeader([]);void 0');await delay(150);
  check(await evaluate('highlight_count===0&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'),'empty delayed native target arrays use automatic coordination without clearing or repainting the current heading');
  await evaluate('window.detached_heading=document.createElement("h2");detached_heading.setAttribute("cid","sync_3");native_outline.highlightVisibleHeader([detached_heading],0,true,false);void 0');await delay(150);
  check(await evaluate('highlight_count===0&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_25"'),'a delayed target from a detached document cannot select its old matching outline label');
  await evaluate('window.pending_click_target=document.querySelector("#write > [cid=sync_26]");setTimeout(()=>native_outline.highlightVisibleHeader([pending_click_target],0,true,false),500)');
  await scroll_to(3022);
  check(await evaluate('highlight_count===1&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_33"'),'dragging across multiple chapters selects the readable destination heading immediately');
  await delay(380);await evaluate('native_outline.highlightVisibleHeader();void 0');await delay(150);
  check(await evaluate('highlight_count===1&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_33"&&document.querySelector("content").scrollTop===3022'),'a 500ms click callback for an offscreen heading in the same document cannot overwrite and lock the new reading position');
  await scroll_to(2530);
  await evaluate('window.partial_call_count=highlight_count;native_outline.highlightVisibleHeader([pending_click_target],0,true,false);void 0');await delay(150);
  check(await evaluate('highlight_count===partial_call_count&&document.querySelector("#outline-content .outline-active")?.dataset.ref==="sync_27"'),'an old click target whose top has left the reading buffer cannot reclaim selection merely because its bottom still intersects the screen');
  await scroll_to(2350);
  check(await evaluate('document.querySelector("#outline-content .outline-active")?.dataset.ref===expected_cid'),'large reverse jumps follow the destination chapter without keeping an old explicit target');
  await evaluate(`(()=>{
    const write=document.querySelector('#write');window.dense_headings=write.innerHTML;
    write.innerHTML='<h2 cid="sync_0" style="height:40px;margin:0">Previous chapter</h2><p style="height:1000px;margin:0">Long introduction</p><h2 cid="sync_1" style="height:40px;margin:0">Visible table chapter</h2><table style="height:900px"><tr><td>Long table</td></tr></table><h2 cid="sync_2" style="height:40px;margin:0">Following chapter</h2><h3 cid="sync_3" style="height:40px;margin:0">Child chapter</h3><p style="height:1000px;margin:0">Long body</p><h2 cid="sync_4" style="height:40px;margin:0">Final short chapter</h2><p style="height:60px;margin:0">End.</p>';
    window.overlapping_footer=document.createElement('footer');overlapping_footer.className='ty-footer';overlapping_footer.style.cssText='position:fixed;left:268px;right:0;bottom:0;height:32px;background:white;z-index:4';overlapping_footer.textContent='Native footer';document.body.append(overlapping_footer);
    rebuild_outline();simulate_native_scroll(200);
  })()`);await delay(180);
  const selected_is=async(cid,label)=>check(await evaluate(`document.querySelector('#outline-content .outline-active')?.dataset.ref==='sync_${cid}'`),label);
  const heading_at=async(cid,position)=>{
    const top=await evaluate(`(()=>{const content=document.querySelector('content'),rect=document.querySelector('#write > [cid=sync_${cid}]').getBoundingClientRect();return Math.round(content.scrollTop+rect.top-content.getBoundingClientRect().top-(${position}));})()`);
    await scroll_to(top);
  };
  await selected_is(0,'long text without a visible heading keeps the containing chapter');
  await heading_at(1,"document.querySelector('content').clientHeight-3");
  await selected_is(0,'a heading with only a 3px sliver at the bottom does not steal selection');
  await heading_at(1,"document.querySelector('content').clientHeight-54");
  await selected_is(0,'a heading partly covered by the native footer is not mistaken for a fully readable title');
  await heading_at(1,"document.querySelector('content').clientHeight-86");
  await selected_is(1,'a fully readable heading near the bottom selects before reaching the viewport top');
  await heading_at(1,"document.querySelector('content').clientHeight/2");
  await selected_is(1,'a chapter heading at screen center is selected while its preceding paragraph remains visible');
  await capture('visible_table_heading');
  for(const position of [3,-3,4,-4])await heading_at(1,position);
  await selected_is(1,'a selected heading near the top survives small wheel reversals');
  await heading_at(1,-100);
  await selected_is(1,'a long table with no readable heading retains its own chapter');
  await heading_at(2,"document.querySelector('content').clientHeight/2");
  await selected_is(2,'the next heading takes over in the middle of a long table page');
  await heading_at(2,-16);
  await selected_is(3,'a child heading takes over after the preceding heading exits the top buffer');
  await heading_at(2,3);
  await selected_is(3,'a few pixels of reverse scrolling do not select the earlier adjacent heading again');
  await heading_at(2,20);
  await selected_is(2,'scrolling up selects an earlier heading when it fully reenters the readable viewport');
  await evaluate('simulate_native_scroll(document.querySelector("content").scrollHeight)');await delay(180);
  await selected_is(4,'the last short chapter is selected even when it cannot be scrolled to the screen top');
  await evaluate('overlapping_footer.remove();document.querySelector("#write").innerHTML=dense_headings;rebuild_outline();simulate_native_scroll(2350)');await delay(180);
  await evaluate('outline.dispose()');
  check(await evaluate('native_outline.highlightVisibleHeader===original_native_highlight'),'dispose restores the exact native highlight function installed before binding');
  await evaluate('window.outline=outline_qa.install_workspace_outline({sidebar,outline:{hideSearch:native_outline.hideSearch,clearSearch:native_outline.clearSearch,isSearchShown:native_outline.isSearchShown}});rebuild_outline();document.querySelector("#outline-content").scrollTop=0;'); await delay(120);
  check(await evaluate(`(()=>{const pane=document.querySelector('#outline-content'),active=pane.querySelector('.outline-label.outline-active'),row=active?.parentElement,rect=row?.getBoundingClientRect(),bounds=pane.getBoundingClientRect();return active?.dataset.ref===expected_cid&&row.classList.contains('outline-item-active')&&active.closest('.outline-h1').classList.contains('outline-item-open')&&rect.top>=bounds.top-1&&rect.bottom<=bounds.bottom+1;})()`), 'missing native API uses the same cid-based selection, expansion and reveal semantics');
  check(await evaluate('document.querySelector("content").scrollTop===document_scroll_before'), 'DOM fallback also leaves the document scroll position unchanged');
  await evaluate(`(()=>{const content=document.querySelector('content');content.scrollTop=450;window.scroll_expected_cid='sync_4';window.scrolled_document_position=content.scrollTop;content.dispatchEvent(new Event('scroll'));})()`); await delay(120);
  check(await evaluate('scroll_expected_cid!==expected_cid&&document.querySelector("#outline-content .outline-label.outline-active")?.dataset.ref===scroll_expected_cid'), 'an open outline follows the first readable heading inside the viewport');
  check(await evaluate('document.querySelector("content").scrollTop===scrolled_document_position'), 'scroll-driven outline synchronization preserves the new document position');
  await evaluate('document.querySelector("#write").textContent=original_text;sidebar.classList.remove("open")');
  await capture('compact_outline');
  await evaluate('sidebar.classList.remove("active-tab-outline");const panel=document.createElement("section");panel.className="linux-note-workspace-search";panel.innerHTML="<textarea class=workspace-search-query>当前搜索</textarea>";document.querySelector("#sidebar-content").append(panel);');
  check(await evaluate('getComputedStyle(document.querySelector(".workspace-search-query")).display!=="none"'), 'workspace search input is not hidden by outline rules');
  check(await evaluate('document.querySelector("#write").textContent===original_text'), 'outline cleanup leaves document text unchanged');
  check(await evaluate('[...document.querySelectorAll("#outline-content .outline-expander")].every(node=>node.querySelector("svg")?.dataset.gitIcon==="chevron-right"&&getComputedStyle(node,"::before").content==="none")'),'native outline expanders use official Codicons without duplicate pseudo glyphs');
  await evaluate('outline.dispose()');
  check(await evaluate('!document.querySelector("#outline-content .workspace-official-icon-slot")&&!document.querySelector("#outline-content .outline-expander svg")'),'dispose restores untouched native expander nodes');
  check(await evaluate('getComputedStyle(document.querySelector("#outline-content")).paddingLeft==="18px"&&!document.querySelector("[data-workspace-outline-style]")'), 'dispose removes outline-only layout and observers');
  await evaluate('document.querySelector("#write").innerHTML="<h2 cid=sync_4>Destination heading</h2>";window.native_pane=document.querySelector("#outline-content");window.native_parent=native_pane.parentNode;window.document_active=true;window.native_binding=outline_qa.install_workspace_outline({sidebar,document_active:()=>document_active,outline:native_outline});native_pane.querySelectorAll(".outline-active").forEach(node=>node.classList.remove("outline-active"));document.querySelector("content").dispatchEvent(new Event("scroll"));');await delay(80);
  check(await evaluate('!native_pane.querySelector(".outline-active")'), 'a closed native outline does not claim a current visible heading');
  await evaluate('sidebar.classList.add("open","active-tab-outline");native_binding.refresh()');await delay(120);
  check(await evaluate('native_pane.querySelector(".outline-active")?.dataset.ref===scroll_expected_cid&&native_pane.parentNode===native_parent&&document.querySelectorAll("#outline-content").length===1'), 'opening standalone Outline synchronizes the destination in the same native tree');
  await evaluate('window.preserved_scroll=document.querySelector("content").scrollTop;document_active=false;native_binding.refresh()');
  check(await evaluate('getComputedStyle(native_pane).display==="none"&&getComputedStyle(document.querySelector(".workspace-outline-empty")).display!=="none"'), 'source documents hide stale Markdown headings and show the native view empty state');
  await evaluate('sidebar.classList.remove("active-tab-outline");native_binding.refresh()');
  check(await evaluate('getComputedStyle(document.querySelector(".workspace-outline-empty")).display==="none"'), 'Outline empty state does not leak into another sidebar view');
  await evaluate('document_active=true;sidebar.classList.add("active-tab-outline");native_binding.refresh()');await delay(100);
  check(await evaluate('document.querySelector("content").scrollTop===preserved_scroll&&native_pane.parentNode===native_parent'), 'switching sidebar views preserves reading position and native tree ownership');
  await evaluate('native_binding.dispose();native_binding.dispose();native_binding.refresh()');check(await evaluate('native_pane.parentNode===native_parent&&!document.querySelector(".workspace-outline-empty")&&!sidebar.hasAttribute("data-document-outline")&&native_outline.highlightVisibleHeader===original_native_highlight'), 'idempotent Outline disposal leaves the native tree, clears owned state and restores native highlighting');
  console.log(JSON.stringify({status:'PASS',checks,compact,narrow,evidence}));test_window.destroy();app.exit(0);
}).catch(async error=>{console.error(error);console.error(evidence);if(test_window&&!test_window.isDestroyed()){await capture('failure');test_window.destroy();}app.exit(1);});
