import assert from "node:assert/strict";
import fs from "node:fs";
import { transform } from "esbuild";

const compiled = await transform(fs.readFileSync('src/reading_history.ts', 'utf8'), { loader: 'ts', format: 'esm' });
const { create_reading_history } = await import(`data:text/javascript;base64,${Buffer.from(compiled.code).toString('base64')}`);
const location = (file_path, scroll_top) => ({ file_path, scroll_top, scroll_left: 0, cursor: null });
const history = create_reading_history(3);
let current = location('chapter_a.md', 10);
const restore = async (target) => { current = target; return true; };
assert.equal(await history.travel(-1, current, restore), false);
history.record_jump(current, location('chapter_a.md', 800));
current = location('chapter_a.md', 920);
assert.equal(await history.travel(-1, current, restore), true);
assert.equal(current.scroll_top, 10);
assert.equal(await history.travel(1, current, restore), true);
assert.equal(current.scroll_top, 920, '前进恢复离开目标时的阅读位置');
history.record_jump(current, location('chapter_b.md', 50));
current = location('chapter_b.md', 50);
assert.equal(await history.travel(-1, current, async () => false), false, '取消文件打开');
assert.equal(await history.travel(-1, current, restore), true, '取消后历史索引不变');
assert.equal(current.file_path, 'chapter_a.md');
history.record_jump(current, location('chapter_c.md', 70));
current = location('chapter_c.md', 70);
assert.equal(await history.travel(1, current, restore), false, '新跳转清除旧前进分支');
await assert.rejects(history.travel(-1, current, async () => { throw new Error('open failed'); }));
assert.equal(await history.travel(-1, current, restore), true, '打开异常后可再次导航');
history.record_jump(current, current);
let finish;
const pending = history.travel(-1, current, () => new Promise((resolve) => { finish = resolve; }));
assert.equal(await history.travel(-1, current, restore), false, '导航期间不重复打开文件');
finish(false);
await pending;
console.log('reading history: anchors, files, scroll restoration, branching, cancellation and reentrancy passed');
