import {workspace_text} from "./workspace_i18n";
import {workspace_element as el,workspace_button as button,workspace_dialog} from './workspace_widgets';
import {acquire_workspace_style} from './workspace_styles';
import css from './source_outline_settings.css';
import {discover_language_environments,resolve_python_environment} from './language_environment';
import {discover_language_server} from './language_analysis_service';
import {read_language_service_profiles,save_language_service_profiles,type language_service_profile} from './language_service_settings';
let current_dialog:ReturnType<typeof workspace_dialog>|undefined;
/** The form only holds a draft; JSON and dropdown share the configuration owner, and both cancellation and staleness discoveries are not written. */
export function open_language_service_settings(root:string,current_root:()=>string=()=>root){
 current_dialog?.close();let closed=false,generation=0;
 const dialog=workspace_dialog(workspace_text("language_service_settings_view_select_language_services_and_environment"),workspace_text("language_service_settings_view_cancel"),()=>{closed=true;generation++;style.remove();if(current_dialog===dialog)current_dialog=undefined;},{focus_out:false});current_dialog=dialog;
 dialog.root.classList.add('source-outline-settings');const style=acquire_workspace_style('typora-code-source-outline-settings',css,{},dialog.root);
 const field=<T extends 'input'|'select'|'textarea'>(tag:T,name:string,title:string,hint='')=>{const label=el('label','source-outline-settings-field'),input=el(tag);input.dataset.field=name;input.setAttribute('aria-label',title);label.append(el('span','',title),input);if(hint)label.append(el('small','',hint));dialog.content.append(label);return input;};
 const language=field('select','language',workspace_text("language_service_settings_view_language"));for(const [id,name] of Object.entries({c:'C',cpp:'C++',python:'Python',java:'Java',shell:'Bash / Shell',powershell:'PowerShell',csharp:'C#',rust:'Rust',javascript:'JavaScript',typescript:'TypeScript'}))language.append(new Option(name,id));
 const scope=field('select','scope',workspace_text("language_service_settings_view_configuration_scope"));scope.append(new Option(workspace_text("language_service_settings_view_current_workspace"),'workspace'),new Option(workspace_text("language_service_settings_view_all_workspaces_user"),'user'));if(!root){scope.value='user';scope.options[0].disabled=true;}
 const provider=field('select','provider',workspace_text("language_service_settings_view_analysis_mode"));for(const [id,name] of Object.entries({default:workspace_text("language_service_settings_view_default_parser"),lsp:workspace_text("language_service_settings_view_external_language_service_lsp"),disabled:workspace_text("language_service_settings_view_disable_analysis_keep_basic_highlighting")}))provider.append(new Option(name,id));
 const candidates=field('select','environment',workspace_text("language_service_settings_view_detected_program"),workspace_text("language_service_settings_view_only_detect_environment_variables_and_common_locations_in_th"));
 const command=field('input','command',workspace_text("language_service_settings_view_path_to_the_language_service_or_runtime"),workspace_text("language_service_settings_view_you_can_manually_enter_an_absolute_path_to_the_executable_fi"));command.spellcheck=false;
 const picker=el('input');picker.type='file';picker.hidden=true;picker.accept='.exe';picker.onchange=()=>{try{const file=picker.files?.[0];if(!file)return;command.value=(file as any).path||(window as any).reqnode('electron').webUtils.getPathForFile(file);provider.value='lsp';}catch(error){report(String(error));}};
 dialog.content.append(button(workspace_text("language_service_settings_view_select_the_program_file"),()=>picker.click()),picker);
 const venv=field('input','venv',workspace_text("language_service_settings_view_python_virtual_environment_directory"),workspace_text("language_service_settings_view_relative_directory_is_parsed_according_to_the_current_projec"));
 const use_venv=button(workspace_text("language_service_settings_view_use_this_virtual_environment"),()=>{const request=++generation;void resolve_python_environment(venv.value,root).then(file=>{if(closed||request!==generation)return;command.value=file;args.value=JSON.stringify(['-m','pylsp']);provider.value='lsp';report(workspace_text("language_service_settings_view_the_interpreter_has_been_selected_please_confirm_that_this_e"));}).catch(error=>{if(!closed&&request===generation)report(String(error.message||error));});});dialog.content.append(use_venv);
 const args=field('textarea','args',workspace_text("language_service_settings_view_start_parameters_json_array"),workspace_text("language_service_settings_view_for_example_python_is_m_pylsp_java_fills_in_jdt_ls_start_par"));args.rows=3;
 const initialization=field('textarea','initialization_options',workspace_text("language_service_settings_view_initialization_options_json_object"));initialization.rows=3;
 const settings=field('textarea','settings',workspace_text("language_service_settings_view_service_settings_json_object"));settings.rows=3;
 const status=el('p','source-outline-settings-status');status.setAttribute('role','status');dialog.content.append(status);const report=(text:string)=>{status.textContent=text;};
 const valid=()=>{if(current_root()!==root)throw Error(workspace_text("language_service_settings_view_the_workspace_has_been_switched_please_close_it_and_reconfig"));};
 const detect=async()=>{const request=++generation;candidates.replaceChildren(new Option(workspace_text("language_service_settings_view_detecting"),''));try{const values=await discover_language_environments(language.value,root);if(closed||request!==generation)return;candidates.replaceChildren(new Option(values.length?workspace_text("language_service_settings_view_select_the_detected_program"):workspace_text("language_service_settings_view_not_found_you_can_manually_enter_the_path"),''));for(const [index,item] of values.entries()){const option=new Option(`${{server:workspace_text("language_service_settings_view_language_service"),runtime:workspace_text("language_service_settings_view_runtime"),compiler:workspace_text("language_service_settings_view_compiler_command_line_tool")}[item.kind]} · ${item.source} · ${item.path}`,String(index));option.disabled=item.kind==='compiler';candidates.append(option);}candidates.onchange=()=>{const item=values[Number(candidates.value)];if(candidates.value===''||!item)return;command.value=item.path;args.value=JSON.stringify(item.args);if(language.value==='rust')settings.value=JSON.stringify({'rust-analyzer':{checkOnSave:false,cargo:{buildScripts:{enable:false}},procMacro:{enable:false}}},null,2);provider.value='lsp';report(item.kind==='server'?workspace_text("language_service_settings_view_the_language_service_has_been_selected_the_configuration_wil"):workspace_text("language_service_settings_view_the_runtime_has_been_selected_please_confirm_that_the_corres"));};}catch(error){if(!closed&&request===generation)report(String(error));}};
 const load=()=>{generation++;const value=read_language_service_profiles(root,scope.value as 'user'|'workspace')[language.value]||{provider:'default'};provider.value=value.provider;command.value=value.command||'';args.value=JSON.stringify(value.args||[],null,2);initialization.value=JSON.stringify(value.initialization_options||{},null,2);settings.value=JSON.stringify(value.settings||{},null,2);venv.value='';venv.parentElement!.hidden=language.value!=='python';use_venv.hidden=language.value!=='python';report(workspace_text("language_service_settings_view_selecting_a_program_will_not_be_saved_immediately_switching"));void detect();};
 language.onchange=load;scope.onchange=load;
 dialog.content.addEventListener('input',()=>{generation++;});
 for(const control of [provider,command,args,initialization,settings,venv,candidates])control.addEventListener('change',()=>{generation++;});
 const save=button(workspace_text("language_service_settings_view_save_configuration"),()=>{const request=++generation;void(async()=>{try{valid();const next:language_service_profile={provider:provider.value as language_service_profile['provider']};if(next.provider==='lsp'){next.command=command.value.trim();next.args=JSON.parse(args.value);next.initialization_options=JSON.parse(initialization.value);next.settings=JSON.parse(settings.value);await discover_language_server(next.command);}if(closed||request!==generation)return;valid();save_language_service_profiles(root,scope.value as 'user'|'workspace',{...read_language_service_profiles(root,scope.value as 'user'|'workspace'),[language.value]:next});report(workspace_text("language_service_settings_view_the_configuration_has_been_saved_the_current_file_will_be_re"));}catch(error){if(!closed&&request===generation)report(workspace_text("language_service_settings_view_save_failed")+String((error as Error).message||error));}})();},'source-outline-settings-save');save.dataset.action='save';
 const inherit=button(workspace_text("language_service_settings_view_restore_inheritance"),()=>{try{valid();const values={...read_language_service_profiles(root,scope.value as 'user'|'workspace')};delete values[language.value];save_language_service_profiles(root,scope.value as 'user'|'workspace',values);load();}catch(error){report(String(error));}});inherit.dataset.action='inherit';
 dialog.footer.prepend(button(workspace_text("language_service_settings_view_redetect"),()=>{void detect();}),inherit,save);load();return dialog;
}
