import {workspace_text} from "./workspace_i18n";
import {type workspace_dialog,workspace_element as el,workspace_button as button,workspace_option as option} from "./workspace_widgets";
import {terminal_defaults,type terminal_settings_store,type terminal_settings} from "./terminal_settings";

export function show_terminal_settings(store:terminal_settings_store,dialog:ReturnType<typeof workspace_dialog>){
  const form=el("div","terminal-settings-form"),filter=el("input");filter.placeholder=workspace_text("terminal_settings_view_search_terminal_settings");filter.setAttribute("aria-label",workspace_text("terminal_settings_view_search_terminal_settings"));
  const current=store.get(),inputs=new Map<keyof terminal_settings,HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>();
  const row=(key:keyof terminal_settings,label:string,control:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement,help="")=>{control.dataset.setting=key;control.setAttribute("aria-label",label);const label_node=el("label","terminal-setting",label);label_node.append(control);if(help)label_node.append(el("small","",help));form.append(label_node);inputs.set(key,control);};
  const profile=el("select"),detection_status=el("small");detection_status.setAttribute("role","status");
  const fill_profiles=(selected:string)=>{profile.replaceChildren(option("",workspace_text("terminal_settings_view_auto_select")));const profiles=store.profiles();for(const item of profiles)profile.append(option(item.id,item.title));
    if(selected&&!profiles.some(item=>item.id===selected))profile.append(option(selected,selected+workspace_text("terminal_settings_view_currently_unavailable")));profile.value=selected;detection_status.textContent=store.warnings().join(" ");};
  fill_profiles(current.profile);row("profile",workspace_text("terminal_settings_view_default_configuration"),profile);
  const detect=button(workspace_text("terminal_settings_view_re_detect_terminal"),()=>{detect.disabled=true;
    void store.refresh().then(()=>{if(dialog.root.isConnected)fill_profiles(profile.value);}).catch(failure=>{if(dialog.root.isConnected)error.textContent=String(failure instanceof Error?failure.message:failure);})
      .finally(()=>{if(dialog.root.isConnected)detect.disabled=false;});});profile.parentElement?.append(detect,detection_status);
  for(const[key,label,min,max,step]of [["font_size",workspace_text("terminal_settings_view_font_size"),6,100,1],["line_height",workspace_text("terminal_settings_view_line_height_multiplier"),1,3,0.1],["letter_spacing",workspace_text("terminal_settings_view_character_spacing"),-5,10,0.1],["cursor_width",workspace_text("terminal_settings_view_cursor_width"),1,10,1],["scrollback",workspace_text("terminal_settings_view_scroll_buffer_lines"),0,100000,1],["scroll_sensitivity",workspace_text("terminal_settings_view_wheel_speed"),0.1,20,0.1],["fast_scroll_sensitivity",workspace_text("terminal_settings_view_alt_wheel_speed_multiplier"),1,20,1],["minimum_contrast",workspace_text("terminal_settings_view_minimum_contrast"),1,21,0.5],["tab_stop_width",workspace_text("terminal_settings_view_tab_width"),1,32,1]]as const){const input=el("input");input.type="number";input.min=String(min);input.max=String(max);input.step=String(step);input.value=String(current[key]);row(key,label,input);}
  for(const[key,label,values]of [
    ["location",workspace_text("terminal_settings_view_default_terminal_position"),[["panel",workspace_text("terminal_settings_view_bottom_panel")],["editor",workspace_text("terminal_settings_view_editor_tab")]]],
    ["font_weight",workspace_text("terminal_settings_view_weight"),[["normal",workspace_text("terminal_settings_view_normal")],["bold",workspace_text("terminal_settings_view_bold")]]],
    ["cursor_style",workspace_text("terminal_settings_view_cursor_style"),[["block",workspace_text("terminal_settings_view_block")],["bar",workspace_text("terminal_settings_view_vertical_line")],["underline",workspace_text("terminal_settings_view_underline")]]],
    ["tabs_location",workspace_text("terminal_settings_view_session_list_location"),[["right",workspace_text("terminal_settings_view_right")],["left",workspace_text("terminal_settings_view_left")]]],
    ["tabs_hide",workspace_text("terminal_settings_view_auto_hide_session_list"),[["single_terminal",workspace_text("terminal_settings_view_when_only_one_terminal")],["single_group",workspace_text("terminal_settings_view_when_only_one_group")],["never",workspace_text("terminal_settings_view_never")]]],
    ["right_click",workspace_text("terminal_settings_view_right_click_operations"),[["menu",workspace_text("terminal_settings_view_show_menu")],["copy_paste",workspace_text("terminal_settings_view_copy_with_selection_otherwise_paste")],["paste",workspace_text("git_diff_editor_paste")]]],
    ["split_cwd",workspace_text("terminal_settings_view_split_workspace_directory"),[["initial",workspace_text("terminal_settings_view_inherit_initial_directory")],["workspace",workspace_text("terminal_settings_view_current_workspace_directory")]]],
  ]as const){const control=el("select");for(const[value,title]of values)control.append(option(value,title));control.value=current[key];row(key,label,control);}
  for(const[key,label]of [["cursor_blink",workspace_text("terminal_settings_view_cursor_blinking")],["smooth_scrolling",workspace_text("terminal_settings_view_smooth_scrolling")],["copy_on_selection",workspace_text("terminal_settings_view_select_and_copy")],["confirm_multiline",workspace_text("terminal_settings_view_confirm_before_paste_multiple_lines")]]as const){const control=el("input");control.type="checkbox";control.checked=current[key];row(key,label,control);}
  for(const[key,label]of [["font_family",workspace_text("terminal_settings_view_font_family")],["cwd",workspace_text("terminal_settings_view_default_workspace_directory")]]as const){const control=el("input");control.value=current[key];row(key,label,control,key==="cwd"?workspace_text("terminal_settings_view_leave_blank_to_use_current_workspace_relative_paths_start_fr"):"");}
  for(const[key,label,help]of [["env",workspace_text("terminal_settings_view_environment_variables_json"),workspace_text("terminal_settings_view_string_setting_variable_null_deletes_variable_changes_take_e")],["profiles",workspace_text("terminal_settings_view_custom_shell_configuration_json"),workspace_text("terminal_settings_view_each_item_includes_id_title_executable_args_can_attach_cwd_e")]]as const){const control=el("textarea");control.rows=key==="profiles"?10:4;control.value=JSON.stringify(current[key],null,2);control.spellcheck=false;row(key,label,control,help);}
  const example=el("details","terminal-profile-example"),summary=el("summary","",workspace_text("terminal_settings_view_configuration_example"));example.append(summary,el("pre","",JSON.stringify({id:"project_shell",title:workspace_text("terminal_settings_view_project_shell"),executable:"${env:SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe",args:["-NoLogo"],cwd:"${workspaceFolder}",env:{PROJECT_MODE:"dev"},icon:"terminal",color:"#007ACC"},null,2)));
  const error=el("p","terminal-settings-error");error.setAttribute("role","alert");dialog.content.append(filter,form,example,error);
  filter.oninput=()=>{for(const label of form.children)if(label instanceof HTMLElement)label.hidden=!label.textContent?.toLowerCase().includes(filter.value.toLowerCase());};
  dialog.footer.prepend(button(workspace_text("markdown_color_menu_apply"),()=>{try{const result:any={...current};for(const[key,input]of inputs)result[key]=input instanceof HTMLTextAreaElement?JSON.parse(input.value):input instanceof HTMLInputElement&&input.type==="checkbox"?input.checked:input instanceof HTMLInputElement&&input.type==="number"?Number(input.value):input.value;store.update(result);dialog.close();}catch(failure){error.textContent=String(failure instanceof Error?failure.message:failure);}}),button(workspace_text("terminal_settings_view_restore_default_settings"),()=>{try{store.update(terminal_defaults);dialog.close();}catch(failure){error.textContent=String(failure);}}));
  return dialog;
}
