import {reset_content_appearance} from "./workspace_content_zoom";
import {READING_IMAGE_DEFAULTS,IMAGE_ALIGNMENT_VALUES,read_reading_image_settings,write_reading_image_setting,observe_reading_image_settings,reading_image_alignment_labels} from "./reading_image_settings";
import {workspace_text, workspace_text as localize} from "./workspace_i18n";
import {read_workspace_language_preference,save_workspace_language_preference} from "./workspace_locale";
import {open_language_service_settings} from './language_service_settings_view';
import {read_language_service_profiles,save_language_service_profiles,observe_language_services} from "./language_service_settings";
import {NETWORK_DEFAULTS,read_network_settings,write_network_setting} from './workspace_network_settings';
import {TEXT_PRESENTATION_DEFAULTS,read_text_presentation,update_text_presentation,observe_text_presentation} from './workspace_text_presentation';
import {register_workspace_settings,notify_workspace_settings,type workspace_settings_section} from './workspace_settings_registry';
import {get_workspace_app} from './workspace_bootstrap';
import {FILE_SETTING_DEFAULTS,read_workspace_save_settings,set_workspace_save_settings,observe_workspace_save_settings} from './workspace_save_settings';
import {WORKSPACE_EDITOR_DEFAULTS,read_workspace_editor_settings,set_workspace_editor_setting,observe_workspace_editor_settings} from './workspace_editor_settings';
import {TITLEBAR_DEFAULTS,read_titlebar_settings,toggle_titlebar_setting} from './workspace_titlebar_settings';
import {BREADCRUMB_DEFAULTS,read_breadcrumb_settings,update_breadcrumb_settings,observe_breadcrumb_settings} from './workspace_breadcrumbs_settings';
import {git_diff_defaults,read_git_diff_preferences,update_git_diff_preferences,watch_git_diff_preferences} from './git_diff_settings';
import {REMOTE_SSH_DEFAULTS,read_remote_ssh_settings,write_remote_ssh_setting} from './remote_ssh_settings';
import {read_source_outline_settings,save_source_outline_settings} from './source_outline_settings';
import type {workspace_file_host} from './workspace_files';
import {WORKSPACE_COLOR_ROLES} from './workspace_color_catalog';
import {mount_color_settings} from './workspace_color_view';

export function bind_workspace_settings_sections(files:workspace_file_host){
  const releases:(()=>void)[]=[],user=()=> workspace_text("terminal_workspace_user_settings"),root=()=>files.context_root(),project=()=>workspace_text("settings_sections_workspace", {value_0: String(root()||workspace_text("file_tree_folder_not_opened"))});
  const choice_labels:Record<string,string>={"environment":workspace_text("settings_choice_environment"),"direct":workspace_text("settings_choice_direct"),"manual":workspace_text("settings_choice_manual"),"off":workspace_text("settings_choice_off"),"on":workspace_text("settings_choice_on"),"last":workspace_text("settings_choice_last"),"afterDelay":workspace_text("settings_choice_afterdelay"),"onFocusChange":workspace_text("settings_choice_onfocuschange"),"onWindowChange":workspace_text("settings_choice_onwindowchange"),"editorOrder":workspace_text("settings_choice_editororder"),"alphabetical":workspace_text("settings_choice_alphabetical"),"fullPath":workspace_text("settings_choice_fullpath"),"position":workspace_text("settings_choice_position"),"name":workspace_text("settings_choice_name"),"type":workspace_text("settings_choice_type")};
  const add=(section:workspace_settings_section)=>releases.push(register_workspace_settings({...section,fields:section.fields.map(field=>({...field,choice_labels:field.choice_labels??choice_labels}))}));
  add({id:'images',title:workspace_text('image_layout_section'),scope:user,defaults:READING_IMAGE_DEFAULTS,fields:[{key:'alignment',title:workspace_text('image_layout_alignment'),choices:[...IMAGE_ALIGNMENT_VALUES],choice_labels:reading_image_alignment_labels(),description:workspace_text('image_layout_description')},{key:'scale',title:workspace_text('image_layout_scale'),description:workspace_text('image_layout_scale_description')},{key:'size_mode',title:workspace_text('image_layout_size_mode'),choices:['natural','fit_width'],choice_labels:{natural:workspace_text('image_layout_natural'),fit_width:workspace_text('image_layout_fit')}}],read:read_reading_image_settings,write:write_reading_image_setting});
  releases.push(observe_reading_image_settings(notify_workspace_settings));
  add({id:'appearance',title:localize('appearance_section'),scope:user,defaults:{},fields:[{key:'reset_defaults',title:localize('appearance_reset'),description:localize('appearance_reset_description'),refresh_after_action:true,action:()=>{reset_content_appearance();window.dispatchEvent(new Event('typora-code:reset-appearance'));}}],read:()=>({}),write:()=>{}});
  add({id:'language',title:localize('language_section'),scope:user,defaults:{display_language:'auto'},fields:[{key:'display_language',title:localize('language_preference'),choices:['auto','zh-cn','en'],choice_labels:{auto:localize('language_auto'),'zh-cn':localize('language_chinese'),en:localize('language_english')},description:localize('language_restart')}],read:()=>({display_language:read_workspace_language_preference(get_workspace_app()?.settings)}),write:(_key,value)=>{const settings=get_workspace_app()?.settings;if(!settings)throw Error('Workspace settings are unavailable.');save_workspace_language_preference(settings,value);}});
  add({id:'colors',title:workspace_text("markdown_color_menu_custom_color"),scope:()=> workspace_text("settings_sections_user_settings_vscode2026_light_dark"),defaults:{},fields:WORKSPACE_COLOR_ROLES.map(role=>({key:role.key,title:role.title,description:role.variable||role.selector})),read:()=>({}),write:()=>{throw Error(workspace_text("settings_sections_color_settings_are_saved_through_the_palette"));},mount:mount_color_settings});
  add({id:'network',title:workspace_text("settings_sections_network"),scope:user,defaults:NETWORK_DEFAULTS,fields:[{key:'proxy_mode',title:workspace_text("settings_sections_proxy_mode"),choices:['environment','direct','manual'],description:workspace_text("settings_sections_environment_use_https_proxy_http_proxy_and_no_proxy_environm")},{key:'http_proxy_url',title:workspace_text("settings_sections_http_request_proxy"),description:workspace_text("settings_sections_for_http_target_for_example_http_proxy_company_8080_supports")},
    {key:'https_proxy_url',title:workspace_text("settings_sections_https_request_proxy"),description:workspace_text("settings_sections_for_https_target_for_example_http_proxy_company_8081_support")},{key:'ca_file',title:workspace_text("settings_sections_enterprise_ca_certificate_file"),description:workspace_text("settings_sections_add_trusted_pem_certificate_package_or_der_certificate_pem_c"),file_extensions:['pem','crt','cer']}],read:read_network_settings,write:write_network_setting});
  add({id:'editor',title:workspace_text("explorer_sections_editor"),scope:user,defaults:{...WORKSPACE_EDITOR_DEFAULTS,...TEXT_PRESENTATION_DEFAULTS},fields:[{key:'word_wrap',title:workspace_text("settings_sections_text_auto_wrap"),description:workspace_text("settings_sections_source_code_historical_versions_diffs_and_source_previews_wr")},{key:'enable_preview',title:workspace_text("editor_actions_enable_preview_editor")},{key:'wrap_tabs',title:workspace_text("settings_sections_tab_wrapping_wrap_tabs"),description:workspace_text("settings_sections_tabs_display_as_multiple_lines_when_they_exceed_available_wi")},{key:'link_preview_enabled',title:workspace_text("settings_sections_auto_preview_selected_links"),description:workspace_text("settings_sections_preview_selected_links_as_read_only_in_the_lower_left_withou")}],read:()=>({...read_workspace_editor_settings(),...read_text_presentation()}),write:(key,value)=>key==='word_wrap'?update_text_presentation(value as boolean):set_workspace_editor_setting(key,value as boolean)});
  const file_labels=[workspace_text("save_settings_auto_save"),workspace_text("settings_sections_auto_save_delay_milliseconds"),workspace_text("save_settings_auto_save_only_files_in_the_workspace"),workspace_text("save_settings_auto_save_only_when_there_are_no_diagnostic_errors"),workspace_text("save_settings_enable_local_history"),workspace_text("settings_sections_number_of_historical_entries_per_file"),workspace_text("settings_sections_merge_adjacent_save_windows_seconds"),workspace_text("settings_sections_history_exclusion_rules_json"),workspace_text("save_settings_maximum_visible_lines_in_open_editors"),workspace_text("settings_sections_minimum_visible_line_count_for_open_editors"),workspace_text("save_settings_sort_of_open_editors"),workspace_text("settings_sections_show_open_editors"),workspace_text("settings_sections_show_timeline")];
  add({id:'files',title:workspace_text("settings_sections_explorer_and_saving"),scope:user,defaults:FILE_SETTING_DEFAULTS,fields:Object.keys(FILE_SETTING_DEFAULTS).map((key,index)=>({key,title:file_labels[index]||key,choices:key==='files.autoSave'?['off','afterDelay','onFocusChange','onWindowChange']:key==='explorer.openEditors.sortOrder'?['editorOrder','alphabetical','fullPath']:undefined})),read:read_workspace_save_settings,write:(key,value)=>{const baseline=(FILE_SETTING_DEFAULTS as any)[key];if(typeof baseline==='number'&&(typeof value!=='number'||value<0||!Number.isInteger(value)))throw Error(workspace_text("settings_sections_enter_a_non_negative_integer"));if(key.endsWith('exclude')&&(!value||Array.isArray(value)||typeof value!=='object'||Object.values(value).some(item=>typeof item!=='boolean')))throw Error(workspace_text("settings_sections_exclusion_rules_must_be_a_glob_to_boolean_value_json_object"));set_workspace_save_settings({[key]:value});}});
  add({id:'titlebar',title:workspace_text("settings_sections_top_bar"),scope:user,defaults:TITLEBAR_DEFAULTS,fields:[{key:'menu_bar',title:workspace_text("settings_sections_show_menu_bar")},{key:'command_center',title:workspace_text("settings_sections_show_file_search")},{key:'navigation_controls',title:workspace_text("settings_sections_show_back_and_forward")}],read:()=>read_titlebar_settings(get_workspace_app()?.settings),write:(key,value)=>{if((read_titlebar_settings(get_workspace_app()?.settings) as any)[key]!==value)toggle_titlebar_setting(get_workspace_app()?.settings,key as keyof typeof TITLEBAR_DEFAULTS);}});
  const crumb_labels:Record<string,string>={enabled:workspace_text("breadcrumbs_show_breadcrumbs"),file_path:workspace_text("breadcrumbs_settings_file_path"),symbol_path:workspace_text("breadcrumbs_settings_symbol_path"),icons:workspace_text("breadcrumbs_settings_show_icon"),show_editor_type:workspace_text("breadcrumbs_settings_show_editor_type"),symbol_sort_order:workspace_text("breadcrumbs_settings_symbol_sort"),symbol_path_separator:workspace_text("breadcrumbs_settings_copy_symbol_path_separator")};
  add({id:'breadcrumbs',title:workspace_text("settings_sections_breadcrumbs_workspace"),scope:project,defaults:BREADCRUMB_DEFAULTS,fields:Object.keys(BREADCRUMB_DEFAULTS).map(key=>({key,title:crumb_labels[key],choices:key==='file_path'||key==='symbol_path'?['on','off','last']:key==='symbol_sort_order'?['position','name','type']:undefined})),read:()=>read_breadcrumb_settings(root()),write:(key,value)=>update_breadcrumb_settings(root(),root()?'workspace':'user',key as any,value)});
  const diff_labels:Record<string,string>={render_side_by_side:workspace_text("settings_sections_side_by_side_comparison"),inline_when_narrow:workspace_text("settings_sections_narrow_width_auto_inline"),ignore_trim_whitespace:workspace_text("settings_sections_ignore_leading_and_trailing_whitespace_differences"),hide_unchanged:workspace_text("settings_sections_hide_unmodified_areas"),show_moves:workspace_text("settings_sections_show_moved_code"),render_markdown:workspace_text("settings_sections_markdown_default_rendering_comparison")};
  add({id:'diff',title:workspace_text("breadcrumbs_difference_editor"),scope:user,defaults:{...git_diff_defaults},fields:Object.keys(git_diff_defaults).map(key=>({key,title:diff_labels[key]})),read:read_git_diff_preferences,write:(key,value)=>update_git_diff_preferences({[key]:value})});
  const ssh_labels:Record<string,string>={ssh_path:workspace_text("settings_sections_openssh_program_path_empty_for_system_default"),config_file:workspace_text("settings_sections_ssh_configuration_file_path_empty_for_openssh_default"),connect_timeout:workspace_text("settings_sections_connection_timeout_seconds"),server_alive_interval:workspace_text("settings_sections_connection_keep_alive_interval_seconds_0_disable"),server_alive_count:workspace_text("settings_sections_number_of_consecutive_failed_keep_alive_attempts"),request_timeout:workspace_text("settings_sections_ssh_protocol_handshake_timeout_seconds"),refresh_interval:workspace_text("settings_sections_visible_remote_directory_refresh_interval_seconds_0_disable")};
  add({id:'ssh',title:workspace_text("settings_sections_ssh_remote"),scope:user,defaults:REMOTE_SSH_DEFAULTS,fields:Object.keys(REMOTE_SSH_DEFAULTS).map(key=>({key,title:ssh_labels[key],description:key==='config_file'?workspace_text("settings_sections_port_key_proxy_and_account_are_managed_by_openssh_host_key_i"):undefined})),read:read_remote_ssh_settings,write:write_remote_ssh_setting});
  add({id:'outline',title:workspace_text("language_service_settings_view_language_service"),scope:project,defaults:{clangd_path:'',compile_commands_dir:'',fallback_flags:[],user_languages:{},workspace_languages:{}},fields:[{key:'environment',title:workspace_text("settings_sections_select_language_service_and_environment"),description:workspace_text("settings_sections_detect_system_programs_select_python_virtual_environment_or"),action:()=>open_language_service_settings(root(),root)},{key:'user_languages',title:workspace_text("settings_sections_configure_by_language_user_json"),description:workspace_text("settings_sections_key_is_python_java_c_cpp_etc_language_identifiers_each_item")}, {key:'workspace_languages',title:workspace_text("settings_sections_configure_by_language_current_workspace_json"),description:workspace_text("settings_sections_same_named_language_fully_overrides_user_configuration_delet")},{key:'clangd_path',title:workspace_text("settings_sections_clangd_path_user_level")},{key:'compile_commands_dir',title:workspace_text("settings_sections_compilation_database_directory_workspace")},{key:'fallback_flags',title:workspace_text("settings_sections_backup_compilation_parameters_json_array")}],read:()=>({...read_source_outline_settings(root()),user_languages:read_language_service_profiles(root(),'user'),workspace_languages:read_language_service_profiles(root(),'workspace')}),write:(key,value)=>key==='user_languages'||key==='workspace_languages'?save_language_service_profiles(root(),key==='user_languages'?'user':'workspace',value):save_source_outline_settings(root(),{...read_source_outline_settings(root()),[key]:value})});
  releases.push(observe_language_services(notify_workspace_settings),observe_text_presentation(notify_workspace_settings),observe_workspace_save_settings(notify_workspace_settings),observe_workspace_editor_settings(notify_workspace_settings),observe_breadcrumb_settings(notify_workspace_settings),watch_git_diff_preferences(notify_workspace_settings));
  window.addEventListener('linux-note-workspace-context-changed',notify_workspace_settings);
  return{dispose(){window.removeEventListener('linux-note-workspace-context-changed',notify_workspace_settings);for(const release of releases.reverse())release();}};
}
